### PR TITLE
Fix CI failures

### PR DESCRIPTION
**Pull request by crisbeto**
Includes the following changes to fix the broken CI:

### fix(compiler): handle typeof expressions in serializer
Fixes that some changes which landed at the same time caused a compilation error in the serialized.

### test(compiler-cli): fix broken test
Fixes a test that broke because a pipe wasn't marked explicitly as `standalone: false`.

### test(compiler): update failing tests
Fixes some tests that started failing, because angular#58154 made it so placeholder-only messages are extracted while angular#58176 added some tests that only contain placeholders.

### CODE REVIEW

**Review by devversion — APPROVED** [review]

**Comment by devversion** [comment]
Thanks @crisbeto

**Comment by devversion** [comment]
This PR was merged into the repository by commit 597103761319619ba7096deddf1bcc4a89ddd3ee.

The changes were merged into the following branches: main
