### ISSUE TITLE
compiler-cli > 5.1 dies during error display

### ISSUE THREAD

**Issue by inossidabile** [angular/angular#21014]
## I'm submitting a...

<pre><code>
[ x ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
Use `@angular/compiler-cli` 5.1.x. Put `"allowJs": true` into `.tsconfig` and try building via WebPack with `@ngtools/webpack`. It correctly yields a error that is supposed to be shown but instead it dies with this:
```
ERROR in TypeError: compiler_1.isFormattedError is not a function
    at syntaxErrorToDiagnostics (/app/client/node_modules/@angular/compiler-cli/src/transformers/program.js:794:25)
    at AngularCompilerProgram._addStructuralDiagnostics (/app/client/node_modules/@angular/compiler-cli/src/transformers/program.js:481:49)
    at AngularCompilerProgram._createProgramOnError (//app/client/node_modules/@angular/compiler-cli/src/transformers/program.js:473:18)
    at /app/client/node_modules/@angular/compiler-cli/src/transformers/program.js:151:48
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:667:11)
    at startup (bootstrap_node.js:201:16)
```

## Expected behavior
Showing a error (works in 5.0.x):
```
Cannot write file '/app/client/webpack.config.js' because it would overwrite input file.
```

## Minimal reproduction of the problem with instructions
Compile anything that yields a error with compiler-cli > 5.1.

## Environment

<pre><code>
Angular version: 5.0.4

Browser: CLI

For Tooling issues:
- Node version: XX  8.5.0
- Platform:  Mac
</code></pre>

**Comment by inossidabile** [comment]
Apparently just a peer version conflict. Wasn't clear from stack trace, closing.

**Comment by Jackclarify** [comment]
@angular/compiler-cli down-grade t  version 5.0.5, it is okay

**Comment by AlhagebAlmansoor** [comment]
may I know how did you solve the problem please? , I am facing the same problem when trying to run the command webpack --env.prod

**Comment by FreakTheMighty** [comment]
@inossidabile can you clarify how your resolved this?

**Comment by inossidabile** [comment]
Make sure you use exactly the same version of Angular itself and Angular compiler. For instance if you try to use 5.1 against 5.0 you get this issue. That was my problem too - slight difference in versions in peer deps.
