### ISSUE TITLE
Ivy (9.1.5) causes build failure

### ISSUE THREAD

**Issue by n9niwas** [angular/angular#36992]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/compiler-cli (ngcc)

### Is this a regression?

 Yes, the previous version in which this bug was not present was: `9.1.0`

### Description

In JIT mode build fails with
File name 'node_modules/apollo-angular/selectpipe.d.ts' differs from already included file name 'node_modules/apollo-angular/SelectPipe.d.ts' only in casing
In AOT mode build fails with
Symbol SelectPipe declared in * is not exported from apollo-angular

## 🔬 Minimal Reproduction

Clone https://github.com/n9niwas/ngccbug
Run
```bash
yarn
yarn start
```

## 🔥 Exception or Error
<pre><code>
ERROR in node_modules/apollo-angular/ApolloModule.d.ts:4:25 - error TS1149: File name '/Users/blah/Documents/ngrepros/ngccbug/node_modules/apollo-angular/selectpipe.d.ts' differs from already included file name '/Users/blah/Documents/ngrepros/ngccbug/node_modules/apollo-angular/SelectPipe.d.ts' only in casing.

4 import * as ɵngcc1 from './selectpipe';
</code></pre>

Also if I enable `aot` the error is different:
<pre><code>
ERROR in Symbol SelectPipe declared in /Users/blah/Documents/ngrepros/ngccbug/node_modules/apollo-angular/selectpipe.d.ts is not exported from apollo-angular (import into /Users/blah/Documents/ngrepros/ngccbug/src/app/app.component.ts)
</code></pre>
This was also working fine in `9.1.0`

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.4
Node: 13.11.0
OS: darwin x64

Angular: 9.1.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.4
@angular-devkit/build-angular     0.901.4
@angular-devkit/build-optimizer   0.901.4
@angular-devkit/build-webpack     0.901.4
@angular-devkit/core              9.1.4
@angular-devkit/schematics        9.1.4
@angular/cli                      9.1.4
@ngtools/webpack                  9.1.4
@schematics/angular               9.1.4
@schematics/update                0.901.4
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Anything else relevant?**

**Comment by owi1972** [comment]
It also worked in 9.1.3

**Comment by sandervn** [comment]
The build fails in 9.1.5 if Ivy is enabled. If it's not enabled, it succeed.

**Comment by wvankuipers** [comment]
Just had the same issue, 9.1.4 builds fine, but 9.1.5 gives the same issue with duplicated file names and incorrect casing.

**Comment by wvankuipers** [comment]
Probably related to #36968

**Comment by cedricduffournet** [comment]
Same issue with angulartics lib
https://github.com/angulartics/angulartics2/issues/380

**Comment by petebacondarwin** [comment]
Thanks for the reproduction @n9niwas. It made all the difference!

I have found the problem. It is a bug in ngcc. 

During processing ngcc is spotting that the operating system is case-insensitive and then adding imports to files with canonical paths. E.g.

```
import { Apollo } from './Apollo';
import { SelectPipe } from './SelectPipe';
import * as ɵngcc0 from '@angular/core';
import * as ɵngcc1 from './selectpipe';
export declare const PROVIDERS: (typeof Apollo)[];
export declare const DECLARATIONS: (typeof SelectPipe)[];
export declare class ApolloModule {
    static ɵmod: ɵngcc0.ɵɵNgModuleDefWithMeta<ApolloModule, [typeof ɵngcc1.SelectPipe], never, [typeof ɵngcc1.SelectPipe]>;
    static ɵinj: ɵngcc0.ɵɵInjectorDef<ApolloModule>;
}
```

Note that there are two imports to the same file:

```
import { SelectPipe } from './SelectPipe';
import * as ɵngcc1 from './selectpipe';
```

The first is from the original file. The second is added by ngcc.

Working on a fix.

**Comment by tnlthanzeel** [comment]
same issue i had this morning when i installed a clean version of angular 9 globally

ERROR in TypeError: Cannot read property 'flags' of undefined
at resolveAlias (D:\samples projects\angular9helloword\helloWorld\node_modules\typescript\lib\typescript.js:36513:37)
at checkAliasSymbol (D:\samples projects\angular9helloword\helloWorld\node_modules\typescript\lib\typescript.js:64502:26)
at checkImportBinding (D:\samples projects\angular9helloword\helloWorld\node_modules\typescript\lib\typescript.js:64534:13)
at checkImportDeclaration (D:\samples projects\angular9helloword\helloWorld\node_modules\typescript\lib\typescript.js:64552:29) at checkSourceElementWorker (D:\samples projects\angular9helloword\helloWorld\node_modules\typescript\lib\typescript.js:64961:28)

"devDependencies": {
"@angular-devkit/build-angular": "~0.901.4",
"@angular/cli": "~9.1.4",
"@angular/compiler-cli": "~9.1.4",
"@angular/language-service": "~9.1.4",
"@types/node": "^12.11.1",
"@types/jasmine": "~3.5.0",
"@types/jasminewd2": "~2.0.3",
"codelyzer": "^5.1.2",
"jasmine-core": "~3.5.0",
"jasmine-spec-reporter": "~4.2.1",
"karma": "~5.0.0",
"karma-chrome-launcher": "~3.1.0",
"karma-coverage-istanbul-reporter": "~2.1.0",
"karma-jasmine": "~3.0.1",
"karma-jasmine-html-reporter": "^1.4.2",
"protractor": "~5.4.3",
"ts-node": "~8.3.0",
"tslint": "~6.1.0",
"typescript": "~3.8.3"
}

Angular CLI: 9.1.4
Node: v12.13.0
OS: windows 10
NPM : 6.12.0

i just did "ng new helloword" and after the project was created i tried "ng s -o" and threw the error above

please help

**Comment by tademeit** [comment]
> Thanks for the reproduction @n9niwas. It made all the difference!
> 
> I have found the problem. It is a bug in ngcc.
> 
> During processing ngcc is spotting that the operating system is case-insensitive and then adding imports to files with canonical paths. E.g.
> 
> ```
> import { Apollo } from './Apollo';
> import { SelectPipe } from './SelectPipe';
> import * as ɵngcc0 from '@angular/core';
> import * as ɵngcc1 from './selectpipe';
> export declare const PROVIDERS: (typeof Apollo)[];
> export declare const DECLARATIONS: (typeof SelectPipe)[];
> export declare class ApolloModule {
>     static ɵmod: ɵngcc0.ɵɵNgModuleDefWithMeta<ApolloModule, [typeof ɵngcc1.SelectPipe], never, [typeof ɵngcc1.SelectPipe]>;
>     static ɵinj: ɵngcc0.ɵɵInjectorDef<ApolloModule>;
> }
> ```
> 
> Note that there are two imports to the same file:
> 
> ```
> import { SelectPipe } from './SelectPipe';
> import * as ɵngcc1 from './selectpipe';
> ```
> 
> The first is from the original file. The second is added by ngcc.
> 
> Working on a fix.

Nice, thanks for the quick help!

**Comment by xiaotaoliu** [comment]
so, 
how to fix this problem?

> Thanks for the reproduction @n9niwas. It made all the difference!
> 
> I have found the problem. It is a bug in ngcc.
> 
> During processing ngcc is spotting that the operating system is case-insensitive and then adding imports to files with canonical paths. E.g.
> 
> ```
> import { Apollo } from './Apollo';
> import { SelectPipe } from './SelectPipe';
> import * as ɵngcc0 from '@angular/core';
> import * as ɵngcc1 from './selectpipe';
> export declare const PROVIDERS: (typeof Apollo)[];
> export declare const DECLARATIONS: (typeof SelectPipe)[];
> export declare class ApolloModule {
>     static ɵmod: ɵngcc0.ɵɵNgModuleDefWithMeta<ApolloModule, [typeof ɵngcc1.SelectPipe], never, [typeof ɵngcc1.SelectPipe]>;
>     static ɵinj: ɵngcc0.ɵɵInjectorDef<ApolloModule>;
> }
> ```
> 
> Note that there are two imports to the same file:
> 
> ```
> import { SelectPipe } from './SelectPipe';
> import * as ɵngcc1 from './selectpipe';
> ```
> 
> The first is from the original file. The second is added by ngcc.
> 
> Working on a fix.

now I know it is a bug in ngcc.     but how to fix it? My project still not work. 
Can someone tell me what should I do? 
Many Thanks.(I am a beginner)

**Comment by cedricduffournet** [comment]
Waiting for a fix or install previous angular version (previous than 9.1.5 in my case)

**Comment by petebacondarwin** [comment]
@xiaotaoliu - for now roll-back your Angular versions to 9.1.4.
You can do this by changing all the `@angular/...` framework packages in your `package.json` to 9.1.4.

E.g.

```
  "dependencies": {
    "@angular/animations": "9.1.4",
    "@angular/cdk": "^9.2.2",
    "@angular/common": "9.1.4",
    "@angular/compiler": "9.1.4",
    "@angular/core": "9.1.4",
    "@angular/elements": "9.1.4",
    "@angular/forms": "9.1.4",
    "@angular/material": "^9.2.2",
    "@angular/platform-browser": "9.1.4",
    "@angular/platform-browser-dynamic": "9.1.4",
    "@angular/router": "9.1.4",
    "@angular/service-worker": "9.1.4",
    ...
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.901.4",
    "@angular/cli": "9.1.4",
    "@angular/compiler-cli": "9.1.4",
    "@angular/language-service": "9.1.4",
    ...
```

And then re-installing your dependencies (i.e. `yarn` or `npm install`).

**Comment by tnlthanzeel** [comment]
> @xiaotaoliu - for now roll-back your Angular versions to 9.1.4.
> You can do this by changing all the `@angular/...` framework packages in your `package.json` to 9.1.4.
> 
> E.g.
> 
> ```
>   "dependencies": {
>     "@angular/animations": "9.1.4",
>     "@angular/cdk": "^9.2.2",
>     "@angular/common": "9.1.4",
>     "@angular/compiler": "9.1.4",
>     "@angular/core": "9.1.4",
>     "@angular/elements": "9.1.4",
>     "@angular/forms": "9.1.4",
>     "@angular/material": "^9.2.2",
>     "@angular/platform-browser": "9.1.4",
>     "@angular/platform-browser-dynamic": "9.1.4",
>     "@angular/router": "9.1.4",
>     "@angular/service-worker": "9.1.4",
>     ...
>   },
>   "devDependencies": {
>     "@angular-devkit/build-angular": "0.901.4",
>     "@angular/cli": "9.1.4",
>     "@angular/compiler-cli": "9.1.4",
>     "@angular/language-service": "9.1.4",
>     ...
> ```
> 
> And then re-installing your dependencies (i.e. `yarn` or `npm install`).

this is a temporary fix ryt?

**Comment by xiaotaoliu** [comment]
I did this. and now it works.
Thank you very much.

**Comment by xiaotaoliu** [comment]
@petebacondarwin 
I did this. and now it works.
Thank you very much.

**Comment by NamrataDG** [comment]
My Angular versions are already pointing to 9.1.4.But its still failing.
"dependencies": {
    "@angular/animations": "~9.1.4",
    "@angular/common": "~9.1.4",
    "@angular/compiler": "~9.1.4",
    "@angular/core": "~9.1.4",
    "@angular/forms": "~9.1.4",
    "@angular/platform-browser": "~9.1.4",
    "@angular/platform-browser-dynamic": "~9.1.4",
    "@angular/router": "~9.1.4",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.4",
    "@angular/cli": "~9.1.4",
    "@angular/compiler-cli": "~9.1.4",
    "@angular/language-service": "~9.1.4",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~3.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",

**Comment by tnlthanzeel** [comment]
> My Angular versions are already pointing to 9.1.4.But its still failing.
> "dependencies": {
> "@angular/animations": "~9.1.4",
> "@angular/common": "~9.1.4",
> "@angular/compiler": "~9.1.4",
> "@angular/core": "~9.1.4",
> "@angular/forms": "~9.1.4",
> "@angular/platform-browser": "~9.1.4",
> "@angular/platform-browser-dynamic": "~9.1.4",
> "@angular/router": "~9.1.4",
> "rxjs": "~6.5.4",
> "tslib": "^1.10.0",
> "zone.js": "~0.10.2"
> },
> "devDependencies": {
> "@angular-devkit/build-angular": "~0.901.4",
> "@angular/cli": "~9.1.4",
> "@angular/compiler-cli": "~9.1.4",
> "@angular/language-service": "~9.1.4",
> "@types/jasmine": "~3.5.0",
> "@types/jasminewd2": "~2.0.3",
> "@types/node": "^12.11.1",
> "codelyzer": "^5.1.2",
> "jasmine-core": "~3.5.0",
> "jasmine-spec-reporter": "~4.2.1",
> "karma": "~5.0.0",
> "karma-chrome-launcher": "~3.1.0",
> "karma-coverage-istanbul-reporter": "~2.1.0",
> "karma-jasmine": "~3.0.1",
> "karma-jasmine-html-reporter": "^1.4.2",
> "protractor": "~5.4.3",
> "ts-node": "~8.3.0",
> "tslint": "~6.1.0",

do this

npm install @angular/core@9.1.4 @angular/animations@9.1.4 @angular/common@9.1.4 @angular/forms@9.1.4 @angular/platform-browser@9.1.4 @angular/router@9.1.4 @angular/platform-browser-dynamic@9.1.4 @angular/compiler@9.1.4 @angular/compiler-cli@9.1.4 @angular/language-service@9.1.4

**Comment by simonua** [comment]
@NamrataDG, you are using a tilde wildcard (e.g. "~9.1.4") which will install patch versions. 9.1.5 and 9.1.4 are both valid. Notice how petebacondarwin's versions are pinned explicitly to the versions to use ("9.1.4"). Once updated, run `npm i`, and you should be good to go.

**Comment by NamrataDG** [comment]
@simonua  Thanks a lot..It worked.

**Comment by petebacondarwin** [comment]
It appears, at least locally that #37008 fixes the problem in https://github.com/n9niwas/ngccbug

**Comment by petebacondarwin** [comment]
We have just released 9.1.6 which should not have this problem. Please test.

**Comment by christopherthielen** [comment]
9.1.6 works for me, thanks for the quick turnaround!

**Comment by cedricduffournet** [comment]
9.1.6 works for me also, thanks

**Comment by mgechev** [comment]
As @petebacondarwin mentioned, upgrading to 9.1.6 should fix the problem. Closing the issue now. In case the problem is still not resolved, feel free to open a new one.

**Comment by webm0nk3y** [comment]
This is back after upgrading to 9.1.7

**Comment by petebacondarwin** [comment]
Can you provide more details in a fresh issue please @webm0nk3y
