### PR TITLE
build(compiler-cli): fix tsconfig.json

### LINKED ISSUE #22721: Circularity issue in compiler-cli/tsconfig.json
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Circularity detected while resolving configuration hinted by VS Code
in `compiler-cli/tsconfig.json`
This causes dependencies to not resolve in `symbol_query_spec.ts` for example
dependecies-not-resolved

## Expected behavior

No Circularity issues

## Minimal reproduction of the problem with instructions
Checkout master branch and pull latest changes
Seems to be introduced by c602563589a7e14f0c57ee5b191979039aa370db

Here is the current content of tsconfig
 ```typescript
{
    "extends": "./tsconfig.json",
    "compilerOptions": {
        "target": "es2015",
        "lib": [
            "es2015"
        ]
    }
}
```

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

### PR DESCRIPTION
**Pull request by benbraou**
Fixes #22721

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
In `compiler-cli/tsconfig.json`, there is a circularity issue (it is extending itself)
```json
{
   "extends": "./tsconfig.json",
   "compilerOptions": {
       "target": "es2015",
       "lib": [
           "es2015"
       ]
   }
}
```

Issue Number: N/A
 #22721

## What is the new behavior?
update `compiler-cli/tsconfig.json` introduced by c602563589a7e14f0c57ee5b191979039aa370db

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by benbraou** [comment]
I removed the `tsconfig.json` which made all dependencies in `compiler-cli` spec files resolved correctly.
Hopefully, this is the accepted way to go

**Comment by IgorMinar** [comment]
It's odd that my VS Code doesn't complain about this. It is obviously wrong.

However if you delete the file, the editors will not understand that it's ok to use es2015 apis in the compiler-cli code. The proper fix would be to change the extends to "../tsconfig.json". Can you please update your PR to that?

**Comment by benbraou** [comment]
Thanks @IgorMinar for the feedback
1. My VS Code started to complain after I deleted both `node_modules` and `dist` folders and then I did `yarn install` + run build and test scripts. Maybe this is how you could reproduce
1. I updated my PR as you suggested to have `compiler-cli/tsconfig.json` have the `"extends": "../tsconfig.json"`
1. When I did that, all dependencies in the spec files were correctly resolved. However, `jasmine` types were missing (I kept getting the error `Cannot find name 'describe' `)
jasmine
4. So, I declared the type `jasmine` in `compiler-cli/tsconfig.json` and that solved the issue for me.

I have updated my PR accordingly. Please let me know if this is not the way to go

**Comment by benbraou** [comment]
rebased on top of master and force pushed in order to have a new travis build (previous was failing due to timeout in `aio`)

**Review by IgorMinar — APPROVED** [review]

**Comment by IgorMinar** [comment]
thank you!
