### ISSUE TITLE
After upgrade from Angular 17 to 18: polyfills?.some is not a function

### ISSUE THREAD

**Issue by cesco69** [angular/angular#56025]
### Which @angular/* package(s) are the source of the bug?

compiler-cli

### Is this a regression?

Yes

### Description

I have upgrade from Angular 17 to 18 with:
```
ng update @angular/core@18 @angular/cli@18 --force --allow-dirty
ng update @angular/cdk@18 @angular/material@18 --force --allow-dirty
```
When I run `ng serve`
```
Application bundle generation complete. [30.669 seconds]

Watch mode enabled. Watching for file changes...
NOTE: Raw file sizes do not reflect development server per-request transformations.
An unhandled exception occurred: polyfills?.some is not a function
See "C:\Users\GERARD~1\AppData\Local\Temp\ng-w1ouV2\angular-errors.log" for further details.
```
angular-errors.log show:
```
[error] TypeError: polyfills?.some is not a function
    at isZonelessApp (D:\a-team\usbim-llpp\frontend\node_modules\.pnpm\@angular+build@18.0.0_@angular+compiler-cli@18.0.0_@angular+localize@18.0.0_@types+node@20.12_3bg7bdsu3zoaz37rnqvhp7tkye\node_modules\@angular\build\src\tools\esbuild\utils.js:390:24)
    at serveWithVite (D:\a-team\usbim-llpp\frontend\node_modules\.pnpm\@angular+build@18.0.0_@angular+compiler-cli@18.0.0_@angular+localize@18.0.0_@types+node@20.12_3bg7bdsu3zoaz37rnqvhp7tkye\node_modules\@angular\build\src\builders\dev-server\vite-server.js:198:234)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Please provide the exception or error you saw

```true
[error] TypeError: polyfills?.some is not a function
    at isZonelessApp (D:\a-team\usbim-llpp\frontend\node_modules\.pnpm\@angular+build@18.0.0_@angular+compiler-cli@18.0.0_@angular+localize@18.0.0_@types+node@20.12_3bg7bdsu3zoaz37rnqvhp7tkye\node_modules\@angular\build\src\tools\esbuild\utils.js:390:24)
    at serveWithVite (D:\a-team\usbim-llpp\frontend\node_modules\.pnpm\@angular+build@18.0.0_@angular+compiler-cli@18.0.0_@angular+localize@18.0.0_@types+node@20.12_3bg7bdsu3zoaz37rnqvhp7tkye\node_modules\@angular\build\src\builders\dev-server\vite-server.js:198:234)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 18.0.0
Node: 20.10.0
Package Manager: pnpm 8.10.5
OS: win32 x64

Angular: 18.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, localize, material, material-date-fns-adapter
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1800.0 (cli-only)
@angular-devkit/build-angular   18.0.0
@angular-devkit/core            18.0.0 (cli-only)
@angular-devkit/schematics      18.0.0 (cli-only)
@schematics/angular             18.0.0 (cli-only)
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.6
```
