### ISSUE TITLE
Regression regarding angular 11.1 with async pipe in template not infering the right type

### ISSUE THREAD

**Issue by bulldog98** [angular/angular#40637]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/compiler-cli I guess

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 11.0.9

### Description

 Given a component with an Output test: EventEmitter<{label: test}> if you use it in an async pipe,
you the type is not inferred in the template, but is instead unknown, while the language service reports the correct type.

## 🔬 Minimal Reproduction

 https://github.com/bulldog98/angular-11.1-regression
StackBlitz is not suitable, because this problem causes the app to not compile. To see the bug, just try to run the project

## 🔥 Exception or Error
<pre><code>

Error: src/app/app.component.html:2:30 - error TS2571: Object is of type 'unknown'.

2   {{ (emitting.test | async).label }}
                                           ~~~~~

  src/app/app.component.ts:5:16
    5   templateUrl: './app.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AppComponent.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.2
@angular-devkit/build-angular   0.1101.2
@angular-devkit/core            11.1.2
@angular-devkit/schematics      11.1.2
@angular/cli                    11.1.2
@schematics/angular             11.1.2
@schematics/update              0.1101.2
rxjs                            6.6.3
typescript                      4.1.3
</code></pre>

**Anything else relevant?**

**Comment by JoostK** [comment]
I traced this to have been caused by #39627. The overridden declaration of `EventEmitter.subscribe` prevents types from flowing as expected, resulting in the `unknown` type. I am not entirely sure why this was not a problem before #39627; `EventEmitter` extends from `Subject -> Observable -> Subscribable`. The only difference is that `Observable` is a class (i.e. has a value) whereas `Subscribable` is an interface.

A workaround would be to use `emitter.asObservable()` which gets you an `Observable<T>` which does allow for proper type inference.

**Comment by petebacondarwin** [comment]
Interestingly, simple switching the `Subscribable` with `Observable` in the `common.d.ts` file results in a different error:

```
Error: src/app/app.component.html:2:30 - error TS2531: Object is possibly 'null'.
```

Rather than `Object is possibly `unknown``.

**Comment by petebacondarwin** [comment]
And indeed reverting `@angular/common` to 11.0.9 does result in this same `Object is possibly 'null'` error...
So I think that there is something else going on perhaps in the compiler that is causing this regression and that the error is a red-herring.

**Comment by bulldog98** [comment]
Oh if I remember correctly in the real code we used ?.label to access the property, which worked but after upgrading it ceased to work

**Comment by petebacondarwin** [comment]
Perhaps the change from TS 4.0 to TS 4.1 causes the problem?

**Comment by JoostK** [comment]
@petebacondarwin I did compare the generated type-check code and it's identical. Also there is no difference between TS 4.0 and TS 4.1. The error `Object is possibly 'null'.` is expected for the `async` pipe as it emits `null` when no value has been emitted yet, so its return type is always `T | null`.

**Comment by petebacondarwin** [comment]
OK adding the  `?.label` and changing `Subscribable` to `Observable` does indeed fix the problem.

**Comment by petebacondarwin** [comment]
I think we might be able to fix this by making the `EventEmitter.subscribe()` method more similar to the one in `Subscribable`...

```ts
    subscribe(observer?: any): Subscription;
    subscribe(next: null | undefined, error: null | undefined, complete: () => void): Subscription;
    subscribe(next: null | undefined, error: (error: any) => void, complete?: () => void): Subscription;
    subscribe(next: (value: T) => void, error: null | undefined, complete: () => void): Subscription;
    subscribe(next?: (value: T) => void, error?: (error: any) => void, complete?: () => void): Subscription;
```
