### ISSUE TITLE
[compiler]: fullTemplateTypeCheck throws with IllegalState

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#19485]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Compiling 
```
<div *ngFor="let race of races | slice:0:4">
  <h2>{{ race.name }}</h2>
</div>
```

with `races: Array<RaceModel> = [];`

and ngc configured to use `fullTemplateTypeCheck` throws:

```
Error: Error: Illegal State: referring to a type without a variable {"filePath":"/Users/cedric/Code/ninjasquad/formation/Angular2/ponyracer/node_modules/@angular/common/common.d.ts","name":"SlicePipe","members":[]}
    at ViewBuilder.getOutputVar (/Users/cedric/Code/ninjasquad/formation/Angular2/ponyracer/node_modules/@angular/compiler/bundles/compiler.umd.js:26317:19)
```

## Expected behavior
It should compile without errors.

## Environment

<pre><code>
Angular version: 5.0.0-rc.0

For Tooling issues:
- Node version: 8.4.0
- Platform:  OSX 10.12

</code></pre>

cc @tbosch as we spoke on Slack about this.

**Comment by cexbrayat** [comment]
I'm still having issues when beta testing this flag (even if it's better than when I opened the issue), here are my findings.

A simple template with a `routerLink`:
```
<a class="nav-item nav-link" routerLink="/races">Races</a>
```
 throws:
```
Directive RouterLinkWithHref, Cannot find name '$event'. Did you mean 'Event'?
```

With forms, too:

```
<div class="row">
  <div class="col-md-4 offset-md-4">
    <h1>Sign up</h1>

    <form (ngSubmit)="register()" [formGroup]="userForm">

      <div class="form-group">
        <label for="login" id="login-label">Login</label>
        <input id="login" class="form-control" formControlName="login">
        <div *ngIf="loginCtrl.dirty && loginCtrl.hasError('required')" id="login-warning">Login is required</div>
      </div>

      <div class="form-group">
        <label for="password">Password</label>
        <input id="password" class="form-control" type="password" formControlName="password">
        <div *ngIf="passwordCtrl.dirty && passwordCtrl.hasError('required')">Password is required</div>
      </div>

      <div class="form-group">
        <label for="birthYear">Birth year</label>
        <input id="birthYear" class="form-control" type="number" formControlName="birthYear">
        <div *ngIf="birthYearCtrl.dirty && birthYearCtrl.hasError('required')">Birth year is required</div>
      </div>

      <button class="btn btn-primary" type="submit" [disabled]="userForm.invalid">Let's Go!</button>
    </form>
  </div>
</div>
```

raises:

```
register.component.html(5,5): Directive FormGroupDirective, Cannot find name '$event'
register.component.html(9,9): Directive DefaultValueAccessor, Property '_handleInput' does not exist on type 'DefaultValueAccessor'.
register.component.html(9,9): Directive DefaultValueAccessor, Cannot find name '$event'.
register.component.html(9,9): Directive DefaultValueAccessor, Property '_compositionStart' does not exist on type 'DefaultValueAccessor'.
register.component.html(9,9): Directive DefaultValueAccessor, Property '_compositionEnd' does not exist on type 'DefaultValueAccessor'. Did you mean '_compositionMode'?
register.component.html(21,9): Directive ɵbc, Cannot find name '$event'
```

More inconveniently, I'm also experiencing the original error of this issue. I narrowed it down (thanks to git bisect) to the else syntax:

```
<div class="text-center" *ngIf="!user; else loggedIn">
  <a class="btn btn-large btn-primary" routerLink="/login">Login</a>
  <a class="btn btn-large btn-primary" routerLink="/register">Register</a>
</div>
```

throws:

```
Illegal State: referring to a type without a variable {"filePath":"/Users/cedric/Code/ninjasquad/formation/Angular2/ponyracer/node_modules/@angular/core/core.d.ts","name":"TemplateRef","members":[]}
```

The issue should probably be reopened (cc @chuckjaz @tbosch )

**Comment by tbosch** [comment]
Part of https://github.com/angular/angular/issues/19792.

**Comment by tbosch** [comment]
Minimal reproduction is here: https://github.com/tbosch/ng-repro/tree/issue-19485

**Comment by tbosch** [comment]
Proposed solution:
- always add `TemplateRef` to the `externalReferences` in `AotCompiler._createNgFactoryStub` (see here)[https://github.com/angular/angular/blob/master/packages/compiler/src/aot/compiler.ts#L208].
