### ISSUE TITLE
Error In Production Build on Mac - Mojave (10.14.2)

### ISSUE THREAD

**Issue by omrsmeh** [angular/angular#28322]
# 🐞 bug report
I using the lazy loading of modules in angular. But I having the following problem...

### Issue is this
- When I am using the
`const routes: Routes = [
  { path: '', component: LoginComponent, pathMatch: 'full' },
  { path: 'login', component: LoginComponent },
  { path: 'news', loadChildren: './news/news.module#NewsModule', canActivate: [ AuthGuardService ] }
];`

It will not work in development environment, and show error in console after login
 
`ERROR Error: Uncaught (in promise): TypeError: undefined is not a function
TypeError: undefined is not a function
    at Array.map (<anonymous>)
    at webpackAsyncContext ($_lazy_route_resourc…namespace object:15)
    at SystemJsNgModuleLoader.push../node_modules/@angular/core/fesm5/core.js.SystemJsNgModuleLoader.loadAndCompile (core.js:17170)
    at SystemJsNgModuleLoader.push../node_modules/@angular/core/fesm5/core.js.SystemJsNgModuleLoader.load (core.js:17162)
    at RouterConfigLoader.push../node_modules/@angular/router/fesm5/router.js.RouterConfigLoader.loadModuleFactory (router.js:3608)
    at RouterConfigLoader.push../node_modules/@angular/router/fesm5/router.js.RouterConfigLoader.load (router.js:3596)
    at MergeMapSubscriber.project (router.js:2605)
    at MergeMapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._tryNext (mergeMap.js:61)
    at MergeMapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._next (mergeMap.js:51)
    at MergeMapSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (Subscriber.js:54)
    at resolvePromise (zone.js:831)
    at resolvePromise (zone.js:788)
    at zone.js:892
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:16147)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
    at drainMicroTaskQueue (zone.js:601)
    at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:502)
    at invokeTask (zone.js:1744)
defaultErrorLogger	@	core.js:14597
push../node_modules/@angular/core/fesm5/core.js.ErrorHandler.handleError	@	core.js:14645
next	@	core.js:16628
schedulerFn	@	core.js:12609
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub	@	Subscriber.js:196
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next	@	Subscriber.js:134
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next	@	Subscriber.js:77
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next	@	Subscriber.js:54
push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next	@	Subject.js:47
push../node_modules/@angular/core/fesm5/core.js.EventEmitter.emit	@	core.js:12593
(anonymous)	@	core.js:16178
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke	@	zone.js:391
push../node_modules/zone.js/dist/zone.js.Zone.run	@	zone.js:150
push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular	@	core.js:16115
onHandleError	@	core.js:16178
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.handleError	@	zone.js:395
push../node_modules/zone.js/dist/zone.js.Zone.runGuarded	@	zone.js:164
_loop_1	@	zone.js:694
api.microtaskDrainDone	@	zone.js:703
drainMicroTaskQueue	@	zone.js:608
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask	@	zone.js:502
invokeTask	@	zone.js:1744
globalZoneAwareCallback	@	zone.js:1781
error (async)		
customScheduleGlobal	@	zone.js:1883
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask	@	zone.js:410
onScheduleTask	@	zone.js:301
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask	@	zone.js:404
push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask	@	zone.js:238
push../node_modules/zone.js/dist/zone.js.Zone.scheduleEventTask	@	zone.js:264
(anonymous)	@	zone.js:2054
(anonymous)	@	http.js:1619
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable._trySubscribe	@	Observable.js:43
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe	@	Observable.js:29
(anonymous)	@	subscribeTo.js:21
subscribeToResult	@	subscribeToResult.js:11
push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._innerSub	@	mergeMap.js:74
push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._tryNext	@	mergeMap.js:68
push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._next	@	mergeMap.js:51
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next	@	Subscriber.js:54
(anonymous)	@	scalar.js:5
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable._trySubscribe	@	Observable.js:43
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe	@	Observable.js:29
push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapOperator.call	@	mergeMap.js:29
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe	@	Observable.js:24
push../node_modules/rxjs/_esm5/internal/operators/filter.js.FilterOperator.call	@	filter.js:15
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe	@	Observable.js:24
push../node_modules/rxjs/_esm5/internal/operators/map.js.MapOperator.call	@	map.js:18
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe	@	Observable.js:24
push../node_modules/rxjs/_esm5/internal/operators/catchError.js.CatchOperator.call	@	catchError.js:18
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe	@	Observable.js:24
push../src/app/core/login/login.component.ts.LoginComponent.onSubmit	@	login.component.ts:32
(anonymous)	@	LoginComponent.html:11
handleEvent	@	core.js:21673
callWithDebugContext	@	core.js:22767
debugHandleEvent	@	core.js:22470
dispatchEvent	@	core.js:19122
(anonymous)	@	core.js:20612
schedulerFn	@	core.js:12621
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub	@	Subscriber.js:196
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next	@	Subscriber.js:134
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next	@	Subscriber.js:77
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next	@	Subscriber.js:54
push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next	@	Subject.js:47
push../node_modules/@angular/core/fesm5/core.js.EventEmitter.emit	@	core.js:12593
push../node_modules/@angular/forms/fesm5/forms.js.FormGroupDirective.onSubmit	@	forms.js:5253
(anonymous)	@	LoginComponent.html:11
handleEvent	@	core.js:21673
callWithDebugContext	@	core.js:22767
debugHandleEvent	@	core.js:22470
dispatchEvent	@	core.js:19122
(anonymous)	@	core.js:19569
(anonymous)	@	platform-browser.js:993
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask	@	zone.js:423
onInvokeTask	@	core.js:16147
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask	@	zone.js:422
push../node_modules/zone.js/dist/zone.js.Zone.runTask	@	zone.js:195
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask	@	zone.js:498
invokeTask	@	zone.js:1744
globalZoneAwareCallback`

- And when I have fix it in development environment it will show error in production mode (i.e. when I create build through `ng build --prod --aot`) after login -

`main.7447ae5….js:1 ERROR Error: Uncaught (in promise): Error: Runtime compiler is not loaded
Error: Runtime compiler is not loaded
    at mo (main.7447ae5….js:1)
    at t.compileModuleAsync (main.7447ae5….js:1)
    at e.project (main.7447ae5….js:1)
    at e._tryNext (main.7447ae5….js:1)
    at e._next (main.7447ae5….js:1)
    at e.next (main.7447ae5….js:1)
    at t._subscribe (main.7447ae5….js:1)
    at t._trySubscribe (main.7447ae5….js:1)
    at t.subscribe (main.7447ae5….js:1)
    at t.call (main.7447ae5….js:1)
    at P (polyfills.20d0bb3….js:1)
    at P (polyfills.20d0bb3….js:1)
    at polyfills.20d0bb3….js:1
    at e.invokeTask (polyfills.20d0bb3….js:1)
    at Object.onInvokeTask (main.7447ae5….js:1)
    at e.invokeTask (polyfills.20d0bb3….js:1)
    at t.runTask (polyfills.20d0bb3….js:1)
    at g (polyfills.20d0bb3….js:1)
    at t.invokeTask [as invoke] (polyfills.20d0bb3….js:1)
    at m (polyfills.20d0bb3….js:1)
eo	@	main.7447ae5….js:1
t.handleError	@	main.7447ae5….js:1
next	@	main.7447ae5….js:1
e.object.i	@	main.7447ae5….js:1
e.__tryOrUnsub	@	main.7447ae5….js:1
e.next	@	main.7447ae5….js:1
e._next	@	main.7447ae5….js:1
e.next	@	main.7447ae5….js:1
e.next	@	main.7447ae5….js:1
e.emit	@	main.7447ae5….js:1
(anonymous)	@	main.7447ae5….js:1
e.invoke	@	polyfills.20d0bb3….js:1
t.run	@	polyfills.20d0bb3….js:1
t.runOutsideAngular	@	main.7447ae5….js:1
onHandleError	@	main.7447ae5….js:1
e.handleError	@	polyfills.20d0bb3….js:1
t.runGuarded	@	polyfills.20d0bb3….js:1
e	@	polyfills.20d0bb3….js:1
r.microtaskDrainDone	@	polyfills.20d0bb3….js:1
g	@	polyfills.20d0bb3….js:1
t.invokeTask	@	polyfills.20d0bb3….js:1
m	@	polyfills.20d0bb3….js:1
k	@	polyfills.20d0bb3….js:1
error (async)		
j	@	polyfills.20d0bb3….js:1
e.scheduleTask	@	polyfills.20d0bb3….js:1
onScheduleTask	@	polyfills.20d0bb3….js:1
e.scheduleTask	@	polyfills.20d0bb3….js:1
t.scheduleTask	@	polyfills.20d0bb3….js:1
t.scheduleEventTask	@	polyfills.20d0bb3….js:1
(anonymous)	@	polyfills.20d0bb3….js:1
(anonymous)	@	main.7447ae5….js:1
t._trySubscribe	@	main.7447ae5….js:1
t.subscribe	@	main.7447ae5….js:1
(anonymous)	@	main.7447ae5….js:1
X	@	main.7447ae5….js:1
e._innerSub	@	main.7447ae5….js:1
e._tryNext	@	main.7447ae5….js:1
e._next	@	main.7447ae5….js:1
e.next	@	main.7447ae5….js:1
(anonymous)	@	main.7447ae5….js:1
t._trySubscribe	@	main.7447ae5….js:1
t.subscribe	@	main.7447ae5….js:1
t.call	@	main.7447ae5….js:1
t.subscribe	@	main.7447ae5….js:1
t.call	@	main.7447ae5….js:1
t.subscribe	@	main.7447ae5….js:1
t.call	@	main.7447ae5….js:1
t.subscribe	@	main.7447ae5….js:1
t.call	@	main.7447ae5….js:1
t.subscribe	@	main.7447ae5….js:1
t.onSubmit	@	main.7447ae5….js:1
(anonymous)	@	main.7447ae5….js:1
handleEvent	@	main.7447ae5….js:1
handleEvent	@	main.7447ae5….js:1
$a	@	main.7447ae5….js:1
(anonymous)	@	main.7447ae5….js:1
e.object.i	@	main.7447ae5….js:1
e.__tryOrUnsub	@	main.7447ae5….js:1
e.next	@	main.7447ae5….js:1
e._next	@	main.7447ae5….js:1
e.next	@	main.7447ae5….js:1
e.next	@	main.7447ae5….js:1
e.emit	@	main.7447ae5….js:1
e.onSubmit	@	main.7447ae5….js:1
(anonymous)	@	main.7447ae5….js:1
handleEvent	@	main.7447ae5….js:1
handleEvent	@	main.7447ae5….js:1
$a	@	main.7447ae5….js:1
(anonymous)	@	main.7447ae5….js:1
(anonymous)	@	main.7447ae5….js:1
e.invokeTask	@	polyfills.20d0bb3….js:1
onInvokeTask	@	main.7447ae5….js:1
e.invokeTask	@	polyfills.20d0bb3….js:1
t.runTask	@	polyfills.20d0bb3….js:1
t.invokeTask	@	polyfills.20d0bb3….js:1
m	@	polyfills.20d0bb3….js:1`

### Description

My Package file will be:
`
{
  "name": "indian-apps-ui",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^7.1.4",
    "@angular/cdk": "^7.2.0",
    "@angular/common": "~7.1.0",
    "@angular/compiler": "~7.1.0",
    "@angular/core": "~7.1.0",
    "@angular/flex-layout": "^7.0.0-beta.23",
    "@angular/forms": "~7.1.0",
    "@angular/material": "^7.2.0",
    "@angular/platform-browser": "~7.1.0",
    "@angular/platform-browser-dynamic": "~7.1.0",
    "@angular/router": "~7.1.0",
    "@ngx-pwa/local-storage": "^7.3.0",
    "core-js": "^2.5.4",
    "hammerjs": "^2.0.8",
    "ngx-store": "^2.1.0",
    "rxjs": "~6.3.3",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.12.1",
    "@angular/cli": "~7.1.4",
    "@angular/compiler-cli": "~7.1.0",
    "@angular/language-service": "~7.1.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.1.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.1.6"
  }
}
`
I am following Angular guide to create lazy module loading but not successful.

Additionally, I have created two function in my `app-routing.module.ts` file, called `actualFileName, childComponentName` and used it as follows:

`import { environment } from '../environments/environment';
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { LoginComponent } from './core/login/login.component';
import { AuthGuardService } from './service/auth-guard.service';
import { NewsModule } from './news/news.module';

const actualFileName = (fileName: string): string => {
  fileName = fileName.replace('-a', 'A').replace('-b', 'B').replace('-c', 'C').replace('-d', 'D').replace('-e', 'E')
             .replace('-f', 'F').replace('-g', 'G').replace('-h', 'H').replace('-i', 'I').replace('-j', 'J')
             .replace('-k', 'K').replace('-l', 'L').replace('-m', 'M').replace('-n', 'N').replace('-o', 'O')
             .replace('-p', 'P').replace('-q', 'Q').replace('-r', 'R').replace('-s', 'S').replace('-t', 'T')
             .replace('-u', 'U').replace('-v', 'V').replace('-w', 'W').replace('-x', 'X').replace('-y', 'Y')
             .replace('-z', 'Z');
  let fileNameArr = fileName.split('.');
  fileName = '';

  fileNameArr.forEach(n => {
    fileName += n.substr(0, 1).toUpperCase() + n.substr(1);
  });

  return fileName;
}

const childComponentName = (fileName: string, loadFileName: any): any => {
  let returnVal: any = () => loadFileName;

  if(environment.production === true) {
    let fName = fileName.substr(fileName.lastIndexOf('/') + 1);
    returnVal = (fileName + '#' + actualFileName(fName)).toString();
  }

  return returnVal;
}

const routes: Routes = [
  { path: '', component: LoginComponent, pathMatch: 'full' },
  { path: 'login', component: LoginComponent },
  { path: 'news', loadChildren: childComponentName('./news/news.module', NewsModule), canActivate: [ AuthGuardService ] }
];

@NgModule({
  imports: [RouterModule.forRoot(routes, {useHash: true})],
  exports: [RouterModule]
})
export class AppRoutingModule { }
`

Which convert `loadChildren` into function in development environment and `loadChildren` into string which specified module name.  

Mac OS: Mojave (10.14.2)
Node: v11.6.0
NPM: 6.5.0-next.0
Other Versions as follows: 

Angular CLI: 7.1.4
Node: 11.6.0
OS: darwin x64
Angular: 7.1.4
... cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.2
@angular-devkit/build-angular     0.12.2
@angular-devkit/build-optimizer   0.12.2
@angular-devkit/build-webpack     0.12.2
@angular-devkit/core              7.2.2
@angular-devkit/schematics        7.1.4
@angular/animations               7.2.1
@angular/cdk                      7.2.1
@angular/flex-layout              7.0.0-beta.23
@angular/material                 7.2.1
@ngtools/webpack                  7.2.2
@schematics/angular               7.1.4
@schematics/update                0.11.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.28.4

Please help me...
