### ISSUE TITLE
Typings is missing in zone.js 0.11.1

### ISSUE THREAD

**Issue by OpportunityLiu** [angular/angular#38584]
# 🐞 bug report

### Affected Package

 

After update zone.js from 0.10.3 to 0.11.1, my code
```ts

    const bluebirdPatchSymbol = Zone.__symbol__('bluebird') as keyof ZoneType;
    const bluebirdPatch = Zone[bluebirdPatchSymbol] as (b: typeof Bluebird) => void;
    bluebirdPatch(Bluebird);
```
 reports 
```
ERROR in error TS2688: Cannot find type definition file for 'zone.js'.
src/browser/main.ts:14:33 - error TS2304: Cannot find name 'Zone'.

14     const bluebirdPatchSymbol = Zone.__symbol__('bluebird') as keyof ZoneType;
                                   ~~~~
src/browser/main.ts:14:70 - error TS2304: Cannot find name 'ZoneType'.

14     const bluebirdPatchSymbol = Zone.__symbol__('bluebird') as keyof ZoneType;
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 0.10.3

### Description

`"typings"` field is missing in new package.json.

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

in #36540
```

    typings property are removed from package.json, instead using files property, because now we have several d.ts files as typings.

"files": [
    "./zone.js.d.ts",
    "./zone.api.extensions.ts",
    "./zone.configurations.api.ts"
  ],

```

in #38528
```
After update to APF, the directories and files options are not compatible,
so we need to remove those fileds to make sure everything work as expected.
```

**Comment by OpportunityLiu** [comment]
Currently using
```ts
/// <reference types="zone.js/zone.js" />
```
as a workaround

**Comment by JiaLiPassion** [comment]
@OpportunityLiu , thank you for reporting the issue, I will fix this one asap.
