### ISSUE TITLE
double escaped backtick in template literal string in template html  breaks from @angular/ v21.2.2

### ISSUE THREAD

**Issue by emeryao** [angular/angular#67675]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

No

### Description

```html
@let versionInfo = `Version: \`${info}\``;
<div>{{ versionInfo }}</div>
```

double escaped backtick in template html cause a error with version `21.2.2` and later but works with version `21.2.1`

the scenario is that I just want to show some markdown string literals in the template html so I have to escape the backtick symbol to make it a code block for markdown

and if I remove the second escaped backtick it works again with version `21.2.2`

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-yviu1qjq

and below is the worked link with the same codes but with version `21.2.1`

https://stackblitz.com/edit/stackblitz-starters-ntqt2vnt

### Please provide the exception or error you saw

```true
TS2304: Cannot find name '_t1'. [plugin angular-compiler]
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI       : 21.2.2
Angular           : 21.2.2
Node.js           : 22.22.0
Package Manager   : npm 10.8.2
Operating System  : linux x64

┌───────────────────────────┬───────────────────┬───────────────────┐
│ Package                   │ Installed Version │ Requested Version │
├───────────────────────────┼───────────────────┼───────────────────┤
│ @angular/build            │ 21.2.2            │ 21.2.2            │
│ @angular/cli              │ 21.2.2            │ 21.2.2            │
│ @angular/common           │ 21.2.2            │ 21.2.2            │
│ @angular/compiler         │ 21.2.2            │ 21.2.2            │
│ @angular/compiler-cli     │ 21.2.2            │ 21.2.2            │
│ @angular/core             │ 21.2.2            │ 21.2.2            │
│ @angular/forms            │ 21.2.2            │ 21.2.2            │
│ @angular/platform-browser │ 21.2.2            │ 21.2.2            │
│ @angular/router           │ 21.2.2            │ 21.2.2            │
│ rxjs                      │ 7.8.2             │ ^7.8.2            │
│ typescript                │ 5.9.3             │ ^5.9.3            │
└───────────────────────────┴───────────────────┴───────────────────┘
```

### Anything else?

Please help and sorry for my poor English

**Comment by emeryao** [comment]
fow now I have to use concatenated strings to workaround this 
```html
@let versionInfo = '`Version: `' + `${info}` + '`';
<div>{{ versionInfo }}</div>
```
