### ISSUE TITLE
Angular 5: this.http.get(...).map is not a function

### ISSUE THREAD

**Issue by ebrehault** [angular/angular#20460]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

With Angular 5.0.0 and 5.0.1, when using the RxJS `map` operator on a HttpClient method (like `get` or `post`), we get the following error:

```
this.http.get(...).map is not a function
```

The very same thing used to work with Angular 4.4.

But maybe I am missing something super obvious.

## Expected behavior

It should apply the map to the observable and return a new observable.

## Minimal reproduction of the problem with instructions

Basic example:

```
import { HttpClient } from '@angular/common/http';
import { map } from 'rxjs/operators';
...
    this.http.get('https://reqres.in/api/users')
      .map(res => res.data)
      .subscribe(res => console.log(res));
```
Here is a plunker which shows the error: http://plnkr.co/edit/D53FgpSxYwMQo9C1PVgy?p=preview

## Environment

<pre><code>
Angular version: 5.0.1

Browser:
- [x] Chrome (desktop) version 62.0.3202.94
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8
- Platform:  Mac

Others:

</code></pre>

**Comment by mlc-mlapis** [comment]
`HttpClient` implementation includes already inner using of the `map` ... it works for you automatically

**Comment by ericmartinezr** [comment]
Plus what @mlc-mlapis commented, you're mixing lettable operators and the prototype patching method. Use one or the other.

For your case it should be 

```
      this.http.get('https://reqres.in/api/users')
      .pipe(
        map(res => res.data) // or any other operator
      )
      .subscribe(res => console.log(res));
```
As mentioned here https://github.com/ReactiveX/rxjs/blob/master/doc/lettable-operators.md

[Example](https://stackblitz.com/edit/angular-1lrkza?file=app%2Fapp.component.ts).

**Comment by ebrehault** [comment]
Oh ok, maybe I read the upgrade recommandations too quickly when moving to Angular 5 :)

Thank you very much :)

**Comment by ShashankBodkhe** [comment]
@ ericmartinezr commented on Nov 16, 2017 - Thank you so much :)

**Comment by juanlet** [comment]
I dont see the breakpoint stoping inside  that map function if it's inside a pipe...any idea why??

**Comment by madrugada21** [comment]
@ericmartinezr   You saved my day!!!
