### ISSUE TITLE
TS2314: Generic type 'Type<T>' requires 1 type argument(s) - after upgrade to 2.0.0-rc.7

### ISSUE THREAD

**Issue by squarewave24** [angular/angular#11616]
getting this error after upgrading to angular 2.0.0-rc.7

this error comes from:
`node_modules/@angular/router/config.d.ts(6,17): error TS2314: Generic type 'Type<T>' requires 1 type argument(s)`

as far as I can tell this is a typescript compatibility issue. I ensured that I upgraded to latest typescript: 
```
$ tsc -v
Version 2.0.0
```

here is my package.json
```
  "dependencies": {
    "@angular/common": "2.0.0-rc.7",
    "@angular/compiler": "2.0.0-rc.7",
    "@angular/core": "2.0.0-rc.7",
    "@angular/forms": "2.0.0-rc.7",
    "@angular/http": "2.0.0-rc.7",
    "@angular/platform-browser": "2.0.0-rc.7",
    "@angular/platform-browser-dynamic": "2.0.0-rc.7",
    "@angular/upgrade": "2.0.0-rc.7",
    "@angular/router": "3.0.0-alpha.7",
    "ag-grid": "5.2.x",
    "ag-grid-ng2": "5.2.3",
    "angular2-in-memory-web-api": "0.0.19",
    "bootstrap": "^3.3.6",
    "core-js": "^2.4.1",
    "jquery": "3.1.0",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.12",
    "systemjs": "0.19.27",
    "zone.js": "0.6.21"
  },
  "devDependencies": {
    "concurrently": "^2.2.0",
    "lite-server": "^2.2.2",
    "typescript": "^2.0.2",
    "typings":"^1.3.2"
  }
```

**Comment by herlon214** [comment]
:+1:

**Comment by brandonroberts** [comment]
Your installed version of the router is too old. The latest version is `3.0.0-rc.3`

**Comment by vicb** [comment]
Thanks @brandonroberts

**Comment by squarewave24** [comment]
thanks but the version of router i had was actually newer than 3.0.0-rc.3. I initially started with this one but it was missing things to work with rc.7 angular. 

since final version came out today I updated my config per guidelines [here ](https://angular.io/docs/ts/latest/quickstart.html)and trying to get that to work now.
