### ISSUE TITLE
Angular build issue

### ISSUE THREAD

**Issue by smangalath** [angular/angular#20767]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Got the latest angular code cloned locally and after the pre-requisites are done, ran ./build.sh
building is not working

## Expected behavior

./build.sh to compile packages

## Minimal reproduction of the problem with instructions

1. Clone the latest angular
2. Complete pre-requisites
3. run ./build.sh
## What is the motivation / use case for changing the behavior?

Build to work properly

## Environment
Mac pro
<pre><code>
Angular version: X.Y.Z

Latest
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 NA
For Tooling issues:
- Node version: XX  
- Platform:  
Node 6.9.1
Mac platform
Others:

</code></pre>
Error message
angular/dist/tools/@angular/compiler-cli/src/perform_compile.js:200
        if (compiler_1.isSyntaxError(e)) {
                       ^

TypeError: compiler_1.isSyntaxError is not a function

**Comment by IgorMinar** [comment]
Are you on the master branch? The master is building just fine. I just verified it locally.

What version of node are you using? And have you used yarn to install dependencies?

**Comment by smangalath** [comment]
Hello Igor,
Thank you very much for responding to my  request. 
Node : I am using version 6.11.1
Yes I am using yarn to resolve dependencies.

**Comment by IgorMinar** [comment]
Try fetching and checking our master again? Also upgrade to node 8 which we just upgraded to and reinstall your yarn dependencies.

**Comment by smangalath** [comment]
Tried with the latest clone from master after upgrading nodejs to 8.x. it stops at the same error reported above. export and imports are  found to be proper for isSyntaxError
Seems to be a transient issue.
Repro steps
Pre-requisite : upgrade nodejs 8.x

1. get the master cloned
2. yarn install to resolve dependencies
3. ./build.sh to build angular
it is erroring out the step#3

**Comment by vicb** [comment]
Is this still an issue ?
