### ISSUE TITLE
After update angular 16 - property '_isScalar' does not exist on type 'Observable<any[]>'.

### ISSUE THREAD

**Issue by karthigamahe** [angular/angular#56818]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

I recently updated to angular 16 from V15, After change the observable which we declared doesn't contain/returning the propertly '_isScalar' which is worked before

 "rxjs": "~7.5.5",
  "tslib": "^2.3.0",
 "@angular/core": "^16.2.12",

this is the observable
`  rowData = new Observable<any[]>();
`
we are checking this  _isScalar like below

```
if (this.rowData._isScalar !== false) {
//some code
}
```

This was perfectly working fine in angular 15 after updated to 16 application showing compilation error like below

```
 error TS2339: Property '_isScalar' does not exist on type 'Observable<any[]>'.

259     if (this.rowData._isScalar !== false) {
```

```
error TS2322: Type 'Observable<any[]>' is not assignable to type 'any[]'.

56     <ag-grid-angular id="ga_Grid" style="width: 100%;height:100%" class="ag-theme-alpine" [rowData]="rowData"
                                                                                              ~~~~~~~
```

I need a help here why the observable not returning _isScalar propertly or do i need to change the declaration part

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular cli - 16.2.12
```

### Anything else?

Please help me to resolve this issue or alternate way to handle this

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

---

`Observable._isScalar` used to be an internal field of `Observable`, it was made visible in https://github.com/ReactiveX/rxjs/pull/3520 with a comment to indicate it's internal (also reflected in the use of the underscore prefix, which is a convention for a private field) and this field was eventually removed in https://github.com/ReactiveX/rxjs/pull/5572.

**Comment by karthigamahe** [comment]
@JoostK  since it was removed so we shouldn't use this internal field or do we any other alternates

**Comment by karthigamahe** [comment]
Okay Thank you.. In out code we are using isScalar to conditional check if its false we are setting up some values. so in this case if we remove the condition case will it be  cause of any issue or we missing any important check ?
