### ISSUE TITLE
Compilation breaks after update to 9.0.0-rc.13: `Duplicate identifier 'ɵngcc0'`

### ISSUE THREAD

**Issue by cyrilletuzi** [angular/angular#35095]
# 🐞 bug report

### Affected Package
I think the issue is in `@angular/compiler-cli` as it's about `ngcc`, but not sure.

### Is this a regression?

Yes, it was OK in previous RC (rc.12 and below).

### Reproduction

- `npm install @angular/cli@next -g`
- `ng new helloworld --skipGit` (git is disabled to avoid ng commands blocking because repo is not clean, otherwise you have to commit every change)
- `cd helloworld`
- `npm install @angular/{animations,common,compiler,core,forms,platform-browser,platform-browser-dynamic,router,compiler-cli,language-service}@9.0.0-rc.12` (rollback to rc.12, as CLI installed rc.13)
- add any library, for example: `ng add @angular/material@next` and add `MatCardModule` in `AppModule` imports
- `npm start` (to run the compilation with rc.12)
- `ng update @angular/core --next` (will update to rc.13)
- `npm start` 

## 🔥 Exception or Error

Compilation breaks with a lot of errors like this one (it's just an example):

<pre><code>
import * as ɵngcc0 from '@angular/core';
                   ~~~~~~
    node_modules/@angular/material/core/selection/pseudo-checkbox/pseudo-checkbox.d.ts:13:13 -
error TS2300: Duplicate identifier 'ɵngcc0'.
</code></pre>


## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-rc.12
Node: 12.14.1
OS: darwin x64

Angular: 9.0.0-rc.13
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.12
@angular-devkit/build-angular     0.900.0-rc.12
@angular-devkit/build-optimizer   0.900.0-rc.12
@angular-devkit/build-webpack     0.900.0-rc.12
@angular-devkit/core              9.0.0-rc.12
@angular-devkit/schematics        9.0.0-rc.12
@angular/cdk                      9.0.0-rc.9
@angular/cli                      9.0.0-rc.12
@angular/material                 9.0.0-rc.9
@ngtools/webpack                  9.0.0-rc.12
@schematics/angular               9.0.0-rc.12
@schematics/update                0.900.0-rc.12
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**
Quite sure the issue comes from #35079. Before rc.13, when ng updating, next compilation would be blocked, asking to clean up `node_moddules` (#35082).

With rc.13, compilation is not blocked anymore, Angular do a new `ngcc` compilation (`Compiling @angular/core : es2015 as esm2015`), but then fails because of old artifacts. If you clean `node_modules` (`npm ci`), then compilation works again.

Also note that:
- if you have no library at all, the issue doesn't happen,
- it's not specific to Material, it happens with all librairies.

So I think #35079 does not clean up libraries packages.

**Comment by IgorMinar** [comment]
I've tried to repro this in https://github.com/angular/angular/pull/35101 but so far I'm not having luck.

**Comment by cyrilletuzi** [comment]
Repro: [https://github.com/cyrilletuzi/ngcc-cleanup](https://github.com/cyrilletuzi/ngcc-cleanup)

To reproduce:

```bash
git clone https://github.com/cyrilletuzi/ngcc-cleanup
cd ngcc-cleanup
npm run issue
```

**Comment by gkalpak** [comment]
Thx for the repro, @cyrilletuzi. It really helped the to the bottom of it more quickly 💯

So, it turns out we are not invalidating our `FileSystem` cache correctly [when moving a file][1] or [when removing a directory][2] during clean-up. I have verified the fix against your repro - PR incoming 🚀 

[1]: https://github.com/angular/angular/blob/4d36b2f6e/packages/compiler-cli/src/ngtsc/file_system/src/cached_file_system.ts#L73-L81
[2]: https://github.com/angular/angular/blob/4d36b2f6e/packages/compiler-cli/src/ngtsc/file_system/src/cached_file_system.ts#L93-L98
