### ISSUE TITLE
ngcc generates invalid property metadata

### ISSUE THREAD

**Issue by devversion** [angular/angular#30569]
# 🐞 bug report

### Affected Package

`@angular/compiler-cli` / `ngcc`

### Description

Currently when compiling `@angular/cdk/a11y` with `ngcc`, the generated property metadata call (`setClassMetadata`) incorrectly sets metadata for the `autoCapture` property within the `FocusTrap` twice.

```ts
ɵngcc0.ɵsetClassMetadata(..., {
  autoCapture: [{
      type: Input,
      args: ['cdkTrapFocusAutoCapture']
    }], 
  autoCapture: [], 
});
```

This means that the first occurrence will be accidentally overwritten and the metadata is discarded. The duplication seems to happen because `autoCapture` declares a `getter` and a `setter`.

As far as I could tell the issue is that `ngcc` returns the getter and setter for `reflection.getMembersOfClass(FocusTrap)` but sets decorators that are either defined on getter or setter as `decorators` for both members. This then results in two properties with the same name in the `setClassMetadata` call.

 https://github.com/angular/angular/blob/master/packages/compiler-cli/src/ngtsc/annotations/src/metadata.ts#L59-L62

## 🔬 Minimal Reproduction

https://github.com/devversion/ivy-ngcc-generates-duplicate-prop-metadata

## 🔥 Exception or Error

See: https://github.com/angular/components/issues/16066

Defining the same property multiple times seems to cause an exception in IE11 with `use strict` mode. This is actually reasonable as the first declaration is accidentally overwritten in an object literal.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
@angular/*: 8.0.0-rc.4
@angular/cdk: 8.0.0-rc.1
</code></pre>

**Comment by ajosef** [comment]
[#30637](https://github.com/angular/angular/issues/30637) is closed, which was marked as a duplicate of this issue, but Ivy is still not working on IE11 even in Angular 8.1. 
Is there any way to make Ivy work on IE11?
Is anyone tracking this issue?

**Comment by rajeshmogasala** [comment]
Same problem for me also.Could you please tell us is it fixed or do we have any work around ?
Thank you.
SCRIPT1046: Multiple definitions of a property not allowed in strict mode

**Comment by preli** [comment]
Same for me

**Comment by filipesilva** [comment]
I see this happening in Angular CLI 9.0.0-next.0 apps using IE10:
```
SCRIPT1046: Multiple definitions of a property not allowed in strict mode
```
```
/*@__PURE__*/ _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵsetClassMetadata"](NgForOf, [{
        type: _angular_core__WEBPACK_IMPORTED_MODULE_0__["Directive"],
        args: [{ selector: '[ngFor][ngForOf]' }]
    }], function () { return [{ type: _angular_core__WEBPACK_IMPORTED_MODULE_0__["ViewContainerRef"] }, { type: _angular_core__WEBPACK_IMPORTED_MODULE_0__["TemplateRef"] }, { type: _angular_core__WEBPACK_IMPORTED_MODULE_0__["IterableDiffers"] }]; }, { _viewContainer: [], _template: [], _differs: [], _ngForOfDirty: [], _differ: [], ngForOf: [{
            type: _angular_core__WEBPACK_IMPORTED_MODULE_0__["Input"]
        }], ngForTrackBy: [{
            type: _angular_core__WEBPACK_IMPORTED_MODULE_0__["Input"]
        }], ngForTrackBy: [], ngForTemplate: [{
            type: _angular_core__WEBPACK_IMPORTED_MODULE_0__["Input"]
        }], ngDoCheck: [], _applyChanges: [], _perViewChange: [] });
    return NgForOf;
}());
```

**Comment by richardbrammer** [comment]
I get the same error using Ivy and IE11 in vendor-es5.js

**Comment by Splaktar** [comment]
Is `freq1: low` correct for this issue? It seems a little low for an issue that breaks apps on an entire, supported, browser?

**Comment by matzematthaey** [comment]
same issue for us. blocks using angular8+ in IE11.

**Comment by gkalpak** [comment]
@matzematthaey: Just to clarify, this issue if about ngcc, which means that it only affects app with Ivy turned on (which is the default in v9, but not v8).

**Comment by SpeedoPasanen** [comment]
In case someone needs to push an IVY app to production now (not sure if it's a good idea) and support IE, a workaround is to search `"use strict";` in `dist/*-es5` and replace all occurrances with empty.

**Comment by james-schwartzkopf** [comment]
> In case someone needs to push an IVY app to production now (not sure if it's a good idea) and support IE, a workaround is to search `"use strict";` in `dist/*-es5*` and replace all occurrances with empty.

Better to replace it with '"----------"; so source maps, etc. still line up.

This is the script we are using:
```
import * as fs from 'fs';
import * as path from 'path';

//TODO get rid of this once @angular/angular #30569 is fixed
//https://github.com/angular/angular/issues/30569

const [_, __, ...dirs] = process.argv;

dirs.forEach(
  dir => fs.readdirSync(dir)
    .filter(filename => /[.]js$/.test(filename))
    .filter(filename => !/-es2015(|[.][0-9a-f]+)[.]js$/.test(filename))
    .forEach(filename => {
      const filepath = path.join(dir, filename);
      const text = fs.readFileSync(filepath, 'utf-8');
      const newText = text.replace(/"use strict";/g, '"----------";');
      if (newText !== text) {
        fs.writeFileSync(filepath, newText, 'utf-8');
      }
    })
);
```

**Comment by nmainardi** [comment]
this problem still persisting with this configuration:
```
Angular CLI: 8.3.20
Node: 13.2.0
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.20
@angular-devkit/build-angular     0.803.20
@angular-devkit/build-optimizer   0.803.20
@angular-devkit/build-webpack     0.803.20
@angular-devkit/core              8.3.20
@angular-devkit/schematics        8.3.20
@angular/cli                      8.3.20
@ngtools/webpack                  8.3.20
@schematics/angular               8.3.20
@schematics/update                0.803.20
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
```
If you need my test project I'm going to upload it tomorrow. 
@james-schwartzkopf how to implement your workaround? How are you using your script? Thank you all

**Comment by M4R1KU** [comment]
@nmainardi It is fixed in 9.0.0-rc.3. You have to upgrade to atleast this version.
