### ISSUE TITLE
window.screen.orientation does not work in typescript (v2.3.3) used in angular 2/4

### ISSUE THREAD

**Issue by harishkumar329** [angular/angular#20814]
Getting following error when I try to lock the screen orientation,

Property 'lockOrientation' does not exist on type 'Screen'

**Type script Code (v2.3.3)**
var lockFunction =  window.screen.lockOrientation || window.screen.mozLockOrientation || window.screen.msLockOrientation || window.screen.orientation;

The same works with the following **JQuery code**
var lockFunction =  window.screen.orientation.lock;
if($.isFunction(lockFunction)){
	lockFunction.call(window.screen.orientation, 'landscape');
}
It is a native web app, not trying with ionic or PhoneGap.

Thanks in advance.

**Comment by pkozlowski-opensource** [comment]
See https://github.com/angular/angular/issues/20802#issuecomment-349358300

There is really _no_ point in re-opening the same issue over and over again, the answer is in the provided link. It seems to be an issue that is already tracked in TypeScript: https://github.com/Microsoft/TypeScript/issues/18480
