### ISSUE TITLE
TypeScript Infinity and NaN errors

### ISSUE THREAD

**Issue by p3pp8** [angular/angular#54744]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

After updating to V17 core and material i'm facing this issue:

```
Error: node_modules/@angular/common/index.d.ts:2880:5 - error TS2452: An enum member cannot have a numeric name.

2880     Infinity = 9,
         ~~~~~~~~


Error: node_modules/@angular/common/index.d.ts:2885:5 - error TS2452: An enum member cannot have a numeric name.

2885     NaN = 10,
         ~~~
```

As **Infinity** and **NaN** are part of another enum and are at least reserved.

Any help appreciated!

### Please provide the exception or error you saw

```true
Error: node_modules/@angular/common/index.d.ts:2880:5 - error TS2452: An enum member cannot have a numeric name.

2880     Infinity = 9,
         ~~~~~~~~


Error: node_modules/@angular/common/index.d.ts:2885:5 - error TS2452: An enum member cannot have a numeric name.

2885     NaN = 10,
         ~~~
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.2.3
Node: 18.19.1
OS: windows 11

Angular Material: V17.2.2
```

**Comment by JoostK** [comment]
This is due to using TypeScript 5.4, which only becomes supported in 17.3 which has not yet been released.
