### ISSUE TITLE
[bug] Migrating 8 to 9  Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas'

### ISSUE THREAD

**Issue by indraraj26** [angular/angular#35644]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ng 8 

### Description
Getting lot of errors in console after migrating 8 to 9 even for children shared component which is exported from shared.module.ts;

```
src/app/masters/components/holiday/manage-holidays/manage-holidays.component.html:16:m40 - error NG8002: Can't bind to 'formGroup' since it isn't a known property of 'form'.

    16             <form class="example-form" [formGroup]="manageHoliday" (ngSubmit)="onSubmit()">

```

```
 error NG8001: 'app-alert' is not a known element:
    1. If 'app-alert' is an Angular component, then verify that it is part of this module.
    2. If 'app-alert' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

    19                         <app-alert [type]="'danger'" [message]="errorMessage"></app-alert>
```

in Browser console:
```
core.js:3866 ERROR Error: Uncaught (in promise): Error: Angular JIT compilation failed: '@angular/compiler' not loaded!
  - JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
  - Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
  - Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping.
Error: Angular JIT compilation failed: '@angular/compiler' not loaded!
  - JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
  - Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
  - Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping.
    at getCompilerFacade (core.js:548)
    at Function.get (core.js:25892)
    at getNgModuleDef (core.js:1865)
    at new NgModuleFactory (core.js:24245)
    at Compiler_compileModuleSync__POST_R3__ (core.js:27071)
    at Compiler_compileModuleAsync__POST_R3__ [as compileModuleAsync] (core.js:27076)
    at MergeMapSubscriber.project (router.js:3632)
    at MergeMapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._tryNext (mergeMap.js:61)
    at MergeMapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._next (mergeMap.js:51)
    at MergeMapSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (Subscriber.js:53)
    at resolvePromise (zone.js:836)
    at resolvePromise (zone.js:795)
    at zone.js:897
    at ZoneDelegate.invokeTask (zone.js:431)
    at Object.onInvokeTask (core.js:27453)
    at ZoneDelegate.invokeTask (zone.js:430)
    at Zone.runTask (zone.js:198)
    at drainMicroTaskQueue (zone.js:611)
    at ZoneTask.invokeTask [as invoke] (zone.js:517)
    at invokeTask (zone.js:1671)
```
```
src/app/shared/shared.module.ts:121:14 - error NG6002: Appears in the NgModule.imports of SettingsModule, but itself has errors

121 export class SharedModule {}
```

In browser console
```
core.js:3866 ERROR Error: ASSERTION ERROR: Stored value should never be NO_CHANGE. [Expected=> [object Object] !== [object Object] <=Actual]
    at throwError (core.js:1078)
    at assertNotSame (core.js:1042)
    at getBinding (core.js:13250)
    at pureFunction1Internal (core.js:24588)
    at Module.ɵɵpipeBind1 (core.js:24746)
    at NgTableComponent_tbody_10_tr_1_ng_template_3_ng_container_0_td_1_Template (ng-table.component.html:45)
    at executeTemplate (core.js:7562)
    at refreshView (core.js:7439)
    at refreshDynamicEmbeddedViews (core.js:8505)
    at refreshView (core.js:7459)
```
code : 
```
<ng-container *ngFor="let key of settings[1].keys">
                <td *ngIf="!isButton(key);else button">{{item[key] | ckescape | date}}</td>
                <ng-template #button>
                  <td *ngIf="key === 'payment_status'; else noAction" style="cursor: pointer;" (click)="handleActionClick(key, ind)">
                    <div>
                      <span [ngClass]="settings[0].custom?.buttons?.values[key][item[key]]['class']" class="label">{{settings[0].custom?.buttons?.values[key][item[key]]['name']}}</span>
                    </div>
                  </td>
                  <ng-template #noAction>
                    <td>
                      <div>
                        <span [ngClass]="settings[0].custom?.buttons?.values[key][item[key]]['class']" class="label">{{settings[0].custom?.buttons?.values[key][item[key]]['name']}}</span>
                      </div>
                    </td>
                  </ng-template>
                </ng-template>
              </ng-container>
```
## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 9.0.3
Node: 10.16.0
OS: win32 x64

Angular: 9.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.3
@angular-devkit/build-angular     0.900.3
@angular-devkit/build-optimizer   0.900.3
@angular-devkit/build-webpack     0.900.3
@angular-devkit/core              9.0.3
@angular-devkit/schematics        9.0.3
@angular/cdk                      8.1.4
@angular/cli                      9.0.3
@angular/material                 8.1.4
@ngtools/webpack                  9.0.3
@schematics/angular               9.0.3
@schematics/update                0.900.3
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

**Comment by indraraj26** [comment]
It is resolved by running again and again ng serve -o and ng serve -o --aot

for this error :  core.js:3866 ERROR Error: ASSERTION ERROR: Stored value should never be NO_CHANGE. [Expected=> [object Object] !== [object Object] <=Actual]

i had to change pipe name **date** to **customDate**
