### ISSUE TITLE
AoT compilation fails when emitting metadata and the outDir does not yet exist

### ISSUE THREAD

**Issue by elwynelwyn** [angular/angular#13359]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
Setup tsconfig.json to emit metadata, and specify an `outDir`:
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "declaration": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["dom", "es6"],
    "module": "commonjs",
    "moduleResolution": "node",
    "noEmitOnError": true,
    "noImplicitAny": false,
    "outDir": "./dist",
    "rootDir": "./src",
    "sourceMap": true,
    "target": "es5",
    "inlineSources": false
  },

  "files": [
    "./src/index.ts"
  ],

  "angularCompilerOptions": {
    "genDir": "compiled",
    "skipMetadataEmit" : false,
    "strictMetadataEmit": true
  }
}
```

Delete the outDir prior to compiling, e.g. with these npm scripts:
```
  "scripts": {
    "prebuild": "rimraf ./dist ./compiled",
    "build": "ngc -p ./tsconfig.json"
  },
```
(where `rimraf` is a delete utility)

Run the build script

**Expected behavior**
I expect compiled js, maps, .d.ts and metadata.json to be created in `/dist`
However, no output is created, and the compilation crashes out with:
`Error: ENOENT: no such file or directory, open 'D:\data\myPorject\dist\my-file.metadata.json'`

This is because in `@angular\tsc-wrapped\src\compiler_host.js` inside this function `MetadataWriterHost.prototype.writeMetadata`  `fs.writeFileSync` is called without checking if the directory exists.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
Ability to clean before build

**Please tell us about your environment:**
OS: Windows 10
IDE: WebStorm
PM: npm

* **Angular version:** 2.0.X
"@angular/compiler": "2.3.0",
"@angular/compiler-cli": "2.3.0",
"@angular/core": "2.3.0",
"@angular/platform-server": "2.3.0",

* **Browser:**
n/a
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.0.10

* **Node (for AoT issues):** `node --version` =   
v6.9.1

**Comment by Delagen** [comment]
+1 does not fixed in 4.0.0-rc.2

**Comment by Tuupertunut** [comment]
For some reason, a workaround that worked for me was updating typescript to the latest (2.2.1) version.

**Comment by DzmitryShylovich** [comment]
@Delagen still doesn't work in 4.0?

**Comment by Delagen** [comment]
Seems to fixed in latest build. Error appeared when skipTemplateCodegen option used. Now this works as I know

**Comment by DzmitryShylovich** [comment]
@elwynelwyn can you confirm, please, that it works without errors in the latest version and close the issue? thanks

**Comment by dherges** [comment]
@DzmitryShylovich have a similar issue here. `ngc` fails after the `dist` folder was truncated. However, running `tsc` prior to `ngc` works.


```bash
$ rm -rf dist
$ node_modules/.bin/ngc -p src/lib/tsconfig.lib.json
Error: ENOENT: no such file or directory, open '....dist\ng-hal\lib\rxjs\follow.metadata.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at MetadataWriterHost.writeMetadata (...\node_modules\@angular\tsc-wrapped\src\compiler_host.js:164:22)
    at MetadataWriterHost.writeFile (...l\node_modules\@angular\tsc-wrapped\src\compiler_host.js:143:19)
    at Object.writeFile (...\node_modules\typescript\lib\typescript.js:64240:132)
    at Object.writeFile (...\node_modules\typescript\lib\typescript.js:9020:14)
    at printSourceFileOrBundle (...\node_modules\typescript\lib\typescript.js:61204:16)
    at emitSourceFileOrBundle (...\node_modules\typescript\lib\typescript.js:61155:21)
    at Object.forEachEmittedFile (...\node_modules\typescript\lib\typescript.js:8986:17)
Compilation failed
```

Then:

```bash
$ node_modules/.bin/tsc -p src/lib/tsconfig.lib.json
$ node_modules/.bin/ngc -p src/lib/tsconfig.lib.json
```

Result: files emitted to `dist` folder.

Surprisingly, none of the following `"angularCompilerOptions"` in `tsconfig.lib.json` seem to affect the result:

```json
{
  "angularCompilerOptions": {
    "annotateForClosureCompiler": true,
    "skipTemplateCodegen": true,
    "strictMetadataEmit": true
  },
  "buildOnSave": false,
  "compileOnSave": false,
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "declaration": true,
    "sourceMap": true,
    "inlineSources": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "noEmitOnError": true,
    "noImplicitAny": false,
    "stripInternal": true,
    "baseUrl": "",
    "rootDir": "./src",
    "outDir": "../../dist/ng-hal/lib",
    "typeRoots": [
      "../../node_modules/@types"
    ],
    "lib": [
      "dom",
      "es2015"
    ]
  },
  "files": [
    "src/index.ts",
    "src/typings/halfred.d.ts"
  ],
  "exclude": [
    "node_modules",
    "dist",
    "gh-pages",
    "**/*.ngfactory.ts",
    "**/*.shim.ts",
    "**/*.spec.ts"
  ]
}
```

If `"skipMetadataEmit": true` is used, it works although no *.metadata.json is emitted (obviously). So that isn't a solution either.

```json
  "typescript": "~2.2.1",
  "@angular/compiler": "~2.4.10",
  "@angular/compiler-cli": "~2.4.10"
```

**Comment by tbosch** [comment]
Hello, we need a reproduction for this, as it's unclear which settings exactly caused the error.
Please create a branch on Github that reproduces the error...

**Comment by elwynelwyn** [comment]
Closing, I cannot reproduce the bug.
My repro example was using `@angular/tsc-wrapped@4.0.2` and while the code in question doesn't seem to have changed (the call to `fs.writeFileSync`) it appears the `outDir` has already been created by the time `writeMetaData` runs.

**Comment by Koslun** [comment]
We seem to be able to replicate this in our project somehow in `angular 4.1.2`. Getting:
```bash
[01:56:48] [Webpack] Error: ENOENT: no such file or directory, open '<my project root>\dist\src\app\shared\transfer-state\transfer-state.metadata.json'
```
Where we also delete the `dist `folder before we generate all our code. Simply adding the `dist `folder back before the angular compiler wants to use it we seemingly avoid the error from happening.

Possible differences are that we are compiling a server rendering entry as well. Where the first compilation done fails but the second succeeds, which I would assume be due to`dist `folder having been created in time for the second compilation. Also been using https://github.com/shlomiassaf/ngc-webpack rather than `ngc` directly.

Another thing of note is that our AoT builds take 30-60 seconds to build and about 15 minutes to bundle with webpack, where we further generally hit the maximum amount of RAM so have to override the default RAM limit in node using: 

```bash
node --max_old_space_size=16000 node_modules/gulp/bin/gulp.js serve:dist
```

If it's helpful here are the tsconfig's we used for AoT (browser is ran first and thus is the one failing):

**`tsconfig.json`:**
```json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "module": "es2015",
    "moduleResolution": "node",
    "noImplicitAny": false,
    "pretty": true,
    "diagnostics": true,
    "lib": [
      "dom",
      "es2016"
    ],
    "outDir": "dist",
    "removeComments": false,
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ]
  },
  "compileOnSave": false,
  "buildOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  },
  "include": [
    "src/**/*"
  ],
  "awesomeTypescriptLoaderOptions": {
    "useWebpackText": true,
    "forkChecker": true
  },
  "exclude": [
    "node_modules",
    "dist",
    "reports",
    "gulp_tasks"
  ]
}
```
**`tsconfig.browser.aot.json`:**
```json
{
  "extends": "./tsconfig.json",
  "angularCompilerOptions": {
    "debug": true,
    "genDir": "src/ngfactory",
    "skipCodeGeneration": false,
    "entryModule": "src/app/app.browser.module#AppBrowserModule"
  },
  "exclude": [
    "src/main.jit.ts",
    "src/server.aot.ts",
    "src/server.jit.ts"
  ]
}
```
**`tsconfig.server.aot.json`:**
```json
{
  "extends": "./tsconfig.json",
  "angularCompilerOptions": {
    "debug": true,
    "genDir": "src/ngfactory",
    "skipCodeGeneration": false,
    "entryModule": "./src/app/app.server.module#AppServerModule"
  },
  "exclude": [
    "./src/main.aot.ts",
    "./src/main.jit.ts",
    "./src/server.jit.ts"
  ]
}
```

Our fix is to just add `"skipMetadataEmit" : true,` to our `"angularCompilerOptions"` as I take the emit to only be necessary for libraries and not web apps like our project. 

Not sure if any other option would fix it but guessing that it then might just be avoided due to a racing condition or by simply creating the `dist `folder in advance. Nevertheless, given that it can happen I think it is still a bug that it can't simply create a new folder for itself. Especially as it is not immediately obvious that this is the root cause of the error, should you ever happen to encounter it.

**Comment by CaerusKaru** [comment]
As far as I can tell, this bug has been resolved in Angular v5
