### ISSUE TITLE
Angular Upgrade from 8 to 9 - Ivy Compilation Errors in Templates

### ISSUE THREAD

**Issue by kandrianatos** [angular/angular#43873]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

I successfully upgrade my angular app from version 8 to version 9 according to Angular Update Guide, and i solved all the issues that occurred in ts files.

In version 8 i was not using Ivy, i was using View Engine as it is the default.

After the upgrade to 9 my angular application is working only with the Ivy disabled ("enableIvy": false in tsconfig.json). With Ivy enabled am getting a lot of errors in templates, some of those errors are:

- Can't bind to 'my-property' since it isn't a known property of 'my-component'
- No directive found with exportAs 'ngForm'
- Can't bind to 'ngClass' since it isn't a known property of 'div'
- Can't bind to 'routerLink' since it isn't a known property of 'a'
- templateUrl: "./my-component.component.html", Error occurs in the template of component
- 'my-component' is not a known element 
If 'my-component' is an Angular component, then verify that it is part of this module.
If 'my-component' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

I am not getting those errors using View Engine and the app works fine.

It seems to be a configuration or Modules Import issue? Am lazy loading modules like:
`loadChildren: () => import('./items/items.module').then(m => m.ItemsModule)`

In package.json am using
`"postinstall": "ngcc"`

And in tsconfig.json
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "downlevelIteration": true,
    "importHelpers": true,
    "module": "esnext",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es6",
    "typeRoots": ["node_modules/@types"],
    "types": ["jest"],
    "lib": ["es2015", "dom"],
    "skipLibCheck": true
  },
  "angularCompilerOptions": {
    "enableIvy": true
  },
}
```
Any Ideas? :)

### Please provide the environment you discovered this bug in

```true
Angular CLI: 9.1.15
Node: 12.22.7
OS: win32 x64

Angular: 9.1.13
... animations, common, compiler, compiler-cli, core, forms     
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------     
@angular-devkit/architect         0.901.15
@angular-devkit/build-angular     0.901.15
@angular-devkit/build-optimizer   0.901.15
@angular-devkit/build-webpack     0.901.15
@angular-devkit/core              9.1.15
@angular-devkit/schematics        9.1.15
@angular/cli                      9.1.15
@angular/localize                 12.2.10
@ngtools/webpack                  9.1.15
@schematics/angular               9.1.15
@schematics/update                0.901.15
rxjs                              6.6.7
typescript                        3.8.3
webpack                           4.42.0
```

**Comment by petebacondarwin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`; or consider asking on [Discord](https://discord.com/invite/angular or ) or [Gitter](https://gitter.im/angular/angular).

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question).
