### ISSUE TITLE
angular lazyload loadChildren not found module after upgrade to 4.0 

### ISSUE THREAD

**Issue by innovaFTA** [angular/angular#15484]
Lazy module load with loadChildren does not work after upgrade to angular 4.0. 

I also upgrade my angular-cli,npm and node version to latest. but when I rollback to 2.4 it is fine. working very nice. 

Error is : 
`ERROR Error: Uncaught (in promise): Error: Cannot find module './depPages/customers/customers.module'.
Error: Cannot find module './depPages/customers/customers.module'.`

routing.ts  part is; 

`    {
        path: 'customers',
        loadChildren: './depPages/customers/customers.module#CustomersModule',
        data: {
          Id: 'A2'
        }
        // canActivate: [AuthGuardService]
      },`

my module.ts; 
`// Angular Libraries...
import { NgModule } from '@angular/core';
import { HttpModule } from '@angular/http';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { SelectModule } from 'angular2-select';
import { BusyModule } from 'angular2-busy';

// Customer Related Components..
import { CustomerRoutingModule } from './customers.routing.module';
import { CustomersComponent } from './customers.component';
import { NewCustomerComponent } from './new-customer/new-customer.component';
import { EditCustomerComponent } from './edit-customer/edit-customer.component';

// Userdefined Modules..
import { InnovaGridModule } from '../../shared/components/innovagrid/innova-grid.module';
import { InnovaToastrModule } from '../../shared/components/depToaster/depToaster.module';

// Services..
import { CustomersService } from './services/customers.service';

@NgModule({
    imports: [
        CustomerRoutingModule,
        FormsModule,
        HttpModule,
        InnovaGridModule,
        ReactiveFormsModule,
        CommonModule,
        InnovaToastrModule,
        SelectModule,
        BusyModule
    ],
    declarations: [
        CustomersComponent,
        NewCustomerComponent,
        EditCustomerComponent
    ],
    providers: [
        CustomersService
    ]
})

export class CustomersModule { }`

is there any suggestion about it. is it a known issue ? 

thank you.

**Comment by DzmitryShylovich** [comment]
Please reproduce in plunkr. You can use http://plnkr.co/edit/lU32vBJY9KYXZUTW7GQQ?p=preview as a starting point

**Comment by innovaFTA** [comment]
thank you DzmitryShylovich,

I solved my problem.
there is no configuration for Angular 4.0 in plunker yet. So I cant reproduce it. 

I only clear all node_modules folder and run "npm-install" again. Now everything works fine.

**Comment by DzmitryShylovich** [comment]
> there is no configuration for Angular 4.0 in plunker yet. So I cant reproduce it.

http://plnkr.co/edit/lU32vBJY9KYXZUTW7GQQ?p=preview

> Now everything works fine.

👍 close the issue please. thanks
