### PR TITLE
build(docs-infra): fixed broken stackblitz examples

### LINKED ISSUE #42116: stackblitz example of http are not working
I was checking docs of http and found that stackblitz examples are not working

# Docs or angular.io Bug Report

### Description

Stackblitz example under [https://angular.io/guide/http#setup-for-server-communication](https://angular.io/guide/http#setup-for-server-communication) is  some time working and some time failing with error 

```Error in src/test.css
Error: ENOENT: No such file or directory., '/dev/null'
```

while other stackblitz example under [https://angular.io/guide/http#testing-http-requests](https://angular.io/guide/http#testing-http-requests) is failing every time.

It gives error
```Error in src/testing/global-jasmine.ts (1:28)
Cannot find module 'jasmine-core/lib/jasmine-core/jasmine.js' or its corresponding type declarations.
```

## Minimal Reproduction
Visit Angular docs
### What's the affected URL?**

[https://angular.io/guide/http#testing-http-requests](https://angular.io/guide/http#testing-http-requests)
### Reproduction Steps**
Provided in description

### Expected vs Actual Behavior**
stackblitz example shouldn't fail

## Screenshot
Screenshot 2021-05-16 at 9 33 50 PM
Screenshot 2021-05-16 at 9 33 43 PM

## Exception or Error
provided  in description

### Browser info
Any browser

### Anything else relevant?
No

### PR DESCRIPTION
**Pull request by iRealNirmal**
This commit fixes the broken stackblitz examples.

Closes #42116 .

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Some of stackblitz example were broke with PR #42001 

Issue Number: #42001 

## What is the new behavior?
With this PR broken stackblitz issue is resolved.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: aio/content/examples/http/stackblitz.json [hunk 1]
```diff
@@ -8,5 +8,6 @@
     "!src/main-specs.ts"
   ],
   "file": "src/app/app.component.ts", 
-  "tags": ["http"]
+  "tags": ["http"],
+  "devDependencies": ["jasmine-core", "jasmine-marbles"]
```
Comment (petebacondarwin) [inline aio/content/examples/http/stackblitz.json:12]: jasmine-marbles is not needed here.

File: aio/content/examples/security/stackblitz.json [hunk 2]
```diff
@@ -5,5 +5,6 @@
     "!**/*.js"
   ],
   "file": "src/app/app.component.ts",
-  "tags": ["security"]
+  "tags": ["security"],
+  "devDependencies": ["jasmine-core", "jasmine-marbles"]
```
Comment (petebacondarwin) [inline aio/content/examples/security/stackblitz.json:9]: this is not needed

**Review by petebacondarwin — APPROVED** [review]
LGTM
