### ISSUE TITLE
Does Angular support ES5 JavaScript with DSL?

### ISSUE THREAD

**Issue by pavel-blagodov** [angular/angular#20305]
I get ng.core.Pipe(...).Class is not a function after upgrading to 5.0.0. Did I miss something?

**Comment by alexzuza** [comment]
Seems it is related to https://github.com/angular/angular/commit/cac130eff9b9cb608f2308ae40c42c9cd1850c4d#diff-635fe23be5795132e3385c8f4899dc3a

**Comment by pavel-blagodov** [comment]
Ha, we still have JavaScript without DSL.

**Comment by jasonaden** [comment]
@pavel-blagodov Closing based on linked commit.

**Comment by gimmi** [comment]
I'm trying to upgrade a JS app from Angular `4.4.3` to `5.0.5`, the app is completely broken because of this. I did a search on the official documentation for finding the proper way of using Angular 5 without TipeScript, but the only doc I was able to find are related to Angular 2:

https://v2.angular.io/docs/ts/latest/cookbook/ts-to-js.html

Is there some updated doc on how to use Angular with plain JavaScript, or now TypeScript has become a requirement?

**Comment by trotyl** [comment]
```html
<!DOCTYPE html>
<title>Hello Angular</title>
<main>TODO</main>
<script>
Reflect.getOwnMetadata = () => {}
</script>
<script src="https://unpkg.com/zone.js/dist/zone.js"></script>
<script src="https://unpkg.com/rxjs/bundles/Rx.js"></script>
<script src="https://unpkg.com/@angular/core/bundles/core.umd.js"></script>
<script src="https://unpkg.com/@angular/common/bundles/common.umd.js"></script>
<script src="https://unpkg.com/@angular/compiler/bundles/compiler.umd.js"></script>
<script src="https://unpkg.com/@angular/platform-browser/bundles/platform-browser.umd.js"></script>
<script src="https://unpkg.com/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js"></script>
<script>
class AppComponent { }

AppComponent.annotations = [
  new ng.core.Component({
    selector: 'main',
    template: '<h1>Hello Angular</h1>',
  })
]

class AppModule { }

AppModule.annotations = [
  new ng.core.NgModule({
    imports: [
      ng.platformBrowser.BrowserModule,
    ],
    declarations: [
      AppComponent,
    ],
    bootstrap: [
      AppComponent,
    ],
  })
]

ng.platformBrowserDynamic.platformBrowserDynamic().bootstrapModule(AppModule)
</script>
```

@gimmi  This is runnable, but I won't suggest it.

**Comment by gimmi** [comment]
Thanks @trotyl for code snippet.

Is `Reflect.getOwnMetadata = () => {}` required? What's the meaning?

**Comment by trotyl** [comment]
@gimmi This way it would not require [Metadata Reflection API](https://github.com/rbuckton/reflect-metadata) but Angular still checks that. The demo was originally made in v4, just checked it's no more needed in v5.
