### ISSUE TITLE
Effects don't work after updating from @angular/cli 14.2.11 to 14.2.12

### ISSUE THREAD

**Issue by magioloro** [angular/angular#51174]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Hi at all,

after upgrading to angular/cli 14.2.12 all my NgRx effects using fetch() are broken: 

Example code: 

```
downloadInvoice$ = createEffect(() =>
        this.actions$.pipe(
            ofType(TasksActions.downloadInvoice),
            fetch({
                run: (action: ReturnType<typeof TasksActions.downloadInvoice>) =>
                    TaskUtil.loadInvoicePdf(action.orderId, this.taskService).pipe(
                        map(() => TasksActions.downloadInvoiceSuccess())
                    ),
                onError: (action: ReturnType<typeof TasksActions.downloadInvoice>, error: any) =>
                    TasksActions.downloadInvoiceError({ error })

            })
        )
    );
```

When reverting to 14.2.11 everything runs like clockwork again.

### Please provide the exception or error you saw

```true
Error: src/app/portal/tasks/+state/tasks.effects.ts:199:13 - error TS2345: Argument of type '(source: ActionStatesStream<[], { orderId: string; } & TypedAction<"[Tasks] DownloadInvoice">>) => Observable<Action>' is
 not assignable to parameter of type 'OperatorFunction<unknown, unknown>'.
  Types of parameters 'source' and 'source' are incompatible.
    Type 'Observable<unknown>' is missing the following properties from type 'Observable<ActionOrActionWithStates<[], { orderId: string; } & TypedAction<"[Tasks] DownloadInvoice">>>': _isScalar, _trySubscribe, _sub
scribe

199             fetch({
                ~~~~~~~
200                 run: (action: ReturnType<typeof TasksActions.downloadInvoice>) =>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
206
   
207             })
    ~~~~~~~~~~~~~~
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.2.12
Node: 18.16.0 (Unsupported)
Package Manager: yarn 3.6.0
OS: win32 x64

Angular: 14.3.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1402.12
@angular-devkit/build-angular      14.2.12
@angular-devkit/core               14.2.12
@angular-devkit/schematics         14.2.12
@angular/cdk                       14.2.7
@angular/cli                       14.2.12
@angular/flex-layout               14.0.0-beta.41
@angular/material                  14.2.7
@angular/material-moment-adapter   14.2.7
@schematics/angular                14.2.12
@ngrx/effects                      14.3.3
rxjs                               7.8.1
typescript                         4.7.4
webpack                            5.88.2
```

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

---

`@angular/cli` 14.2.12 only updated its `semver` dependency. It may be that other packages were updated alongside it that now cause the compilation error to occur. This particular type error is unrelated to the CLI version though.
