### ISSUE TITLE
http.get(..).map function is not working with alpha 48

### ISSUE THREAD

**Issue by MurhafSousli** [angular/angular#5632]
since I updated to alpha 48, http.get(...).map is no longer working.

 `EXCEPTION: TypeError: json.map is not a function in [null]`
```
@Injectable()
export class WPService implements IWPService {
    baseURL: string = 'http://localhost/wptest/api';
    http: Http;
    constructor(http: Http) {
        this.http = http;
    }
    GetPosts() {
        var query = this.baseURL + '/get_posts/';
        return new JsonObject(this.http.get(query));
    }
}

@Injectable()
export class JsonObject {
    constructor(json: Observable<any>) {
        json.map(res => res.json()).map(data => {          // <= 
            for (var entry in data) {
                if (data.hasOwnProperty(entry)) {
                    this[entry] = data[entry];
                }
            }
        }).subscribe();
    }
}
```

when I downgraded to alpha 47, .map worked again. maybe it has something to do with the integrated rxjs

**Comment by rolandjitsu** [comment]
I got the same issue :+1:

**Comment by ericmartinezr** [comment]
Guys, you have to add `map` (install `rxjs@5.0.0-alpha.11`)

```
import 'rxjs/operators/map';
```

I don't know if for Http module we will always have to do this. As far as I know `map` is one of the defaults one. Anyway, with this you can make it work for now until you get an official answer

Note that I had to map it like this

```
System.config({
	paths: {
		'rxjs/operators/*' : 'node_modules/rxjs/operators/*.js'
        }
}
```

**Comment by micmro** [comment]
I wonder if this might have to do with #5643?

**Comment by janishorsts** [comment]
We have this issue after upgrading node from 4.2.x to 5.1.x

**Comment by todoubaba** [comment]
With alpha.50, add `map` by
``` typescript
import 'rxjs/operator/map';
```
and
```  typescript
System.config({
  paths: {
    'rxjs/operator/*': 'node_modules/rxjs/add/operator/*.js',
    'rxjs/*' : 'node_modules/rxjs/*.js'
  }
});
```
It just works, is that right?

**Comment by ericmartinezr** [comment]
@todoubaba yes, it is. I just match the paths names to avoid confusions on my head, lol. You can put whatever you want in the left, the important part is on the right.

**Comment by dgwaldo** [comment]
I'm on alpha-5.2 and still having this issue.  Also had to add default extension for the packages.

```
System.config({
            packages: {
                'app': { defaultExtension: 'js' },
                '../node_modules/rxjs': { defaultExtension: 'js' }
            },
            paths: {
                'rxjs/operator/*': '../node_modules/rxjs/add/operator/*.js',
                'rxjs/*': '../node_modules/rxjs/*.js'
            }
        });
```

**Comment by NisStrom** [comment]
I'm facing the same issue also using alpha-52.

**Comment by playground** [comment]
Having the same issue with alpha52 TypeError: http.get(...).map is not a function

**Comment by rolandjitsu** [comment]
@playground as @ericmartinezr pointed out, you need to include the operators you are going to use like `import 'rxjs/operators/map';` for example.

@dgwaldo, your system config should look like:
```js
System.config({
            packages: {
                'app': { defaultExtension: 'js' },
                'rxjs': { defaultExtension: 'js' }
            },
            paths: {
                'rxjs/operator/*': '../node_modules/rxjs/add/operator/*.js',
                'rxjs/*': '../node_modules/rxjs/*.js'
            }
});
```
I use something like the following:
```js
System.defaultJSExtensions = true;
System.config({
	paths: {
		'rxjs/operator/*': 'lib/rxjs/add/operator/*.js',
		'rxjs/*' : 'lib/rxjs/*.js'
	}
});
```

**Comment by robwormald** [comment]
The simplest syntax for this with SystemJS is :
```js
System.config({
  map: {
    rxjs: 'node_modules/rxjs' //or wherever you have it installed
  },
  packages: {
    rxjs: {
      defaultExtension: 'js'
   }
  }
})
```

**Comment by playground** [comment]
@robwormald @rolandjitsu try those config but still getting the same error.

**Comment by robwormald** [comment]
should be `import 'rxjs/add/operator/map'` - note the *add* in the import path. that brings in the self patching module.

**Comment by sivaah** [comment]
I was upgrading from 2.0.0-alpha.44 to 2.0.0-beta.0, got the same issue and issue is fixed by adding a single line in app.ts

```
import 'rxjs/add/operator/map';
```

Thanks @robwormald

**Comment by aaronksaunders** [comment]
i am on 2.0.0-beta.0 and still seeing issue, not sure why this was closed? Is the official fix what @robwormald stated above

**Comment by robwormald** [comment]
@aaronksaunders yep, this is "works as intended" - we are purposefully not shipping the 95+ operators that come with RxJS (and the associated 300KB or so they add) in favor of allowing opt-in to specific ones you want.

Longer term we *may* include a few with the http module by default, but for the moment its opt-in till we decide which ones are necessary. Ideally i'd like to obviate the need for .map entirely for 99% of use cases. 

Easiest thing is in your `main.ts` (or whatever) file to either import them ad-hoc:
```typescript
import 'rxjs/add/operator/map'
```
Or if you really don't want to mess with it and want the whole kitchen sink o' operators / specific Observables (eg `Observable.fromEvent`)
```typescript
import 'rxjs/Rx' 
```
which will add all of them. Note that you only need to do the above *once*, before you use Http, not in every single file you are going to use it.

**Comment by aaronksaunders** [comment]
thanks, i did what you suggested and added it to my app.ts

**Comment by jasonspick** [comment]
Chrome is throwing a 403 when doing what is described above, is anyone else seeing this?

node_modules/rxjs/Observable/ 403 (Forbidden)

**Comment by mkeen** [comment]
Chrome doesn't "throw" 403's. Probably a permissions issue.

**Comment by burakAs** [comment]
+1 @robwormald

**Comment by hzitoun** [comment]
I got the same issue but I got it resolved thanks to @robwormald

**Comment by MichaelThessel** [comment]
+1 @robwormald

**Comment by rpolevoi** [comment]
Am I the only person who cannot fathom why the http/jsonp examples on the Angular 2 site (Developer Guide - http client) -- both in the sample code and the versions in the provided Plunker demos -- fail to make this critical point?  The .map and other operators used in these basic training examples do not reflect the required operator imports, and this is very counterproductive for those trying to learn Ang 2.  (How the Plunker demos run theses operators without the imports is still a mystery to me.) People trying to wrap their heads around Observables as a replacement for Promises -- a worthwhile effort surely in the longer run -- deserve not to be confused by the text and code in the official Angular 2 Developer Guide.

**Comment by mithun-daa** [comment]
I am facing a somewhat similar issue. I have an Angular 2 app that uses the `http` service to get data from the server. The get works just find and I can see the data come back. As soon as I try to map that data to something I get an error mentioned in this issue. I follow @robwormald suggestions and add an import to my `main` and update my `System.config`. But now I get a new error. Looks like it is looking for `fromPromise` and does not find that file in the `node_modules` folder. Any idea why `fromPromise` is missing and who is calling it?

```
System.config({
        map: {
            rxjs: 'node_modules/rxjs' 
        },
        packages: {        
          'js': {
            format: 'cjs',
            defaultExtension: 'js'
          },
          rxjs: {
            defaultExtension: 'js'
          }
        }
      });
```

**Comment by rpolevoi** [comment]
I don't get this bit about adding to your System.config() in the html page.

The problem is just that .map (and all of the operators for observables) need to be imported into the file in which you are using http or jspon.

Thus if you have a file for a service or component that calls http, and which you need .map() to handle the res.json () unwrap step (to grab the body from the response object), you need to the following imports at the top of the file:

import {Http, Response} from 'angular2/http';
import {Headers, RequestOptions} from 'angular2/http';
_(plus)_
import 'rxjs/add/operator/map';       // _to import just map operator_
**(or)**
import 'rxjs/Rx';     _// if you want to import all the operators while developing and then go back and just    import exactly what you ended up needing for production_

It's just that simple and it only because the observable(containing the repsonse object) returned by http method does not inherently have access to any operators -- like map, do, etc, unless you provide them.

Your System.config need not refer to rxjs at all.  The following works for me where all the my angular files (components, services, directives, etc.) are in an "app" folder.

      System.config({
        packages: {        
          app: {
            format: 'register',
            defaultExtension: 'js'
          }
        }
      });

But the rx bundle must be included with the other necessary script loads in the head of the html page.

    <script src="node_modules/rxjs/bundles/Rx.js"></script>  

BTW:  If all else fails, you can skip the map() call and subscribe directly to the response observable returned by the http call, like this:

        this.http.get('people')
           .subscribe(
                res => this.persons = res.json(),
                error =>  console.log(error)
                );

This at least proves that you are getting back an observable with the correct data.  subscribe is not considered an operator, but rather a method of any observable instance.  Thus it can never be missing.

**Comment by jimbasilio** [comment]
IMO This really needs to be added to the angular2 documentation (```import rxjs/Rx``` or importing operators 1 by 1). I struggled for a day pulling my hair out not understand what I was missing about Observables and really thinking I was missing something massive (which I guess I was). It's a difficult thing to just 'know' if you are new to angular2/Rxjs.

**Comment by Jefftopia** [comment]
@jimbasilio Not the easiest thing to find, but it's there: https://angular.io/docs/ts/latest/guide/server-communication.html

**Comment by wardbell** [comment]
We do call this out in the http doc, in its own [Enable RxJS Operators](https://angular.io/docs/ts/latest/guide/server-communication.html#!#enable-rxjs-operators) section.

I don't know how we can be more clear. Open to suggestions.

Much else has changed since this issue was raised. I suggest that we close this issue.

**Comment by caffinatedmonkey** [comment]
What's the difference between the following?

    import 'rxjs/add/operator/map'

and

    import 'rxjs/operator/map'
