### ISSUE TITLE
Getting compilation error: Could not find a declaration file for module 'source-map' after upgrade to latest version 11.1.0

### ISSUE THREAD

**Issue by anup11** [angular/angular#40516]

**Comment by petebacondarwin** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Comment by IT-CASADO** [comment]
I see the same warnings after upgrading to 11.1.0


```
Compiling @angular/animations : es2015 as esm2015
Warning: Unable to fully load C:/Code/AngularProject/ClientApp/node_modules/@angular/animations/animations.d.ts for source-map flattening: Circular source file mapping dependency: C:/Code/AngularProject/ClientApp/node_modules/@angular/animations/animations.d.ts.map -> C:/Code/AngularProject/ClientApp/node_modules/@angular/animations/animations.d.ts.map
Warning: Unable to fully load C:/Code/AngularProject/ClientApp/node_modules/@angular/core/core.d.ts for source-map flattening: Circular source file mapping dependency: C:/Code/AngularProject/ClientApp/node_modules/@angular/core/core.d.ts.map -> C:/Code/AngularProject/ClientApp/node_modules/@angular/core/core.d.ts.map
```

**Comment by petebacondarwin** [comment]
@IT-CASADO - please can you ensure that you have cleaned out and reinstalled all your node_modules. If the problem still occurs please put together a reproduction and create a new issue with reference to it.

**Comment by IT-CASADO** [comment]
@petebacondarwin - don't see any warnings after cleaning and re-installing node_modules

**Comment by petebacondarwin** [comment]
OK, that's good right?
