### ISSUE TITLE
Build from master: Angular compiles successfully but angular2.dev.js throws errors. Simple questions about build process.

### ISSUE THREAD

**Issue by jomeier** [angular/angular#2191]
Hi,

a few questions from an angular2-build-newbie :-) I'm sure it's a simple one for angular veterans.

Today I built angular with the instructions from DEVELOPER.md for the first time. 

```javascript
...
npm install
gulp build
```

I took the sources from the master branch (from yesterday) and compilation ran without errors. After the compilation I got a dist directory with 'dist/bundle' and 'dist/build' directories (don't know the difference. Which directory is for which purpose?).

I tested the resulting angular2.dev.js with this simple typescript code here (under Visual Studio 2013 with Typescript 1.5beta, Traceur 0.0.87 and the module loader script jspm.io/system...) from the Quickstart tutorial) :

```javascript
/// <reference path="../../Scripts/typings/angular2/angular2.d.ts" />  
import {Component, View, bootstrap} from 'angular2/angular2';
import {Inject} from 'angular2/di';

class test1{
  constructor() {
  }
}

@Component({
    selector: 'app',
    properties: { 'newtodo': 'newtodo' },
    appInjector: [test1]  // Dependency Injection von 'test1' 
})
@View({
    templateUrl: 'partials/mainPage'
})
class MyAppComponent {
...
```

This code works with 2.0.0 Alpha 25.

I used 'angular2.dev.js' (961.019 Bytes) from the directory 'angular/dist/bundle' in my main html page and after loading it, the page isn't displayed but in the console I see this error:

```javascript
Uncaught TypeError: angular2_1.Component is not a function
```

If I use 'angular2.js' from the same directory, I get this error:

```javascript
es6-module-loader@0.16.5.src.js:2605 GET https://registry.jspm.io/javascripts/myapp.js 404 (Not Found)
```

It seems to me that I make a systematic error cause the error messages differ so much. If I use angular2 2.0.0 Alpha25 everything works perfectly.

Is the code from the master branch always working or should we wait for new Alpha releases? I'm waiting for Alpha26 cause it contains fixes for iOs. 

I think it would be a great idea if we had a dist directory anywhere with continuous (and tested) builds in it. Everyone could test the master branch's content without having to build it themselves (and making errors by doing so).

Sorry for asking such newb questions but I didn't find documentation about this topics and maybe your advices are also helpful for other angular 2 developers. Maybe the DEVELOPER.md could be expanded with a few more detailled instructions (which codebase to use, which directories in the dist folder are responsible for what, ...).

Josef

**Comment by jomeier** [comment]
I played around with cherry picking the commit which fixes the iOS map problem and merging it into the alpha 25 code base. It worked.

It seems as if the code of the current master branch is not guaranteed to be always working. Correct me if I'm wrong, please.
