### ISSUE TITLE
directives/ng_switch.ts has no exported member 'SwitchView'.

### ISSUE THREAD

**Issue by robwormald** [angular/angular#7656]
**Note: for support questions, please use one of these channels:** https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

Bug.

* **What is the current behavior?**

In beta.10, importing angular2/common and compiling with typescript fails with:
`node_modules/angular2/src/common/directives/ng_plural.d.ts(2,10): error TS2305: Module '".../node_modules/angular2/src/common/directives/ng_switch"' has no exported member 'SwitchView'.`

This is likely related to `SwitchView` being marked internal, introduced in https://github.com/angular/angular/commit/a4b5cb837682ce61f8c07eabd7ae8c4dc3ba80a7 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

No TSC failures

- Angular version: 2.0.0-beta.10
- TSC 1.8.9

**Comment by robwormald** [comment]
cc @alexeagle - i'm not sure why this would surface now, but it has. TS change?

**Comment by KevinJannis** [comment]
@robwormald Having the same issue after upgrading. 

Using:
Angular-2.0.0-beta.10 
Typescript 1.8.7

**Comment by jpleclerc** [comment]
Any workaround beside going back to beta 9?

**Comment by leosvelperez** [comment]
@robwormald I'm having the same issue with beta.10 and Typescript 1.8.2

**Comment by ericmartinezr** [comment]
Guys, just wait for beta.11. This error messages isn't blocking, it's just an ugly error message in your consoles, nothing more.

**Comment by alexeagle** [comment]
@robwormald: we missed this in tests because https://github.com/angular/angular/blob/master/typing_spec/basic_spec.ts has too little coverage. We need a more full-featured example to be compiled by the typings test, https://github.com/angular/angular/blob/master/gulpfile.js#L987
Maybe we can compile all our examples using this fixture, which would give a lot of coverage with no extra maintenance.

**Comment by robwormald** [comment]
closed in #7657

**Comment by JaKXz** [comment]
@robwormald just out of curiousity, was @alexeagle's suggestion taken into account? If I can help make that happen I'd like to :)

**Comment by alexeagle** [comment]
@JaKXz please, it would be awesome if you could contribute this. I don't think anyone on the core team has had time to address it.

**Comment by alexeagle** [comment]
Filed that issue to followup.
