### ISSUE TITLE
Error when updating from 7 to 8. TypeError: Cannot read property '_metadataResolver' of undefined

### ISSUE THREAD

**Issue by unnarb** [angular/angular#32741]
I have a multi-project angular project which is in angular v.7.2.2, although not using the library functionality.

I have tried to update the project 3 times. This time updating all other dependencies and always getting the same error which doesn't tell me anything:

Error when updating from 7 to 8. TypeError: Cannot read property '_metadataResolver' of undefined.

This is the full output when running ng update @angular/core --from 7 --to 8 --migrate-only (after seeing this message before)

  ------ Static Query Migration ------
            With Angular version 8, developers need to
            explicitly specify the timing of ViewChild and
            ContentChild queries. Read more about this here:
            https://v8.angular.io/guide/static-query-migration

            The template migration strategy uses the Angular compiler internally and therefore projects that no longer build successfully after the update cannot use the template migration strategy. Please ensure there are no AOT compilation errors.

            Could not setup migration strategy for "src/tsconfig.app.json". The following error has been reported:

            TypeError: Cannot read property '_metadataResolver' of undefined

            Migration can be rerun with: "ng update @angular/core --from 7 --to 8 --migrate-only"

            ------------------------------------------------
Two or more projects are using identical roots. Unable to determine project using current working directory. Using default workspace project instead.
Two or more projects are using identical roots. Unable to determine project using current working directory. Using default workspace project instead.
            ------ Renderer to Renderer2 Migration ------
            As of Angular 9, the Renderer class is no longer available.
            Renderer2 should be used instead.

**Comment by unnarb** [comment]
This is not the same error as when I run the update the first time. Then no output relates to projects using identical roots:

 ------ Static Query Migration ------
            With Angular version 8, developers need to
            explicitly specify the timing of ViewChild and
            ContentChild queries. Read more about this here:
            https://v8.angular.io/guide/static-query-migration

            The template migration strategy uses the Angular compiler internally and therefore projects that no longer build successfully after the update cannot use the template migration strategy. Please ensure there are no AOT compilation errors.


            TypeError: Cannot read property '_metadataResolver' of undefined

            Migration can be rerun with: "ng update @angular/core --from 7 --to 8 --migrate-only"

**Comment by ericmartinezr** [comment]
Sounds like a dup of https://github.com/angular/angular-cli/issues/15523

**Comment by AndrewKushnir** [comment]
Hi @unnarb, as @ericmartinezr mentioned, this issue looks like a duplicate of the existing one in CLI repo: [angular/angular-cli#14980](https://github.com/angular/angular-cli/issues/14980). You can subscribe to the mentioned thread to receive updates. Thank you.
