### ISSUE TITLE
JSDoc @type annotation cause angular/compiler-cli( ngc) build failed

### ISSUE THREAD

**Issue by jackjoy** [angular/angular#19969]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

```
The following jsdoc-style comment was auto generated by visual studio code. When build with 
@angular/compiler-cli v4.4.5, it output a warning : '@type annotations are redundant with TypeScript 
equivalen ts', and following gulp task failed.

/**
	 * Data fields.
	 * 
	 * @readonly
	 * @type {IChartOptions}
	 */
	public get dataFields() : IChartOptions
	{
		return this._dataFields;
	}

const ngc = require('@angular/compiler-cli/src/main').main;
gulp.task('ngc', function ()
	{
		return ngc({
			project: `${tmpFolder}/tsconfig.es5.json`
		}).then((exitCode) =>
		{
			if (exitCode === 1)
			{
				// This error is caught in the 'compile' task by the runSequence method callback
				// so that when ngc fails to compile, the whole compile process stops running
				throw new Error('ngc compilation failed')
			}
		})
	});

NOTES: not all such @type annotations but only some will cause this issue. If remove the @type line in
 the comment,it will build ok.

```

## Expected behavior

Should build without error.

## Environment

<pre><code>
Angular version: 4.4.5

Browser:
- [ x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  
npm@3.10.10
node@v6.10.1

Others:

</code></pre>

**Comment by jasonaden** [comment]
If the `@type` annotation was generated by vscode, you should probably change the generation settings to not include it since it's redundant. When downleveling TypeScript to JS for Closure, we need to have correct JSDoc comments for Closure.

**Comment by jackjoy** [comment]
I think it should be warnings instead of errors which block building process.Since code comments should not block building.Even more,the same code build ok with angular 4.2.x with same configuration,but can't now with 4.4.x and 5.0.

**Comment by croso-df** [comment]
Having to refactor a large codebase and modifying linters to migrate to v5 is quite cumbersome. Is there any other way to get around this? Can I disable jsdoc parsing? or jsdoc parsing is a critical step of the of the build process?

**Comment by Lexanius** [comment]
@croso-df  Have u found a way?
