### ISSUE TITLE
withExperimentalAutoCleanupInjectors + provideExperimentalWebMcpTools race condition causes InvalidStateError: Duplicate tool name on repeated route navigation

### ISSUE THREAD

**Issue by 9kubczas4** [angular/angular#68899]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

When using `provideExperimentalWebMcpTools` inside a `Route.providers` array together with `withExperimentalAutoCleanupInjectors()`, navigating away from a route and back to it throws:

```
InvalidStateError: Failed to execute 'registerTool' on 'ModelContext': Duplicate tool name
  at declareExperimentalWebMcpTool (core.mjs)
```

The Angular docs state:
When registering tools to a particular route, consider configuring the router to use `withExperimentalAutoCleanupInjectors` to ensure tools are automatically unregistered when the user navigates away from the route.

Following this guidance does not prevent the error.

**Reproduction**

```
// app.routes.ts
export const APP_ROUTES: Routes = [
  {
    path: 'products',
    loadComponent: () => import('./products.component').then(m => m.ProductsComponent),
    providers: [provideExperimentalWebMcpTools([filterProductsTool])],
  },
];

// app.config.ts
export const appConfig: ApplicationConfig = {
  providers: [
    provideRouter(APP_ROUTES, withExperimentalAutoCleanupInjectors()),
    // ...
  ],
};
```

Steps to reproduce: https://webmcp-angular-demo.web.app/

Navigate to /products
Navigate away to any other route
Navigate back to /products (it could work as expected on first few attempts, so please try a few more attempts)
InvalidStateError: Duplicate tool name is thrown

Repository: https://github.com/9kubczas4/web-mcp-angular

### Please provide a link to a minimal reproduction of the bug

https://github.com/9kubczas4/web-mcp-angular

### Please provide the exception or error you saw

```true
main-PJGA7QVG.js:4 ERROR InvalidStateError: Failed to execute 'registerTool' on 'ModelContext': Duplicate tool name
    at Lv (main-PJGA7QVG.js:4:121936)
    at main-PJGA7QVG.js:4:122088
    at ht.resolveInjectorInitializers (main-PJGA7QVG.js:4:7160)
    at new Gn (main-PJGA7QVG.js:4:89625)
    at _d (main-PJGA7QVG.js:4:89765)
    at as (main-PJGA7QVG.js:5:51382)
    at us (main-PJGA7QVG.js:5:51978)
    at Dr.matchSegmentAgainstRoute (main-PJGA7QVG.js:5:56874)
    at Dr.processSegmentAgainstRoute (main-PJGA7QVG.js:5:55617)
    at Dr.processSegment (main-PJGA7QVG.js:5:55318)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI       : 22.0.0-rc.1
Angular           : 22.0.0-rc.1
Node.js           : 22.22.3
Package Manager   : npm 10.9.8
Operating System  : darwin arm64

Package                   | Installed Version
--------------------------|------------------
@angular/build            | 22.0.0-rc.1
@angular/cli              | 22.0.0-rc.1
@angular/common           | 22.0.0-rc.1
@angular/compiler         | 22.0.0-rc.1
@angular/compiler-cli     | 22.0.0-rc.1
@angular/core             | 22.0.0-rc.1
@angular/forms            | 22.0.0-rc.1
@angular/platform-browser | 22.0.0-rc.1
@angular/router           | 22.0.0-rc.1
rxjs                      | 7.8.2
typescript                | 6.0.3
vitest                    | 4.1.7
@mcp-b/webmcp-polyfill    | 2.3.2
```

**Comment by JeanMeche** [comment]
I ran into some issues with Chrome 147, but after updating to 148 it seems to run smoothly. Could you double check?

**Comment by 9kubczas4** [comment]
Hi @JeanMeche,

It exists on Chrome 148 on my side as well.

https://drive.google.com/file/d/1Cl5lGsNH7Y5ObuObdwlWhVx4-Y5Oq2Oy/view?usp=sharing

**Comment by JeanMeche** [comment]
Hum okay. I can reproduce it very unconsistently. I'm wondering if we're hitting a Chrome bug. 

https://github.com/user-attachments/assets/3a937c7e-2c7d-4061-81c2-dbf88935cf14

The code that is supposed to remove the tool silently fails (we can see that we reach 5 tools) instead of the expected 4.

**Comment by JeanMeche** [comment]
I just updated to `149.0.7827.103` and I cannot reproduce the error anymore. Can you confirm ?

**Comment by 9kubczas4** [comment]
Hi @JeanMeche,

That's correct it works without problems in newer versions of Chrome. We can close this issue right now.

Thank you! :)
