### ISSUE TITLE
Typescript path alias not working when using the new @angular-devkit/build-angular:application

### ISSUE THREAD

**Issue by nicolae536** [angular/angular#53338]
### Which @angular/* package(s) are the source of the bug?

compiler-cli, compiler

### Is this a regression?

Yes

### Description

In webpack build we could define path aliases for certain folders and imports things using an index.ts file in the root of the folder. After upgrade to 17 and migrating the build system to new @angular-devkit/build-angular:application it seems typescrpt paths are ignored. Is there an alternative way to define them ?

### Please provide a link to a minimal reproduction of the bug

https://github.com/nicolae536/angular-typescript-paths

### Please provide the exception or error you saw

```true
⠏ Building...✘ [ERROR] TS2307: Cannot find module '@components' or its corresponding type declarations. [plugin angular-compiler]

    src/app/app.component.ts:4:23:
      4 │ import { testFn } from "@components";
        ╵                        ~~~~~~~~~~~~~


✘ [ERROR] Could not resolve "@components"

    src/app/app.component.ts:4:23:
      4 │ import { testFn } from "@components";
        ╵                        ~~~~~~~~~~~~~

  You can mark the path "@components" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.


Application bundle generation failed. [2.524 seconds]
Watch mode enabled. Watching for file changes...
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.5
Node: 20.10.0
Package Manager: npm 10.2.3
OS: darwin arm64

Angular: 17.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.5
@angular-devkit/build-angular   17.0.5
@angular-devkit/core            17.0.5
@angular-devkit/schematics      17.0.5
@schematics/angular             17.0.5
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by JoostK** [comment]
Please provide more information, e.g. the exact path mappings are relevant. Ideally a minimum reproduction is provided.
