### ISSUE TITLE
_factories is undefined after angular 12 upgrade causes application is not loading

### ISSUE THREAD

**Issue by prathviraj-ac** [angular/angular#43662]
Please file any Angular CLI issues at: https://github.com/angular/angular-cli/issues/new

For the time being, we keep Angular CLI issues in a separate repository.
i  am on angular 12.2.7 after upgrade from version 9 to 12 and this peace of code is gives undefined value 

**const factories = Array.from(this.resolver['_factories'].keys());**

i have set "enableIvy": false and   "declarationMap": false in tsconfig but still have same issue. 

**vendor.js:75164 ERROR TypeError: Cannot read properties of undefined (reading 'keys')
    at DynamicWidgetComponent.push.49476.DynamicWidgetComponent.getFactoryClass (dynamic-widget.component.ts:148)
    at DynamicWidgetComponent.push.49476.DynamicWidgetComponent.buildComponent (dynamic-widget.component.ts:98)
    at DynamicWidgetComponent.push.49476.DynamicWidgetComponent.ngOnChanges (dynamic-widget.component.ts:64)
    at DynamicWidgetComponent.rememberChangeHistoryAndInvokeOnChangesHook (vendor.js:69108)
    at callHook (vendor.js:70357)
    at callHooks (vendor.js:70300)
    at executeInitAndCheckHooks (vendor.js:70236)
    at refreshView (vendor.js:78949)
    at refreshEmbeddedViews (vendor.js:80268)
    at refreshView (vendor.js:78964)**

**Comment by JoostK** [comment]
The `_factories` property is a private field in ViewEngine's runtime implementation. ViewEngine can no longer be used for applications in Angular 12; disabling the `enableIvy` flag reports a warning in the CLI and switches back to Ivy regardless of the flag.
