### ISSUE TITLE
AOT: ngfactory files no longer being generated

### ISSUE THREAD

**Issue by dhardtke** [angular/angular#20082]
## I'm submitting a...
<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When running `ngc -p tsconfig-aot.json` I get
> app/main-aot.ts(3,34): error TS2307: Cannot find module '../compiled/app/app.module.ngfactory'.

It worked perfectly fine with Angular 4.x, I changed the tsconfig-aot.json accordingly.

## Expected behavior
Compilation should work flawlessly.

## Environment

<pre><code>
Angular version: 5.0.0
 
For Tooling issues:
- Node version: 8.4.0  
- Platform:  Windows 10
- TypeScript: 2.4.2
</code></pre>

tsconfig-aot.json
```json
{
    "compilerOptions": {
        "target": "es2015",
        "module": "esnext",
        "moduleResolution": "node",
        "sourceMap": false,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "noImplicitAny": true,
        "suppressImplicitAnyIndexErrors": true,
        "rootDir": ".",
        "baseUrl": "./app",
        "lib": [
            "dom",
            "es5",
            "es2015",
            "es2016",
            "es2017.object"
        ],
        "outDir": "compiled"
    },
    "files": [
        "app/app.module.ts",
        "app/main-aot.ts"
    ],
    "exclude": [
        "node_modules",
        "**/*.spec.ts",
        "app/testing",
        "tslint",
        "config"
    ],
    "angularCompilerOptions": {
        "annotationsAs": "decorators",
        "entryModule": "app/app.module#AppModule",
        "skipMetadataEmit": true,
        "preserveWhitespaces": false
    }
}
```

main-aot.ts:
```typescript
import {platformBrowser} from "@angular/platform-browser";

import {AppModuleNgFactory} from "../compiled/app/app.module.ngfactory";

platformBrowser().bootstrapModuleFactory(AppModuleNgFactory);
```

**Comment by Toxicable** [comment]
Could you please provide a minimal reproduction of your issue, the code you have supplied is not enough to reproduce your issue.
Also have you followed our upgrade guide? https://angular-update-guide.firebaseapp.com/

**Comment by blacksonic** [comment]
Typescript files are no longer emitted on AOT compilation, just use the generated Javascript files.

**Comment by petersalomonsen** [comment]
Experiencing exactly the same. Following the documentation here:

https://angular.io/guide/aot-compiler

Expecting to be able to import the generated module.ngfactory like this:

import { AppModuleNgFactory } from './app/app.module.ngfactory';

But the factory ts file and the mentioned aot folder is nowhere to be found.

Is the documentation up to date here?

**Comment by dhardtke** [comment]
Minimal reproduction:
```bash
git clone https://github.com/dhardtke/no-ngfactory-ngc
cd no-ngfactory-ngc
yarn install
yarn run ngc
```
=> `src/main-aot.ts(3,36): error TS2307: Cannot find module '../aot/src/app/app.module.ngfactory'.`

We are not using the CLI in our project. We are using Webpack with a custom config that uses @ngtools/webpack (which is irrelevant for this problem). I followed the official guide, as far as I can tell the `main.ts` generated by ng-cli is configured to use JIT, yet it somehow "magically" uses AOT when running `ng build --prod`?

**Comment by dhardtke** [comment]
Tried the same as in https://github.com/angular/angular/issues/19780, but it's not working... -.-

**Comment by dhardtke** [comment]
Okay, fixed (at least for me):

You need to be absolutely sure to use a path in your `main-aot.ts` file that is pointing to the same app.module file, but with the ".ngfactory" suffix, e.g. for me, my main-aot.ts is lying in the same folder as my app.module.ts:
> import { AppModuleNgFactory } from "./app.module.ngfactory";

**Comment by scott-m-snyder** [comment]
I'm having the same issue with ngfactory.ts files stopped being built in 5.0.  Worked in 4.4.6

**Comment by dhardtke** [comment]
I am using webpack and Angular with AOT and @ngtools/webpack perfectly fine.
Also, I am using JIT with webpack-dev-server for development.

**Comment by sarunint** [comment]
@p3x-robot in `@ngtools/webpack`, there are now 2 plugins. `AngularCompilerPlugin`, which is for Angular v5+ and `AotPlugin`, which is for v4 and older. Please use the correct one.

**Comment by freezy** [comment]
> You need to be absolutely sure to use a path in your main-aot.ts file that is pointing to the same app.module file, but with the ".ngfactory" suffix, e.g. for me, my main-aot.ts is lying in the same folder as my app.module.ts

So suddenly the ngfactory file is in a different folder than the `genDir` folder it used to be. Since the file is not actually physically created during the Webpack build, this was a nightmare to debug. Is this documented somewhere? I've read through the [changelog](https://github.com/angular/angular/blob/master/CHANGELOG.md) and I haven't found anything. Also the [AOT guide](https://angular.io/guide/aot-compiler) doesn't have any info about this, and there used to be a guide for setting up AOT with Webpack, but it seems to be gone.

**Comment by smasala** [comment]
hasn't `genDir` been replaced by `outDir`?

**Comment by trotyl** [comment]
@freezy It's actually mentioned in the update guide:

> Do not rely on gendir, instead look at using skipTemplateCodeGen. [Read more](https://github.com/angular/angular/issues/19339#issuecomment-332607471)
