### ISSUE TITLE
A runtime error is thrown when calling `detectChanges`  inside the `transform` method of a pipe.

### ISSUE THREAD

**Issue by ahasall** [angular/angular#38611]
# 🐞 bug report

### Affected Package

The issue is caused by package `@angular/core`.

### Description

A runtime error is thrown when calling `detectChanges`  inside the `transform` method of a pipe.

## 🔬 Minimal Reproduction

A reproduction of this issue can be found [here](https://github.com/ahasall/router-localize-material-ivy-bug-repro).

## 🔥 Exception or Error

```javascript
core.js:4200 ERROR TypeError: Cannot read property 'call' of undefined
    at callHook (core.js:3045)
    at callHooks (core.js:3008)
    at executeCheckHooks (core.js:2941)
    at selectIndexInternal (core.js:6177)
    at Module.ɵɵadvance (core.js:6156)
    at AppComponent_Template (app.component.html:1)
    at executeTemplate (core.js:7306)
    at refreshView (core.js:7175)
    at refreshComponent (core.js:8329)
    at refreshChildComponents (core.js:6968)
```

## 🌍  Your Environment

**Angular Version:**

```bash
Angular CLI: 10.0.7
Node: 12.18.3
OS: darwin x64

Angular: 10.0.12
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.7
@angular-devkit/build-angular     0.1000.7
@angular-devkit/build-optimizer   0.1000.7
@angular-devkit/build-webpack     0.1000.7
@angular-devkit/core              10.0.7
@angular-devkit/schematics        10.0.7
@angular/cdk                      10.1.3
@angular/cli                      10.0.7
@angular/material                 10.1.3
@ngtools/webpack                  10.0.7
@schematics/angular               10.0.7
@schematics/update                0.1000.7
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0
```

**Anything else relevant?**

This issue only happens when Ivy is enabled.

**Comment by devversion** [comment]
Just for later reference. We chatted about this briefly in the GDE channel.

> It looks like the hook data structure is the same, given we always have the same hooks, but the start hook data structure is
different and incorrect with the detectChanges [..] For later reference: startIndex is appearing on the hook function, instead of on the directive index when the error is thrown.

It is unexpected that `startIndex` for the hook invocations is selecting a hook callback, compared to a directive index as usually. Initially suspicion is that the hooks are re-triggered immediately due to the explicit `detectChanges` while the hook flags are still being updated.

https://cs.opensource.google/angular/angular/+/master:packages/core/src/render3/hooks.ts;l=227-230?q=PREORDER_HOOK_FLAGS&ss=angular

**Comment by crisbeto** [comment]
I've been looking into it. It seems to happen if there is an init hook, an `ngOnChanges` hook and a binding with a pipe on the same element. Here's a simplified test.

```
fit('', () => {
  @Pipe({name: 'testPipe', pure: true})
  class TestPipe implements PipeTransform {
    constructor(private _changeDetectorRef: ChangeDetectorRef) {}

    transform(value: any) {
      this._changeDetectorRef.detectChanges();
      return value;
    }
  }

  @Component({
    template: `<div [dir]="1 | testPipe">{{1 | testPipe}}</div>`,
  })
  class App {
  }

  @Directive({selector: '[dir]'})
  class Dir {
    @Input('dir') value: any;
    ngOnChanges() {}
    ngAfterViewInit() {}
  }

  TestBed.configureTestingModule({declarations: [App, Dir, TestPipe]});
  const fixture = TestBed.createComponent(App);
  fixture.detectChanges();
});
```

I'll try to either resolve it or post my findings here.

**Comment by crisbeto** [comment]
I spent some more time on it and I found a couple of solutions, but they ended up breaking other functionality so I think I'll leave this for somebody that knows the hook logic better. Here's what I've got so far:

1. It doesn't break due to the pipe in particular, but because `ViewContainerRef.detectChanges` is called at the wrong time. The issue can be reproduced by calling it inside an input setter of a directive that has `ngAfterViewInit` and `ngOnChanges` hooks. Here's an even simpler test case:
```ts
it('should not throw when calling detectChanges from setter', () => {
  @Directive({selector: '[dir]'})
  class Dir implements OnChanges, AfterViewInit {
    constructor(private _changeDetectorRef: ChangeDetectorRef) {}

    @Input('dir')
    set value(_value: any) {
      this._changeDetectorRef.detectChanges(); // Triggers the error.
    }
    ngOnChanges() {}
    ngAfterViewInit() {}
  }

  @Component({template: `<div [dir]="value">{{value}}</div>`})
  class App {
    value = 1;
  }

  TestBed.configureTestingModule({declarations: [App, Dir]});
  const fixture = TestBed.createComponent(App);
  fixture.detectChanges();
});
```

2. I _think_, the error happens because we re-enter [`refreshView`](https://github.com/angular/angular/blob/master/packages/core/src/render3/instructions/shared.ts#L405) in the middle of it running the init hooks. In this particular case, it breaks when it's trying to run `ngAfterViewInit`, but the same problem can be observed if we change it to `ngAfterContentInit`, `ngAfterViewChecked` or `ngAfterContentChecked`.
3. We've dealt with a re-entrant change detection issue like this in the past by moving some of the `LView` state into the global store (see https://github.com/angular/angular/commit/e16f75db566e7bb22d8b8c1566f8ed5be6874be0). I suspect that we may have to do the same for `LView[FLAGS]`, but I don't know what the side-effects of doing so would be.
4. The way I tried to fix it was to update the flags which determine whether a hook is allowed to run before actually running the hook. This worked for the test case above, but it broke a bunch of unrelated tests.

**Comment by marcj** [comment]
I have the same issue after upgrading to v11 (v10 works fine). I use a [library](https://github.com/marcj/angular-desktop-ui) that has ZoneJS deactivated and uses for updating the view ChangeDetectorRef's detectChanges. This error appears in weird scenarios only when I have a nested ngFor for example.

```
core.js:6006 ERROR TypeError: Cannot read property 'call' of undefined
    at callHook (core.js:2485)
    at callHooks (core.js:2451)
    at executeCheckHooks (core.js:2384)
    at selectIndexInternal (core.js:8167)
    at Module.ɵɵadvance (core.js:8156)
    at AppComponent_ng_container_23_ng_container_1_Template (app.component.ts:38)
    at executeTemplate (core.js:9302)
    at refreshView (core.js:9171)
    at refreshEmbeddedViews (core.js:10278)
    at refreshView (core.js:9195)
    at refreshEmbeddedViews (core.js:10278)
    at refreshView (core.js:9195)
    at refreshComponent (core.js:10324)
    at refreshChildComponents (core.js:8968)
    at refreshView (core.js:9221)
    at renderComponentOrTemplate (core.js:9285)
    at tickRootContext (core.js:10498)
    at detectChangesInRootView (core.js:10523)
    at RootViewRef.detectChanges (core.js:22528)
    at ApplicationRef.tick (core.js:29181)
    at ApplicationRef._loadComponent (core.js:29217)
    at ApplicationRef.bootstrap (core.js:29158)
    at core.js:28860
    at Array.forEach (<anonymous>)
    at PlatformRef._moduleDoBootstrap (core.js:28860)
    at core.js:28830
```

![Screenshot 2020-12-08 at 23 07 00](https://user-images.githubusercontent.com/450980/101547126-16857280-39aa-11eb-947b-d719af9033a5.png)

![Screenshot 2020-12-08 at 23 06 30](https://user-images.githubusercontent.com/450980/101547070-053c6600-39aa-11eb-992f-86191633da21.png)


After looking at the code:
https://cs.opensource.google/angular/angular/+/master:packages/core/src/render3/hooks.ts;l=216-217?q=PREORDER_HOOK_FLAGS&ss=angular
it seems strange to me to iterate over `arr` using `i < array.length` and then look ahead using `arr[i + 1]`. This way the last iteration has always `hook = undefined`, except if you have a unchecked [convention that the last item is a number and causes `break`](https://cs.opensource.google/angular/angular/+/master:packages/core/src/render3/hooks.ts;l=221?q=PREORDER_HOOK_FLAGS&ss=angular).

Although v10 has the same code there, after downgrading to v10.2.7 this error does not appear anymore.
