### ISSUE TITLE
Chrome 41 issue - Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by pbender87** [angular/angular#28315]
# 🐞 bug report

### Affected Package
@angular/core
@angular/common
@angular/platform-browser-dynamic

### Description

The pre generated app (Angular CLI 7.2.2) does not work with Chromium Version 41.0.2272.0 (64-bit).
If i create a new app with the Angular CLI 7.2.2 and start the pre generated project , the app crashes with the following error: Uncaught TypeError: undefined is not a function

## 🔬 Minimal Reproduction
Create a new project with the Angular CLI 7.2.2 and start the app:

<pre><code>
$ ng new hello-world
$ cd hello-world/
$ npm run serve
</code></pre>

## 🔥 Exception or Error
<img width="806" alt="bildschirmfoto 2019-01-23 um 14 04 19" src="https://user-images.githubusercontent.com/46962961/51608541-1300b380-1f18-11e9-9349-911363e37af7.png">

## 🌍  Your Environment

**Chrome Version:**
Chromium Version 41.0.2272.0 (64-bit)

**Angular Version:**
<pre><code>
$ ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.2.2
Node: 10.15.0
OS: darwin x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.12.2
@angular-devkit/core         7.2.2
@angular-devkit/schematics   7.2.2
@schematics/angular          7.2.2
@schematics/update           0.12.2
rxjs                         6.3.3
typescript                   3.2.2
</code></pre>

**Comment by pbender87** [comment]
https://developers.google.com/search/docs/guides/rendering:

> Googlebot uses a web rendering service (WRS) that is based on Chrome 41 (M41). Generally, WRS supports the same web platform features and capabilities that the Chrome version it uses

So this means Google doesn't support its own Framework anymore (by default)?

**Comment by mlc-mlapis** [comment]
@pbender87 ... hmm, when I tested Google Search Console the last time (5 months ago) to render web site based on Angular ... it was rendered perfectly even without SSR ... just normal SPA app and Google could be able to render JS in it.
