### ISSUE TITLE
[8.1] Ivy compilation error with boolean checkbox

### ISSUE THREAD

**Issue by juergenzimmermann** [angular/angular#31401]
# 🐞 bug report

### Affected Package
@angular/compiler

### Is this a regression?
Yes, after upgrading from 8.0 to 8.1

### Description
Here is the component class in TypeScript with an HTML template having a _boolean checkbox_:

```
@Component({
    selector: 'hs-create-lieferbar',
    templateUrl: './create-lieferbar.component.html',
})
export class CreateLieferbarComponent implements OnInit {
    @Input()
    readonly form!: FormGroup;

    readonly lieferbar = new FormControl(false);

    ngOnInit() {
        this.form.addControl('lieferbar', this.lieferbar);
    }
}
```

Here is the HTML template which only works when the `<input .../>` tag is omitted:

```
...
<div class="col col-10" [formGroup]="form">
    <div class="checkbox">
        <input
            id="lieferbarInput"
            type="checkbox"
            formControlName="lieferbar"
        />
    </div>
</div>
```

## 🔬 Minimal Reproduction
Please see above.

## 🔥 Exception or Error
<pre><code>
ERROR in __ng_typecheck__.ts:656:5 - error TS2322: Type 'string' is not assignable to type 'boolean'.

656     _t5.checked = "" + ctx.lieferbar;
        ~~~~~~~~~~~
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.1.0
Node: 12.5.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.801.0
@angular-devkit/core         8.1.0
@angular-devkit/schematics   8.1.0
@schematics/angular          8.1.0
@schematics/update           0.801.0
rxjs                         6.4.0
</code></pre>

**Comment by alexzuza** [comment]
Hey,
unfortunately I couldn't reproduce this issue with the code you provided. 
Can you please create a minimal reproducible example as a clean github repository?

**Comment by alxhub** [comment]
Yes, I think the provided code is incomplete. `lieferbar` is not bound to any `[checked]` property in your example.

**Comment by alxhub** [comment]
Closing this, as no working reproduction was provided in 7 days. @juergenzimmermann, please feel free to re-open this issue with a working reproduction if you're still experiencing the problem.
