### PR TITLE
fix(ngcc): correctly invalidate cache when moving/removing files/directories

### LINKED ISSUE #35095: Compilation breaks after update to 9.0.0-rc.13: `Duplicate identifier 'ɵngcc0'`
# 🐞 bug report

### Affected Package
I think the issue is in `@angular/compiler-cli` as it's about `ngcc`, but not sure.

### Is this a regression?

Yes, it was OK in previous RC (rc.12 and below).

### Reproduction

- `npm install @angular/cli@next -g`
- `ng new helloworld --skipGit` (git is disabled to avoid ng commands blocking because repo is not clean, otherwise you have to commit every change)
- `cd helloworld`
- `npm install @angular/{animations,common,compiler,core,forms,platform-browser,platform-browser-dynamic,router,compiler-cli,language-service}@9.0.0-rc.12` (rollback to rc.12, as CLI installed rc.13)
- add any library, for example: `ng add @angular/material@next` and add `MatCardModule` in `AppModule` imports
- `npm start` (to run the compilation with rc.12)
- `ng update @angular/core --next` (will update to rc.13)
- `npm start` 

## 🔥 Exception or Error

Compilation breaks with a lot of errors like this one (it's just an example):

<pre><code>
import * as ɵngcc0 from '@angular/core';
                   ~~~~~~
    node_modules/@angular/material/core/selection/pseudo-checkbox/pseudo-checkbox.d.ts:13:13 -
error TS2300: Duplicate identifier 'ɵngcc0'.
</code></pre>


## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-rc.12
Node: 12.14.1
OS: darwin x64

Angular: 9.0.0-rc.13
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.12
@angular-devkit/build-angular     0.900.0-rc.12
@angular-devkit/build-optimizer   0.900.0-rc.12
@angular-devkit/build-webpack     0.900.0-rc.12
@angular-devkit/core              9.0.0-rc.12
@angular-devkit/schematics        9.0.0-rc.12
@angular/cdk                      9.0.0-rc.9
@angular/cli                      9.0.0-rc.12
@angular/material                 9.0.0-rc.9
@ngtools/webpack                  9.0.0-rc.12
@schematics/angular               9.0.0-rc.12
@schematics/update                0.900.0-rc.12
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**
Quite sure the issue comes from #35079. Before rc.13, when ng updating, next compilation would be blocked, asking to clean up `node_moddules` (#35082).

With rc.13, compilation is not blocked anymore, Angular do a new `ngcc` compilation (`Compiling @angular/core : es2015 as esm2015`), but then fails because of old artifacts. If you clean `node_modules` (`npm ci`), then compilation works again.

Also note that:
- if you have no library at all, the issue doesn't happen,
- it's not specific to Material, it happens with all librairies.

So I think #35079 does not clean up libraries packages.

### PR DESCRIPTION
**Pull request by gkalpak**
One particular scenario where this was causing problems was when the [BackupFileCleaner][1] restored a file (such as a `.d.ts` file) by [moving the backup file][2] to its original location, but the modified content was kept in the cache.

Fixes #35095.

[1]: https://github.com/angular/angular/blob/4d36b2f6e/packages/compiler-cli/ngcc/src/writing/cleaning/cleaning_strategies.ts#L54
[2]: https://github.com/angular/angular/blob/4d36b2f6e/packages/compiler-cli/ngcc/src/writing/cleaning/cleaning_strategies.ts#L61

### CODE REVIEW

File: integration/ngcc/test.sh [hunk 1]
```diff
@@ -140,6 +160,18 @@ assertSucceeded "Expected 'ngcc' to log 'Compiling'."
   assertSucceeded "Expected 'ngcc' to not add trailing commas to factory function parameters in UMD."
 
 
+# Can it correctly clean up and re-compile when dependencies are already compiled by a different version?
+# (Use sync mode to ensure all tasks share the same `CachedFileSystem` instance.)
+  assertNotEquals "1.3.3.7" `node --print "require('@angular/material/button/package.json').__processed_by_ivy_ngcc__.main"`
```
Comment (IgorMinar) [inline integration/ngcc/test.sh]: Add a note about why you picked 1.3.3.7

File: integration/ngcc/test.sh [hunk 2]
```diff
@@ -3,7 +3,7 @@
 # Do not immediately exit on error to allow the `assertSucceeded` function to handle the error.
 #
 # NOTE:
-# Each statement should be followed by an `assertSucceeded`/`assertFailed` or `exit 1` statement.
+# Each statement should be followed by an `assert*` or `exit 1` statement.
```
Comment (IgorMinar) [inline integration/ngcc/test.sh]: Not for this PR but a general note: Can we please stop writing these scripts in bash?

Shelljs is the way to go. Please don't let more bash scripts into the repo during core reviews.

File: integration/ngcc/mock-ngcc-version.js [hunk 3]
```diff
@@ -0,0 +1,47 @@
...
+ *
+ * This script replaces the ngcc version that is used as marker to make already processed packages
+ * appear as if they were processed by a different version. This allows testing the clean-up logic
+ * without the overhead of actually installing an older version, compiling the dependencies, then
+ * installing the current version and compiling again.
+ */
+
+const {readFileSync, writeFileSync} = require('fs');
+
+const mockVersion = process.argv[2] || 'MOCK.VERSION';
```
Comment (IgorMinar) [inline integration/ngcc/mock-ngcc-version.js]: The default value seems dubious. Maybe just require the an argument is provided?

File: integration/ngcc/mock-ngcc-version.js [hunk 4]
```diff
@@ -0,0 +1,47 @@
...
+const buildMarkerPath = require.resolve('@angular/compiler-cli/ngcc/src/packages/build_marker');
+const buildMarkerVersionRe = /\bNGCC_VERSION = '([^']+)';/;
+
+const oldContent = readFileSync(buildMarkerPath, 'utf8');
```
Comment (IgorMinar) [inline integration/ngcc/mock-ngcc-version.js]: older -> original? Please rename throughout the file.

Older could also refer to semver lower version which is not necessarily the case.

**Review by IgorMinar — CHANGES_REQUESTED** [review]

File: integration/ngcc/test.sh (hunk 2 above)
Comment (gkalpak) [reply integration/ngcc/test.sh]: Amen to that :smiley:

File: packages/compiler-cli/src/ngtsc/file_system/test/cached_file_system_spec.ts [hunk 5]
```diff
@@ -252,6 +252,24 @@ describe('CachedFileSystem', () => {
...
     });
+
+    it('should delete the `to` "readFile" cache (if `from` was not cached)', () => {
+      spyOn(delegate, 'moveFile');
+      const readFileSpy = spyOn(delegate, 'readFile');
+
+      // Fill the xyz "readFile" cache
+      readFileSpy.and.returnValue('xyz content');
+      fs.readFile(xyzPath);
+      readFileSpy.calls.reset();
```
Comment (petebacondarwin) [inline packages/compiler-cli/src/ngtsc/file_system/test/cached_file_system_spec.ts]: I don't think this is necessary, since you are rewriting the spy below.

**Review by petebacondarwin — CHANGES_REQUESTED** [review]
The source code changes look perfect! Thanks for tidying this up @gkalpak.

What is our policy for updating `integration/ngcc/yarn.lock`?

Could we change the integration test to modify the build markers in `@angular/material/button/package.json` and then run ngcc again, rather than hacking ngcc itself to have a different version?
Modifying ngcc is much more brittle to internal code changes in the ngcc source code - as we found wth the components repo unit tests.

File: integration/ngcc/mock-ngcc-version.js (hunk 4 above)
Comment (gkalpak) [reply integration/ngcc/mock-ngcc-version.js]: I had it like this originally <sub>(pun intented)</sub>, but liked the `old*`/`new*` symmetry.
Changed it to `original*`/`updated*`.

Comment (IgorMinar) [reply integration/ngcc/mock-ngcc-version.js]: Sgtm

File: integration/ngcc/mock-ngcc-version-marker.js [hunk 6]
```diff
@@ -0,0 +1,50 @@
...
+ * **Usage:**
+ * ```sh
+ * node mock-ngcc-version-marker <entry-point> <mock-ngcc-version>
+ *
+ * # Example:
+ * # node mock-ngcc-version-marker @angular/material/button 3.0.0
+ * ```
+ *
+ * Ngcc marks entry-points as processed by adding marker properties in their `package.json`. It uses
+ * a version as marker in order to be able to distinguish entry-points processed by a different ngcc
```
Comment (petebacondarwin) [inline integration/ngcc/mock-ngcc-version-marker.js]:
```suggestion
 * a version as a marker in order to be able to distinguish entry-points processed by a different ngcc
```

File: integration/ngcc/test.sh [hunk 7]
```diff
@@ -140,6 +160,27 @@ assertSucceeded "Expected 'ngcc' to log 'Compiling'."
   assertSucceeded "Expected 'ngcc' to not add trailing commas to factory function parameters in UMD."
 
 
+# Can it correctly clean up and re-compile when dependencies are already compiled by a different version?
+  readonly actualNgccVersion=`node --print "require('@angular/compiler-cli/package.json').version"`
+  readonly mockNgccVersion="3.0.0"
+
+  # Mock the ngcc version marker on a package make it appear as if compiled by a different ngcc version.
```
Comment (petebacondarwin) [inline integration/ngcc/test.sh]:
```suggestion
  # Mock the ngcc version marker on a package to make it appear as if it is compiled by a different ngcc version.
```

**Review by petebacondarwin — APPROVED** [review]

**Review by IgorMinar — APPROVED** [review]

**Comment by mhevery** [comment]
[presubmit](http://test/OCL:292996966:BASE:292997002:1580766832586:91b3c27a)

**Comment by gkalpak** [comment]
BTW, regarding the `yarn.lock` file update:

These lockfiles depend on the locally built Angular packages (and their dependencies), because the integration projects have dependencies such as `"@angular/core": "file:../../dist/packages-dist/core"`.

However, we do not go and update these lockfiles every time the dependencies of the Angular packages change (such as after 37f39d6db). So, they get updated whenever someone happens to run the integration project locally, but that should be fine. (The same updates happen every time they run on CI.)
