### ISSUE TITLE
Angular2 AoT Compiler Errors 

### ISSUE THREAD

**Issue by DeeM297** [angular/angular#12156]
I have updated an ionic2 project from beta 11 to rc0 and so it's now using angular 2.0.0 instead of rc4. I'm no longer able to compile and getting this error:

> Error: Error encountered resolving symbol values statically. Calling function 'createStore', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in c:/Ionic/ionic-redux-test/.tmp/app/app.module.ts, resolving symbol AppModule in c:/Ionic/ionic-redux-test/.tmp/app/app.module.ts

These are the modifications I've made in _app.module.ts_ in order to use the redux store and I think this is giving those errors:

Just before @NgModule
```

//Redux - ReduxThunk - rootReducer
import { Store, createStore, applyMiddleware } from 'redux';
import ReduxThunk  from 'redux-thunk';
import { rootReducer } from '../modules/rootReducer';

const appStore = createStore(
    rootReducer,
    applyMiddleware(ReduxThunk)
);
```

And adding this in the providers array:
```
providers: [
    { provide: 'AppStore', useValue: appStore }
]
```

* **Node (for AoT issues):** `node --version` =   
Node v4.2.6
npm v3.8.2

Any ideas on what should be done differently?

**Comment by DzmitryShylovich** [comment]
Try to use `useFactory` instead of `useValue`

**Comment by DeeM297** [comment]
Thanks for the quick reply! It gave me the same errors and this line got highlighted in red in visual code.

**Comment by DzmitryShylovich** [comment]
Take a look how they create aot-friendly reducer in this project https://github.com/ngrx/example-app/blob/master/src/app/reducers/index.ts#L81

**Comment by DeeM297** [comment]
Thanks for looking into it. I was able to solve it with the following change in *app.module.ts*

```
    // const appStore = createStore(
    //   rootReducer,
    //   applyMiddleware(ReduxThunk)
    // );
    
    export function appStore(): any {
      return createStore(
                rootReducer,
                applyMiddleware(ReduxThunk)
              );
    };
```

**Comment by DzmitryShylovich** [comment]
You can close the issue if it was resolved.

**Comment by DeeM297** [comment]
I'm able to build but not use the AppStore. In home.ts, I was doing this
```
export class HomePage {
    constructor(
        @Inject('AppStore') public appStore: any,
    ) { }

    testRedux(){
        this.appStore.dispatch((dispatch)=> {
            dispatch({type: 'INCREMENT'});});
        console.log(this.appStore.getState().increment.counter);
    }
}
```
And getting this error

> this.appStore.getState is not a function
> TypeError: this.appStore.getState is not a function

Any ideas on where this could be coming from?

**Comment by DzmitryShylovich** [comment]
What is appStore? Does it have `getState` method?

**Comment by DeeM297** [comment]
appStore is the Redux store which is created by the function createStore(). It has the getState method.

More info on the Store [here ](https://egghead.io/lessons/javascript-redux-store-methods-getstate-dispatch-and-subscribe)and [here](http://redux.js.org/docs/api/Store.html).

**Comment by aluanhaddad** [comment]
Sounds like the function is not being called.

**Comment by DzmitryShylovich** [comment]
Take a look at [ngrx/store](https://github.com/ngrx/store) and [ng2-redux](https://github.com/angular-redux/ng2-redux). [Difference](https://github.com/ngrx/store/issues/169#issuecomment-231515115) between projects.

**Comment by DeeM297** [comment]
Thank you for the link. That's exactly the problem I'm facing: 

> The process for creating a Redux store with middleware using the actual Redux library maps poorly to Angular 2 DI providers. 

The project was working with rc4 and now in angular 2.0.0 and AoT, I'm having a hard time with it. I've tried to applied what's written in this post: [Making your Angular 2 library statically analyzable for AoT](https://medium.com/@isaacplmann/making-your-angular-2-library-statically-analyzable-for-aot-e1c6f3ebedd5) 

I'm following AoT best practise by changing _const lambda_ into _export function_ but then getting stuck in using the store.
```
// const appStore = createStore(
//   rootReducer,
//   applyMiddleware(ReduxThunk)
// );

export function appStore(): any {
  return createStore(
            rootReducer,
            applyMiddleware(ReduxThunk)
          );
};
```

One idea I'm exploring is to take the _createStore()_ out of _app.module.ts_ and do it in an independent provider. 

And just found this project which took the same route: [Angular/Redux Complex UI Example](https://github.com/ng-cookbook/angular2-redux-complex-ui/blob/master/src/app/app-bootstrap.ts). 
I'm going to try and see what happens.

**Comment by DeeM297** [comment]
Was able to solve the DI problem. Thank you for helping me out. 👍 =)
