### ISSUE TITLE
after updating to v15

### ISSUE THREAD

**Issue by musheghz** [angular/angular#48220]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

core.mjs:9229 ERROR Error: Uncaught (in promise): TypeError: instanceCleanupFn is not a function
TypeError: instanceCleanupFn is not a function
    at processCleanups (core.mjs:6552:13)
    at cleanUpView (core.mjs:6493:9)
    at destroyViewTree (core.mjs:6325:17)
    at destroyLView (core.mjs:6470:9)
    at RootViewRef.destroy (core.mjs:13642:9)
    at ComponentRef.destroy (core.mjs:14081:23)
    at RouterOutlet.deactivate (router.mjs:2575:28)
    at ActivateRoutes.deactivateRouteAndOutlet (router.mjs:2966:28)
    at ActivateRoutes.deactivateRouteAndItsChildren (router.mjs:2939:18)
    at ActivateRoutes.deactivateRouteAndOutlet (router.mjs:2962:18)
    at resolvePromise (zone.js:1211:31)
    at resolvePromise (zone.js:1165:17)
    at zone.js:1278:17
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.mjs:26584:33)
    at _ZoneDelegate.invokeTask (zone.js:405:60)
    at Zone.runTask (zone.js:178:47)
    at drainMicroTaskQueue (zone.js:585:35)
    at ZoneTask.invokeTask [as invoke] (zone.js:491:21)
    at invokeTask (zone.js:1661:18)

### Minimal Reproduction

cant share code

### Your Environment

```text
Angular CLI: 15.0.1
Node: 16.13.0
Package Manager: npm 8.1.0
OS: darwin x64

Angular: 15.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1500.1
@angular-devkit/build-angular      15.0.1
@angular-devkit/core               15.0.1
@angular-devkit/schematics         15.0.1
@angular/cdk                       15.0.0
@angular/flex-layout               10.0.0-beta.32
@angular/material                  15.0.0
@angular/material-moment-adapter   15.0.0
@schematics/angular                15.0.1
rxjs                               6.6.0
typescript                         4.9.3
```

### Anything else relevant?

{
  "name": "fuse",
  "version": "8.1.2",
  "license": "https://themeforest.net/licenses/terms/regular",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --open",
    "start-hmr": "ng serve --configuration hmr --source-map=false --hmr-warning=false",
    "start-hmr-sourcemaps": "ng serve --configuration hmr --source-map=true --hmr-warning=false",
    "build": "node --max_old_space_size=8000 ./node_modules/@angular/cli/bin/ng build --dev",
    "build-stats": "node --max_old_space_size=8000 ./node_modules/@angular/cli/bin/ng build --dev --stats-json",
    "build-prod": "node --max_old_space_size=8000 ./node_modules/@angular/cli/bin/ng build --configuration production",
    "build-dev": "node --max_old_space_size=8000 ./node_modules/@angular/cli/bin/ng build --configuration dev",
    "build-stage": "node --max_old_space_size=8000 ./node_modules/@angular/cli/bin/ng build --configuration stage",
    "build-prod-stats": "node --max_old_space_size=8000 ./node_modules/@angular/cli/bin/ng build --prod --stats-json",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "postinstall": "ngcc",
    "bundle-report": "webpack-bundle-analyzer dist/stats.json"
  },
  "private": true,
  "dependencies": {
    "@ag-grid-community/all-modules": "*",
    "@ag-grid-community/angular": "*",
    "@ag-grid-community/core": "*",
    "@angular-material-components/datetime-picker": "^8.0.0",
    "@angular/animations": "15.0.1",
    "@angular/cdk": "15.0.0",
    "@angular/common": "15.0.1",
    "@angular/compiler": "15.0.1",
    "@angular/core": "15.0.1",
    "@angular/flex-layout": "10.0.0-beta.32",
    "@angular/forms": "15.0.1",
    "@angular/material": "15.0.0",
    "@angular/material-moment-adapter": "15.0.0",
    "@angular/platform-browser": "15.0.1",
    "@angular/platform-browser-dynamic": "15.0.1",
    "@angular/router": "15.0.1",
    "@ngrx/effects": "14.3.2",
    "@ngrx/router-store": "14.3.2",
    "@ngrx/store": "14.3.2",
    "@ngrx/store-devtools": "14.3.2",
    "@ngx-translate/core": "13.0.0",
    "@swimlane/dragula": "3.8.0",
    "@swimlane/ngx-charts": "9.0.0",
    "@swimlane/ngx-datatable": "^20.1.0",
    "@swimlane/ngx-dnd": "8.1.2",
    "@types/prismjs": "1.16.1",
    "ag-grid-angular": "^27.0.1",
    "ag-grid-community": "^27.0.1",
    "angular-calendar": "0.28.16",
    "angular-in-memory-web-api": "0.11.0",
    "angular2-csv": "~0.2.5",
    "angular2-moment": "1.9.0",
    "chart.js": "2.9.3",
    "chartjs-plugin-annotation": "0.5.7",
    "classlist.js": "1.1.20150312",
    "d3": "5.16.0",
    "date-fns": "1.30.1",
    "flag-icon-css": "3.5.0",
    "hammerjs": "^2.0.8",
    "lodash": "4.17.19",
    "moment": "2.27.0",
    "ng2-charts": "2.3.2",
    "ng2-file-upload": "1.4.0",
    "ng2-tooltip-directive": "2.10.3",
    "ngrx-store-freeze": "0.2.4",
    "ngx-color-picker": "8.2.0",
    "ngx-cookie-service": "2.4.0",
    "ngx-mat-select-search": "3.3.0",
    "ngx-moment": "3.5.0",
    "ngx-order-pipe": "2.0.4",
    "ngx-trend": "6.1.1",
    "perfect-scrollbar": "1.5.0",
    "postcss": "8.3.4",
    "postcss-scss": "4.0.0",
    "prismjs": "1.20.0",
    "rxjs": "6.6.0",
    "web-animations-js": "2.3.2",
    "zingchart-angular": "1.0.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "15.0.1",
    "@angular-eslint/builder": "14.0.0-alpha.4",
    "@angular-eslint/eslint-plugin": "14.0.0-alpha.4",
    "@angular-eslint/eslint-plugin-template": "14.0.0-alpha.4",
    "@angular-eslint/schematics": "14.0.0-alpha.4",
    "@angular-eslint/template-parser": "14.0.0-alpha.4",
    "@angular/cli": "15.0.1",
    "@angular/compiler-cli": "15.0.1",
    "@angular/language-service": "15.0.1",
    "@angularclass/hmr": "2.1.3",
    "@ngrx/schematics": "14.3.2",
    "@types/jasmine": "~3.6.0",
    "@types/jasminewd2": "2.0.8",
    "@types/lodash": "4.14.158",
    "@types/node": "14.0.24",
    "@typescript-eslint/eslint-plugin": "5.29.0",
    "@typescript-eslint/parser": "5.29.0",
    "eslint": "^8.18.0",
    "file-saver": "2.0.5",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "6.3.3",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "3.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "ngx-daterangepicker-material": "2.4.1",
    "protractor": "7.0.0",
    "ts-node": "8.10.2",
    "tslib": "2.4.0",
    "typescript": "^4.9.3",
    "webpack-bundle-analyzer": "3.8.0"
  }
}

**Comment by JoostK** [comment]
Without a reproduction we won't be able to investigate.
