### PR TITLE
build: fix compilation error due to conflict

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes a compilation error that happened, because a couple of related PRs landed at the same time.

### CODE REVIEW

**Review by AndrewKushnir — APPROVED** [review]

**Comment by alxhub** [comment]
This PR was merged into the repository by commit 5419af61921aea0faacee88851c8243b8df817b5.
