### ISSUE TITLE
R3InjectorError encountered after upgrading from Angular 19.1.4 to 19.2.6

### ISSUE THREAD

**Issue by cdskill** [angular/angular#60881]
### Which @angular/* package(s) are the source of the bug?

upgrade

### Is this a regression?

Yes

### Description

Description:
After upgrading my workspace from Angular 19.1.4 to 19.2.6, I am encountering several R3InjectorError errors in the console when the application is deployed. These errors appear only in a deployed environment.

Steps to Reproduce:

- Upgrade the workspace from Angular 19.1.4 to 19.2.6.
- Build the application using the production configuration.
- Deploy the built application locally. (http-server)
- Open the browser console and observe the R3InjectorError messages.

Additional Details:
The issue does not occur during a standard development build.
Reproducing the error requires using the production configuration.
The errors are related to dependency injection, suggesting there might be a misconfiguration or a breaking change introduced in version 19.2.6.
Any insights or recommendations on how to resolve this issue would be greatly appreciated.

### Please provide the exception or error you saw

```true
2716.73cbd997df6af897.js:1 ERROR NullInjectorError: R3InjectorError[au -> o -> o]: 
  NullInjectorError: No provider for o!
    at Ri.get (2716.73cbd997df6af897.js:1:32871)
    at an.get (2716.73cbd997df6af897.js:1:36343)
    at an.get (2716.73cbd997df6af897.js:1:36343)
    at gw (2716.73cbd997df6af897.js:1:31099)
    at Ie (2716.73cbd997df6af897.js:1:31177)
    at Ba (2716.73cbd997df6af897.js:1:31646)
    at Object.r [as factory] (2716.73cbd997df6af897.js:1:38808)
    at an.hydrate (2716.73cbd997df6af897.js:1:37832)
    at an.get (2716.73cbd997df6af897.js:1:36296)
    at e.synchronize (2716.73cbd997df6af897.js:1:166836)

THEN optimization=false:

7705.de4db2f7e67e939d.js:7087 ERROR NullInjectorError: R3InjectorError(Environment Injector)[RendererFactory2 -> DomRendererFactory2 -> DomRendererFactory2]: 
  NullInjectorError: No provider for DomRendererFactory2!
    at NullInjector.get (7705.de4db2f7e67e939d.js:2161:21)
    at R3Injector.get (7705.de4db2f7e67e939d.js:2689:27)
    at R3Injector.get (7705.de4db2f7e67e939d.js:2689:27)
    at injectInjectorOnly (7705.de4db2f7e67e939d.js:1667:28)
    at ɵɵinject (7705.de4db2f7e67e939d.js:1673:59)
    at injectArgs (7705.de4db2f7e67e939d.js:1798:17)
    at Object.factory (7705.de4db2f7e67e939d.js:2897:46)
    at 7705.de4db2f7e67e939d.js:2802:35
    at runInInjectorProfilerContext (7705.de4db2f7e67e939d.js:1438:5)
    at R3Injector.hydrate (7705.de4db2f7e67e939d.js:2801:11)
handleError	@
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
"@angular/animations": "19.2.6",
    "@angular/common": "19.2.6",
    "@angular/compiler": "19.2.6",
    "@angular/core": "19.2.6",
    "@angular/forms": "19.2.6",
    "@angular/platform-browser": "19.2.6",
    "@angular/platform-browser-dynamic": "19.2.6",
    "@angular/router": "19.2.6",
    "@nx/angular": "20.1.4",
    "typescript": "5.7.3",
```

**Comment by JeanMeche** [comment]
Hi, without a reproduction this is hardly actionnable to us. Could you please provide a stackblitz that exposes that issue. Thank you.

**Comment by cdskill** [comment]
I understand that reproducing a minimal example is require but since this issue occurs within a complex monorepo that involves many dependencies in an Angular microfrontend architecture I cannot now. However, I was able to identify a workaround in our shell-level application by adding the following provider:

```typescript
providers: [
  // ... other providers
  importProvidersFrom(BrowserModule),
  // ... other providers
]
```

Notably, this additional provider was not required before upgrading to Angular 19.2.6—everything worked as expected without it.

Based on the error I encountered and the fix implemented, it seems likely that others upgrading to 19.2.6 might face this same issue. I hope that sharing this workaround can help anyone encountering similar problems.

While I plan to attempt creating a reproducible example, I cannot guarantee success given the complexity of our current setup.

**Comment by JoostK** [comment]
I suspect this happens because `@angular/platform-browser` is present _twice_. In that case, there are multiple copies of `DomRendererFactory2` which have distinct tokens, so if the "primary" token is registered and a "secondary" copy is requested, it won't resolve to the "primary" token. Manually importing `importProvidersFrom(BrowserModule)` emphasises my suspicion; doing that will also register the "secondary"  copy. That may work to some extent but should not be considered a fix, and may result in unexpected behaviour.

**Comment by JoostK** [comment]
Yes please don't consider that a solution, it isn't correct. Updates can easily result in duplicate copies if there's (peer) dependency issues or in monorepos/workspaces there may be diverging versions of the same package specified, also resulting in duplicates.

**Comment by cdskill** [comment]
I hope someone will take it in charge asap 👀 I know there is not a reproduction but I estimates there is enough info to investigates, range version, the nature of error I encounter, ...

**Comment by JeanMeche** [comment]
Since we didn't observe this issue in Google's code base, we strongly believe that there is something happening specifically in your project. 

Without a repro this is hardly actionable on our side.

**Comment by cdskill** [comment]
I don't think I'm isolate case here we have someone else https://github.com/angular/components/issues/30609 with Injector error since angular 19 but seems to be closed and resolved. 

The monorepo was working perfectly fine since 18.2.0 then 19.0.5 then to 19.1.5 and finally crash on 19.2.[6-7].

**Comment by JeanMeche** [comment]
The component issue is totally unrelated as it was a regression inside the CDK. 

Dependency duplication are not rare when doing minor updates. This is why we're hinting at it.

**Comment by cdskill** [comment]
@JoostK thx for at least trying to give me some leads.
So when there is the output of `npm ls` command:
npm ls @angular/platform-browser

```
@df-nx-monorepo/source@0.0.0 /Users/x.x/work/df-nx-monorepo
├─┬ @angular/forms@19.2.6
│ └── @angular/platform-browser@19.2.6 deduped
├─┬ @angular/platform-browser-dynamic@19.2.6
│ └── @angular/platform-browser@19.2.6 deduped
├── @angular/platform-browser@19.2.6
├─┬ @angular/router@19.2.6
│ └── @angular/platform-browser@19.2.6 deduped
├─┬ @storybook/angular@8.5.3
│ └── @angular/platform-browser@19.2.6 deduped
└─┬ primeng@19.0.10
  └── @angular/platform-browser@19.2.6 deduped
```

and when I analyze bundle of the shell app and the remote there is the result (i've removed the non recommend fix of importProvidersFrom):

Shell app:

<img width="2045" alt="Image" src="https://github.com/user-attachments/assets/3f034c7f-7684-44cb-9ec8-5b0dbd50770d" />

Remote app:

![Image](https://github.com/user-attachments/assets/7df59575-210f-4056-a6f5-244e53f176ec)

**Comment by JoostK** [comment]
Is `@angular/platform-browser` a shared MF module? I don't think it is judging by the presence of the two red blocks. Note that Angular (CLI) doesn't support MF applications so we cannot really offer any guidance on this matter.

**Comment by cdskill** [comment]
Unfortunately we had to downgrade to 19.1.4... because the workaround brought others issue... @JoostK even running the shell in standalone this issue. And as I said previously very vicious error since it occurs only in configuration=production but locally served everything is fine

**Comment by wartab** [comment]
> I hope someone will take it in charge asap 👀 I know there is not a reproduction but I estimates there is enough info to investigates, range version, the nature of error I encounter, ...

There have been ~10 releases between the version 19.1.5 and 19.2.6 you mentioned. It's not actually reasonable to inspect every modification between these versions when you can't provide a reproduction. Perhaps you could try to narrow down which versions breaks it exactly. Sometimes you get lucky and it's a patch version that breaks things and not a feature release like 19.2.0.

**Comment by alxhub** [comment]
I'm going to close this, as it's almost certainly caused by a duplicated instance of `platform-browser` on the page. If you find this is not the case, feel free to open a new issue with a minimal reproduction.

**Comment by cpoulsen** [comment]
I have the same issue also running microfrontends.
The `platform-browser` is federated.
I can pinpoint the issue to arise from `19.2.4` -> `19.2.5`, however there is nothing in the [release notes](https://github.com/angular/angular/releases/tag/19.2.5) regarding this package

```
NullInjectorError: R3InjectorError[RendererFactory2 -> RendererFactory2 -> DomRendererFactory2 -> DomRendererFactory2]: 
  NullInjectorError: No provider for DomRendererFactory2!


RuntimeError: NG0200: Circular dependency in DI detected for RendererFactory2. Find more at https://angular.dev/errors/NG0200
```

**Comment by cdskill** [comment]
I suppose an other case, https://stackoverflow.com/questions/79577933/angular-19-module-federation-esm-standalone-component-%e2%86%92-ng0200-circular-di. We need ur support
