### ISSUE TITLE
Property binding error after updating to Angular 13

### ISSUE THREAD

**Issue by ibrahimxcool** [angular/angular#44453]
### Which @angular/* package(s) are the source of the bug?

compiler, language-service

### Is this a regression?

Yes

### Description

I'm getting this error

> Property binding ngIf not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations"

Even thou it works fine when I run ` ng serve`.
![image](https://user-images.githubusercontent.com/69388870/145705234-620c9714-fc3e-42c8-af5d-dc3bfec91e15.png)
![image](https://user-images.githubusercontent.com/69388870/145705237-5f10bdf1-2a1b-419d-af26-6fe0dec6fbcf.png)

I started to get this compilation error when I updated angular to v13

I already tried restarting Vscode and reinstalling Angular Language Service and installing a previous version of Angular Language Service... None of them works..

My app.module.ts
```
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';

@NgModule({
  declarations: [AppComponent],
  imports: [CommonModule, BrowserModule, AppRoutingModule],
  providers: [],
  bootstrap: [AppComponent],
  exports: [CommonModule, BrowserModule],
})
export class AppModule {}
```

**Comment by JoostK** [comment]
What version of the language service are you using?

The mentioned error is not present in the current version of the language service. It was reported by the ViewEngine variant of the language service (and compiler), but since Angular 13 only the Ivy-based language service is available. Since Angular packages themselves are now also in Ivy format, any language service configuration that is still using ViewEngine is no longer able to understand Angular's packages.

**Comment by ibrahimxcool** [comment]
@JoostK Angular Language Service v13.1.0. It's the latest version available on VS Code

**Comment by JoostK** [comment]
Do you have the `Use legacy View Engine language service.` option enabled in the plugin's configuration? The VSCode client has some logic to determine whether the project can use the Ivy language service, such that incompatible projects will fallback to using ViewEngine. With the `Use legacy View Engine language service.` option enabled, however, this fallback behavior is forcibly enabled. That results in an incompatibility with Angular 13, as ViewEngine cannot work with Angular 13 packages.

**Comment by nardo7** [comment]
I had experienced this issue as well after updating to angular 13 and deactivating `Use legacy View Engine language service` solved it

**Comment by JoostK** [comment]
Fixed in angular/vscode-ng-language-service#1575
