### ISSUE TITLE
CanDeactivate being called with null component and providers not being provided to new component

### ISSUE THREAD

**Issue by slubowsky** [angular/angular#15626]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
After upgrading working app from 4.0.0 to 4.0.1 or 4.1.0-beta.0, when navigating to a new component (lazy loaded but dont know if that matters yet) CanDeactivate guard is called with null component and providers are not being provided to new component (sometimes I get only one of these errors, sometimes I get both as shown below, and occasionally I get other errors not captured here)

```
ERROR Error: Uncaught (in promise): Error: No provider for MyService!
Error
    at injectionError (core.es5.js:1231) [angular]
    at noProviderError (core.es5.js:1269) [angular]
    at ReflectiveInjector_._throwOrNull (core.es5.js:2770) [angular]
    at ReflectiveInjector_._getByKeyDefault (core.es5.js:2809) [angular]
    at ReflectiveInjector_._getByKey (core.es5.js:2741) [angular]
    at ReflectiveInjector_.get (core.es5.js:2610) [angular]
    at AppModuleInjector.NgModuleInjector.get (core.es5.js:3557) [angular]
    at MySearchModuleInjector.NgModuleInjector.get (core.es5.js:3557) [angular]
    at resolveDep (core.es5.js:10930) [angular]
    at createClass (core.es5.js:10799) [angular]
    at createDirectiveInstance (core.es5.js:10627) [angular]
    at createViewNodes (core.es5.js:11977) [angular]
    at createRootView (core.es5.js:11882) [angular]
    at callWithDebugContext (core.es5.js:13013) [angular]
    at injectionError (core.es5.js:1231) [angular]
    at noProviderError (core.es5.js:1269) [angular]
    at ReflectiveInjector_._throwOrNull (core.es5.js:2770) [angular]
    at ReflectiveInjector_._getByKeyDefault (core.es5.js:2809) [angular]
    at ReflectiveInjector_._getByKey (core.es5.js:2741) [angular]
    at ReflectiveInjector_.get (core.es5.js:2610) [angular]
    at AppModuleInjector.NgModuleInjector.get (core.es5.js:3557) [angular]
    at MySearchModuleInjector.NgModuleInjector.get (core.es5.js:3557) [angular]
    at resolveDep (core.es5.js:10930) [angular]
    at createClass (core.es5.js:10799) [angular]
    at createDirectiveInstance (core.es5.js:10627) [angular]
    at createViewNodes (core.es5.js:11977) [angular]
    at createRootView (core.es5.js:11882) [angular]
    at callWithDebugContext (core.es5.js:13013) [angular]
    at resolvePromise (zone.js:712) [angular]
    at resolvePromise (zone.js:683) [angular]
    at :4200/polyfills.bundle.js:2764:17 [angular]
    at Object.onInvokeTask (core.es5.js:4116) [angular]
    at ZoneDelegate.webpackJsonp.626.ZoneDelegate.invokeTask (zone.js:397) [angular]
    at Zone.webpackJsonp.626.Zone.runTask (zone.js:165) [<root> => angular]
    at drainMicroTaskQueue (zone.js:593) [<root>]
    at HTMLAnchorElement.ZoneTask.invoke (zone.js:464) [<root>]
defaultErrorLogger @ core.es5.js:1084
ErrorHandler.handleError @ core.es5.js:1144
next @ core.es5.js:4754
schedulerFn @ core.es5.js:3828
SafeSubscriber.__tryOrUnsub @ Subscriber.js:234
SafeSubscriber.next @ Subscriber.js:183
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ core.es5.js:3814
NgZone.triggerError @ core.es5.js:4185
onHandleError @ core.es5.js:4146
webpackJsonp.626.ZoneDelegate.handleError @ zone.js:369
webpackJsonp.626.Zone.runGuarded @ zone.js:141
_loop_1 @ zone.js:604
drainMicroTaskQueue @ zone.js:613
ZoneTask.invoke @ zone.js:464
core.es5.js:1084 

ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'canDeactivate' of null
TypeError: Cannot read property 'canDeactivate' of null
    at CanDeactivateGuard.webpackJsonp.224.CanDeactivateGuard.canDeactivate (CanDeactivate.ts:9)
    at MergeMapSubscriber.project (router.es5.js:4394)
    at MergeMapSubscriber._tryNext (mergeMap.js:120)
    at MergeMapSubscriber._next (mergeMap.js:110)
    at MergeMapSubscriber.Subscriber.next (Subscriber.js:89)
    at ArrayObservable._subscribe (ArrayObservable.js:114)
    at ArrayObservable.Observable._trySubscribe (Observable.js:57)
    at ArrayObservable.Observable.subscribe (Observable.js:45)
    at MergeMapOperator.call (mergeMap.js:85)
    at Observable.subscribe (Observable.js:42)
    at EveryOperator.call (every.js:33)
    at Observable.subscribe (Observable.js:42)
    at Object.subscribeToResult (subscribeToResult.js:22)
    at MergeMapSubscriber._innerSub (mergeMap.js:130)
    at MergeMapSubscriber._tryNext (mergeMap.js:127)
    at CanDeactivateGuard.webpackJsonp.224.CanDeactivateGuard.canDeactivate (CanDeactivate.ts:9)
    at MergeMapSubscriber.project (router.es5.js:4394)
    at MergeMapSubscriber._tryNext (mergeMap.js:120)
    at MergeMapSubscriber._next (mergeMap.js:110)
    at MergeMapSubscriber.Subscriber.next (Subscriber.js:89)
    at ArrayObservable._subscribe (ArrayObservable.js:114)
    at ArrayObservable.Observable._trySubscribe (Observable.js:57)
    at ArrayObservable.Observable.subscribe (Observable.js:45)
    at MergeMapOperator.call (mergeMap.js:85)
    at Observable.subscribe (Observable.js:42)
    at EveryOperator.call (every.js:33)
    at Observable.subscribe (Observable.js:42)
    at Object.subscribeToResult (subscribeToResult.js:22)
    at MergeMapSubscriber._innerSub (mergeMap.js:130)
    at MergeMapSubscriber._tryNext (mergeMap.js:127)
    at resolvePromise (zone.js:712) [angular]
    at resolvePromise (zone.js:683) [angular]
    at :4200/polyfills.bundle.js:2764:17 [angular]
    at Object.onInvokeTask (core.es5.js:4116) [angular]
    at ZoneDelegate.webpackJsonp.626.ZoneDelegate.invokeTask (zone.js:397) [angular]
    at Zone.webpackJsonp.626.Zone.runTask (zone.js:165) [<root> => angular]
    at drainMicroTaskQueue (zone.js:593) [<root>]
    at HTMLAnchorElement.ZoneTask.invoke (zone.js:464) [<root>]
```

**Expected behavior**
CanDeactivate guard should not be called with null component and providers should be provided

**Minimal reproduction of the problem with instructions**

Will try to create plnkr when have time.

**What is the motivation / use case for changing the behavior?**

Breaking change. Causes crash in existing code that works as expected in 4.0.0

**Please tell us about your environment:**

@angular/cli: 1.0.0
node: 7.7.1
os: win32 x64
@angular/common: 4.1.0-beta.0
@angular/compiler: 4.1.0-beta.0
@angular/core: 4.1.0-beta.0
@angular/forms: 4.1.0-beta.0
@angular/http: 4.1.0-beta.0
@angular/platform-browser: 4.1.0-beta.0
@angular/platform-browser-dynamic: 4.1.0-beta.0
@angular/router: 4.1.0-beta.0
@angular/cli: 1.0.0
@angular/compiler-cli: 4.1.0-beta.0

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Only tried in Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
> Will try to create plnkr when have time.

nothing we can do without a plunkr :)

**Comment by slubowsky** [comment]
@DzmitryShylovich My app isn't doing anything special so I wanted to get this out there as I expect others will run into this when they upgrade as well. I'm guessing you will see more details soon. Meanwhile you could think about if something like https://github.com/angular/angular/commit/f368381d1282f56631569b0d67dd623544db8128 could be causing a problem like this

**Comment by DzmitryShylovich** [comment]
> I expect others will run into this when they upgrade as well

yeah, there's another issue https://github.com/angular/angular/issues/15627 but it's hard to tell anything without small working repro

**Comment by vicb** [comment]
Where do you provide `MyService`.
If you can add a minimal reproduction, that would help a lot.
Thanks

**Comment by slubowsky** [comment]
@vicb The service is provided by a parent module - parent of both the first component and the one being navigated to. The first component has no issues using services being provided by it from same parent. Its only on navigation to the sibling that the issue occurs. (All components are being lazy loaded including parent)

**Comment by DzmitryShylovich** [comment]
@slubowsky do you use `CanLoad` guard?

**Comment by slubowsky** [comment]
@DzmitryShylovich No, I do not use CanLoad guard (but I do use canActivate)

**Comment by DzmitryShylovich** [comment]
@slubowsky I tried the most trivial setup and it works https://plnkr.co/edit/VA1TTu44HioViK5YQfUC?p=preview

**Comment by vicb** [comment]
I think that the pb occurs when the hook is provided by the lazy loaded module (seems like we always use the module injector of the `Router` instead of the module injector from the route)

**Comment by slubowsky** [comment]
@DzmitryShylovich Forked yours and made something closer to what Im doing and can not yet duplicate. Everything works :( Ill continue trying to break it when I get a chance.
https://plnkr.co/edit/nfR6dcZKTtm0Yc7StFdm?p=preview

**Comment by slubowsky** [comment]
@DzmitryShylovich @vicb I have a partial reproduction in a simple repo - https://github.com/slubowsky/router-bug 
I was able to reproduce the provider not being provided portion of the problem, but not yet the null component being passed to the deactivate guard.

Turns out that if you navigate in from the top of the app you wont see the issue. Everything seems to work as you navigate through the components. The problem only occurs when you have already navigated down to a lower level component and refresh the page (as I constantly do during development).

For example, if you run the code from the repo (ng serve) and navigate to localhost:4200/ you can then click back and forth on all the links and everything works. Navigate to grandchild detail link (http://localhost:4200/app/lazy/grandchild-detail) and then refresh the browser. Now click the grandchild search link - crash! - `core.es5.js:1084 ERROR Error: Uncaught (in promise): Error: No provider for GrandchildSearchService!`

Switch angular back to 4.0.0 problem goes away.

(Not sure there's really anything substantially different in this repo as compared to the plnkr I created above - https://plnkr.co/edit/nfR6dcZKTtm0Yc7StFdm?p=preview. I think its more likely that's its just near impossible to perform the required UI manipulations to cause the bug to occur in a plnkr)

**Comment by DzmitryShylovich** [comment]
@slubowsky I was able to reproduce, thanks. yeah, the bug was introduced by https://github.com/angular/angular/pull/15467

**Comment by DzmitryShylovich** [comment]
The funny thing is that is doesn't work even without guards so it's something else

**Comment by DzmitryShylovich** [comment]
@slubowsky ok I found the bug. Here https://github.com/angular/angular/commit/23bf34853c83b2131991e11da1c8dcc75ee3d731#diff-86faca9d9f6af67bf4abf6c3f6ab380bR108 `ngModule` instead of `childConfig.module`.
Can you please open `node_modules/@angular/router/@angular/router.es5.js` file and paste this instead of `RouterPreloader.prototype.processRoutes` implementation:
```
RouterPreloader.prototype.processRoutes = function (ngModule, routes) {
      var /** @type {?} */ res = [];
      for (var _i = 0, routes_5 = routes; _i < routes_5.length; _i++) {
        var c = routes_5[_i];
        // we already have the config loaded, just recurse
        if (c.loadChildren && !c.canLoad && ((c))._loadedConfig) {
          var /** @type {?} */ childConfig = ((c))._loadedConfig;
          res.push(this.processRoutes(childConfig.module, childConfig.routes));
        }
        else if (c.loadChildren && !c.canLoad) {
          res.push(this.preloadConfig(ngModule, c));
        }
        else if (c.children) {
          res.push(this.processRoutes(ngModule, c.children));
        }
      }
      return mergeAll.call(from(res));
    };
```
does it fix all your issues?

**Comment by slubowsky** [comment]
@DzmitryShylovich I'll take a better look a later today but after some quick testing it does appear to have fixed all the problems.
