### ISSUE TITLE
An unhandled exception occurred: Cannot find module '@angular-devkit/build-webpack' 12.1.1

### ISSUE THREAD

**Issue by kolkov** [angular/angular#42726]
Build error after update to 12.1.1

![image](https://user-images.githubusercontent.com/3740898/124036837-4f993900-da07-11eb-8428-7f4c3d20b48b.png)

![image](https://user-images.githubusercontent.com/3740898/124036570-df8ab300-da06-11eb-96da-3f25b989938d.png)

```
An unhandled exception occurred: Cannot find module '@angular-devkit/build-webpack'
Require stack:
- D:\Go\freicon\web\node_modules\@angular-devkit\build-angular\src\dev-server\index.js
- D:\Go\freicon\web\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- D:\Go\freicon\web\node_modules\@angular-devkit\architect\node\index.js
- D:\Go\freicon\web\node_modules\@angular\cli\models\architect-command.js
- D:\Go\freicon\web\node_modules\@angular\cli\commands\serve-impl.js
- D:\Go\freicon\web\node_modules\@angular-devkit\schematics\tools\export-ref.js
- D:\Go\freicon\web\node_modules\@angular-devkit\schematics\tools\index.js
- D:\Go\freicon\web\node_modules\@angular\cli\utilities\json-schema.js
- D:\Go\freicon\web\node_modules\@angular\cli\models\command-runner.js
- D:\Go\freicon\web\node_modules\@angular\cli\lib\cli\index.js
- D:\Go\freicon\web\node_modules\@angular\cli\lib\init.js
- D:\Go\freicon\web\node_modules\@angular\cli\bin\ng
See "C:\Users\Andy\AppData\Local\Temp\ng-tCGKQ6\angular-errors.log" for further details.

Process finished with exit code 127
```
```

Angular CLI: 12.1.0
Node: 16.4.0 (Unsupported)
Package Manager: npm 7.19.0
OS: win32 x64

Angular: 12.1.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.0
@angular-devkit/build-angular   12.1.0
@angular-devkit/core            12.1.0
@angular-devkit/schematics      12.1.0
@angular/cdk                    12.1.0
@angular/cli                    12.1.0
@angular/pwa                    0.803.29
@schematics/angular             12.1.0
rxjs                            6.6.7
typescript                      4.2.4

Warning: The current version of Node (16.4.0) is not supported by Angular.
PS D:\Go\freicon\web>
```
