### PR TITLE
docs(aio): Update lazy loading docs for Angular v6

### PR DESCRIPTION
**Pull request by samalexander**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] angular.io application / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Following the current lazy loading docs results in a compilation error, because loadChildren takes a relative path under Angular V6.

Issue Number: N/A

## What is the new behavior?
Compilation succeeds.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by samalexander** [comment]
I signed it!

**Comment by brandonroberts** [comment]
Using absolute paths that start with the `app/` are supported by the CLI in V6 and work correctly in the examples. I don't think we need to change this in the docs.

**Comment by samalexander** [comment]
@brandonroberts absolute paths starting with `app/` don't seem to work with CLI v6.0.0 - see repro steps [here](https://github.com/angular/angular-cli/issues/10630), perhaps this is a bug with the CLI?
