### ISSUE TITLE
Angular 12 to 14 upgrade error; __webpack_require__.h is not a function 

### ISSUE THREAD

**Issue by devna13** [angular/angular#48254]
### Which @angular/* package(s) are the source of the bug?

upgrade

### Is this a regression?

No

### Description

after upgrading angular 12 to 14 I'm getting this error at runtime in browser. UI loads correctly, nothing is broken, it's just this error pops up in browser console before page loads.

Uncaught TypeError: __webpack_require__.h is not a function at 1211 (index.js:43:58) at __webpack_require__ (bootstrap:19:1) at __webpack_exec__ (auth-theming.scss?8317:1:1) at auth-theming.scss?8317:1:1 at webpackJsonpCallback (jsonp chunk loading:34:1) at styles.js:1:81

I'm using angular material and have custom theme but even removing the theme scss doesn't resolve the error.

I still get this error, replacing angular.json build > options > styles
"styles": ["src/theme/auth-theme.scss", "src/styles.scss"], with "styles": [],

![image](https://user-images.githubusercontent.com/4080343/204322177-9cfa78da-9182-45fa-8ee2-760983edfba7.png)

### Please provide the environment you discovered this bug in (run `ng version`)

```true
ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 14.2.10
Node: 14.20.0
Package Manager: npm 6.14.17
OS: win32 x64

Angular: 14.2.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, router

Package                             Version
-------------------------------------------------------------
@angular-devkit/architect           0.1402.10
@angular-devkit/build-angular       14.2.10
@angular-devkit/core                14.2.10
@angular-devkit/schematics          14.2.10
@angular/cdk                        14.2.7
@angular/cli                        14.2.10
@angular/material                   14.2.7
@angular/platform-browser-dynamic   14.2.11
@schematics/angular                 14.2.10
rxjs                                6.6.7
typescript                          4.6.4
```
