### ISSUE TITLE
.map doesnt work after upgrade to RC 1

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular#8495]
Hi,

The map doesn't seem to be working after upgrade to Rc 1. In below code I am receiving error 
Property 'map' does not exist on type 'Observable<Response>'

this.http.post('/someurl/', body)
            .map(res => res.json())
            .catch(this.handleError);

**Comment by ericmdantas** [comment]
What was the latest working version?

**Comment by naveedahmed1** [comment]
It was working with 2.0.0-beta.17

**Comment by thelgevold** [comment]
Map seems to be working for me in rc-1. Maybe there is some configuration issue in your project?

Here is a demo of it working:
http://www.syntaxsuccess.com/angular-2-samples/#/demo/http

```
this.http.post('url/', JSON.stringify({firstName:'Joe',lastName:'Smith'}),{headers:headers})
            .map((res: Response) => res.json())
            .subscribe((res:Person) => this.postResponse = res);
```

**Comment by bromzh** [comment]
Did you include .map operator from rxjs in your bundle?

**Comment by floriank** [comment]
Faced the same problem today with **rc.0**:

Solution is to either include all of `Rx`:

```typescript
import 'rxjs/Rx'
```

or to selectively include `map` itself (as suggested by @bromzh):

```typescript
import 'rxjs/add/operator/map'
```

The [documentation](https://angular.io/docs/ts/latest/guide/server-communication.html#!#rxjs) (`Http` Client) is a bit lacking here - it only says to include it completely. It could be clarified.

**Comment by naveedahmed1** [comment]
I have the below imports:

import {Injectable, Inject, EventEmitter} from '@angular/core';
import {Http, Response, Headers} from '@angular/http';
import {Observable} from 'rxjs/Rx';
import 'rxjs/add/operator/map';

But I am still receiving the below error:

Property 'map' does not exist on type 'Observable<Response>'.


this.http.post('/myurl/', body)
            .map(res => res.json()) <-----This line shows above error.
            .catch(this.handleError);

**Comment by ericmartinezr** [comment]
Change
```
import {Observable} from 'rxjs/Rx';
import 'rxjs/add/operator/map';
```

to
```
import {Observable} from 'rxjs/Observable';
import 'rxjs/add/operator/map';
```

**Comment by naveedahmed1** [comment]
Still no success. I would like to add that when I installed npm packages using below command:

npm install --save @angular/core @angular/compiler @angular/common @angular/platform-browser @angular/platform-browser-dynamic rxjs@5.0.0-beta.6 zone.js@0.6.12

It showed below warnings on command prompt:

npm WARN MyProject No description
npm WARN MyProject No repository field.
npm WARN MyProject No license field.

**Comment by naveedahmed1** [comment]
Got it fixed! sharing the details if anyone still struggling to get Angular2 RC1 work with ASP.Net MVC

Visual Studio 2015 is shipped with a very old version of npm. Therefore the very first thing your need to do is download and install the latest version of Node from https://nodejs.org/en/ (I installed v6.1.0, current latest). After this you need to tell Visual Studio to use latest version instead of the embedded old version. For this follow the below steps:

In Visual Studio from top menu go to Tools > Options

Expand Project and Solution node shown in dialog Select External Web Tools

Add a new entry pointing to C:\Program Files\nodejs\ 
(or point to to location where you installed nodejs)

Move it to the top of the list.

Restart Visual Studio and restore npm packages.

Now if you try to compile the project, you might see alot of errors mainly due to the missing type definitions.

Therefore, you will have to add

/// <reference path="../node_modules/angular2-in-memory-web-api/typings/browser.d.ts" />

on top of your main.ts or bootstrap.ts that will remove typings error.

Please note if you are upgrading your project from any of Angular 2 beta versions you will have to follow the instructions mentioned at https://github.com/angular/angular/blob/master/CHANGELOG.md#200-rc0-2016-05-02 to update your code.

**Comment by ngydat** [comment]
I still have the issue :(

**Comment by deeleman** [comment]
What TypeScript compiler version are you using @ngydat?

**Comment by ngydat** [comment]
@deeleman 1.8.10

**Comment by deeleman** [comment]
@ngydat Yep, I should have pointed out that myself at first, since I encountered that same issue a few days ago when upgrading my code to RC.1 and updating the compiler version just did the trick. Glad to know that everything works fine now on your end. :)

**Comment by naveedahmed1** [comment]
@ngydat  if you are still having issues, please check my detailed answer here:

http://stackoverflow.com/a/37079769/2755616

**Comment by JBildstein** [comment]
I had the same issue and after hours of trying things I think it was because I installed rxjs@5.0.0-beta.8 while the angular http packaged needed beta.6
After removing beta.8 and reinstalling all packages it works now.

**Comment by wesleycho** [comment]
This issue can probably be closed, it seems like everyone has found a resolution on their side.
