### ISSUE TITLE
karma tests issue after update to 11.1.0

### ISSUE THREAD

**Issue by LPCmedia** [angular/angular#40507]
# 🐞 bug report

### Affected Package
After updating a lot of tests fail with :

    x should not create custom style if already created
      Chrome Headless 83.0.4103.0 (Mac OS 10.16.0)
    **TypeError: fn.bind is not a function
        at newTrustedFunctionForJIT (http://localhost:9876/_karma_webpack_/vendor.js:15486:15)**
        at JitEvaluator.evaluateCode (http://localhost:9876/_karma_webpack_/vendor.js:15550:29)
        at JitEvaluator.evaluateStatements (http://localhost:9876/_karma_webpack_/vendor.js:15524:21)
        at JitCompiler._interpretOrJit (http://localhost:9876/_karma_webpack_/vendor.js:37651:39)
        at JitCompiler._compileModule (http://localhost:9876/_karma_webpack_/vendor.js:37519:36)
        at http://localhost:9876/_karma_webpack_/vendor.js:37487:39
        at Object.then (http://localhost:9876/_karma_webpack_/vendor.js:11143:52)
        at JitCompiler._compileModuleAndAllComponents (http://localhost:9876/_karma_webpack_/vendor.js:37483:26)
        at JitCompiler.compileModuleAndAllComponentsSync (http://localhost:9876/_karma_webpack_/vendor.js:37440:42)
        at CompilerImpl.compileModuleAndAllComponentsSync (http://localhost:9876/_karma_webpack_/vendor.js:206555:39)

### Is this a regression?
yes

### Description

after updating about 400/2000 tests are failing with the issue above. The issue exists using chrome rather than chrome headless. 

## 🔬 Minimal Reproduction

not at this time

## 🔥 Exception or Error
<pre><code>
    **TypeError: fn.bind is not a function
        at newTrustedFunctionForJIT (http://localhost:9876/_karma_webpack_/vendor.js:15486:15)**
        at JitEvaluator.evaluateCode (http://localhost:9876/_karma_webpack_/vendor.js:15550:29)
        at JitEvaluator.evaluateStatements (http://localhost:9876/_karma_webpack_/vendor.js:15524:21)
        at JitCompiler._interpretOrJit (http://localhost:9876/_karma_webpack_/vendor.js:37651:39)
        at JitCompiler._compileModule (http://localhost:9876/_karma_webpack_/vendor.js:37519:36)
        at http://localhost:9876/_karma_webpack_/vendor.js:37487:39
        at Object.then (http://localhost:9876/_karma_webpack_/vendor.js:11143:52)
        at JitCompiler._compileModuleAndAllComponents (http://localhost:9876/_karma_webpack_/vendor.js:37483:26)
        at JitCompiler.compileModuleAndAllComponentsSync (http://localhost:9876/_karma_webpack_/vendor.js:37440:42)
        at CompilerImpl.compileModuleAndAllComponentsSync (http://localhost:9876/_karma_webpack_/vendor.js:206555:39)
</code></pre>

## 🌍  Your Environment

**Angular Version:**

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.7
@angular-devkit/build-angular   0.1101.0
@angular-devkit/core            11.1.0
@angular-devkit/schematics      11.0.7
@schematics/angular             11.1.0
@schematics/update              0.1101.0
ng-packagr                      11.0.3
rxjs                            6.6.3
typescript                      4.1.3
webpack                         4.44.2

    "karma": "6.0.1",
    "karma-chrome-launcher": "3.1.0",
    "karma-coverage": "2.0.3",
    "karma-jasmine": "4.0.1",

**Anything else relevant?**
we use chrome headless vs. chrome but both have the issue. we also have the issue with karma "5.2.3"

**Comment by JoostK** [comment]
What version of Chrome are you running your tests on? There is a known bug in Chrome 83 in its Trusted Type support, per https://github.com/angular/components/pull/21238#issuecomment-742899789.

I wonder if something can be done in the FW to avoid the hard crash, e.g. fall back on no trusted type support? @bjarkler

**Comment by petebacondarwin** [comment]
We are already sniffing for trusted types here: https://github.com/angular/angular/blame/f54662e93164ffb14cb0ba98dea5887b40fde8da/packages/compiler/src/output/output_jit_trusted_types.ts#L105

So perhaps we could do a more fine-grained sniffing or add a catch block...

**Comment by LPCmedia** [comment]
@JoostK Chrome Headless 83.0.4103.0 (Mac OS 10.16.0) I can try another version any particular one ?

**Comment by JoostK** [comment]
So Chrome 83 is known to be buggy, according to https://github.com/angular/components/pull/21238#issuecomment-742899789 I would've thought that a newer version should resolve the crash. But according to your statement that it also crashes in your local Chrome 87 I wonder what may be going on there...

**Comment by LPCmedia** [comment]
let me double check the chrome 87 part again, that could be my mistake.
we have something setting process.env.CHROME_BIN somewhere.

**Comment by LPCmedia** [comment]
@JoostK ok so we are good to go in chrome 87. This was related to chrome 83. Is there somewhere in the docs we can add this as a compatibility. I would be glad to add it ? Otherwise I leave it with you if its worth fixing or supporting 83 👍

**Comment by reifi** [comment]
Thanks for the chromium info!
Possible quickfix, in case anybody else stumbles across this who is also not as deeply involved as the guys here:
I used for example an old puppeteer (3.1.0) and updated it now (5.1.0) which brought a new chromium (88) where fn.bind issue is gone too..

**Comment by QuentinFarizon** [comment]
I have the same error after switching to Angular 11, on Chrome **87**

**Comment by petebacondarwin** [comment]
@QuentinFarizon  - did you check your version of puppeteer too?

**Comment by IgorMinar** [comment]
As Joost already mentioned, this exception is thrown due to a known issue with Chrome 83. We've intentionally didn't try to work around the issue because Chrome 83 is over a year old and according to [statcounter](https://gs.statcounter.com/browser-version-market-share#monthly-202011-202012-bar) this version of Chrome had only 0.19% usage worldwide in December. 

We strongly encourage you to update to a newer version of Chrome (or newer version of puppeteer, which brings in newer version of Chrome). This resolves the problem, and upgrades your testing infrastructure to test against a browser is actually used by users using your app.

We verified that the issue is no longer present in the [browsers supported by Angular](https://angular.io/guide/browser-support), e.g. Chrome 87.

If you see the problem, please check the version of the browser you are using and keep in mind that puppeteer and certain other testing tools bring in their own version of Chrome, so the version you are using for browsing might be different from that used by your testing tools.

If for whatever reason, this issue does occur on a supported browser please let us know and we'll address it quickly.

We'll keep on monitoring this issue in case the impact of it is more widespread than what we understand it to be.

**Comment by QuentinFarizon** [comment]
I have been precise enough, sorry. I'm seeing this error while using Angular in an Ionic project. My local Chrome version is 87, but the app uses the webview version installed. Is it possible the Chrome webview is of version 83 ? How can I check ?

**Comment by alexzaporozhets** [comment]
@IgorMinar the latest stable version of QT uses Chrome 83.0.4103.122 for QtWebengineProcess (https://code.qt.io/cgit/qt/qtwebengine.git/tree/dist/changes-5.15.2) and usually such applications are not counted on the statcounter website.

Unless you reconsider your decision to don't fix the problem for Chrome 83, many people using QtWebEngine for their applications will not be able to use angular.

**Comment by appimpact** [comment]
According to the official release notes, latest version of Samsung Internet browser is based on Chromium 83:

https://developer.samsung.com/internet/release-note.html

Considering mentioned, we hope that you will reconsider the importance of creating fix for this as that is quite a large number of users that are affected by this bug.

**Comment by AndrewKushnir** [comment]
Thanks everyone for the feedback and additional info!

This issue would be resolved by the changes in PR #40815, which should be available in one of the next patch versions of Angular.

**Comment by AndrewKushnir** [comment]
Closing this ticket since corresponding PR #40815 was merged and the fix would be available in v11.2.1 in a few days. Please let us know if the problem still exists after upgrading to Angular v11.2.1. Thank you.
