### ISSUE TITLE
Trouble updating from angular 2 to angular 4

### ISSUE THREAD

**Issue by lilitiger** [angular/angular#25795]
Hello everyone, I'm facing errors during my update. I'm trying to update my project from Angular 2.0.1 to 4.0.0.

I updated too typescript as follow :

```
Angular CLI: 6.1.5 Node: 8.11.4 OS: win32 x64 Angular: 4.0.0 ... animations, common, compiler, compiler-cli, core, forms ... http, platform-browser, platform-browser-dynamic ... platform-server, router, tsc-wrapped, upgrade

Package Version
@angular-devkit/architect 0.7.5 (cli-only) @angular-devkit/core 0.7.5 (cli-only) @angular-devkit/schematics 0.7.5 (cli-only) @schematics/angular 0.7.5 (cli-only) @schematics/update 0.7.5 (cli-only) rxjs 5.0.1 typescript 2.3.0

```
When I launch "tsc" command, I still have the following errors:

```
bower_components/alasql/partners/typescript/test.ts(2,18): error TS2300: Duplicate identifier 'require'.
bower_components/marked-element/marked-element.d.ts(11,1): error TS6053: File 'C:/Users/hc/Projects/proj/proj-backend/frontends/cockpit/bower_components/polymer/types/polymer.d.ts' not found.
bower_components/marked-element/marked-element.d.ts(88,48): error TS2694: Namespace 'Polymer' has no exported member 'Element'.
bower_components/paper-spinner/paper-spinner-behavior.d.ts(11,1): error TS6053: File 'C:/Users/hc/Projects/proj/proj-backend/frontends/cockpit/bower_components/polymer/types/polymer.d.ts' not found.
bower_components/paper-spinner/paper-spinner-lite.d.ts(11,1): error TS6053: File 'C:/Users/hc/Projects/proj/proj-backend/frontends/cockpit/bower_components/polymer/types/polymer.d.ts' not found.
bower_components/paper-spinner/paper-spinner-lite.d.ts(12,1): error TS6053: File 'C:/Users/hc/Projects/proj/proj-backend/frontends/cockpit/bower_components/paper-styles/color.d.ts' not found.
bower_components/paper-spinner/paper-spinner-lite.d.ts(43,51): error TS2694: Namespace 'Polymer' has no exported member 'Element'.
bower_components/paper-spinner/paper-spinner.d.ts(11,1): error TS6053: File 'C:/Users/hc/Projects/proj/proj-backend/frontends/cockpit/bower_components/polymer/types/polymer.d.ts' not found.
bower_components/paper-spinner/paper-spinner.d.ts(12,1): error TS6053: File 'C:/Users/hc/Projects/proj/proj-backend/frontends/cockpit/bower_components/paper-styles/color.d.ts' not found.
bower_components/paper-spinner/paper-spinner.d.ts(48,47): error TS2694: Namespace 'Polymer' has no exported member 'Element'.
node_modules/@types/node/index.d.ts(242,13): error TS2300: Duplicate identifier 'require'.
src/SafeManagementResponsibilityChecker.ts(22,14): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
src/UserSuggester.ts(16,14): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
src/app.module.ts(3,22): error TS2305: Module '"C:/Users/hc/Projects/proj/proj-backend/frontends/cockpit/node_modules/@angular/http/http"' has no exported member 'HttpClient'.
src/app.module.ts(6,104): error TS2307: Cannot find module 'ngx-translate/ng2-translate'.
src/app.module.ts(7,31): error TS2307: Cannot find module 'agm/core'.
src/app.module.ts(11,48): error TS2307: Cannot find module '@agm/core'.
src/app.module.ts(206,14): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
src/app.ts(84,14): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
src/app.ts(107,5): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
src/app.ts(132,19): error TS2339: Property 'i18nValue' does not exist on type 'TranslateService'.
src/app.ts(133,58): error TS2339: Property 'value' does not exist on type 'Observable<any>'.
```
And many more, the number of errors is big and I'm not sure if I need to correct each lines of my source code or not? The application works on Angular 2.0.1. But The errors come here in bower dependecies and node_modules dependencies.

Any idea or someone facing the same?

Thank you all for your help

**Comment by IgorMinar** [comment]
Looking over the errors, it looks like these issues were not caused by the upgrade in Angular, but rather by upgrading the typescript version. The new typescript compiler often surfaces previously hidden issues, so you'll need to go over these issues and resolve them one by one.

**Comment by lilitiger** [comment]
Thanks for the answer. I understand that I have to correct the source code of my project. But some errors seems to be related to the dependencies/libraries used in the project. Does it mean that I should maybe update some libraries?
