### ISSUE TITLE
router typescript error

### ISSUE THREAD

**Issue by fabiohaertel** [angular/angular#44844]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

After upgrading Angular app from 12.2.9 to 13.2.0

Trying to build/serve the app gives a typescript validation error.

### Please provide the exception or error you saw

```true
Error: node_modules/@angular/router/router.d.ts:652:6 - error TS1023: An index signature parameter type must be either 'string' or 'number'.

652     [key: string | symbol]: any;
         ~~~


Error: node_modules/@angular/router/router.d.ts:1626:6 - error TS1023: An index signature parameter type must be either 'string' or 'number'.

1626     [key: string | symbol]: any;
          ~~~
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.1.4
Node: 16.12.0
Package Manager: npm 8.1.0
OS: win32 x64

Angular: 13.2.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1202.15
@angular-devkit/build-angular     13.1.4
@angular-devkit/build-optimizer   0.1202.15
@angular-devkit/core              12.2.9
@angular-devkit/schematics        12.2.9
@angular/cli                      13.1.4
@schematics/angular               12.2.9
rxjs                              6.6.7
typescript                        4.5.5
```

**Comment by sg-gdarnell** [comment]
Support for symbols in index signatures were added in TS 4.4 (https://devblogs.microsoft.com/typescript/announcing-typescript-4-4-rc/#symbol-template-signatures).

I see version 4.5.5 in your bug report, but are you certain your not using an earlier version?

**Comment by fabiohaertel** [comment]
Not sure how, I'm gonna check. Seems to be a project related thing then. Thanks.

**Comment by KacperObal** [comment]
Did you found what was the problem? I have the same issue.

**Comment by fabiohaertel** [comment]
I was using @angular-builders/custom-webpack in angular.json

`architect": {
        "build": {
          "builder": "@angular-builders/custom-webpack:browser",`

Replaced it with ngx-build-plus

`"builder": "ngx-build-plus:browser",`

package.json
"ngx-build-plus": "^13.0.1",

**Comment by krskrs** [comment]
Thank you guys, this helped me as well!

**Comment by chacabuk** [comment]
I have exactly same issue, and i can't solved it.

In my angular.json i have: `architect": { "build": { "builder": "@angular-devkit/build-angular:browser"`

I allways use: @angular-devkit, I don't know the package "ngx-build-plus".
```

Angular CLI: 13.2.2
Node: 16.13.1
Package Manager: npm 8.1.2
OS: win32 x64

Angular: 13.2.1
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.2
@angular-devkit/build-angular   13.2.2
@angular-devkit/core            13.2.2
@angular-devkit/schematics      13.2.2
@angular/cli                    13.2.2
@schematics/angular             13.2.2
rxjs                            6.6.7
typescript                      4.5.5


```

**Comment by Coder7777** [comment]
> e: @angular-devkit, I don't know the package "ngx-build-plus".

Did you figure out? I encounter the same issue with you.

**Comment by Coder7777** [comment]
> [name: string]: any;

I change router.d.ts definition 

export declare type Data = {
    // [key: string | symbol]: any;
    [name: string]: any;
};

It looks like work well temporary.

**Comment by parksmart-dev** [comment]
```
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 13.2.6
Node: 16.13.0
Package Manager: npm 8.1.0
OS: darwin x64

Angular: 13.2.6
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.6
@angular-devkit/build-angular   13.2.6
@angular-devkit/core            13.2.6
@angular-devkit/schematics      13.2.6
@schematics/angular             13.2.6
rxjs                            7.5.5
typescript                      4.5.5
```


Same issue, anyone know how to fix it?
