### ISSUE TITLE
error in @angular/compiler-cli@17.0.4 vs typescript@5.3.2

### ISSUE THREAD

**Issue by huineng** [angular/angular#53085]
### Which @angular/* package(s) are the source of the bug?

compiler-cli

### Is this a regression?

Yes

### Description

Compile issue with typescript 5.3.3
Is working with typescript 5.1.6

maybe related to this pull request https://github.com/angular/angular/pull/52572

### Please provide the exception or error you saw

```true
node_modules/@angular/compiler-cli/src/ngtsc/core/src/host.d.ts:20:22 - error TS2420: Class 'DelegatingCompilerHost' incorrectly implements interface 'Omit<RequiredDelegations<ExtendedTsCompilerHost>, "getSourceFile" | "fileExists">'.
  Property 'jsDocParsingMode' is missing in type 'DelegatingCompilerHost' but required in type 'Omit<RequiredDelegations<ExtendedTsCompilerHost>, "getSourceFile" | "fileExists">'.

20 export declare class DelegatingCompilerHost implements Omit<RequiredDelegations<ExtendedTsCompilerHost>, 'getSourceFile' | 'fileExists'> {
                        ~~~~~~~~~~~~~~~~~~~~~~

  node_modules/typescript/lib/typescript.d.ts:7825:9
    7825         jsDocParsingMode?: JSDocParsingMode;
                 ~~~~~~~~~~~~~~~~
    'jsDocParsingMode' is declared here.

node_modules/@angular/compiler-cli/src/ngtsc/core/src/host.d.ts:65:22 - error TS2420: Class 'NgCompilerHost' incorrectly implements interface 'RequiredDelegations<ExtendedTsCompilerHost>'.
  Property 'jsDocParsingMode' is missing in type 'NgCompilerHost' but required in type 'RequiredDelegations<ExtendedTsCompilerHost>'.

65 export declare class NgCompilerHost extends DelegatingCompilerHost implements RequiredDelegations<ExtendedTsCompilerHost>, ExtendedTsCompilerHost, NgCompilerAdapter {
                        ~~~~~~~~~~~~~~

  node_modules/typescript/lib/typescript.d.ts:7825:9
    7825         jsDocParsingMode?: JSDocParsingMode;
                 ~~~~~~~~~~~~~~~~
    'jsDocParsingMode' is declared here.

node_modules/@angular/compiler-cli/src/ngtsc/program_driver/src/ts_create_program_driver.d.ts:19:22 - error TS2420: Class 'DelegatingCompilerHost' incorrectly implements interface 'Omit<RequiredDelegations<CompilerHost>, "getSourceFile" | "writeFile" | "fileExists">'.
  Property 'jsDocParsingMode' is missing in type 'DelegatingCompilerHost' but required in type 'Omit<RequiredDelegations<CompilerHost>, "getSourceFile" | "writeFile" | "fileExists">'.

19 export declare class DelegatingCompilerHost implements Omit<RequiredDelegations<ts.CompilerHost>, 'getSourceFile' | 'fileExists' | 'writeFile'> {
                        ~~~~~~~~~~~~~~~~~~~~~~

  node_modules/typescript/lib/typescript.d.ts:7825:9
    7825         jsDocParsingMode?: JSDocParsingMode;
                 ~~~~~~~~~~~~~~~~
    'jsDocParsingMode' is declared here.


Found 3 errors in 2 files.

Errors  Files
     2  node_modules/@angular/compiler-cli/src/ngtsc/core/src/host.d.ts:20
     1  node_modules/@angular/compiler-cli/src/ngtsc/program_driver/src/ts_create_program_driver.d.ts:19
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
"@angular/compiler-cli": "^17.0.4",
"typescript": "^5.3.2",
node v18.18.2
mac
```

**Comment by crisbeto** [comment]
Angular 17.0.x doesn't have the change to support TS 5.3. It is targeted to Angular 17.1.0.
