### ISSUE TITLE
ios - safari & chrome - app will not open - unexpected eof on polyfills 

### ISSUE THREAD

**Issue by NexPlex** [angular/angular#48492]
### Which @angular/* package(s) are the source of the bug?

platform-browser

### Is this a regression?

Yes

### Description

Updated from Angular 9.1.3 to 14.0.0. App works fine on windows PC. on IOS, safari & chrome - app will not open - unexpected eof on polyfills.

Below is a screenshot of the error from the console browser.  And a copy of the polyfill file.

Thank you
Chris

![image](https://user-images.githubusercontent.com/34607168/207690977-7064057f-0161-4c96-bc2f-135d0bcd70bf.png)

**A copy of the polyfill file.**

[polyfills.7fca551addd8edc8.js.txt](https://github.com/angular/angular/files/10230956/polyfills.7fca551addd8edc8.js.txt)

### Please provide a link to a minimal reproduction of the bug

**Will not load app on IOS Angular 14.0.0**
https://app.shippingwonder.com/

**Works on IOS compiled with Angular 9.1.3**
https://app.empowerhope.ai/ 

### Please provide the exception or error you saw

```true
Browse console.
main.5659117c88ca3009.js:2 ERROR SyntaxError: JSON Parse error: Unexpected EOF

polyfills.7fca551addd8edc8.js:2 SyntaxError: JSON Parse error: Unexpected EOF
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.0.0
Node: 16.17.1
Package Manager: npm 8.15.0
OS: win32 x64

Angular: 14.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, material
... material-moment-adapter, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.0
@angular-devkit/build-angular   14.0.0
@angular-devkit/core            14.0.0
@angular-devkit/schematics      14.0.0
@angular/platform-browser       14.0.1
@schematics/angular             14.0.0
rxjs                            7.5.5
typescript                      4.7.2
webpack                         5.74.0
```

**Comment by atscott** [comment]
We recommend upgrading 1 version at a time rather than jumping multiple major versions. Does the same problem exist in versions 10 through 13?

**Comment by NexPlex** [comment]
I'm using the https://keenthemes.com/metronic/ framework
I upgrade the from work from 7 to 8. Metronic 8 is on angular 14. Any debugging suggestions. the only thing in polyfills.ts is zone.js

**Comment by atscott** [comment]
I would suggest reach out to or filing a bug with the metronic developers. This isn't an upgrade path we support, nor is there a minimal reproduction available that doesn't include a dependency on metronic.
