### ISSUE TITLE
Update from Angular 12 to Angular 13 - Karma Tests are failing

### ISSUE THREAD

**Issue by adinapopescu28** [angular/angular#48137]
### Which @angular/* package(s) are the source of the bug?

upgrade

### Is this a regression?

Yes

### Description

After update from Angular 12 to 13 I have this errors:
When I run npm test I get:
Chrome 106.0.0.0 (Windows 10) ERROR: 'JIT compilation failed for injectable', class PlatformLocation { ... }
An error was thrown in afterAll
Uncaught Error: The injectable 'PlatformLocation' needs to be compiled using the JIT compiler, but '@angular/compiler' is not available.
The injectable is part of a library that has been partially compiled.
However, the Angular Linker has not processed the library such that JIT compilation is used as fallback.
Ideally, the library is processed using the Angular Linker to become fully AOT compiled.
Alternatively, the JIT compiler should be loaded by bootstrapping using '@angular/platform-browser-dynamic' or '@angular/platform-server',
or manually provide the compiler with 'import "@angular/compiler";' before bootstrapping.

In our project we don't have Angular-cli. We use Angular together with Webpack and we have Microfrontends Arhitecure.

So, my question is: In Angular 13,  Karma is compatible with stand alone Webpack, to run tests?
If the answer is yes, how can I solve the the error above? (I am looking for a solution that does not require switching to angular cli)

This all the version for my components:
![199949895-f46352dc-ebd9-497a-86bd-984b8a98b5fa](https://user-images.githubusercontent.com/99397990/202915504-56de0e0c-808a-4e89-b52c-ef4e0945ca5d.png)

### Please provide the exception or error you saw

```true
Uncaught Error: The injectable 'PlatformLocation' needs to be compiled using the JIT compiler, but '@angular/compiler' is not available.
  The injectable is part of a library that has been partially compiled.
  However, the Angular Linker has not processed the library such that JIT compilation is used as fallback.
  Ideally, the library is processed using the Angular Linker to become fully AOT compiled.
  Alternatively, the JIT compiler should be loaded by bootstrapping using '@angular/platform-browser-dynamic' or '@angular/platform-server',
  or manually provide the compiler with 'import "@angular/compiler";' before bootstrapping.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.9
Node: 16.13.2
Package Manager: npm 8.1.2
OS: win32 x64

Angular: 13.3.11
... animations, common, compiler, core, forms, language-service
... localize, platform-browser, platform-browser-dynamic       
... platform-server, router

Package                            Version
------------------------------------------------------------   
@angular-devkit/architect          0.1303.9
@angular-devkit/build-angular      13.3.9
@angular-devkit/core               13.3.9
@angular-devkit/schematics         13.3.9
@angular/cdk                       13.3.9
@angular/material                  13.3.9
@angular/material-moment-adapter   13.3.9
@ngtools/webpack                   13.3.9
@schematics/angular                13.3.9 (cli-only)
rxjs                               7.5.7
typescript                         4.4.4
webpack                            5.74.0
```

**Comment by JoostK** [comment]
I'm sorry but custom build configurations are not supported; you'll have to integrate [the Angular Linker into your build pipeline](https://angular.io/guide/creating-libraries#consuming-partial-ivy-code-outside-the-angular-cli).
