### ISSUE TITLE
_createConditionalRootRenderer signature requires 3 arguments, ngfactory call provides only 2

### ISSUE THREAD

**Issue by wrummler** [angular/angular#13312]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I have a project using Angular 2.2.4 configured for AOT. Compilation (and tests etc) work without any problems. When I update to 2.3.0, `ngc` fails with the following error:

```
Error at C:/Users/wrummler/dev/.../app.module.ngfactory.ts:265:71: Supplied parameters do not match any signature of call target.
```

The 2-argument call expression in that file causing the error:

```
import74._createConditionalRootRenderer(this._DomRootRenderer_39,this.parent.get(import74.NgProbeToken,(null as any)))
```

The import:

```
import * as import74 from '@angular/platform-browser/src/dom/debug/ng_probe';
```

The `_createConditionalRootRenderer` function in `ng_probe` was recently changed to require 3 arguments instead of 2. See [this diff](https://github.com/angular/angular/commit/c2fae72bc69cd67e8d3cea50da5e9207e5da28b7#diff-2737fdf36f7eaedaec3749303681c582R42).

Whatever's generating the ngfactory file wasn't correspondingly updated perhaps. (I did not find the specific code that's generating the file, but I probably don't know what to look for.) Based on the usage of `coreTokens`, maybe just changing that 2-argument invocation to have a 3rd `null` argument would be fine? Or maybe `_createConditionalRootRenderer`'s 3rd parameter should simply be optional? Dunno.

**Expected behavior**

`ngc` emits no error after updating angular from 2.2.4 to 2.3.0.

**Minimal reproduction of the problem with instructions**

See above description.

**What is the motivation / use case for changing the behavior?**

So that updating from angular 2.2.4 to 2.3.0 doesn't break AOT.

**Please tell us about your environment:**

Windows 7 64-bit, VS Code 1.7.2, NPM 3.10.3

* **Angular version:** 2.3.0

* **Browser:** Electron 1.4.11

 
* **Language:** TypeScript 2.1.4

* **Node (for AoT issues):** `node --version` = v6.9.1

**Comment by nopantsmonkey** [comment]
still occurring in 
angular v2.4.0 
webpack 2.2.0-rc-1
rxjs 5.0.1
zonejs 0.7.2

**Comment by tbosch** [comment]
We don't support TypeScript 2.1 right now. My guess is that you had stale `.ngfactory.ts` files from a previous angular version around.

Could you delete all `.ngfactory.ts`, downgrade to typescript 2.0.x and try again? We are working on TS 2.1, but its not done yet...

**Comment by wrummler** [comment]
@tbosch Yep, it works with TS 2.0. When I sanity-checked 2.1 afterward (with no leftover ngfactory outputs) I got a different ngc error (which I'm guessing is the "right" error until 2.1 support is reached?), `Cannot find module './__ngc/app.module.ngfactory'.` emanating from my platform-bootstrap file. Thanks for the feedback and good luck on the 2.1 support.

**Comment by tbosch** [comment]
Closing, as caused by missing TS 2.1 support, see https://github.com/angular/angular/issues/13715
