### ISSUE TITLE
Signal forms custom validator with 'fieldTree' field in validation result error

### ISSUE THREAD

**Issue by rahimalizada** [angular/angular#66687]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

Yes

### Description

After upgrading to 21.1.0 and with the removal customError() from signal forms returning ValidationError from custom validator results in compilation error.

Documentation https://angular.dev/guide/forms/signals/validation#using-validate has an example. It does not state that 'fieldTree' works only in submit function, but have a comment in the example code.

```typescript
interface DTO {
  firstName: string;
  lastName: string;
}

export class App {
  private readonly model = model<DTO>({
    firstName: '',
    lastName: '',
  });

  protected readonly form = form(this.model, (path) => {
    validate(path, (ctx) => {
      if (ctx.valueOf(path.firstName).length < 5) {
        return {
          kind: 'test',
          message: 'Message',
          fieldTree: path.lastName, // or ctx.fieldTree.lastName
        };
      }
      return null;
    });    
  });
}
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-8ik35v9w?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
Argument of type '(ctx: RootFieldContext<DTO>) => { kind: string; message: string; fieldTree: SchemaPath<string, 1, Child>; } | null' is not assignable to parameter of type 'FieldValidator<DTO, Root>'.
  Type '{ kind: string; message: string; fieldTree: SchemaPath<string, 1, Child>; } | null' is not assignable to type 'ValidationResult<WithoutField>'.
    Type '{ kind: string; message: string; fieldTree: SchemaPath<string, 1, PathKind.Child>; }' is not assignable to type 'ValidationResult<WithoutField>'.
      Type '{ kind: string; message: string; fieldTree: SchemaPath<string, 1, PathKind.Child>; }' is not assignable to type 'WithoutField'.
        Types of property 'fieldTree' are incompatible.
          Type 'SchemaPath<string, 1, Child>' is not assignable to type 'undefined'.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI       : 21.1.0
Angular           : 21.1.0
Node.js           : 24.12.0
Package Manager   : npm 11.7.0
Operating System  : win32 x64

┌───────────────────────────────────┬───────────────────┬───────────────────┐
│ Package                           │ Installed Version │ Requested Version │
├───────────────────────────────────┼───────────────────┼───────────────────┤
│ @angular-devkit/build-angular     │ 21.1.0            │ 21.1.0            │
│ @angular-devkit/core              │ 21.1.0            │ 21.1.0            │
│ @angular-devkit/schematics        │ 21.1.0            │ 21.1.0            │
│ @angular/animations               │ 21.1.0            │ 21.1.0            │
│ @angular/build                    │ 21.1.0            │ 21.1.0            │
│ @angular/cdk                      │ 21.1.0            │ 21.1.0            │
│ @angular/cli                      │ 21.1.0            │ 21.1.0            │
│ @angular/common                   │ 21.1.0            │ 21.1.0            │
│ @angular/compiler                 │ 21.1.0            │ 21.1.0            │
│ @angular/compiler-cli             │ 21.1.0            │ 21.1.0            │
│ @angular/core                     │ 21.1.0            │ 21.1.0            │
│ @angular/forms                    │ 21.1.0            │ 21.1.0            │
│ @angular/google-maps              │ 21.1.0            │ 21.1.0            │
│ @angular/language-service         │ 21.1.0            │ 21.1.0            │
│ @angular/localize                 │ 21.1.0            │ 21.1.0            │
│ @angular/material                 │ 21.1.0            │ 21.1.0            │
│ @angular/platform-browser         │ 21.1.0            │ 21.1.0            │
│ @angular/platform-browser-dynamic │ 21.1.0            │ 21.1.0            │
│ @angular/pwa                      │ 21.1.0            │ 21.1.0            │
│ @angular/router                   │ 21.1.0            │ 21.1.0            │
│ @angular/service-worker           │ 21.1.0            │ 21.1.0            │
│ @schematics/angular               │ 21.1.0            │ 21.1.0            │
│ rxjs                              │ 7.8.2             │ ~7.8.0            │
│ typescript                        │ 5.9.3             │ ^5.9.3            │
└───────────────────────────────────┴───────────────────┴───────────────────┘
```

**Comment by JoostK** [comment]
Judging by the type system this should use `validateTree`:

```ts
    validateTree(path, (ctx) => {
      if (ctx.valueOf(path.firstName).length < 5) {
        return {
          kind: 'test',
          message: 'Message',
          fieldTree: ctx.fieldTree.lastName,
        };
      }
      return null;
    });
```

**Comment by JoostK** [comment]
In that case, the documentation would need to be updated.

**Comment by rahimalizada** [comment]
@JoostK Thank you!

**Comment by leonsenft** [comment]
> Judging by the type system this should use `validateTree`:
> 
>     validateTree(path, (ctx) => {
>       if (ctx.valueOf(path.firstName).length < 5) {
>         return {
>           kind: 'test',
>           message: 'Message',
>           fieldTree: ctx.fieldTree.lastName,
>         };
>       }
>       return null;
>     });

Correct! `validate` applies to a specific field and any errors it produces will automatically include the validated `fieldTree`.

`validateTree` (and `submit`) allow errors to target other fields by specifying a `fieldTree`.
