### ISSUE TITLE
4.0.0 received no aot compilation error on { provide: 'windowObject', useValue: window },

### ISSUE THREAD

**Issue by dereklin** [angular/angular#15495]
When I was using 2.4.9 and tried to build aot, there was a compilation error regarding this:
```
{ provide: 'windowObject', useValue: window },
```
I upgraded to 4.0.0, and didn't see the error.  I thought Angular 4 is capable of understanding this usage now.  I was wrong.  In production at runtime, the window object is undefined.

In the end, I used the approach described here: https://juristr.com/blog/2016/09/ng2-get-window-ref/ and it works in 4.0.0

But if Angular 4 can't inject the window object with { provide: 'windowObject', useValue: window }, it should give an error during compilation like it did in 2.4.9.

**Comment by DzmitryShylovich** [comment]
Yeah, I can confirm that it doesn't throw during compilation but injects `undefined`.

**Comment by oleonardo** [comment]
+1

**Comment by JoostK** [comment]
I can no longer reproduce in Angular 9, neither using ViewEngine nor Ivy. Closing as resolved.
