### ISSUE TITLE
[2.0.0 final] UpgradeAdapter setTimeout doesn't trigger change detection

### ISSUE THREAD

**Issue by guojenman** [angular/angular#11572]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
setTimeout does not trigger change detection. I have to wrap the timeout in NgZone.run + ChangeDetector.markForCheck() for change detection to happen.

**Expected behavior**
setTimeout should trigger change detection

**Reproduction of the problem**
https://plnkr.co/edit/B3sSt9?p=preview

In the example above you will see two instances of the same ng2 child component contained in a ng2 parent component which was downgraded for ng1.

child 1's input changes via setTimeout + NgZone + markForChange - this one works
child 2's input changes via setTimeout only - this does **not** work

**Please tell us about your environment:**

* **Angular version:** 2.0.0
* **Browser:** [all ]

**Comment by guojenman** [comment]
I have to use the same hack for inside of Http's subscribe. Seems to be working for mouse and key events without the hack though.

**Comment by marcalj** [comment]
@guojenman It's fixed with v2.0.0 final? It's a bug of angular or Zone.js? Thanks!

PD: Congrats for the final release! But the upgrade project still has a lot of problems to rely on... I hope ng-bootstrap and ng2-bootstrap have all functionalities soon to forget using ```ngUpgrade```...

**Comment by pkozlowski-opensource** [comment]
@marcalj we've just released alpha.5 of https://ng-bootstrap.github.io and it contains datepickers in popups. This release brings it very close to angular-ui/bootstrap, feature-wise. If you've got anything critical missing let's discuss in the issue tracker of https://github.com/ng-bootstrap/ng-bootstrap

**Comment by marcalj** [comment]
@pkozlowski-opensource The last thing missing for us is dropdown with append-to-body https://github.com/ng-bootstrap/ng-bootstrap/issues/584#issuecomment-245431416

I'm wating for this issue to be fixed to try v2 final, or I can use RC6 with ng-boostrap alpha.5?

Thanks!

**Comment by guojenman** [comment]
Updated Plnker with 2.0.0 final - same problem :(

**Comment by marcalj** [comment]
@guojenman Did you try with older Zone.js version?

**Comment by guojenman** [comment]
@marcalj Yup

Zone.js v.0.6.17 and earlier -> Zone.assertZonePatched is not a function
Zone.js v.0.6.18 - v.0.6.23 -> The bug as reported in this thread

**Comment by gjdev** [comment]
Http.subscribe has the same problem/bug.

**Comment by guojenman** [comment]
@gjdev @marcalj oh wow, I didn't even think to test w/o UpradeAdapter because this is such a core functionality of angular2 that I would've never thought it would be a bug in core so close to release and even after final. Never take things for granted! :)

Forked the plnker, removed ng1 and added Http

https://plnkr.co/edit/B3sSt9?p=preview

@IgorMinar Can you re-label this or do we need a new bug?

**Comment by marcalj** [comment]
:o wow!

They usually prefer creating new issues to then reference in commits/changelog.

**Comment by guojenman** [comment]
After understanding this bug better I found two related bugs (referenced above), so probably no need for new bug.

**Comment by gjdev** [comment]
I don't think #10208 is the same bug. We encountered this bug only after upgrading from RC4 to 2.0.0. Additionally we have this bug also when converting the Http observable to a promise. #10208 report is for RC4, and explicitly when not converting toPromise.

It's also not #7998 as this is a very old bug report about a very specific component hierarchy, and from way before this bug was introduced.
