### PR TITLE
refactor(compiler): remove support for TypeScript 3.9

### PR DESCRIPTION
**Pull request by AndrewKushnir**
This commit removes TypeScript 3.9 support.

NOTE: corresponding TS 3.9 integration tests will be removed later in a followup cleanup PR.

BREAKING CHANGE:

TypeScript 3.9 is no longer supported, please upgrade to TypeScript 4.0.

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

### CODE REVIEW

**Comment by AndrewKushnir** [comment]
[Presubmit](http://test/OCL:337612640:BASE:337612643:1602898054155:5a2eb9a3).

**Review by alan-agius4 — APPROVED** [review]
Thanks @AndrewKushnir, LGTM

File: packages/compiler-cli/src/typescript_support.ts [hunk 1]
```diff
@@ -12,7 +12,7 @@ import {compareVersions} from './diagnostics/typescript_version';
  * Minimum supported TypeScript version
  * ∀ supported typescript version v, v >= MIN_TS_VERSION
  */
-const MIN_TS_VERSION = '3.9.2';
+const MIN_TS_VERSION = '4.0.0';
```
Comment (kyliau) [inline packages/compiler-cli/src/typescript_support.ts:15]: Is this not applicable to google3? Might be helpful to add this in the comments if that's true.

Comment (AndrewKushnir) [reply packages/compiler-cli/src/typescript_support.ts:18]: Thanks for the comment @kyliau.
This check is disabled in g3 (since we know the TS version) and I've added a comment on that in the code.

**Review by jelbourn — APPROVED** [review]
LGTM

Reviewed-for: global-docs-approvers

**Review by kyliau — APPROVED** [review]

**Comment by KapilSachdev** [comment]
I had encountered an issue with TS 4 and 10.1 which was reported [here](https://github.com/angular/angular/pull/38076#issuecomment-692971745), which is still happening with 11.0.0-rc.0 and TS 4.


```js
ERROR in src/app/some/some.component.ts:26:81 - error TS2729: Property 'some_id' is used before its initialization.

26   public data: any = {some_id: this?.some_id, date: new Date()};
                                                                                   ~~~~~~~~~~~~~~~

  src/app/some/some.component.ts:22:12
    22   @Input() some_id
                  ~~~~~~~~~~~~~~~
    'some_id' is declared here.
```

As it is evident, the variable is defined before its being used.
Also it works fine with `3.9`.
_I'm not sure if `TS 4.0` introduced something that could cause this issue, but i think its `ng` so just wanted to confirm. I tried to look into issue tracker for similar reports, though not that deeply, but didn't found any._

**Comment by AndrewKushnir** [comment]
@KapilSachdev, could you please create a new ticket and provide the necessary information (by following the template), so that the team can have a look? As a part of the new ticket, please also provide an example of the code that doesn't work, so that we can reproduce the problem. Thank you.

**Comment by KapilSachdev** [comment]
Before creating a new issue i wanted to confirm one more thing, in case the behaviour is expected.
When the properties are being called on component initialization the issue occurs with `TS 4` but not with `TS 3.9`.
```js
@Input() some_id
public data: any = {some_id: this?.some_id, date: new Date()};

ngOnInit() {
}
```

Moving the `data` property initialization that uses `@Input()` property inside `ngOnInit` fixes the problem in `TS 4`
```js
@Input() some_id

ngOnInit() {
  public data: any = {some_id: this?.some_id, date: new Date()};
}
```
Is this expected behaviour because `@Input` is not yet passed to the component? In case yes, why it does nto happens with `TS 3.9`

**Comment by AndrewKushnir** [comment]
@KapilSachdev I don't think your use-case is specific to Angular (the error is being produced by the TypeScript). You can see how different version of TypeScript handle this in [TypeScript Playground](https://www.typescriptlang.org/play).
