### ISSUE TITLE
ng update wrote wrong path of main.ts and polyfill.ts in tsconfig.app.json

### ISSUE THREAD

**Issue by SachinShekhar** [angular/angular#35055]
# 🐞 bug report

### Affected Package

 N/A

### Is this a regression?

 Yes, the previous version in which this bug was not present was: v8

### Description

 After upgrading to v9, I found that path of main.ts and polyfill.ts are wrongly written in tsconfig.app.json which makes the app unusable.

## 🔬 Minimal Reproduction

 
Checkout this commit https://github.com/SachinShekhar/angular-ssr-prerendering-bug/commit/593f5999bd356b4ce98ac27db4d24dd797423c43 and run `ng update @angular/core @angular/cli --next`

The result will be https://github.com/SachinShekhar/angular-ssr-prerendering-bug/commit/5528e5fc9baec960a64a4cbb84db72c0561f2df4#diff-d090b1ccd7cff3dfff369e150143bb09

## 🔥 Exception or Error
<pre><code>

ERROR in error TS6053: File 'x:/Bugs/angular-ssr-prerendering-bug/apps/angular-ssr-prerendering-bug/apps/angular-ssr-prerendering-bug/src/main.ts' not found.
error TS6053: File 'x:/Bugs/angular-ssr-prerendering-bug/apps/angular-ssr-prerendering-bug/apps/angular-ssr-prerendering-bug/src/polyfills.ts' not found.
</code></pre>
This error is thrown when I run `ng serve`.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.0.0-rc.11
Node: 12.6.0
OS: win32 x64

Angular: 9.0.0-rc.11
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.11
@angular-devkit/build-angular     0.900.0-rc.11
@angular-devkit/build-optimizer   0.900.0-rc.11
@angular-devkit/build-webpack     0.900.0-rc.11
@angular-devkit/core              9.0.0-rc.11
@angular-devkit/schematics        9.0.0-rc.11
@ngtools/webpack                  9.0.0-rc.11
@nguniversal/builders             9.0.0-rc.1
@nguniversal/common               9.0.0-rc.1
@nguniversal/express-engine       9.0.0-rc.1
@schematics/angular               9.0.0-rc.11
@schematics/update                0.900.0-rc.11
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

This project uses [NX](https://github.com/nrwl/nx) schematics. I've a feeling that it is the culprit.
