### ISSUE TITLE
Throw Node is not defined when server-side rendering

### ISSUE THREAD

**Issue by Shinerising** [angular/angular#23280]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When the server-side rendering progress wants to insert a piece of HTML text (like `Hello <b>bro</b>!`) into template with [innerHTML] but without sanitizer, the terminal throws error message like this: (browser rendering works normally)

```
ERROR ReferenceError: Node is not defined
    at isTemplateElement (.../dist-server/main.js:45681:28)
    at getTemplateContent (.../dist-server/main.js:45676:65)
    at Object._sanitizeHtml [as ɵ_sanitizeHtml] (.../dist-server/main.js:45668:28)
    at DomSanitizerImpl../node_modules/@angular/platform-browser/bundles/platform-browser.umd.js.DomSanitizerImpl.sanitize (.../dist-server/main.js:66931:29)
    ...
```

## Expected behavior

The server-side rendering progress should render safe HTML text directly, for the case that website always need to output some information with format.

## What is the motivation / use case for changing the behavior?

Template:

```HTML
<div class="index-quotename" [innerHTML]="item.name">
</div>
```

And the data fetched from Server is just like this

```JS
item.name = '<b>foo</b> bar'
```

BTW, I tried to import the Node modules exported from domino in main.js which server used to render the webpage, and everything works well.

## Environment

<pre><code>
Angular version: 6.0.0-rc.3

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [x] Safari (desktop) version 11.2
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9.8.0  
- Platform: Mac  

Others:

</code></pre>

**Comment by Epenance** [comment]
Getting this in 6.0.0-rc7 too.

**Comment by Willovent** [comment]
Also in the release

**Comment by vytautas-pranskunas-** [comment]
Also in 6.0.0

**Comment by patrykp57** [comment]
Same in Angular 6.0.1

**Comment by justinappler** [comment]
Looks like this was caused when the Sanitization code moved into core. There were some substantial changes that don't appear to be isomorphic and only work in the browser. At first glance, this PR seems to be the culprit: https://github.com/angular/angular/pull/22540

**Comment by vikerman** [comment]
@justinappler - Thanks for looking into it. Working on a fix

**Comment by vasyliv** [comment]
There are any updates?

**Comment by vikerman** [comment]
@vasyliv - A PR with the fix is in progress as updated in the bug here.

**Comment by eyalhakim** [comment]
Looking forward to this fix

**Comment by m98** [comment]
Anyone knows if I update Angular, this problem will be fixed or it's still waiting to merge and update?

**Comment by Shinerising** [comment]
@m98 v6.0.3(current version) still don't work and I think v6.0.4 should fix this, which could be expected to release this Wednesday or Thursday. You can wait or just try a little fix: add domino's Node implement manually to your SSR code.

**Comment by m98** [comment]
@Shinerising Yes, I would like to use Domino's Node. But how should I implement it for this case?

**Comment by Toxicable** [comment]
@m98 It'll be in the nest release which will be this week

**Comment by alxpsr** [comment]
```
// add to server.ts

function setDomTypes() {
  // Make all Domino types available as types in the global env.
  Object.assign(global, domino['impl']);
  (global as any)['KeyboardEvent'] = domino['impl'].Event;
}

setDomTypes();
```

**Comment by m98** [comment]
@alxpsr 
But what's `domino`? Is there any special module I need to import to `server.ts`? Because I get an error now!

**Comment by alxpsr** [comment]
domino is a server-side DOM implementation (this is a node-module, install it via npm and import to server.ts)

**Comment by Shinerising** [comment]
@m98 In my case, I just add this line to my webpacked server side script bundle directly:
`var Node = __webpack_require__(/*! ./Node */ "./node_modules/domino/lib/Node.js");`
PTW. Angular's serverplatform package has domino required so it's no need to install it again. It's a strange fix but it truly works, but you need to find a right position to insert this line.

**Comment by kblestarge** [comment]
Angular 6.0.4 is out with the fix! Woohoo!

**Comment by bflopez** [comment]
I installed 6.0.4 and am still getting the same issue I believe. Can someone tell me if this is the same issue or a different one? I ran my build with webpack 2.7 and dev-tool 'eval'. If I run it with 'source-map' it tells me 'l/r is not a function' and I can trace that back to http-errors/inherits where it doesn't understand HTMLElement. At a loss why my build isn't working with ng6 including 6.0.4. No errors when building. Just can't get it to start when running 'node dest/main.server.bundle.js'

```
webpack:///./~/domino/lib/htmlelts.js?:76
var HTMLElement = exports.HTMLElement = define({
                                        ^
TypeError: define is not a function
    at eval (webpack:///./~/domino/lib/htmlelts.js?:76:41)
    at Object.<anonymous> (/home/dev/hunter/site/src/dest/main.server.bundle.js:1:1618354)
    at t (/home/dev/hunter/site/src/dest/main.server.bundle.js:1:172)
    at eval (webpack:///./~/domino/lib/Document.js?:24:12)
    at Object.<anonymous> (/home/dev/hunter/site/src/dest/main.server.bundle.js:1:1330096)
    at t (/home/dev/hunter/site/src/dest/main.server.bundle.js:1:172)
    at eval (webpack:///./~/domino/lib/DOMImplementation.js?:7:16)
    at Object.<anonymous> (/home/dev/hunter/site/src/dest/main.server.bundle.js:1:1236505)
    at t (/home/dev/hunter/site/src/dest/main.server.bundle.js:1:172)
    at eval (webpack:///./~/domino/lib/index.js?:5:25)
```
