### ISSUE TITLE
Incremental build - ngtypecheck - error TS1110: Type expected.

### ISSUE THREAD

**Issue by claytongreen** [angular/angular#42667]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes. Worked previously v12.0.5

### Description

Initial build using `ng s` succeeds, but on incremental build I get `error TS1110: Type expected.` when using `angular-imask` directive on an input element.
https://github.com/uNmAnNeR/imaskjs/tree/master/packages/angular-imask

## 🔬 Minimal Reproduction

https://github.com/claytongreen/ngtypecheck-error

Build with basic `ng s`
Comment out `<p>Testing` in `app.component.html` to cause rebuild

## 🔥 Exception or Error

```
Error: src/app/app.component.ngtypecheck.ts:5:36 - error TS1110: Type expected.

5 const _ctor1: <Opts extends import().default.AnyMaskedOptions = any>(init: Pick<i1.IMaskDirective<Opts>, "imaskElement" | "imask" | "unmask">) => i1.IMaskDirective<Opts> = null!;
                                     ~
```

## 🌍 Your Environment

<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 12.1.0
Node: 14.17.0
Package Manager: npm 7.9.0
OS: win32 x64

Angular: 12.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.0
@angular-devkit/build-angular   12.1.0
@angular-devkit/core            12.1.0
@angular-devkit/schematics      12.1.0
@schematics/angular             12.1.0
rxjs                            6.6.7
typescript                      4.3.4
</code></pre>

**Comment by JoostK** [comment]
This has regressed in #42492, where the compiler has started accepting more type parameters for directives.

In this case, the string literal in the `import` type node is not properly recreated in the typecheck source file. It was assumed in #42492 that any potential errors would not actually be reported, as only type check errors that actually come from a template should be reported. In this case however, there is a syntactical error and the CLI is always reporting those, even when occurring outside of template code.

I see three action items:
1. Properly recreate literals in the type check file
2. Either disallow or rewrite import type nodes
3. Update the CLI to not report syntactic errors in typecheck files.

**Comment by alxhub** [comment]
I think option 3 is the right choice, here. `ngtypecheck` files should be private to the compiler.
