### ISSUE TITLE
Angular 13. Karma errors 

### ISSUE THREAD

**Issue by adinapopescu28** [angular/angular#47974]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

After update from Angular 12 to 13 I have this errors:
When I run npm test I get
1. karma start
webpack was not included as a framework in karma configuration, setting this automatically...
karma-webpack does not currently support custom entries, if this is something you need,
consider opening an issue.
karma-webpack does not currently support customized filenames via
webpack output.filename, if this is something you need consider opening an issue.
defaulting [name]/index.js?t=[fullhash] to [name].js.

2. Chrome 106.0.0.0 (Windows 10) ERROR: 'JIT compilation failed for injectable', class PlatformLocation { ... }
  An error was thrown in afterAll
  Uncaught Error: The injectable 'PlatformLocation' needs to be compiled using the JIT compiler, but '@angular/compiler' is not available.
  The injectable is part of a library that has been partially compiled.
  However, the Angular Linker has not processed the library such that JIT compilation is used as fallback.
  Ideally, the library is processed using the Angular Linker to become fully AOT compiled.
  Alternatively, the JIT compiler should be loaded by bootstrapping using '@angular/platform-browser-dynamic' or '@angular/platform-server',
  or manually provide the compiler with 'import "@angular/compiler";' before bootstrapping.

This all the version for my components:
![image](https://user-images.githubusercontent.com/99397990/199949895-f46352dc-ebd9-497a-86bd-984b8a98b5fa.png)

Has anyone encountered these problems?

Thank you!

### Please provide the exception or error you saw

```true
Uncaught Error: The injectable 'PlatformLocation' needs to be compiled using the JIT compiler, but '@angular/compiler' is not available.
  The injectable is part of a library that has been partially compiled.
  However, the Angular Linker has not processed the library such that JIT compilation is used as fallback.
  Ideally, the library is processed using the Angular Linker to become fully AOT compiled.
  Alternatively, the JIT compiler should be loaded by bootstrapping using '@angular/platform-browser-dynamic' or '@angular/platform-server',
  or manually provide the compiler with 'import "@angular/compiler";' before bootstrapping.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.9
Node: 16.13.2
Package Manager: npm 8.1.2
OS: win32 x64

Angular: 13.3.11
... animations, common, compiler, core, forms, language-service
... localize, platform-browser, platform-browser-dynamic       
... platform-server, router

Package                            Version
------------------------------------------------------------   
@angular-devkit/architect          0.1303.9
@angular-devkit/build-angular      13.3.9
@angular-devkit/core               13.3.9
@angular-devkit/schematics         13.3.9
@angular/cdk                       13.3.9
@angular/material                  13.3.9
@angular/material-moment-adapter   13.3.9
@ngtools/webpack                   13.3.9
@schematics/angular                13.3.9 (cli-only)
rxjs                               7.5.7
typescript                         4.4.4
webpack                            5.74.0
```

**Comment by JoostK** [comment]
It looks like you're using a custom build setup, which is not something we support in the issue tracker.

As for the second error: Angular 13 started shipping its NPM libraries using a new partial compilation format, which then needs to become fully AOT compiled in the build pipeline. The CLI takes care of this, but custom build pipelines will have to configure the Angular linker as mentioned in that error. Alternatively the JIT compiler can be used as fallback, but I wouldn't recommend that as your production build would require the usage of teh Angular linker (to avoid using the JIT compiler in production, which would have security, bundle size and performance implications).

**Comment by adinapopescu28** [comment]
Hello.
I tried a lot of stuff to solve this issue but didn't had so much luck.
Can you be more clear? What steps should I follow to solve the problem?

Thank you!
