### ISSUE TITLE
locale data have disappeared in 6.0.0-rc.1

### ISSUE THREAD

**Issue by jnizet** [angular/angular#23103]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The following line doesn't compile anymore (it did compile in 6.0.0-rc.0):

```
import localeFr from '@angular/common/locales/fr';
```

It produced the following error:

    error TS2307: Cannot find module '@angular/common/locales/fr'

Nothing in the changelog (unless I missed something)warns about a new module to use for the locale data. the documentation at next.angular.io still uses this module, too.

## Expected behavior

it should compile

## Environment

<pre><code>
Angular version: 6.0.0-rc.1

 
For Tooling issues:
- Node version: 8.9.0  
- Platform: Mac 

Others:

</code></pre>

**Comment by IgorMinar** [comment]
oops. good catch. we'll fix this in rc.2 next week. sorry about the trouble...

**Comment by alexeagle** [comment]
Should be fixed by 7ca7720
