### ISSUE TITLE
tsickle is not installed by default in 7.0.0-rc.0

### ISSUE THREAD

**Issue by steveblue** [angular/angular#26290]
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Noticed a breaking change when updating a simple app from 6.1.x to 7.0.0-rc.0 and trying to bundle our applications with closure compiler.

tsickle is not installed when running `npm install` on typical angular packages.

## Expected behavior

tsickle is installed by `@angular` packages like before.

## Minimal reproduction of the problem with instructions

`npm install -g @angular/cli@latest angular-rollup@latest`
`ngr new my-app` <-- you are generating a new app with ngr instead of ng
Update angular packages to 7.0.0-rc.0 and typescript to 3.1.1
`ngr build prod --serve`
Notice in terminal error about `tsickle` module is missing
```
: Error: Cannot find module 'tsickle'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
```
`npm install tsickle`
Error is gone.

* NOTE there is separate issue preventing closure compiler from bundling because of new dependence on `@angular/compiler` in `@angular/core` package.

 If you add below to the closure.conf the build will now work.
```
--js node_modules/@angular/compiler/package.json
--js node_modules/@angular/compiler/fesm2015/compiler.js
```

## What is the motivation / use case for changing the behavior?

Maintenance of tsickle version is now on application team and is no longer in sync with compiler.

## Environment

<pre><code>
Angular version: 7.0.0-rc.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v9.5.0
- Platform:  MacOS

Others:

</code></pre>

**Comment by alxhub** [comment]
This is actually by design - `tsickle` is optional as of the RC. I'll defer to @StephenFluin as to whether we should warn about this more prominently.

**Comment by steveblue** [comment]
OK, but now `tsickle` is not a dependency of `@angular/compiler-cli` how are teams using tsickle supposed to know which version of `tsickle` is directly compatible with `@angular/compiler-cli` other than being on the latest version of both packages?

**Comment by StephenFluin** [comment]
@alexeagle is looking at the right resolution, because for most developers tsickle is optional.

**Comment by alexeagle** [comment]
If you have tsickle enabled in your `angularCompilerOptions` and don't have the `tsickle` npm package installed, we give a nice warning in rules_typescript
https://github.com/bazelbuild/rules_typescript/blob/2031c292a31ed84a2e71d1e43e205895218ab77c/internal/tsc_wrapped/tsc_wrapped.ts#L153-L161
but we don't warn under vanilla `ngc`
https://github.com/angular/angular/blob/665627e254396b052cd4a726729c47dbc3061086/packages/compiler-cli/src/main.ts#L91
which is not so nice.
As for selecting the right version, npm doesn't have a way to constrain versions of an optional dependency. Maybe we can add a runtime check on the version as well.
Finally, I don't expect that any novice users would choose the closure compiler path, so I don't think this needs to be as ergonomic as core parts of Angular.

**Comment by steveblue** [comment]
I mistakenly closed this and reopened it @IgorMinar, wasn't trying to get movement on it. I will close it now though. I still disagree with this design decision.

**Comment by scott-ho** [comment]
why not specify it as a optional or peer dependency?

**Comment by IgorMinar** [comment]
Because it needs to be both optional and peer dep, and npm doesn't have a
way to express that.
