### ISSUE TITLE
Angular compilation failing after migrating to V16

### ISSUE THREAD

**Issue by sambuddha189** [angular/angular#56355]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

Getting compilation errors on running `ng serve` after migrating to v16.

### Please provide the exception or error you saw

```true
error NG6002: This import contains errors, which may affect components that depend on this NgModue.

On opening the angular modules I do not see any import errors or warnings. Not sure what is causing this error to pop up. Could you help please?
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.2.14
Node: 16.16.0
Package Manager: npm 8.11.0
OS: darwin x64

Angular: 16.2.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.14
@angular-devkit/build-angular   16.2.14
@angular-devkit/core            16.2.14
@angular-devkit/schematics      16.2.14
@angular/cdk                    16.2.14
@angular/cli                    16.2.14
@angular/material               16.2.14
@schematics/angular             16.2.14
rxjs                            6.6.7
typescript                      4.9.3
zone.js                         0.13.3
```

### Anything else?

Following is my package json:
{
  "name": "***",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "***",
    "build-prod": "***",
    "build-staging": "***",
    "test": "ng test",
    "lint": "eslint . --ext .ts --fix",
    "e2e": "ng e2e",
    "cypress:open": "npx cypress open",
    "cypress:run": "cypress run",
    "cypress:e2e": "***"
  },
  "eslintIgnore": [
    "*.spec.ts"
  ],
  "private": true,
  "dependencies": {
    "@angular-devkit/core": "^16.2.14",
    "@angular/animations": "^16.2.12",
    "@angular/cdk": "^16.2.14",
    "@angular/common": "^16.2.12",
    "@angular/compiler": "^16.2.12",
    "@angular/core": "^16.2.12",
    "@angular/forms": "^16.2.12",
    "@angular/material": "^16.2.14",
    "@angular/platform-browser": "^16.2.12",
    "@angular/platform-browser-dynamic": "^16.2.12",
    "@angular/router": "^16.2.12",
    "@buzz/columbo-reporter-web": "^1.0.0",
    "@ng-idle/core": "^14.0.0",
    "@swimlane/ngx-charts": "^20.5.0",
    "@typescript-eslint/eslint-plugin": "^3.10.1",
    "@typescript-eslint/parser": "^3.10.1",
    "angular2-multiselect-dropdown": "^5.0.4",
    "core-js": "^2.5.4",
    "d3-format": "1.4.1",
    "eslint": "^7.7.0",
    "eslint-config-airbnb-base": "^14.2.0",
    "eslint-plugin-import": "^2.22.0",
    "lodash": "^4.17.20",
    "ngx-toastr": "^17.0.2",
    "node-gyp": "^10.1.0",
    "primeflex": "^1.0.0",
    "primeicons": "^2.0.0",
    "primeng": "^8.1.1",
    "quill": "^2.0.2",
    "rxjs": "^6.4.0",
    "tslib": "^2.0.0",
    "util": "^0.12.5",
    "zone.js": "~0.13.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^16.2.14",
    "@angular/cli": "^16.2.14",
    "@angular/compiler-cli": "^16.2.12",
    "@angular/language-service": "^16.2.12",
    "@apple/sf-symbols-web": "^5.0.0",
    "@cypress/schematic": "^1.6.0",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^0.0.28",
    "jasmine-core": "~3.8.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.3.9",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.6.0",
    "ng-mocks": "^10.5.4",
    "ngx-spec": "^2.1.4",
    "node-sass": "^9.0.0",
    "protractor": "^7.0.0",
    "start-server-and-test": "^2.0.0",
    "ts-node": "~5.0.1",
    "tslint": "~6.1.0",
    "typescript": "^4.9.3"
  }
}

**Comment by JoostK** [comment]
Please provide a runnable reproduction as without one this isn't actionable to us. Given the reported error there are likely additional errors that indicate what the problem is.

**Comment by sambuddha189** [comment]
There are no additional errors on my terminal, all the errors are same and are getting originated from `app.module.ts`, `shared.module.ts` and the other feature modules :
` error NG6002: This import contains errors, which may affect components that depend on this NgModule.`

I ran `ng update @angular/core@16 @angular/cli@16` to uprade my application from v15 to v16.

My Node version :  16.16.0.

**Comment by JeanMeche** [comment]
It's very likely that you have a module that not compatible with v16 because the library it comes from is not compiler for ivy.

**Comment by json-derulo** [comment]
Seems like the issue is caused by the `angular2-multiselect-dropdown` package. 

https://github.com/CuppaLabs/angular2-multiselect-dropdown/issues/648

**Comment by JoostK** [comment]
That would indeed explain it. Angular only supports libraries that are compiled with N-2, so for Angular 16 that means libraries should have been compiled with at least Angular 14.
