### ISSUE TITLE
12.2.12 i18n compilation error: Localized bundle generation failed: Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by manzonif** [angular/angular#44004]
### Which @angular/* package(s) are the source of the bug?

localize

### Is this a regression?

Yes

### Description

After upgrading our project from 12.0.1 to 12.2.12, building process stop with error:
_Localized bundle generation failed: Cannot read property 'includes' of undefined_

I tried to localize bundle separately, with command:
_node_modules/.bin/localize-translate -r dist -s **/*.js -t src/i18n/messages.it.xlf -o translated_

![err-12 2 12](https://user-images.githubusercontent.com/8948699/139659730-1ab2a779-50a8-4fe3-83a4-d02457d2eac6.png)

**Comment by petebacondarwin** [comment]
Hi @manzonif - thanks for reporting this issue.

Can you please post the results of running `ng version` here?
Also can you try removing your `node_modules` directory and reinstalling it? Sometimes the update fails to ensure that all 3rd party libraries get updated correctly.
Finally, if the problem still persists, could you try to find a small reproduction of this problem and share it here so that I can diagnose the problem. (Without this there will be little i can do to help from the current information provided.)

**Comment by manzonif** [comment]
Hi @petebacondarwin . Running ng build -c=production, process stop with
Localized bundle generation failed: Cannot read property 'includes' of undefined.
I have already tried to remove yarn.lock and node_modules directory, without success.

Unfortunately, providing an entire reproduction example is not a trivial task.
However, the error suggests that Babbel is having difficulty parsing graphql fragments.
I can try to corroborate this hypothesis.

**Comment by petebacondarwin** [comment]
> Babel is having difficulty parsing graphql fragments

That would not surprise me. What do such fragments look like in your code?
Are they exposed directly in the JS code?

**Comment by petebacondarwin** [comment]
From looking it [this](https://www.apollographql.com/docs/react/performance/babel/#fragments) it seems that these fragments are tagged template strings,

```
gql`
    fragment HelloStuff on Hello {
      universe
      galaxy
    }
  `
```

similar to how i18n uses `$localize`.

I wonder if there is a bug in the i18n code when it finds a non-`$localize` tagged template handler.

🤔

**Comment by petebacondarwin** [comment]
Although from your original screenshot, it looks like there is a Babel AST Node called `fragment`?
I assume that Babel does not support this out-of-the-box and requires some kind of plugin?

**Comment by manzonif** [comment]
> From looking it [this](https://www.apollographql.com/docs/react/performance/babel/#fragments) it seems that these fragments are tagged template strings,
> 
> ```
> gql`
>     fragment HelloStuff on Hello {
>       universe
>       galaxy
>     }
>   `
> ```
> 
> similar to how i18n uses `$localize`.
> 
> I wonder if there is a bug in the i18n code when it finds a non-`$localize` tagged template handler.
> 
> 🤔

Yes, it is in this form:
`fragment NameParts on Person {
  firstName
  lastName
}`
https://apollo-angular.com/docs/data/fragments/

that after is included with gql stufs.

The build process does not pose any problems with Angular version 12.0.1

Now I'll try to create new repo with some fragment.

**Comment by perotom** [comment]
I got the same error. Our production builds are failing. Seems like we need to revert back to 12.0.1.
ng v:
```
Angular CLI: 12.2.12
Node: 16.3.0 (Unsupported)
Package Manager: npm 7.16.0
OS: darwin x64

Angular: 12.2.12
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, google-maps, language-service, localize, material
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.12
@angular-devkit/build-angular   12.2.12
@angular-devkit/core            12.2.12
@angular-devkit/schematics      12.2.12
@angular/flex-layout            12.0.0-beta.35
@schematics/angular             12.2.12
rxjs                            6.6.7
typescript                      4.3.5
```

**Comment by manzonif** [comment]
Hi @petebacondarwin.
Unfortunately the problem is not caused by graphql fragments. Repro-app works.

Do you have any suggestions?

**Comment by perotom** [comment]
I can confirm it works with 12.2.3.
<details>
  <summary>ng v</summary>
  
  ```
Angular CLI: 12.2.3
Node: 14.17.5
Package Manager: npm 6.14.14
OS: linux x64

Angular: 12.2.3
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, google-maps, language-service, localize, material
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.3
@angular-devkit/build-angular   12.2.3
@angular-devkit/core            12.2.3
@angular-devkit/schematics      12.2.3
@angular/flex-layout            12.0.0-beta.35
@schematics/angular             12.2.3
rxjs                            6.6.7
typescript                      4.3.5
```
</details>

**Comment by manzonif** [comment]
I Can't confirm :(, but I'm not sure about the way I used to update to 12.2.3, which officially doesn't exist ...

Angular CLI: 12.2.3
Node: 14.16.0
Package Manager: yarn 1.22.4
OS: win32 x64

Angular: 12.2.3
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, material
... platform-browser, platform-browser-dynamic, platform-server
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1202.3
@angular-devkit/build-angular     12.2.3
@angular-devkit/build-optimizer   0.1202.12
@angular-devkit/core              12.2.3
@angular-devkit/schematics        12.2.10
@angular/flex-layout              12.0.0-beta.35
@nguniversal/builders             12.1.3
@nguniversal/common               12.1.3
@nguniversal/express-engine       12.1.3
@schematics/angular               12.2.3
rxjs                              7.4.0
typescript                        4.3.5

Now I have:
![err-12 2 3](https://user-images.githubusercontent.com/8948699/139828640-f2019389-01a0-4c38-b373-6c3a5697abe1.png)

**Comment by nylser** [comment]
We have the same issue with our project. 
Currently at:
```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.2.11
Node: 14.18.1
Package Manager: npm 6.14.15
OS: darwin x64

Angular: 12.2.11
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, material
... platform-browser, platform-browser-dynamic, platform-server
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.11
@angular-devkit/build-angular   12.2.12
@angular-devkit/core            12.2.11
@angular-devkit/schematics      12.2.11
@nguniversal/builders           12.1.3
@nguniversal/express-engine     12.1.3
@schematics/angular             12.2.11
rxjs                            6.6.7
typescript                      4.2.4```


Currently, this seems to correlate with some kind of caching. Deleting the `dist`, as well as the `node_modules/.cache` folders seems to fix the "next" build.

**Comment by reifi** [comment]
Same here
```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 12.2.12
Node: 14.17.5
Package Manager: npm 6.14.14
OS: win32 x64

Angular: 12.2.12
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, localize, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.12
@angular-devkit/build-angular   12.2.12
@angular-devkit/core            12.2.12
@angular-devkit/schematics      12.2.12
@schematics/angular             12.2.12
rxjs                            6.6.7
typescript                      4.2.4

```

works when deleting ./node_modules
```
> rimraf node_modules
> npm install
> ng build --localize --base-href / "--configuration=production,feature"
...
Compiling @angular/material/input : es2015 as esm2015
Compiling @angular/material/icon : es2015 as esm2015
Compiling @angular/material/expansion : es2015 as esm2015
✔ Browser application bundle generation complete.
✔ ES5 bundle generation complete.
✔ Localized bundle generation complete.
✔ Copying assets complete.
✔ Index html generation complete.

```

... but when calling it again:

```
> ng build --localize --base-href / "--configuration=production,feature"

✔ Browser application bundle generation complete.
✔ ES5 bundle generation complete.
✖ Localized bundle generation failed.
Cannot read property 'includes' of undefined
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

**Comment by mahdizarei0614** [comment]
I'm getting the same error with `12.2.12`

**Comment by petebacondarwin** [comment]
@nylser , @reifi and @mahdizarei0614 - could one of you provide a reproduction of this problem that I could look at to investigate?

**Comment by mahdizarei0614** [comment]
I solved it. just change `target` in `tsconfig.ts` to `es5`. it will work fine.

**Comment by werner1234** [comment]
Was anyone able to solve this without targeting es5? Since this is more of a hack imo.

**Comment by werner1234** [comment]
Downgrading to v12.1.4 also works

**Comment by meriturva** [comment]
Downgrading to 12.2.11 also worked for me.
Stacked on 12.x due to ionic 5 so I don't know if it is present on Angular 13.x.

@petebacondarwin I could easily share my private repo with you...tell me if necessary, please be sure to fix that also on 12.x release branch.

**Comment by petebacondarwin** [comment]
That would be great @meriturva - please do share.

**Comment by meriturva** [comment]
Hi to all, I was preparing a repo for sending to @petebacondarwin and I found that cleaning `node_modules` folder solves the issue.
ps: that's why on my CI no error at all!

Please remove node modules and try again. It is no more reproducible on my side now.

**Comment by petebacondarwin** [comment]
Hmm... interesting.  Thanks for the update @meriturva

**Comment by nylser** [comment]
> Hi to all, I was preparing a repo for sending to @petebacondarwin and I found that cleaning `node_modules` folder solves the issue.
> ps: that's why on my CI no error at all!
> 
> Please remove node modules and try again. It is no more reproducible on my side now.

I did try that as well (see my answer above), but after re-installing and build one time with localization the problem appeared again. That doesn't happen on your side?

**Comment by Akk3d1s** [comment]
I prepended this command to my build commands in the package.json file. `rm -rf ./node_modules/.cache`. This solved the issue for me.

**Comment by petebacondarwin** [comment]
Since we have not been able to get a reproduction to debug, there is not much we can do to solve this issue.
So I am going to close it for now. Please open a new issue if you are able to make a reproduction that we can look at.

**Comment by ZNS** [comment]
@Akk3d1s  @petebacondarwin I've run into this same issue, running angular 12.2.12 after upgradring from v10. I only had this issue with one of our build configurations though. And it seems that if I remove "sourceMap": false it resolves the issue. If I add it back I get the same issue. Removing the "node_modules/.cache" before build also works.

**Comment by mlauinger** [comment]
Hi, 
I ran into the same problem after upgrading from 11.2.14 to 12.2.13.
After fidling around with the build-configuration it seems like it is working with `"sourceMap": true` and it fails when `"sourceMap": false`.
Also deleting the node_modules-folder would fix it for the first run.

**Comment by jasonhodges** [comment]
I too can confirm what @mlauinger said. Trying to run `ng build --localize --configuration production` caused the error. Switching `"sourceMap": true` under the production config allowed the build to complete without error. 

Angular CLI: 12.2.13
Node: 14.15.3
Package Manager: npm 6.14.9
OS: darwin x64

Angular: 12.2.13
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, localize
... platform-browser, platform-browser-dynamic, router, upgrade

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1202.2
@angular-devkit/build-angular      12.2.13
@angular-devkit/core               12.2.2
@angular-devkit/schematics         12.2.11
@angular/cdk                       12.2.12
@angular/flex-layout               12.0.0-beta.35
@angular/material                  12.2.12
@angular/material-moment-adapter   12.2.12
@schematics/angular                12.2.13
rxjs                               6.6.7
typescript                         4.3.5
webpack                            5.62.1

**Comment by jamiebarrow** [comment]
I also get the error about "Cannot read property 'includes' of undefined". This appears to come from [here](https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/utils/i18n-inlining.ts#L142) in the master branch, though Angular v12.2x seems slightly different, so look [here for that](https://github.com/angular/angular-cli/blob/12.2.x/packages/angular_devkit/build_angular/src/browser/index.ts#L575).

I ran the cli using `node --inspect --inspect-brk` and noticed that the error is coming from @angular-devkit\build-angular\src\utils\process-bundle.js.

I believe it comes from the below code (the source of whichs seems to be [here](https://github.com/angular/angular-cli/blob/12.2.x/packages/angular_devkit/build_angular/src/utils/process-bundle.ts#L501)):
```
const hasLocalizeName = options.code.includes(localizeName);
```

In my case, it seems like `code` is then undefined, so it seems when the inlineActions was built up it didn't have the `code` being set, which means either it was "downlevel" and result.downlevel.content is undefined, or it was "original" and result.original.content is undefined.

I see in the source code there are usages of no-non-null-assertion eslint comments, and an assertion that its defined, but seems like in this case maybe its actually not defined?

```
// eslint-disable-next-line @typescript-eslint/no-non-null-assertion
code: result.original.content!,
```

Hope this helps.
