### ISSUE TITLE
The provided animation trigger "**" has not been registered! Angular 8 Ivy 

### ISSUE THREAD

**Issue by Avadhesh-Patel** [angular/angular#33080]
Animation Declared as per following.

export const LoaderAnimation = [
trigger('loaderInOut', [
transition(':enter', [ // :enter is alias to 'void => '
style({opacity:0}),
animate(500, style({opacity:1}))
]),
transition(':leave', [ // :leave is alias to ' => void'
animate(500, style({opacity:0}))
])
])
]

Animation Used In HTML

.....
When we are enabling Ivy
"angularCompilerOptions": {
"enableIvy": true
},

then we are getting following Error...

vendor.js:69718 ERROR Error: The provided animation trigger "loaderInOut" has not been registered!
at AnimationTransitionNamespace.push../node_modules/@angular/animations/ivy_ngcc/fesm5/browser.js.AnimationTransitionNamespace._getTrigger (vendor.js:3680)
at AnimationTransitionNamespace.push../node_modules/@angular/animations/ivy_ngcc/fesm5/browser.js.AnimationTransitionNamespace.trigger (vendor.js:3687)
at TransitionAnimationEngine.push../node_modules/@angular/animations/ivy_ngcc/fesm5/browser.js.TransitionAnimationEngine.trigger (vendor.js:4105)
at InjectableAnimationEngine.push../node_modules/@angular/animations/ivy_ngcc/fesm5/browser.js.AnimationEngine.process (vendor.js:5112)
at AnimationRenderer.push../node_modules/@angular/platform-browser/ivy_ngcc/fesm5/animations.js.AnimationRenderer.setProperty (vendor.js:154384)
at elementPropertyInternal (vendor.js:73964)
at ɵɵproperty (vendor.js:79032)
at AppComponent_div_1_Template (ng:///AppComponent.js:20)
at executeTemplate (vendor.js:73603)
at renderEmbeddedTemplate (vendor.js:73548)

**Comment by JoostK** [comment]
Hi @Avadhesh-Patel,

could you please test again with `9.0.0-next.10`, I expect this to have been fixed in https://github.com/angular/angular/pull/32818.

**Comment by JoostK** [comment]
I'll go ahead and close this as a duplicate of #32794 which has been fixed in #32818. If you are still experiencing issues after upgrading to 9.0.0-rc.0 or later, please open a new issue. Thanks for testing Ivy and reporting the issues you experienced!
