### ISSUE TITLE
After upgrading from 14 to 15 I get An unhandled exception occurred: Cannot find module 'ajv/dist/compile/codegen'

### ISSUE THREAD

**Issue by air2** [angular/angular#48142]
### Which @angular/* package(s) are the source of the bug?

compiler-cli

### Is this a regression?

Yes

### Description

I upgraded succesfully from 14 to 15, but when I try to do:
> ng serve --port 4400 --host 0.0.0.0 --disable-host-check --hmr

I get:

```
An unhandled exception occurred: Cannot find module 'ajv/dist/compile/codegen'
Require stack:
- C:\nim\nimLicense\app\node_modules\ajv-keywords\dist\definitions\typeof.js
- C:\nim\nimLicense\app\node_modules\ajv-keywords\dist\keywords\typeof.js
- C:\nim\nimLicense\app\node_modules\ajv-keywords\dist\keywords\index.js
- C:\nim\nimLicense\app\node_modules\ajv-keywords\dist\index.js
- C:\nim\nimLicense\app\node_modules\schema-utils\dist\validate.js
- C:\nim\nimLicense\app\node_modules\schema-utils\dist\index.js
- C:\nim\nimLicense\app\node_modules\webpack-dev-server\lib\Server.js
- C:\nim\nimLicense\app\node_modules\@angular-devkit\build-webpack\src\webpack-dev-server\index.js
- C:\nim\nimLicense\app\node_modules\@angular-devkit\build-webpack\src\index.js
- C:\nim\nimLicense\app\node_modules\@angular-devkit\build-angular\src\builders\dev-server\index.js
- C:\nim\nimLicense\app\node_modules\@angular\cli\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- C:\nim\nimLicense\app\node_modules\@angular\cli\node_modules\@angular-devkit\architect\node\index.js
- C:\nim\nimLicense\app\node_modules\@angular\cli\src\command-builder\architect-base-command-module.js
- C:\nim\nimLicense\app\node_modules\@angular\cli\src\command-builder\architect-command-module.js
- C:\nim\nimLicense\app\node_modules\@angular\cli\src\commands\build\cli.js
- C:\nim\nimLicense\app\node_modules\@angular\cli\src\command-builder\command-runner.js
- C:\nim\nimLicense\app\node_modules\@angular\cli\lib\cli\index.js
- C:\nim\nimLicense\app\node_modules\@angular\cli\lib\init.js
See "C:\Users\ABRUIN~2\AppData\Local\Temp\ng-OnQf04\angular-errors.log" for further details.
```

### Please provide the exception or error you saw

```true
An unhandled exception occurred: Cannot find module 'ajv/dist/compile/codegen'
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.0.0
Node: 16.18.0
Package Manager: npm 8.19.2
OS: win32 x64

Angular: 15.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.0
@angular-devkit/build-angular   15.0.0
@angular-devkit/core            15.0.0
@angular-devkit/schematics      15.0.0
@schematics/angular             14.2.10
rxjs                            7.5.7
typescript                      4.8.4
```

### Anything else?

The log file contents:

```
[error] Error: Cannot find module 'ajv/dist/compile/codegen'
Require stack:
- C:\nim\nimLicense\app\node_modules\ajv-keywords\dist\definitions\typeof.js
- C:\nim\nimLicense\app\node_modules\ajv-keywords\dist\keywords\typeof.js
- C:\nim\nimLicense\app\node_modules\ajv-keywords\dist\keywords\index.js
- C:\nim\nimLicense\app\node_modules\ajv-keywords\dist\index.js
- C:\nim\nimLicense\app\node_modules\schema-utils\dist\validate.js
- C:\nim\nimLicense\app\node_modules\schema-utils\dist\index.js
- C:\nim\nimLicense\app\node_modules\webpack-dev-server\lib\Server.js
- C:\nim\nimLicense\app\node_modules\@angular-devkit\build-webpack\src\webpack-dev-server\index.js
- C:\nim\nimLicense\app\node_modules\@angular-devkit\build-webpack\src\index.js
- C:\nim\nimLicense\app\node_modules\@angular-devkit\build-angular\src\builders\dev-server\index.js
- C:\nim\nimLicense\app\node_modules\@angular\cli\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- C:\nim\nimLicense\app\node_modules\@angular\cli\node_modules\@angular-devkit\architect\node\index.js
- C:\nim\nimLicense\app\node_modules\@angular\cli\src\command-builder\architect-base-command-module.js
- C:\nim\nimLicense\app\node_modules\@angular\cli\src\command-builder\architect-command-module.js
- C:\nim\nimLicense\app\node_modules\@angular\cli\src\commands\build\cli.js
- C:\nim\nimLicense\app\node_modules\@angular\cli\src\command-builder\command-runner.js
- C:\nim\nimLicense\app\node_modules\@angular\cli\lib\cli\index.js
- C:\nim\nimLicense\app\node_modules\@angular\cli\lib\init.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
    at Function.Module._load (node:internal/modules/cjs/loader:833:27)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\nim\nimLicense\app\node_modules\ajv-keywords\dist\definitions\typeof.js:3:19)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)

```

When I do 
> npm ls ajv

I get:

```
nim-licenses-app@1.0.3 C:\nim\nimLicense\app
├─┬ @angular-devkit/build-angular@15.0.0
│ ├─┬ babel-loader@9.1.0
│ │ └─┬ schema-utils@4.0.0
│ │   ├─┬ ajv-keywords@5.1.0
│ │   │ └── ajv@6.12.6 deduped invalid: "^8.8.2" from node_modules/ajv-keywords
│ │   └── ajv@8.11.2
│ └─┬ webpack@5.75.0
│   ├─┬ schema-utils@3.1.1
│   │ ├─┬ ajv-keywords@3.5.2
│   │ │ └── ajv@6.12.6 deduped invalid: "^8.8.2" from node_modules/ajv-keywords
│   │ └── ajv@6.12.6 deduped
│   └─┬ terser-webpack-plugin@5.3.6
│     └─┬ schema-utils@3.1.1
│       ├─┬ ajv-keywords@3.5.2
│       │ └── ajv@6.12.6 deduped invalid: "^8.8.2" from node_modules/ajv-keywords
│       └── ajv@6.12.6 deduped invalid: "^8.8.2" from node_modules/ajv-keywords
├─┬ @angular-devkit/core@15.0.0
│ ├─┬ ajv-formats@2.1.1
│ │ └── ajv@8.11.0
│ └── ajv@8.11.0
├─┬ @cypress/schematic@2.3.0
│ ├─┬ @angular-devkit/core@14.2.10
│ │ └── ajv@8.11.0
│ └─┬ @schematics/angular@14.2.10
│   └─┬ @angular-devkit/core@14.2.10
│     └── ajv@8.11.0
└─┬ eslint@8.28.0
  ├─┬ @eslint/eslintrc@1.3.3
  │ └── ajv@6.12.6 deduped
  └── ajv@6.12.6

npm ERR! code ELSPROBLEMS
npm ERR! invalid: ajv@6.12.6 C:\nim\nimLicense\app\node_modules\ajv

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\tmp\nodejs\npm-cache\_logs\2022-11-21T07_13_56_126Z-debug-0.log
```

When I install ajv as dev dependency, the error goes away, but I nowhere in the upgrade guide saw any mention of ajv, so I am wondering if this should be added, or if there is some bug causing this dependency.
