### PR TITLE
feat: add support for TypeScript 4.0

### PR DESCRIPTION
**Pull request by alan-agius4**

### CODE REVIEW

File: packages/compiler-cli/src/ngtsc/annotations/src/metadata.ts [hunk 1]
```diff
@@ -28,7 +28,7 @@ export function generateSetClassMetadataCall(
   if (!reflection.isClass(clazz)) {
     return null;
   }
-  const id = ts.updateIdentifier(reflection.getAdjacentNameOfClass(clazz));
+  const id = reflection.getAdjacentNameOfClass(clazz);
```
Comment (petebacondarwin) [inline packages/compiler-cli/src/ngtsc/annotations/src/metadata.ts:31]: So as I understand it, `identifiers` never have `typeArguments` (i.e. it is always `undefined`)... right?

File: packages/compiler-cli/src/ngtsc/switch/src/switch.ts [hunk 2]
```diff
@@ -110,10 +110,6 @@ function flipIvySwitchesInVariableStatement(
           stmt.getSourceFile().fileName} for the Ivy switch.`);
     }
 
-    // Copy the identifier with updateIdentifier(). This copies the internal information which
-    // allows TS to write a correct reference to the identifier.
-    newIdentifier = ts.updateIdentifier(newIdentifier);
-
```
Comment (petebacondarwin) [inline packages/compiler-cli/src/ngtsc/switch/src/switch.ts:117]: `newIdentifier` can now have a `const` declaration above.

File: packages/compiler-cli/src/ngtsc/annotations/src/metadata.ts (hunk 1 above)
Comment (alan-agius4) [reply packages/compiler-cli/src/ngtsc/annotations/src/metadata.ts:31]: That is correct, at least I cannot find a case were `typeArguments` is defined.

**Comment by alan-agius4** [comment]
Requesting reviews and G3 presubmit before TS 4 is final, to get ahead of time.
TS 4 final should be released tomorrow.

**Comment by kyliau** [comment]
presubmit: 	http://test/OCL:327476254:BASE:327476296:1597862904109:c514d614

File: packages/compiler-cli/src/ngtsc/shims/src/factory_generator.ts [hunk 3]
```diff
@@ -221,7 +219,8 @@ function transformFactorySourceFile(
     // satisfy closure compiler.
     transformedStatements.push(nonEmptyExport);
   }
-  file.statements = ts.createNodeArray(transformedStatements);
+
+  file = ts.updateSourceFileNode(file, transformedStatements);
```
Comment (petebacondarwin) [inline packages/compiler-cli/src/ngtsc/shims/src/factory_generator.ts:223]: Nice!

Comment (petebacondarwin) [reply packages/compiler-cli/src/ngtsc/shims/src/factory_generator.ts:223]: Is `updateSourceFileNode()` a new API?

File: packages/compiler-cli/src/ngtsc/switch/src/switch.ts [hunk 4]
```diff
@@ -105,7 +104,7 @@ function flipIvySwitchesInVariableStatement(
 
     // Find the post-switch variable identifier. If one can't be found, it's an error. This is
     // reported as a thrown error and not a diagnostic as transformers cannot output diagnostics.
-    let newIdentifier = findPostSwitchIdentifier(statements, postSwitchName);
+    const newIdentifier = findPostSwitchIdentifier(statements, postSwitchName);
```
Comment (petebacondarwin) [inline packages/compiler-cli/src/ngtsc/switch/src/switch.ts:107]: How can this be `const`?
The `newIdentifier` variable gets written to below on line 115.

File: packages/core/schematics/utils/tslint/tslint_html_source_file.ts [hunk 5]
```diff
@@ -17,7 +17,7 @@ export function createHtmlSourceFile(filePath: string, content: string): ts.Sour
 
   // Subtract two characters because the string literal quotes are only needed for parsing
   // and are not part of the actual source file.
-  sourceFile.end = sourceFile.end - 2;
+  (sourceFile.end as number) = sourceFile.end - 2;
```
Comment (petebacondarwin) [inline packages/core/schematics/utils/tslint/tslint_html_source_file.ts:20]: OOC - is this because `.end` is not writeable?

File: packages/compiler-cli/src/ngtsc/reflection/src/type_to_value.ts [hunk 6]
```diff
@@ -60,7 +60,7 @@ export function typeToValue(
         kind: TypeValueReferenceKind.LOCAL,
         // Copying the name here ensures the generated references will be correctly transformed
         // along with the import.
-        expression: ts.updateIdentifier(firstDecl.name),
+        expression: firstDecl.name,
```
Comment (JoostK) [inline packages/compiler-cli/src/ngtsc/reflection/src/type_to_value.ts:63]: The comment above has now become a bit outdated ;)

File: packages/compiler-cli/src/ngtsc/switch/src/switch.ts (hunk 4 above)
Comment (JoostK) [reply packages/compiler-cli/src/ngtsc/switch/src/switch.ts:107]: @petebacondarwin that code was deleted :D

File: packages/compiler-cli/src/ngtsc/transform/src/declaration.ts [hunk 7]
```diff
@@ -250,21 +250,10 @@ export class ReturnTypeTransform implements DtsTransform {
...
-        /* questionToken */ element.questionToken);
-
-    // Copy over any modifiers, these cannot be set during the `ts.updateMethodSignature` call.
-    methodSignature.modifiers = element.modifiers;
-
-    // A bug in the TypeScript declaration causes `ts.MethodSignature` not to be assignable to
-    // `ts.ClassElement`. Since `element` was a `ts.MethodSignature` already, transforming it into
-    // this type is actually correct.
-    return methodSignature as unknown as ts.ClassElement;
+    return ts.updateMethod(
```
Comment (JoostK) [inline packages/compiler-cli/src/ngtsc/transform/src/declaration.ts:253]: Do we know if this still works in TS 3.9? This is a .d.ts transform which was a bit wonky in terms of typings incompatibilities, but this change generates a method declaration an not a method signature as would be the case in the .d.ts, so we should definitely make sure that this still works.

File: packages/core/schematics/utils/tslint/tslint_html_source_file.ts (hunk 5 above)
Comment (alan-agius4) [reply packages/core/schematics/utils/tslint/tslint_html_source_file.ts:20]: Yup

File: packages/compiler-cli/src/ngtsc/shims/src/factory_generator.ts (hunk 3 above)
Comment (alan-agius4) [reply packages/compiler-cli/src/ngtsc/shims/src/factory_generator.ts:223]: No, it’s been there for a while.

File: packages/compiler-cli/src/metadata/evaluator.ts [hunk 8]
```diff
@@ -476,13 +476,16 @@ export class Evaluator {
...
         const unionType = <ts.UnionTypeNode>node;
-
         // Remove null and undefined from the list of unions.
-        const references = unionType.types
-                               .filter(
-                                   n => n.kind != ts.SyntaxKind.NullKeyword &&
-                                       n.kind != ts.SyntaxKind.UndefinedKeyword)
-                               .map(n => this.evaluateNode(n));
+        // TODO(alan-agius4): remove `n.kind !== ts.SyntaxKind.NullKeyword` when
+        // TS 3.9 support is dropped. In TS 4.0 NullKeyword is a child of LiteralType.
```
[the remark this answers is not in the document]
Comment (alan-agius4) [reply packages/compiler-cli/src/metadata/evaluator.ts:481]: Will do a follow up

File: packages/compiler-cli/src/ngtsc/transform/src/declaration.ts (hunk 7 above)
Comment (alan-agius4) [reply packages/compiler-cli/src/ngtsc/transform/src/declaration.ts:253]: We should support 3.9, I’ll verify this tomorrow!

File: packages/compiler-cli/src/ngtsc/switch/src/switch.ts (hunk 4 above)
Comment (petebacondarwin) [reply packages/compiler-cli/src/ngtsc/switch/src/switch.ts:107]: LOL! That was my idea!

File: packages/compiler-cli/src/ngtsc/transform/src/declaration.ts [hunk 9]
```diff
@@ -239,32 +239,49 @@ export class ReturnTypeTransform implements DtsTransform {
...
-      return element;
-    }
-
-    const original = ts.getOriginalNode(element) as ts.MethodDeclaration;
-    if (!this.typeReplacements.has(original)) {
-      return element;
+    // // TODO(alan-agius4): Remove when we no longer support TS 3.9
+    // TS < 3.9
+    if (ts.isMethodSignature(element)) {
+      const original = ts.getOriginalNode(element, ts.isMethodDeclaration);
```
Comment (JoostK) [inline packages/compiler-cli/src/ngtsc/transform/src/declaration.ts:245]: I suspect this is currently broken. This has to be:

```suggestion
      const original = ts.getOriginalNode(element, ts.isMethodSignature);
```

but I'm not sure if the resulting type of `ts.MethodSignature` would work, given that we previously casted it to `ts.MethodDeclaration` (and now I'm not even sure if that cast was right).

**Comment by alan-agius4** [comment]
@kyliau I made the changes to be compatible with a TS 3.9 compilation, can you please try to run a presubmit?

File: packages/compiler-cli/src/ngtsc/transform/src/declaration.ts (hunk 7 above)
Comment (alan-agius4) [reply packages/compiler-cli/src/ngtsc/transform/src/declaration.ts]: tested and works

File: packages/compiler-cli/test/transformers/program_spec.ts [hunk 10]
```diff
@@ -492,11 +492,11 @@ describe('ng program', () => {
           .toBe(true);
       switch (checks.shouldBe) {
         case ShouldBe.Empty:
-          expect(writeData!.data).toMatch(/^(\s*\/\*([^*]|\*[^/])*\*\/\s*)?$/);
+          expect(writeData!.data).toMatch(/^(\s*\/\*([^*]|\*[^\/])*\*\/\s*)?$/);
```
Comment (gkalpak) [inline packages/compiler-cli/test/transformers/program_spec.ts:495]: OOC, why this change? It shouldn't be necessary to escape `/` inside `[...]` 😕

**Review by gkalpak — APPROVED** [review]
Commit message typo in **refactor(compiler-cli): remove usage of \`ts.updateIdentifier\`**:
- `unction updateIdentifier` --> `function updateIdentifier`

File: packages/compiler-cli/test/transformers/program_spec.ts (hunk 10 above)
Comment (alan-agius4) [reply packages/compiler-cli/test/transformers/program_spec.ts:495]: Pretty sure it was failing without the escaping.

Comment (gkalpak) [reply packages/compiler-cli/test/transformers/program_spec.ts:495]: I find that hard to believe 😛
(A little escaping didn't hurt anyone (except for readability maybe 😛), so I don't mind either way :smiley:

**Review by mhevery — APPROVED** [review]
reviewed-for: zone-js
reviewed-for: integration-tests

**Comment by kyliau** [comment]
presubmit: 	http://test/OCL:327655792:BASE:327655821:1597945695710:c17113a5

**Comment by kyliau** [comment]
presubmit: 	http://test/OCL:327713907:BASE:327713958:1597964112307:b52bee83

File: packages/compiler-cli/src/ngtsc/shims/src/factory_generator.ts (hunk 3 above)
Comment (kyliau) [reply packages/compiler-cli/src/ngtsc/shims/src/factory_generator.ts:223]: Wow I didn't know this API exists! Always thought source file is immutable and a clone is necessary when modifying a source.

**Review by kyliau — APPROVED** [review]

**Comment by kyliau** [comment]
g3 presubmit is green!!

**Review by crisbeto — APPROVED** [review]
LGTM

**Review by atscott — CHANGES_REQUESTED** [review]
reviewed-for: fw-router

**Review by atscott — APPROVED** [review]

**Review by jelbourn — APPROVED** [review]
LGTM

**Review by JoostK — APPROVED** [review]

**Review by petebacondarwin — APPROVED** [review]
Reviewed-for: public-api

**Review by jelbourn — APPROVED** [review]
LGTM

Reviewed-for: public-api

**Review by AndrewKushnir — APPROVED** [review]
Reviewed-for: public-api

**Comment by alan-agius4** [comment]
Caretaker: angular robot is reporting pending pullapprove status even though everyone approved.

**Comment by KapilSachdev** [comment]
It seems 0fc44e0 added `TS 4.0` support to `10.1` and i'm assuming it works fine, but i'm getting the below issue while `ng build --prod`

```js
ERROR in src/app/some/some.component.ts:26:81 - error TS2729: Property 'some_id' is used before its initialization.

26   public data: any = {some_id: this?.some_id, date: new Date()};
                                                                                   ~~~~~~~~~~~~~~~

  src/app/some/some.component.ts:22:12
    22   @Input() some_id
                  ~~~~~~~~~~~~~~~
    'some_id' is declared here.
```

As it is evident, the variable is defined before its being used.
Also it works fine with `3.9`.
_I'm not sure if `TS 4.0` introduced something that could cause this issue, but i think its `ng` so just wanted to confirm. I tried to look into issue tracker for similar reports, though not that deeply, but didn't found any._

**Comment by fxck** [comment]
> Property 'serviceStackId$' is used before its initialization.ts(2729)

image

happens only with TS 4
