### ISSUE TITLE
using ngc instead of tsc, getting TypeError: Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by born2net** [angular/angular#13737]
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Running tsc with my lib works fine,but I am trying to move to ngc as I understand it does a better tranplation job.

the error is:
```
root@DESKTOP-VEUHFOL /cygdrive/c/msweb/ng-mslib
$ ./node_modules/.bin/ngc -p ./tsconfig.json
TypeError: Cannot read property 'text' of undefined
    at NodeObject.getText (C:\msweb\ng-mslib\node_modules\typescript\lib\typescript.js:78080:30)
    at Evaluator.evaluateNode (C:\msweb\ng-mslib\node_modules\@angular\compiler-cli\node_modules\@angular\tsc-wrapped\src\evaluator.js:512:66)
    at _loop_1 (C:\msweb\ng-mslib\node_modules\@angular\compiler-cli\node_modules\@angular\tsc-wrapped\src\collector.js:351:54)
    at C:\msweb\ng-mslib\node_modules\@angular\compiler-cli\node_modules\@angular\tsc-wrapped\src\collector.js:410:25
    at visitEachNode (C:\msweb\ng-mslib\node_modules\typescript\lib\typescript.js:13907:30)
    at Object.forEachChild (C:\msweb\ng-mslib\node_modules\typescript\lib\typescript.js:14078:24)
    at MetadataCollector.getMetadata (C:\msweb\ng-mslib\node_modules\@angular\compiler-cli\node_modules\@angular\tsc-wrapped\src\collector.js:233:12)
    at MetadataWriterHost.writeMetadata (C:\msweb\ng-mslib\node_modules\@angular\compiler-cli\node_modules\@angular\tsc-wrapped\src\compiler_host.js:151:51)
    at MetadataWriterHost.writeFile (C:\msweb\ng-mslib\node_modules\@angular\compiler-cli\node_modules\@angular\tsc-wrapped\src\compiler_host.js:143:19)
    at Object.writeFile (C:\msweb\ng-mslib\node_modules\typescript\lib\typescript.js:62522:132)
Compilation failed
```

but again no issues with tsc

the tsconfig is:

```
{
  "compilerOptions": {
    "baseUrl": "",
    "declaration": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "strictNullChecks": false,
    "noImplicitAny": false,
    "lib": ["es2015", "dom"],
    "mapRoot": "./",
    "module": "es2015",
    "moduleResolution": "node",
    "outDir": "dist",
    "sourceMap": true,
    "target": "es5",
    "skipLibCheck": true,
    "paths": {
      "@angular/core": ["node_modules/@angular/core"],
      "rxjs/*": ["node_modules/rxjs/*"]
    },
    "typeRoots": [
      "../node_modules/@types"
    ]
  },
  "angularCompilerOptions": {
    "strictMetadataEmit": true
  }
}

```

**Expected behavior**
I expect ngc to pass, if tsc does

**Minimal reproduction of the problem with instructions**
this is the project:
https://github.com/born2net/ng-mslib
just run tsc and ngc

**What is the motivation / use case for changing the behavior?**
would like to move to ngc from tsc to compile my general npm libs

**Please tell us about your environment:**
Windows 10 x64 latest ts 2.1 and ng 2.4.1

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

* **Node (for AoT issues):** `node --version` =   
v6.5.0

regards

Sean

**Comment by mattlewis92** [comment]
ngc doesn't work with typescript 2.1 yet: https://github.com/angular/angular/issues/13715 - try downgrading to ~2.0.10 😃

**Comment by born2net** [comment]
tx! trying...

**Comment by born2net** [comment]
PERFECT!
tx
