### PR TITLE
Revert "feat(compiler): add support for the `typeof` keyword in template expressions. (#58183)"

### PR DESCRIPTION
**Pull request by devversion**
This reverts commit 0c9d721ac157662b2602cf0278ba4b79325f6882. This breaks CI jobs in `main`, and sync into google3. PR was green and presubmit too; so I'm suspecting some rebase conflicts with other changes being merged at the same time.

### CODE REVIEW

**Review by crisbeto — APPROVED** [review]

**Review by crisbeto — CHANGES_REQUESTED** [review]
I think it'll be easier to just fix the compilation error. I'm sending a PR now.

**Comment by devversion** [comment]
👍 sgtm as well
