### ISSUE TITLE
Support different tsconfig setting for projects and libs

### ISSUE THREAD

**Issue by PengyuApp** [angular/angular#45754]
### Which @angular/* package(s) are relevant/related to the feature request?

compiler

### Description

I'm trying to build an angular ui library to share components inside my workspace.
Due to legacy issue,  I need to use a different tsconfig for this particular lib. 
For example, set `strictPropertyInitialization: false` in the ui lib. 
However I do want my main app remains `strictPropertyInitialization: true`.

I find that if I use `ng serve` to run my app, I'll get compilation error because of the ui lib didn't pass the check.

Seems like `ng serve` is always using the tsconfig from root project and not switching to lib's tsconfig while compiling the lib codes.

### Proposed solution

Support different tsconfig settings.

### Alternatives considered

We can always make the `library` a buildable one. Build it 1st, and then consume it.
But it can be cumbersome

**Comment by JoostK** [comment]
> We can always make the library a buildable one. Build it 1st, and then consume it.
But it can be cumbersome

This sounds like you're using Nx, not the CLI. Buildable libraries in NX are actually the only correct approach to accomplish this, as otherwise the library's source files are just compiled as part of the app's compilation unit, using the app's tsconfig. The CLI requires that libraries are compiled on their own, and each library configuration has a dedicated tsconfig that it uses.

**Comment by JoostK** [comment]
Closing as no follow-up response was received.
