### ISSUE TITLE
Unexpected interaction with window.global and subsequent run-time errors

### ISSUE THREAD

**Issue by mpjc** [angular/angular#28705]
# 🐞 bug report

### Affected Package
Any app created with recent versions of @angular/cli. 
No additional code required beyond adding a single variable.

### Is this a regression?
Some related, unexpected behaviour in older versions, with app-breaking run-time errors in more recent versions (e.g. v7.2.0).

### Description
The core framework appears to have a buggy interaction with `window.global`.

If this variable exists during local development (`ng serve`), the app cannot bootstrap and an exception is thrown (see below).

**More significantly**, if this variable exists for production builds (`ng build --prod`), the application bootstraps successfully, but `window.global` has a number of Angular specific artefacts added to it, such as `window.global.frameworkStabilizers` and `window.global.getAngularTestability`.

In a more complex app, this interaction also results in unpredictable and obscure run-time errors within Angular itself.
E.g.: `NgForOf`-> `NgDoCheck` -> `Diff` ->  `_Renderer[...] is not a function`.
Removing the initial `window.global` value prevents these errors with no other code changes.
I do not have a minimal reproduction for these run-time errors.

Unfortunately, a legacy dependency in my code-base also interacts with `window.global` and as such does not play nicely with Angular, particularly after upgrading from 6 to 7 due to these errors.

Should Angular really own `window.global`?

## 🔬 Minimal Reproduction
Create new application
```
ng new windowGlobal
cd windowGlobal
npm install
```
Update `src/index.html` from:
```
<body>
  <app-root></app-root>
</body>
```
To:
```
<body>
  <app-root></app-root>
  <script>
     window.global = {};
  </script>
</body>
```
Build
```
ng build --prod
```
Serve
```
http-server ./dist/windowGlobal/
```

## 🔥 Exception or Error
Exception when debugging under `ng serve`:
<pre><code>Uncaught Error: Can't resolve all parameters for ApplicationModule: (?).
    at syntaxError (compiler.js:2426)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getDependenciesMetadata (compiler.js:18979)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getTypeMetadata (compiler.js:18872)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata (compiler.js:18740)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleSummary (compiler.js:18550)
    at compiler.js:18664
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata (compiler.js:18652)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleSummary (compiler.js:18550)
    at compiler.js:18637
</code></pre>

## 🌍  Your Environment
**Angular Version:**
<pre><code>@angular/cli@7.3.1
</code></pre>

**Comment by trotyl** [comment]
Seems you're also making contributions to [not making `global` adopted by spec](https://github.com/tc39/proposal-global/issues/20). Please also note you app may also break with other old UMD libraries which are breaking other sites.

Anyway for the sake of these sites the proposal has changed to `globalThis` and has been respected by Angular in https://github.com/angular/angular/pull/28679. Once released you can make sure `globalThis` available (either by VM or polyfill) in the environment.

**Comment by alxhub** [comment]
@trotyl has the right idea, here. `globalThis` is the right answer.
