### PR TITLE
fix(forms): ignore non-index names in FormArray control lookups

### LINKED ISSUE #49077: Mixing FormControl and FormArray in FormGroup throws `control.setValidators is not a function`
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

Yes

### Description

When creating FormGroups dynamically and adding the to a FormGroup which has `FormControl` in it, the error is thrown.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ujiq1x

### Please provide the exception or error you saw

```true
Please see this - [https://stackoverflow.com/q/75461339/2896495](https://stackoverflow.com/q/75461339/2896495)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.1.5
Node: 18.13.0
Package Manager: npm 9.4.2
OS: win32 x64

Angular: 15.1.4
... animations, cdk, common, compiler, compiler-cli, core, forms
... localize, material, platform-browser
... platform-browser-dynamic, router
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by GabeSilvaDev**
## PR Checklist

* [x] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/contributing-docs/commit-message-guidelines.md
* [x] Tests for the changes have been added (for bug fixes / features)
* [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

* [x] Bugfix

## What is the current behavior?

Fixes #49077

`FormArray` currently reads path segments directly from its `controls` array. This means `array.get('filter')` can resolve to `Array.prototype.filter`, while `array.get('length')` returns the array length.

When a `formControlName` is placed directly under `formArrayName`, as in the issue, the directive can receive that function instead of a control and fail with:

```text
TypeError: control.setValidators is not a function
```

instead of reporting that the control couldn't be found.

## What is the new behavior?

Names that aren't control indexes return `null`, so the template case from the issue now reports:

```text
Cannot find control with path: 'products -> filter'
```

Normal numeric paths such as `'items.0'` still work, and the existing negative index behavior from `get([-1])` is preserved.

The check reuses `hasOwnControl` introduced in #69060 for `FormGroup`. For `FormArray`, `length` also needs to be excluded because it's an own property of the array but isn't a control index.

## Does this PR introduce a breaking change?

* [x] No

## Other information

Added `FormArray.get` cases in `form_array_spec.ts` and a `FormArrayName` regression case in `directives_spec.ts`.

`//packages/forms/test:test` and the forms bundling `symbol_test` targets pass locally.

### CODE REVIEW

**Review by atscott — COMMENTED** [review]
AGENT: Thanks for putting this together! After reviewing the trade-offs, we're going to pass on merging this change and close #49077.

Traditional `@angular/forms` (`FormGroup` / `FormArray`) is largely in maintenance mode as we focus on Signal Forms, and we are very cautious about modifying core control lookup paths (`FormArray._find` and `hasOwnControl`, which also runs on every `FormGroup` operation in production) due to the risk of unintended breaking changes (e.g., bypassing `FormArray.prototype.at()` overrides). Since the underlying issue (#49077) has 0 upvotes and only affects which error message is thrown when a template has an invalid control path under `formArrayName`, the risk and runtime cost outweigh the benefit here.
