### ISSUE TITLE
Inputs are not inherited when Ivy is enabled

### ISSUE THREAD

**Issue by kemsky** [angular/angular#30080]
# 🐞 bug report

### Is this a regression?

No

### Description
We build our app with ngc and closure compiler. After enabling Ivy ngc fails almost immediately. Could not find any instructions for this case.

## 🔬 Minimal Reproduction
```
        import {platformBrowser} from '@angular/platform-browser';
        import {AppModuleNgFactory} from './application.module.ngfactory';

        platformBrowser()
            .bootstrapModuleFactory(AppModuleNgFactory)
            .catch(e => console.error('Application bootstrap failed', e));
```
## 🔥 Exception or Error
<pre><code>
[11:51:23] Spa_Source/main.aot.ts:7:34 - error TS2307: Cannot find module './application.module.ngfactory'.

7 import {AppModuleNgFactory} from './application.module.ngfactory';
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
8.0.0-beta.14
</code></pre>

**Comment by alan-agius4** [comment]
Hi, `ngfactory` are only created when using NGC, Ivy uses a different compiler (NGTSC) which doesn't generate factories.

Which means you need to remove the factory references. 
Ie from
```ts
import {platformBrowser} from '@angular/platform-browser';
import {AppModuleNgFactory} from './application.module.ngfactory';

platformBrowser()
    .bootstrapModuleFactory(AppModuleNgFactory)
    .catch(e => console.error('Application bootstrap failed', e));
```

to
```ts
import {platformBrowser} from '@angular/platform-browser';
import {AppModule} from './application.module';

platformBrowser()
    .bootstrapModule(AppModule)
    .catch(e => console.error('Application bootstrap failed', e));
```

Alternatively you can enable factory shims by adding `"allowEmptyCodegenFiles": true` under `angularCompilerOptions` in your `tsconfig.json`. However it's wotth mentioning that the later is not recommended.

**Comment by kemsky** [comment]
@alan-agius4, thanks for information. I've tried recommended approach, but still no success:

```
node_modules/@angular/platform-browser/platform-browser.d.ts:42:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class

42 export declare class BrowserModule {
                        ~~~~~~~~~~~~~
node_modules/@angular/forms/forms.d.ts:2667:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class

2667 export declare class FormsModule {
                          ~~~~~~~~~~~
node_modules/@angular/router/router.d.ts:2403:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class

2403 export declare class RouterModule {
                          ~~~~~~~~~~~~
node_modules/@angular/router/router.d.ts:2403:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class

2403 export declare class RouterModule {
                          ~~~~~~~~~~~~
```

**Comment by JoostK** [comment]
@kemsky From that error I can tell that ngcc has not processed those libraries. Are you using latest Angular CLI to build your application?

**Comment by Petronious** [comment]
@kemsky did you added ivy-ngcc in postinstall steps of package.json?

```
"scripts": {
    "postinstall": "ivy-ngcc",
    ...
```

**Comment by kemsky** [comment]
@Petronious,  Yep, it was my fault, I did not invoke `ivy-ngcc`. There are a couple of problems with Ivy though.

- If you disable Ivy and try to build as usual with regular `ngc` - it fails and you have to remove node_modules and install again.

- I received a lot of strange compiler errors:
```
__ng_typecheck__.ts:13549:11 - error TS2339: Property 'caption' does not exist on type 'HTMLDivElement'.

13549     _t132.caption = "Defendant 4 Is Covered: ";
```

Corresponding template:
```html
<div class="input" [caption]="'Defendant 4 Is Covered: '" name="defendant4IsCovered" type="checkbox" [(ngModel)]="item.defendant4IsCovered"></div>
```
Code:
```typescript
export abstract class AbstractFormComponent<T extends HTMLElement> extends AbstractComponent implements ControlValueAccessor, IFocusContainer {
   ...
    @Input('caption')
    public label:string;
...
}
```
Looks like alias is ignored...

Also I'd like to know is ivy-ngcc documented anywhere? I need to skip processing of certain modules.

**Comment by Petronious** [comment]
Strange, Ivy is supposed to support extends on @Component : https://is-angular-ivy-ready.firebaseapp.com/#/status

Guess you'll have to add @Input('caption') in the concrete classes meanwhile...

**Comment by kemsky** [comment]
@JoostK @alan-agius4 what do you think?

**Comment by alan-agius4** [comment]
NGCC is integrated as part of @ngtools/webpack which is used in the Angular CLI.

Unless you have a custom build system and not using any of the above, you need to run NGCC as a post install hook.

If opting out of ivy is not working, ie a build which used to work is no longer working, we’d need to take a look at it.

Which version of the framework are you using?

**Comment by JoostK** [comment]
> * If you disable Ivy and try to build as usual with regular `ngc` - it fails and you have to remove node_modules and install again.

As part of running ngcc, existing code in `node_modules` is AOT compiled into Ivy instructions. If you run ngcc using its executable `ivy-ngcc` then this step overwrites library files in-place, with a backup file suffixed with `.bak` being produced as well. Besides the generation of Ivy code, the original Angular decorators such as `@Component` and `@Input` etc. are removed from the code, as Ivy conveys such metadata in a different, tree-shakeable way. Therefore, the `node_modules` directory has then been modified in a way that it can no longer be used when disabling Ivy, as vital information is no longer present in the library files.

The same is not true when using the Angular CLI, as its execution of ngcc under the covers will use a different approach that does not suffer from the same problem: instead of overwriting files in-place, a dedicated `__ivy_ngcc__` subdirectory is created in each library that gets compiled for Ivy. The CLI will then redirect Webpack to use the sources from the subdirectory, instead of the non-Ivy code originally shipped to NPM. Hence, this way disabling Ivy should not see the need to reinstall `node_modules`.

> * I received a lot of strange compiler errors:
> 
> ```
> __ng_typecheck__.ts:13549:11 - error TS2339: Property 'caption' does not exist on type 'HTMLDivElement'.
> 
> 13549     _t132.caption = "Defendant 4 Is Covered: ";
> ```
> Corresponding template:
> 
> ```
> <div class="input" [caption]="'Defendant 4 Is Covered: '" name="defendant4IsCovered" type="checkbox" [(ngModel)]="item.defendant4IsCovered"></div>
> ```
> 
> Code:
> 
> ```ts
> export abstract class AbstractFormComponent<T extends HTMLElement> extends AbstractComponent implements ControlValueAccessor, IFocusContainer {
>    ...
>     @Input('caption')
>     public label:string;
> ...
> }
> ```
> 
> Looks like alias is ignored...

Thanks for sharing this! The type checking of Angular template code has been completely redesigned to be far more extensive than the type checking that was done previously. It should be able to catch many more bugs that were previously not discovered. In this case however, I don't have enough insight to see if this is a false-positive in the new type-checker, of if there's legitimately reason to believe there's a type error somewhere.

By the looks of it, a concrete directive/component of `AbstractFormComponent` could not be matched (leaving the property left-over for the `div` element) *or* it could not be statically determined that the parent class of the matched directive/component is `AbstractFormComponent`, which also *currently* results in applying the property to the `div` element.

If you think neither of the above is the case, there may indeed be buggy behavior with either class hierarchies (which _should_ be supported *iff* the class hierarchy can be statically determined) *or* with the aliased input (which _should_ also be taken into account already).

Would you be able to provide a minimal reproduction of this issue, so that we can look into what is causing it?

> 
> Also I'd like to know is ivy-ngcc documented anywhere? I need to skip processing of certain modules.

It doesn't currently have a lot of documentation. May I ask, why do you need to skip processing of certain libraries? Are they Angular libraries that are processed but you think they shouldn't?

**Comment by kemsky** [comment]
@JoostK , I've tried removing input aliases and it did not help, then I tried copy-paste inputs to the inherited classes - it worked, so I'm 100% sure that inputs are not properly inherited (there are no typescript errors, tsconfig is pretty strict). Without it I can not continue testing, because inheritance is used heavily in our application. Creating reproduction on stackblitz may take some time.

See hierarchy screenshot, all parent classes are abstract:
![image](https://user-images.githubusercontent.com/3826972/56883796-6848e580-6a70-11e9-8b65-1986427c0892.png)


Another problem with hyphens, it will not compile:
```typescript
@Input('some-property')
public hello:string;
```

I want to skip processing of certain unused libraries, to minimize build times on CI.

**Comment by LickIt** [comment]
I have created a minimal application for the issue since we are hitting it too:
[https://github.com/LickIt/test-ivy](https://github.com/LickIt/test-ivy)

When you try to do `ng build --aot` you get the following error:
> ERROR in __ng_typecheck__.ts(7,9): error TS2339: Property 'test' does not exist on type 'HTMLElement'.

The problem is that `@Input` properties are not inherited.

```ts
import { Component, Input } from '@angular/core';

abstract class BaseComponent {
    @Input()
    public test: string;
}

@Component({
    selector: 'app-test',
    template: `title: {{ test }}`
})
export class TestComponent extends BaseComponent {}

@Component({
  selector: 'app-root',
  template: `<app-test [test]="title"></app-test>`,
  styles: []
})
export class AppComponent {
  title = 'test-ivy';
}
```

**Comment by alexzuza** [comment]
@LickIt Can you please try to add `TestComponent` to `declarations` array of AppModule?

**Comment by LickIt** [comment]
> @LickIt Can you please try to add `TestComponent` to `declarations` array of AppModule?

Yes, sorry about that. I updated the git repo.
The error is still the same though.

**Comment by alexzuza** [comment]
@LickIt Weird, it works for me
https://ivy.ng-run.com/github/LickIt/test-ivy?open=src%2Fapp%2Ftest.component.ts
But in the demo I use Angular 8.1.0-beta.0

**Comment by denisaangelov** [comment]
You're not using Ivy at all.

**Comment by alexzuza** [comment]
> You're not using Ivy at all. That's why it's working.

@denisaangelov Just wonder how did you know that? Actually I do use Ivy there. The only difference I can only see is that it's Ivy jit mode.

**Comment by JoostK** [comment]
@LickIt @alexzuza @denisaangelov For more details on why this fails please see https://github.com/angular/angular/issues/30754#issuecomment-497456208. TLDR: base classes without `@Component`/`@Directive` decorator fail.

In JIT mode, no template type checking is done, so this error won't occur then.

**Comment by alexzuza** [comment]
@JoostK Thank you again for your valuable input.

> @denisaangelov Just wonder how did you know that?

@denisaangelov I'm still waiting... Can you please be more constructive with your answer?

**Comment by LickIt** [comment]
@JoostK thanks for your explanation, however using JIT is not really practical outside development environments.

I just dropped an example minimal application to help with testing the issue since the last comment in the thread was a request for such an example.

Is defining the base class as a component a possible workaround until this is resolved?

**Comment by JoostK** [comment]
@LickIt sorry I did not mean to suggest turning off JIT as a workaround, it was a response to @alexzuza's comment regarding JIT mode.

All the base class needs as a workaround is the `@Directive` annotation with some random selector. It's not ideal but will allow the usage of template type checking. The template type checking can be disabled in full, by setting two Angular Compiler options in `tsconfig.app.json`:

```
{
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": false,
    "ivyTemplateTypeCheck": false,
  }
}
```

**Disclaimer: the latter option is internal and will disappear**, but given this is intended as workaround it may be helpful.

**Comment by vultix** [comment]
This issue doesn't just affect @Inputs, but also @Output, @ViewChild, @ViewChildren, @ContentChild, @ContentChildren

**Comment by kumaresan-subramani** [comment]
@JoostK , your workaround is not working my case.

https://github.com/angular/angular/issues/30818

**Comment by fxck** [comment]
Same problem here.

```typescript
class FormBase {
  @Input()
  formState: FormGroup;
}

@Component({
  selector: my-form',
  templateUrl: './my-form.component.html'
})
class MyFormComponent extends FormBase { }
```

```
<my-form [state]="state"></my-form>
```

results in 

> Property 'state' does not exist on type 'HTMLElement'.

**Comment by kumaresan-subramani** [comment]
I thought you could you like this

<my-form **state**="state"></my-form>

I have faced this kind of issue once, i removed [] because we dont have to use this for property declaration.

i think so

**Comment by fxck** [comment]
That would pass it a string `"state"`, instead of the desired `FormGroup`.

**Comment by JoostK** [comment]
@fxck It's not working because `FormBase` does not have an Angular decorator like `@Component` or `@Directive` of its own, only an `@Input` decorator. Currently in Ivy, a class like `FormBase` is treated specially as something known as a _base def_. Such definitions are not taken into account in the template type checker, hence it doesn't work.

Going forward, the notion of such _base defs_ will disappear, and an `@Directive` decorator becomes required for any class that has Angular behavior such as `@Input`s. This is currently a work-in-progress effort, with #31379 being a prerequisite for this approach to become viable. Please bear with us while this is being worked on.

**Comment by fxck** [comment]
> an @Directive decorator becomes required for any class that has Angular behavior such as @Inputs.

Wouldn't this be a breaking change? Also having to define at least a selector, for something that clearly won't ever be used as a directive, wouldn't some new decorator be a better? Also will it be required to import a module that declares this directive in order to be able to extends from this directive? And extending a component with a directive class wont break anything?

**Comment by JoostK** [comment]
> Wouldn't this be a breaking change?

Yes, it would be. There will be schematics to perform such migration automatically and tooling that aid in backwards compatibility, like ngcc, will also have logic to allow existing code to keep working.

> Also will it be required to import a module that declares this directive in order to be able to extend from this directive?

Nope, it will not. The exact details on this will be documented as it is implemented.

> And extending a component with a directive class wont break anything?

The base class has to be decorated with `@Directive`, not `@Component`. Extending from a `@Directive` is already possible.

**Comment by fr0** [comment]
> @fxck It's not working because `FormBase` does not have an Angular decorator like `@Component` or `@Directive` of its own, only an `@Input` decorator. Currently in Ivy, a class like `FormBase` is treated specially as something known as a _base def_. Such definitions are not taken into account in the template type checker, hence it doesn't work.
> 
> Going forward, the notion of such _base defs_ will disappear, and an `@Directive` decorator becomes required for any class that has Angular behavior such as `@Input`s. This is currently a work-in-progress effort, with #31379 being a prerequisite for this approach to become viable.

I am confused because this works just fine when Ivy is disabled? So should we technically be adding `@Directive` to our component base classes even when _not_ using Ivy?

> Please bear with us while this is being worked on.

Completely understood. However, I am very slightly nervous because there is already a prerelease for 9.0.0 and issues like this convince me that Ivy is still a ways from being ready.

**Comment by fxck** [comment]
> that Ivy is still a ways from being ready.

Then again.. it is, they still got months before the planned release.

I also wish I was able to start testing it out at this point, but what can you do.

**Comment by pitAlex** [comment]
For angular 8.2.2, adding ``@Directive`` to the base class is still producing this error where ``@Input`` is not inherited. I've noticed that it won't fail if you do something like this ``@Input('name') other_name ...``.

**Comment by fxck** [comment]
It still doesn't work in next.5 fyi.

**Comment by dannyskoog** [comment]
I can confirm the same thing as @fxck stated

**Comment by ADudar** [comment]
also confirm @fxck

**Comment by Svetomechc** [comment]
Is there a working workaround?

**Comment by vladimiry** [comment]
@Svetomechc has  been mentioned before, but it's the ugly one:

```
{
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": false,
    "ivyTemplateTypeCheck": false,
  }
}```

**Comment by Svetomechc** [comment]
@vladimiry yeah it sure is :(

**Comment by JoostK** [comment]
An alternative would now be to annotate the base class with `@Directive()`. It's possible since a short while in the preview releases to omit the options object that's usually passed to `@Directive()`, i.e. a selector is but required any longer.

**Comment by fxck** [comment]
> An alternative would now be to annotate the base class with @Directive(). 

It still doesn't work. It doesn't inherit even from annotated classes.

**Comment by vladimiry** [comment]
I confirm putting `@Directive({})` on abstract/base component doesn't help, just tried it with the most recent v8.2.7 and v9.0.0-next.7 versions.

First of all, the v8.2.7 throws `ERROR in Directive SomeAbstractComponent has no selector, please add it!` error if compile a directive without selector `@Directive({})`. So @angular/core@8.2.7 allows selector-less directives but @angular/compiler@8.2.7 doesn't as it still includes the following check:
```
  if (!meta.selector) {
    throw new Error(`Directive ${meta.name} has no selector, please add it!`);
  }
```

I got the code with `@Directive({})` put on abstract component compiled with v9.0.0-next.7 as @angular/compiler got rid of `meta.selector` check since v9.0.0-next.3. But if I enable the `fullTemplateTypeCheck: true` + `ivyTemplateTypeCheck: true` compiler options I still get the following error: `TS8002:  'someProp' is not a valid property of <some-component>`.

PS enabling `allowEmptyCodegenFiles: true` also doesn't help.

**Comment by Splaktar** [comment]
> @Svetomechc has been mentioned before, but it's the ugly one:
>```json {
>  "angularCompilerOptions": {
>    "fullTemplateTypeCheck": false,
>    "ivyTemplateTypeCheck": false,
>  }
>}
>```
@vladimiry I tried this in a [demo repo](https://github.com/Splaktar/mat-tabs-demo/blob/2c5b4604793da0348ebadd1a9313ce39c9a3aa62/tsconfig.json#L22-L25) and it didn't workaround the issue.

**Comment by Splaktar** [comment]
We're seeing this in Angular Material as well: https://github.com/angular/components/issues/17121

@JoostK if this is the issue for tracking the fact that `ivy-ngcc` can't handle `@Input`s from a base class (as you mentioned in https://github.com/angular/components/issues/17121#issuecomment-536281310), can we please update the issue title to more clearly indicate this?

Can we also please add the https://github.com/angular/angular/labels/hotlist%3A%20components%20team label?

**Comment by vladimiry** [comment]
@Splaktar I use the workaround [directly with AngularCompilerPlugin](https://github.com/vladimiry/ElectronMail/blob/188eeb89503ed264f9f4eea50446776819711fb4/webpack-configs/web/browser-window.ts#L73-L74) and it's functional, ie Angular CLI is not used in this project.

In your case, you have `angularCompilerOptions` defined in both `tsconfig.json` and `tsconfig.app.json` files and I guess it might not be properly inherited from `tsconfig.json`. So you could try to put flags directly to `tsconfig.app.json`.

**Comment by Splaktar** [comment]
@vladimiry that's a good idea, unfortunately, it [didn't work for me](https://github.com/Splaktar/mat-tabs-demo/blob/cc7d0f771bf49d62da6dda2f960ff0e64f0a96f6/tsconfig.app.json#L7-L11). I still get both failures:
```ts
src/app/lib/tabs/tabs.component.ts(25,24): Property 'selectedIndex' does not exist on type 'HTMLElement'.
src/app/lib/tabs/tabs.component.ts(25,64): Property 'dynamicHeight' does not exist on type 'HTMLElement'.
```
Or with `9.0.0-next.8`:
```ts
error TS8002: 'selectedIndex' is not a valid property of <mat-tab-group>.
error TS8002: 'dynamicHeight' is not a valid property of <mat-tab-group>.
```

**Comment by vladimiry** [comment]
Only one template-type-checking flag is disabled [here](https://github.com/Splaktar/mat-tabs-demo/blob/cc7d0f771bf49d62da6dda2f960ff0e64f0a96f6/tsconfig.app.json#L7-L11), I guess maybe disabling both will do the trick:
```
    "fullTemplateTypeCheck": false,
    "ivyTemplateTypeCheck": false,
```

**Comment by dannyskoog** [comment]
@Splaktar Have you checked that the base class of `MatTabGroupComponent` uses the `@Directive` decorator in the `@angular/material` package?

**Comment by Splaktar** [comment]
@vladimiry doh! Sorry it's too early in the morning for me and I wasn't reading carefully enough. That worked! Thank you.

**Comment by Splaktar** [comment]
@dannyskoog it does not.

**Comment by dannyskoog** [comment]
Alright @Splaktar. And I guess it doesn’t matter now that you got it working :)

**Comment by Splaktar** [comment]
@dannyskoog I just verified that workaround. We are still going to need to fix this in Angular Material. I'll look into adding `@Directive('fake-selector')` since we can't use empty selectors w/o breaking our Angular version 8.x users (as it only works in `9.0.0-next.3+`).

**Comment by dannyskoog** [comment]
Yeah @Splaktar. That was what I was trying to get to in the first place :)

Cool. That sounds great!

**Comment by sharikovvladislav** [comment]
@JoostK 

> Going forward, the notion of such base defs will disappear, and an @Directive decorator becomes required for any class that has Angular behavior such as @Inputs.

What about abstract classes of directives/components?

If we add the decorator like Component/Directive, we have to add that entity to the declarations array of some module. We are not able to add abstract class to the declarations array, since constructor of the abstract class can not be executed. We will get following error:

> Cannot assign an abstract constructor type to a non-abstract constructor type.

How this case will be handled when you force Directive on any class with properties decorated via `Input`?

**Comment by JoostK** [comment]
@sharathgeorgem The rules for an `@Directive()` without selector are a little different to regular directives. Concretely, they are required *not* to be present in an the `declarations` array of an NgModule.

**Comment by kemsky** [comment]
well, all this stuff with `@Directive()` this is completely confusing.

**Comment by vladimiry** [comment]
@JoostK is not putting `@Directive()` on parent class a temporary workaround (not working for me anyway)? I don't want to believe it's going to be a final solution, would prefer it to be at least re-named to something like @ParentClass() so it's not confusing and serves a single need.

**Comment by kara** [comment]
> well, all this stuff with @Directive() this is completely confusing.

We are starting to write up migration guides so that the transition is less confusing. See [the guide](https://next.angular.io/guide/migration-undecorated-classes) and specifically [this answer](https://next.angular.io/guide/migration-undecorated-classes#why-is-this-migration-necessary).

**Comment by sharikovvladislav** [comment]
@kara 
1 Should base classes be added to declarations array of any NgModule? 
At the moment, we are getting the "Component is not declared in any Angular module" error.

2 What about the inheritance from abstract classes? 
If you add the decorator to any class/directive, you will have to put it into the declarations array of some module. Abstract classes can not be added to any module declarations array, since you will get "Cannot assign an abstract constructor type to a non-abstract constructor type."

**Comment by pkozlowski-opensource** [comment]
> Should base classes be added to declarations array of any NgModule?

No.

> At the moment, we are getting the "Component is not declared in any Angular module" error.

Are you on the latest `@next` version? Even if you are there is still a problem where we try to resolve / inject dependencies for abstract classes (this is being fixed).

In short: the general idea is that abstract classes will _not_ be added to any `NgModule`

**Comment by trotyl** [comment]
@kara 

Your suggestion helps with the condition where **base class has no decorator (or `@Injectable()`) and derived class has `@Directive()`**, but what about the reverse scenario, where **base class has `@Directive()` and derived class has no decorator (or `@Injectable()`)**?

For example:

```typescript
@Directive({
  selector: '[foo]'
})
export class Foo {
  @Input() foo
}

export class Bar extends Foo {
  @Input() bar
}
```

In this case I may expect `Bar` to simply share the selector of `Foo`, without knowing what it is. But an empty `@Directive()` would make that not possible anymore, isn't it?

**Comment by dannyskoog** [comment]
For me the biggest issue atm is the fact that @Inputs aren't able to be inherited from a base class with Ivy enabled (even though it's decorated with @Directive). This is either a defect (I hope :)) or a breaking change

**Comment by JoostK** [comment]
@dannyskoog It's a defect, definitely. I recently found out that there's indeed a bug even when `@Directive()` is used without a selector, so that's something that needs to be fixed.

**Comment by dannyskoog** [comment]
Thanks for re-confirming @JoostK. I just wanted to point that out in order for that specific issue not to end up in the shadow of all other base class related matters

**Comment by kara** [comment]
>In this case I may expect Bar to simply share the selector of Foo, without knowing what it is. But an empty @Directive() would make that not possible anymore, isn't it?

@trotyl In that case, you would have to copy over the decorator (that's what the schematic does for you automatically). It is slightly more boilerplate, but it's more explicit, so it's easier for anyone to look at the directive and figure out what its selector is without having to drill down the inheritance tree. You do have to know what the selector is, though. It could be an argument for another feature down the line.

Thanks for pointing out the ambiguity. Seems like we need to add another FAQ to the guide about this. cc @kapunahelewong

**Comment by Splaktar** [comment]
> Nope. I am using stable 8.2.9 at the moment. I am trying to get ivy working on it in my project.

@sharikovvladislav I don't believe that selectorless `@Directive()` and the intelligence around not needing to import them into a NgModule is in `8.x`. I believe that it first went into `9.0.0-next.3`, but you would want to grab `9.0.0-next.10` to get the most fixes related to this issue.

With `8.x`, you would need to add a fake selector to your `@Directive()` and import it into a module. For library authors, even if you are targeting `9.x`,  you still need to do this for your library to support Angular `8.x` apps.

**Comment by fr0** [comment]
Using `9.0.0-next.10` and `enableIvy` = `true`, I am having trouble using a base class component with a generic type.

```
import {Component, Directive, Input} from '@angular/core';

@Directive()
export class BaseComponent<T> {
  @Input() value: T;
}

@Component({
  selector: 'app-derived',
  template: `
    {{value}}
  `
})
export class DerivedComponent extends BaseComponent<string> {

}
```

Using this component yields the following error:

```
src/app/app.component.ts:26:18 - error TS8002: 'value' is not a valid property of <app-derived>.

26     <app-derived [value]="'foo'"></app-derived>
```

Note that `DerivedComponent` is imported into the module, but `BaseComponent<T>` is not (how would I even do this with a generic class?)

I also get an error from the Angular language service about "BaseComponent is not declared in any Angular module" but that seems like a bug in the language service.

**Comment by JoostK** [comment]
@fr0 thanks for the additional info. The first error you're getting is exactly this issue, for which I opened #33131 yesterday that fixes that.

The second error is surprising to me, could it be that it's due to a hot-reload (or does the same error persist after restarting `ng build`?). The reason why I'm asking is that in #32416 a very similar error is mentioned, so it may just be that issue.

**Comment by fr0** [comment]
> @fr0 thanks for the additional info. The first error you're getting is exactly this issue, for which I opened #33131 yesterday that fixes that.

Thanks, glad to hear it.

> The second error is surprising to me, could it be that it's due to a hot-reload (or does the same error persist after restarting `ng serve`?). The reason why I'm asking is that in #32416 a very similar error is mentioned, so it may just be that issue.

It happens after restarting `ng serve`, so I don't think it's related to that. When trying to create a reproduction repo, I discovered that it only occurs if `BaseComponent` is in the `declarations` list *and* the `exports` list. Removing it from the `exports` list "fixes" that particular error. Here's a reproduction repo if you think this is worth looking into:  https://github.com/fr0/angular-ivy-test
