### ISSUE TITLE
@angular/compiler-cli declarations bug: has no exported member 'NgTools_InternalApi_NG_2'

### ISSUE THREAD

**Issue by vladimiry** [angular/angular#29220]
# 🐞 bug report

### Affected Package
@angular/compiler-cli

### Description

Wrong TypeScript declaration file.

## 🔬 Minimal Reproduction

package.json:
```json
{
  "name": "compiler-cli-declarations-bug",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "@angular/compiler": "7.2.8",
    "@angular/compiler-cli": "7.2.8",
    "@types/node": "11.11.0",
    "typescript": "3.3.3333"
  }
}
```

index.ts:
```typescript
import {readConfiguration} from "@angular/compiler-cli";

console.log(typeof readConfiguration);

```

Command to execute:
```
npx tsc --strict --noEmitOnError --lib es2015,dom index.ts
```

## 🔥 Exception or Error
```
node_modules/@angular/compiler-cli/index.d.ts:20:10 - error TS2305: Module '"@angular/compiler-cli/src/ngtools_api"' has no exported member 'NgTools_InternalApi_NG_2'.

20 export { NgTools_InternalApi_NG_2 as __NGTOOLS_PRIVATE_API_2 } from './src/ngtools_api';
            ~~~~~~~~~~~~~~~~~~~~~~~~

Found 2 errors.
```

![img](https://user-images.githubusercontent.com/1560781/54127946-ff53d280-441b-11e9-86c9-27de7db9e57d.png)

## Anything else relevant?

Adding `--skipLibCheck` TypeScript compiler option is a workaround:
```
npx tsc --strict --noEmitOnError --lib es2015,dom --skipLibCheck index.ts
```

**Comment by pkozlowski-opensource** [comment]
I don't think we support typescript 3.3 in Angular 7.x, see #28921. Do you get the same error with `~3.2.2`?

**Comment by vladimiry** [comment]
I confirm the same behavior with typescript@3.2.2.

**Comment by exequielc** [comment]
same issue here with

"@angular/compiler": "7.2.0",
"@angular/compiler-cli": "7.2.8",
    "typescript": "~3.2.2"

when running have this error on the console.

Typescript Error
Module '"@angular/compiler-cli/src/ngtools_api"' has no exported member 'NgTools_InternalApi_NG_2'.

**Comment by kirillgroshkov** [comment]
Same error for us

**Comment by vagonpidarasov** [comment]
Same here:

```
ERROR in [at-loader] ./node_modules/@angular/compiler-cli/index.d.ts:14:10 
    TS2305: Module '"@angular/compiler-cli/src/ngtools_api"' has no exported member 'NgTools_InternalApi_NG_2'.
```

```
"@angular/compiler": "8.1.1",
"@angular/compiler-cli": "8.1.1",
```

**Comment by vagonpidarasov** [comment]
Following tsconfig seemed to solve the problem:
```
{
    "compilerOptions": {
        "target": "es5",
        "module": "es2015",
        "lib": ["es2015", "dom"],
        "moduleResolution": "node",
        "types": ["node", "webpack", "core-js", "rx", "jest"],
        "typeRoots": ["node_modules/@types"],
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "sourceMap": true,
        "noEmitHelpers": true,
        "baseUrl": "./",
        "importHelpers": true,
        "esModuleInterop": true
    },

    "exclude": [
        "node_modules"
    ],

    "awesomeTypescriptLoaderOptions": {
        "resolveGlobs": true,
        "forkChecker": true
    },
    "compileOnSave": false,
    "buildOnSave": false
}
```

**Comment by vladimiry** [comment]
The issue is still in place, just tested with the most recent library versions:
  - create `package.json`:
```
{
  "name": "compiler-cli-declarations-bug",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "@angular/compiler": "8.2.0-next.2",
    "@angular/compiler-cli": "8.2.0-next.2",
    "@bazel/typescript": "0.33.1",
    "@types/node": "12.6.8",
    "typescript": "3.4.5"
  }
}
```
  - run `yarn install`
  - create `index.ts`:
```
import {readConfiguration} from "@angular/compiler-cli";
console.log(typeof readConfiguration);
```
  - run `npx tsc  --noEmitOnError --lib es2015,dom index.ts` output:
```
node_modules/@angular/compiler-cli/index.d.ts:14:10 - error TS2305: Module '"@angular/compiler-cli/src/ngtools_api"' has no exported member 'NgTools_InternalApi_NG_2'.

14 export { NgTools_InternalApi_NG_2 as __NGTOOLS_PRIVATE_API_2 } from './src/ngtools_api';
            ~~~~~~~~~~~~~~~~~~~~~~~~

Found 2 errors.
```

**Comment by mosilver** [comment]
I have the same error, after upgrade native script from 5 to 6 and angular 7 to 8, when building Android app I get error

**ERROR in node_modules/@angular/compiler-cli/index.d.ts(21,10): error TS2305: Module
@angular/compiler-cli/src/ngtools_api"' has no exported member 'NgTools_InternalApi_NG_2'.**

**Comment by vladimiry** [comment]
The issue is still here with @angular/compiler-cli@8.2.6:
```
ERROR in ../../../node_modules/@angular/compiler-cli/index.d.ts:14:10 - error TS2305: Module '"@angular/compiler-cli/src/ngtools_api"' has no exported member 'NgTools_InternalApi_NG_2'.

14 export { NgTools_InternalApi_NG_2 as __NGTOOLS_PRIVATE_API_2 } from './src/ngtools_api';
```

**Comment by alasdair-macleod** [comment]
still seeing this with @angular/compiler-cli@8.2.7

chunk {ERROR in ../node_modules/@angular/compiler-cli/index.d.tsmain:} 14main.js, main.js.map: (main) 2.04 kB 10[initial] -  [rendered]error
 TS2305: chunk {Module '"@angular/compiler-cli/src/ngtools_api"' has no exported member 'NgTools_InternalApi_NG_2'.

**Comment by ChrisOrtiz3817** [comment]
I resolved it this way.

went to 
node_modules\@angular\compiler-cli\index.d.ts  

Contents


> export { AotCompilerHost, AotCompilerHost as StaticReflectorHost, StaticReflector, StaticSymbol } from '@angular/compiler';
> export { DiagnosticTemplateInfo, getExpressionScope, getTemplateExpressionDiagnostics } from './src/diagnostics/expression_diagnostics';
> export { AstType, ExpressionDiagnosticsContext } from './src/diagnostics/expression_type';
> export { BuiltinType, DeclarationKind, Definition, PipeInfo, Pipes, Signature, Span, Symbol, SymbolDeclaration, SymbolQuery, SymbolTable } from './src/diagnostics/symbols';
> export { getClassMembersFromDeclaration, getPipesTable, getSymbolQuery } from './src/diagnostics/typescript_symbols';
> export { VERSION } from './src/version';
> export * from './src/metadata';
> export * from './src/transformers/api';
> export * from './src/transformers/entry_points';
> export * from './src/perform_compile';
> export { CompilerOptions as AngularCompilerOptions } from './src/transformers/api';
> export { NgTools_InternalApi_NG_2 as __NGTOOLS_PRIVATE_API_2 } from './src/ngtools_api';
> export { ngToTsDiagnostic } from './src/transformers/util';
> 

Commented out the ngtools_internalApi_ng_2 export

> export { AotCompilerHost, AotCompilerHost as StaticReflectorHost, StaticReflector, StaticSymbol } from '@angular/compiler';
> 
> export { DiagnosticTemplateInfo, getExpressionScope, getTemplateExpressionDiagnostics } from './src/diagnostics/expression_diagnostics';
> 
> export { AstType, ExpressionDiagnosticsContext } from './src/diagnostics/expression_type';
> 
> export { BuiltinType, DeclarationKind, Definition, PipeInfo, Pipes, Signature, Span, Symbol, SymbolDeclaration, SymbolQuery, SymbolTable } from './src/diagnostics/symbols';
> 
> export { getClassMembersFromDeclaration, getPipesTable, getSymbolQuery } from './src/diagnostics/typescript_symbols';
> 
> export { VERSION } from './src/version';
> 
> export * from './src/metadata';
> 
> export * from './src/transformers/api';
> 
> export * from './src/transformers/entry_points';
> 
> export * from './src/perform_compile';
> 
> export { CompilerOptions as AngularCompilerOptions } from './src/transformers/api';
> 
> **// export { NgTools_InternalApi_NG_2 as __NGTOOLS_PRIVATE_API_2 } from './src/ngtools_api';**
> 
> export { ngToTsDiagnostic } from './src/transformers/util';
> 

I also had some other error with 'path' not being found, you might not have this, but I fixed that with
` npm install path`

After making these changes I can compile with ease.
 
For me this started when I tried to (without experience I may add) run some --proxy option on ng serve in an attempt to use the "proxy" method to bypass cors, so I could test and play with bringing in HTML data from other sources, and displaying it in popup windows etc as like an embedded item of sorts.. 

Forgive me if posting links is not allowed, but I tried to follow this guide,  in an effort to set up the initial requirements  needed for having this sort of feature,

[https://medium.com/better-programming/setup-a-proxy-for-api-calls-for-your-angular-cli-app-6566c02a8c4d](https://medium.com/better-programming/setup-a-proxy-for-api-calls-for-your-angular-cli-app-6566c02a8c4d)

**Comment by vladimiry** [comment]
> After making these changes I can compile with ease.

You could simply enable the `skipLibCheck` typescript compilation option as noted in the original message.

**Comment by ChrisOrtiz3817** [comment]
Apparently I have a knack for doing stuff the hard way.

 I sort of fixed this way before I really looked into this page/bug lol.

**Comment by KingDarBoja** [comment]
Got the same error on my project, had to enable `skipLibCheck` on my `tsconfig` file but not happy about that.

```
$ ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 8.3.4
Node: 11.15.0
OS: win32 x64
Angular: 8.2.10
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router, upgrade

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.9
@angular-devkit/build-angular     0.803.9
@angular-devkit/build-optimizer   0.803.9
@angular-devkit/build-webpack     0.803.9
@angular-devkit/core              8.3.9
@angular-devkit/schematics        8.3.4 (cli-only)
@angular/cdk                      8.2.3
@angular/http                     7.2.15
@ngtools/webpack                  8.3.9
@schematics/angular               8.3.4 (cli-only)
@schematics/update                0.803.4 (cli-only)
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.41.0
```

**Comment by vladimiry** [comment]
```
  "compilerOptions": {
    ...
    "skipLibCheck": true
    ...
  },
```

`skipLibCheck` needs to be put to the right tsconfig file.

**Comment by KingDarBoja** [comment]
> ```
>   "compilerOptions": {
>     ...
>     "skipLibCheck": true
>     ...
>   },
> ```
> 
> `skipLibCheck` needs to be put to the right tsconfig file.

Does this decrease the typings feature in my project? I mean, I set it to true and got rid of errors but still not sure if I should have to worry about it.

**Comment by vladimiry** [comment]
> I set it to true and got rid of errors but still not sure if I should have to worry about it.

Those are not the errors of your code but declarations/typings errors of the libraries used in your project. Enabling `skipLibCheck` is a workaround and it's better to remove/disable the flag after this issue gets resolved.

**Comment by KingDarBoja** [comment]
> > I set it to true and got rid of errors but still not sure if I should have to worry about it.
> 
> Those are not the errors of your code but declarations/typings errors of the libraries used in your project. Enabling `skipLibCheck` is a workaround and it's better to remove/disable the flag after this issue gets resolved.

Yeah, I noticed that since I am getting the same errors as you:

```
ERROR in node_modules/@angular-devkit/core/src/utils/partially-ordered-set.d.ts:21:5 - error TS2416: Property 'forEach' in type 'PartiallyOrderedSet<T>' is not assignable to the same propertyin base type 'Set<T>'.
  Type '(callbackfn: (value: T, value2: T, set: PartiallyOrderedSet<T>) => void, thisArg?: any) => void' is not assignable to type '(callbackfn: (value: T, value2: T, set: Set<T>) => void, thisArg?: any) => void'.
    Types of parameters 'callbackfn' and 'callbackfn' are incompatible.
      Types of parameters 'set' and 'set' are incompatible.
        Property 'toJSON' is missing in type 'PartiallyOrderedSet<T>' but required in type 'Set<T>'.

21     forEach(callbackfn: (value: T, value2: T, set: PartiallyOrderedSet<T>) => void, thisArg?: any): void;
       ~~~~~~~

  node_modules/@types/core-js/index.d.ts:78:5
    78     toJSON(): any;
           ~~~~~~~~~~~~~~
    'toJSON' is declared here.
node_modules/@angular/compiler-cli/index.d.ts:14:10 - error TS2305: Module '"@angular/compiler-cli/src/ngtools_api"' has no exported member 'NgTools_InternalApi_NG_2'.
```

By removing '@types/core-js` from my *devDependencies* does solve the first typing error but the second one only works with the `skipLibCheck` as you stated.

Also, while serving my project by using *webpack-dev-server*, I only get a black screen and no console errors neither webpack bundle warnings. I do see my app bundle being generated but not loaded on the network tab.

**Comment by vladimiry** [comment]
I just have tried the 9.0.0-rc.3 release and the issue is gone. So closing as resolved.
