### ISSUE TITLE
ngIf with observer(async) crashes on 2.4.9

### ISSUE THREAD

**Issue by ReneVallecillo** [angular/angular#15197]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I had a simple observer which started with a false value. I use the startWith operator. On my template I had a ngIf with async with my observer as parameter. This was working on 2.3.x, but when I upgraded to 2.4.9 the same codes does not work.

**Expected behavior**
The ngIf would check the observer and interact with the dom when the observer recieves a trusty value.
**Minimal reproduction of the problem with instructions**

Use angular cli rc2, add the following

```
import { Component } from '@angular/core';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/startWith';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app works!';
  observer: Observable<boolean> = new Observable<boolean>().startWith(true);

}
```

and 
```
<h1>
  {{title}}
</h1>

<h2 *ngIf="observer | async">Async</h2>
```

Here is the plunker

http://plnkr.co/edit/QG7jVB8dAr5F7PiK4MUI?p=preview

**Please tell us about your environment:**

OSX El capitan, Angular Cli 1.0.0rc2, vscode

* **Angular version:** 2.0.X
it worked on 2.3.0, upgraded to 2.4.9, stopped working

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TS
* **Node (for AoT issues):** `node --version` =

**Comment by ReneVallecillo** [comment]
Note: 

In my actual project, the ngif throws:

inline template:1:5 caused by: __webpack_require__.i(...) is not a function

If i delete the async part, it runs again.

**Comment by Toxicable** [comment]
@ReneVallecillo I think you're incorrectly making the Observable. Works fine here http://plnkr.co/edit/FnWyj1MAf8reyhwMowTx?p=preview

**Comment by ReneVallecillo** [comment]
@Toxicable That seems to be working on my fresh angular cli, not on my old upgraded project, I'm gonna check if i'm missing something and close the issue if it's something I was missing on my upgrade process of angular cli

**Comment by pkozlowski-opensource** [comment]
@ReneVallecillo I'm going to close this one for now as we don't have reproduce scenario. Please open a new issue (or reopen this one) if / when you can reproduce this problem in a plunker. Thnx!

**Comment by ReneVallecillo** [comment]
Hello, just confirmed is not related to angular itself, I went back and upgraded step by step without upgrading angular cli and it works as expected. Thanks @pkozlowski-opensource and @Toxicable 

I should filed it under cli if it shows again.
