### ISSUE TITLE
HTTP throws "_private__.getDOM(...).getCookie is not a function" if used before bootstrap

### ISSUE THREAD

**Issue by ulfryk** [angular/angular#9294]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
After update to 2.0.0-rc.2 I get this error:
```
// Chrome
Uncaught TypeError: Cannot read property 'getCookie' of null

// FireFox
TypeError: platform_browser_1.__platform_browser_private__.getDOM(...) is null

// Safari
TypeError: null is not an object (evaluating 'platform_browser_1.__platform_browser_private__.getDOM().getCookie')
```

pointing to second line of this part of code:
```javascript
	    CookieXSRFStrategy.prototype.configureRequest = function (req) {
	        var xsrfToken = platform_browser_1.__platform_browser_private__.getDOM().getCookie(this._cookieName);
	        if (xsrfToken && !req.headers.has(this._headerName)) {
	            req.headers.set(this._headerName, xsrfToken);
	        }
	    };
```

**Reproduction of the problem**
It happens when I try to send `GET` request before app bootstrap:

```typescript
import { ReflectiveInjector } from '@angular/core'
import { HTTP_PROVIDERS } from '@angular/http'

import { AuthDao } from '…some/place/in/app'

ReflectiveInjector.resolveAndCreate([...HTTP_PROVIDERS, AuthDao])
  .get(AuthDao)
  .check()
```

and AuthDao's class `check()` method looks like this:

```typescript
import { Observable } from 'rxjs/Observable'
import { Response, Headers, Http } from '@angular/http'

@Injectable()
export class AuthDao {

  constructor(http: Http) {}

  public check(): Observable<Response> {
    return this._http.get('/do/some/check', { 
      headers: new Headers({ 'Accept': 'text/plain;charset=UTF-8' }) 
    })
  }

  …

```

* **Angular version:** 2.0.0-rc.2
 
* **Browser:** [ Chrome 51.0.2704.84 (64-bit) | Firefox 45.0.2 | Safari 9.1.1 ] 
 
* **Language:** [ TypeScript 1.8 ]

**Comment by ulfryk** [comment]
Just tested it against `rc.3` - still the same :|

**Comment by vicb** [comment]
Do you have a plunkr demonstrating the issue ?

**Comment by ulfryk** [comment]
no - have too much regular work, maybe I'll manage to prepare plunkr this weekend.. but only maybe...

The problem is that `__platform_browser_private__.getDOM()` return null before I call `bootstrap(…)`, here:

https://github.com/angular/angular/blob/12c49042abed8847a474c445271f9ba9830d3c18/modules/%40angular/http/src/backends/xhr_backend.ts#L157

**Comment by vicb** [comment]
The issue is that you try to access the DomAdapter before it is actually initialized (which happens in the platform initializers).

**Comment by NathanWalker** [comment]
There should be no DOM dependency here at all actually.
Having this line:
```
var xsrfToken = platform_browser_1.__platform_browser_private__.getDOM().getCookie(this._cookieName);
```
Causes issues with multi-platform integrations like NativeScript https://github.com/NativeScript/nativescript-angular

It would be great if this could come purely from an Injectable and not used explicitly.
https://github.com/angular/angular/blob/master/modules/%40angular/http/src/backends/xhr_backend.ts#L152-L162 is not an Injectable and therefore requires multi-platform integration to provide an entire different `XHRBackend` to swap out the CookieXSRFStrategy which presents this problem.

**Comment by robwormald** [comment]
@NathanWalker it's already injectable - see https://github.com/angular/angular/blob/master/modules/%40angular/http/http.ts#L183

So you could mock it out as described, no?

**Comment by NathanWalker** [comment]
@robwormald ah interesting, seemed like I tried that and it didn't work, lemme try again later tonight, I'll report back...

**Comment by ulfryk** [comment]
@robwormald - great TIP! I'll check it today :)

**Comment by NathanWalker** [comment]
@robwormald totally worked out just fine, thanks again for more enlightenment! Even simpler now 👍

**Comment by ulfryk** [comment]
Ok it works, but IMO it's odd that one have to hack his favourite framework to make it just work :(

new version of my code:

```typescript
import { ReflectiveInjector } from '@angular/core'
import { HTTP_PROVIDERS, Request, XSRFStrategy } from '@angular/http'

import { AuthDao } from '…some/place/in/app'

class FakeXSRFStrategy implements XSRFStrategy {
  public configureRequest(req: Request) { /* */ }
}

const XRSF_MOCK = provide(XSRFStrategy, { useValue: new FakeXSRFStrategy() })

ReflectiveInjector.resolveAndCreate([...HTTP_PROVIDERS, XRSF_MOCK, AuthDao])
  .get(AuthDao)
  .check()
```

Living snippet for anyone that will fall into this issue.

**Comment by IgorMinar** [comment]
I believe that this problem exists only if you use http before you bootstrap. Can you confirm?

(explanation/notes: this happens because http depends on BrowserAdapter for access to cookies and we initialize BrowserAdapter only during bootstrap, so if you try to access getDom() before bootstrap you get nothing and that causes that call to fetch cookies to fail)

**Comment by vicb** [comment]
@IgorMinar I think this is the root cause but the CookieProvider should probablybe moved to the PLATFORM, WDYT ?

The workaround is to call `adapter.makeCurrent()` if you want to use the DOM before platform initialization

**Comment by ulfryk** [comment]
> I believe that this problem exists only if you use http before you bootstrap. Can you confirm?

@IgorMinar - I confirm :)

**Comment by jsight** [comment]
I am running into a problem that looks very similar to this. It happens while writing a jasmine test that uses an HTTP service.

The error is:

> TypeError:  platform_browser_1.__platform_browser_private__.getDOM(...) is null in http://127.0.0.1:8180/windup-web//node_modules/systemjs/dist/system.js line 4 > eval (line 150)

**Comment by vicb** [comment]
This will be fixed in rc5

**Comment by flogo1982** [comment]
I have a similar problem with es5:
http://stackoverflow.com/questions/38779982/get-an-error-from-angular2-http-in-es5

**Comment by TrevorBroderick1** [comment]
Still broken in RC5.

**Comment by jsight** [comment]
It works for me. Maybe there is an initialization step missing or something? Can you post an example?

**Comment by TrevorBroderick1** [comment]
Sure, here's the code. Am I missing something?

```
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { AppModule }              from './app.module';
import {HTTP_PROVIDERS, Http} from '@angular/http';
import {ReflectiveInjector} from '@angular/core';

var injector = ReflectiveInjector.resolveAndCreate([HTTP_PROVIDERS]);
var http = injector.get(Http);

http.get('data.json').map(res => res.json())
    .subscribe(data => {
        platformBrowserDynamic().bootstrapModule(AppModule);
    }
);
```

**Comment by ulfryk** [comment]
```
…, XSRFStrategy } from '@angular/http'

var XRSF_MOCK = { provide: XSRFStrategy, useValue: {
    configureRequest: function() { /* */ }
} };

var injector = ReflectiveInjector.resolveAndCreate([HTTP_PROVIDERS, XRSF_MOCK]);
…
```

Sth like this…

**Comment by TrevorBroderick1** [comment]
That is still using the 'hack' though. If this was fixed shouldn't it work without needing to provide a mock XSRF?

**Comment by jsight** [comment]
@TrevorBroderick1 In our SystemJS loading, we have this:

System.import('../systemjs.config.js')
                .then(function () {
                    return Promise.all([
                        System.import('@angular/core/testing'),
                        System.import('@angular/platform-browser-dynamic/testing')
                    ])
                })

                .then(function (providers) {
                    var testing = providers[0];
                    var testingBrowser = providers[1];

                    testing.TestBed.initTestEnvironment(
                            testingBrowser.BrowserDynamicTestingModule,
                            testingBrowser.platformBrowserDynamicTesting());
                })

I think the call to initTestEnvironment is needed before the resource injection can work.

**Comment by TrevorBroderick1** [comment]
Thanks @jsight 

Can I get some clarification on where this should be done? I'm not sure where the test bed comes into play on this, or how to incorporate it into what I'm trying to do in the bootstrap of main.js.

Where is this code located in your program?

**Comment by jsight** [comment]
@TrevorBroderick1 I am using SystemJS for loading and I have this in my unit-tests.html file. It is just above the System.import calls that load the spec files themselves.

The rest of the code is here:
https://github.com/windup/windup-web/blob/master/ui/src/main/webapp/tests/unit-tests.html
