### ISSUE TITLE
ngc shows an error on a non-existant file in my repo

### ISSUE THREAD

**Issue by tomgeorge** [angular/angular#11882]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
in my fork located here: [https://github.com/tomgeorge/angular2-webpack-starter](https://github.com/tomgeorge/angular2-webpack-starter), on the aot branch, run `npm run ngc`.

Currently I see the following error message:

```
can't resolve module @angular/core/src/di/metadata from C:\Users\Tom\git\angular2-webpack-starter\index.ts
Error: can't find symbol Host exported from module C:/Users/Tom/git/angular2-webpack-starter/node_modules/@angular/core/src/di/metadata.d.ts
    at ReflectorHost.findDeclaration (C:\Users\Tom\git\angular2-webpack-starter\node_modules\@angular\compiler-cli\src\reflector_host.js:173:23)
    at StaticReflector.initializeConversionMap (C:\Users\Tom\git\angular2-webpack-starter\node_modules\@angular\compiler-cli\src\static_reflector.js:148:55)
    at new StaticReflector (C:\Users\Tom\git\angular2-webpack-starter\node_modules\@angular\compiler-cli\src\static_reflector.js:42:14)
    at Function.CodeGenerator.create (C:\Users\Tom\git\angular2-webpack-starter\node_modules\@angular\compiler-cli\src\codegen.js:142:31)
    at codegen (C:\Users\Tom\git\angular2-webpack-starter\node_modules\@angular\compiler-cli\src\main.js:7:36)
    at Object.main (C:\Users\Tom\git\angular2-webpack-starter\node_modules\@angular\tsc-wrapped\src\main.js:30:16)
    at Object.<anonymous> (C:\Users\Tom\git\angular2-webpack-starter\node_modules\@angular\compiler-cli\src\main.js:14:9)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
Compilation failed
```

It's weird because there is no angular2-webpack-starter/index.ts file.  I also did a `console.log` of the `core_1.Host` variable that is is trying to use in a call to `registorDecoratorOrConstructor` in `node_modules/@angular/compiler-cli/src/static_reflector.js` and it is undefined.  However, [this project](https://github.com/qdouble/angular2webpack2-starter) has AoT working, and their `core_1.Host` variable is also undefined.

**Expected behavior**
AoT compiled file in src/compiled

**Reproduction of the problem**
`git clone https://github.com/tomgeorge/angular2-webpack-starter`

`git checkout -b aot`

`git pull origin aot`

`npm install`

`npm run ngc`

**What is the motivation / use case for changing the behavior?**
I would like to use platform-browser to speed up my aplications

**Please tell us about your environment:**
Windows 10 Version 1607 (OS Build 14393.187), Visual Studio Code, Git bash

* **Angular version:** 2.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 

 
* **Language:** [all | TypeScript 2.0.3 | ES6/7 | ES5]
 
* **Node (for AoT issues):** `node --version` =   v5.10.1, note that I tried [this fork](https://github.com/qdouble/angular2webpack2-starter) and AoT worked.

**Comment by manklu** [comment]
To recite @vicb

>Your question sounds like a support request.
>
>Please use the issue tracker only for bugs and feature requests.
>
>Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by sajithaPriyankara** [comment]
@tomgeorge ,, Any positive update with this issue. If so can you please share it here?

**Comment by tomgeorge** [comment]
Unfortunately, no.  The farthest I have gotten is that it will make .js and .js.map files, but not create the angular factory classes.

I found this repo that works though:

https://github.com/qdouble/angular2webpack2-starter

And if you search angular2 aot on github you will find a bunch of examples.

**Comment by arloduff** [comment]
This seems to be a dependency issue. Upgrading the following dependencies to `2.0.0` from an `rc` version seems to do the trick:

    @angular/common
    @angular/compiler
    @angular/core
    @angular/http
    @angular/platform-browser
    @angular/platform-browser-dynamic
    @angular/upgrade

From here, you may run into errors like `Cannot find name 'Map'` or `Cannot find name 'Set'`

To resolve this, just install `@types/core-js@^0.9.34`

**Comment by tomgeorge** [comment]
My team is doing other stuff right now with angular, so ill try your suggestion for AoT later.

Have you run into issues with core-js vs es6-shim? I seem to see a lot more repos with the latter, and right now the compiler is having issues finding Promise.resolve with core-js. I've tried adding core-js to the types array in tsconfig.json, no dice.

**Comment by arloduff** [comment]
Haven't run into those issues, but the typings errors are definitely a mess to debug. We're using both core-js and @types/core-js. I would suggest trying both, as well as upgrading Typescript to "next" and upgrading the typings definitions in your typings.json file. I would think that Promise.resolve would be common enough that there would be a definition out there that would have it.

**Comment by prijindal** [comment]
I am facing this issue with node version 6.7.0 but everything is working fine with node 6.4.0
