### ISSUE TITLE
Routes cannot contain additional objects in angular 2.3.1

### ISSUE THREAD

**Issue by marcuskrahl** [angular/angular#13565]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If you add an object instance to your route definition, the app fails to load with the error `Cannot convert undefined or null to object` with the stack trace:

```Uncaught TypeError: Cannot convert undefined or null to object
    at Function.getPrototypeOf (<anonymous>)
    at ReflectionCapabilities.annotations (http://localhost:4200/main.bundle.js:60005:50)
    at Reflector.annotations (http://localhost:4200/main.bundle.js:60197:44)
    at DirectiveResolver.isDirective (http://localhost:4200/main.bundle.js:18021:61)
    at http://localhost:4200/main.bundle.js:19618:42
    at Array.forEach (native)
    at CompileMetadataResolver._getEntryComponentsFromProvider (http://localhost:4200/main.bundle.js:19617:30)
    at http://localhost:4200/main.bundle.js:19590:83
    at Array.forEach (native)
    at CompileMetadataResolver._getProvidersMetadata (http://localhost:4200/main.bundle.js:19560:19)
    at http://localhost:4200/main.bundle.js:19562:23
    at Array.forEach (native)
    at CompileMetadataResolver._getProvidersMetadata (http://localhost:4200/main.bundle.js:19560:19)
    at http://localhost:4200/main.bundle.js:19198:63
    at Array.forEach (native)
```
The error ist thrown because `ReflectionCapabilities.annotations` tries to access the `prototype` of the passed variable which in this case is an object instance so fails.

This worked in 2.2.4 but fails with 2.3.1. It fails for a webpack build, I haven't tried any other build tools.

**Expected behavior**

The user should be able to add arbitrary properties to route entries without causing compilation errors.

**Minimal reproduction of the problem with instructions**

Add an object instance to a route definition like:

```
import { SomeObject } from "./some-object.model";

const routes: any = [
  {
    path: '',
    children: [],
    data: {
      otherProperty: new SomeObject(),
    }
  }
];
```

see https://github.com/marcuskrahl/angular-bug-route-with-object-instance for an example repository

**Workaround**
If the object instance creation is replaced with a function call, the example works without any problems (but of course the access of the data has to be changed).
```
...
    data: {
      otherProperty:  () => new SomeObject(),
    }
...
```

**What is the motivation / use case for changing the behavior?**

You should be able to add application dependant information to routing entries.

**Please tell us about your environment:**

angular-cli changed to 2.3.1 runtime on Windows 7.
Also does not work on custom webpack build without angular-cli.

* **Angular version:** 2.3.1

* **Browser:** [all]
 
* **Language:** [TypeScript 2.0.10]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
why don't u use router data for arbitrary properties?

**Comment by marcuskrahl** [comment]
Well I guess there is no real reason not to use the data property. Since what I did is a usage error I might as well close this bug.

**Comment by marcuskrahl** [comment]
The problem apparently still exists when using router data for this information. I edited the issue accordingly

**Comment by DzmitryShylovich** [comment]
does it work for a simple object ?
```
 data: {
      otherProperty: {},
}
```

**Comment by marcuskrahl** [comment]
It works with simple objects, but I have to use instances of concrete typescript objects for my use case.

**Comment by DzmitryShylovich** [comment]
Router config is a part of metadata and you can not use functions in metadata. Your code should be statically analyzable. For more info see https://medium.com/@isaacplmann/making-your-angular-2-library-statically-analyzable-for-aot-e1c6f3ebedd5#.dpf91ab62

But I would expect a different error message :)

**Comment by DzmitryShylovich** [comment]
@chuckjaz I would say it's a compiler bug.

**Comment by chuckjaz** [comment]
The angular CLI currently doesn't support 2.3.1. We are working on a new release of the CLI that will support the up coming 2.4.0. I am keeping this bug open for now until we can verify that this is not an issue with 2.4.0 and the new CLI release.

**Comment by marcuskrahl** [comment]
This is not an issue with the cli because the same error exists in my main project which does not use angular cli at all.
Just try it in any other project. The bug is triggered when an object instance is added to the route data and the class was imported into the file containing the route definition.

Am 19. Dezember 2016 20:50:51 MEZ, schrieb Chuck Jazdzewski <notifications@github.com>:
>The angular CLI currently doesn't support 2.3.1. We are working on a
>new release of the CLI that will support the up coming 2.4.0. I am
>keeping this bug open for now until we can verify that this is not an
>issue with 2.4.0 and the new CLI release.
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/angular/angular/issues/13565#issuecomment-268060484

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by hansl** [comment]
Pulling @tbosch.

After investigation, this is an issue with the MetadataResolver. It tries to access `SomeObject.prototype` because it checks that `SomeObject` is a directive and try to object its metadata. Instead of using its constructor it uses the instance, and fails.

Not sure if this is a blocker, but in my opinion people will be using instances. What's weird to me is that we don't respect the schema and look for directives everywhere.

To Tobias:

- The commit creating the failure is this: https://github.com/marcuskrahl/angular-bug-route-with-object-instance/commit/43d59c82819b75ba318bbb33bfd165dd2ce7ca67
- The actual error point and stack:

![screen shot 2016-12-19 at 1 07 20 pm](https://cloud.githubusercontent.com/assets/681969/21329155/22581a94-c5ec-11e6-89e0-b769b0de89f8.png)

**Comment by chuckjaz** [comment]
@marcuskrahl Acknowledged. Hans determined the same thing. @tbosch is not looking into it.

**Comment by gridcellcoder** [comment]
```json
dependencies": {
    "@angular/common": "2.4.1",
    "@angular/compiler": "2.4.1",
    "@angular/core": "2.4.1",
    "@angular/forms": "2.4.1",
    "@angular/http": "2.4.1",
    "@angular/platform-browser": "2.4.1",
    "@angular/platform-browser-dynamic": "2.4.1",
    "@angular/platform-server": "2.4.1",
    ...
    "webpack": "^2.2.0-rc.2"
}
```
I can also confirm that I am getting the same error with the versions above. I don't have any `data` fields but using for example:

```json
path: '', component: Layout, children: [ ]
```
and this is causing issues. Not sure if this is a webpack thing or something else..

@chuckjaz did you say @tbosch is _not_ looking at it or did you mean _now_ looking at it?

**Comment by gillesfabre34** [comment]
Hi, maybe a stupid question, but... this bug was fixed in Angular 2, but I have it with Angular 4.1.1
Is it normal ? I missed something ? Thanks

**Comment by tbosch** [comment]
@gillesfabre34 the commit did make it into Angular4. Could you file a new issue with a way to reproduce your specific problem?

**Comment by gillesfabre34** [comment]
Hi, thanks for your reply. 
Here is my file. The line which creates the bug is the one with "loadChildren". 

```
import { Routes, RouterModule }  from '@angular/router';
import { Pages } from './pages.component';
import { AuthGuard } from './auth/auth.component'
import { NgModule } from "@angular/core";

export const routes: Routes = [
    {
        path: 'home',
        canActivate: [AuthGuard],
        component: Pages,
        children: [
            { path: 'settings', loadChildren: () => System.import('./settings/settings.module') }
        ]
    },
    { path: '', redirectTo: '/home', pathMatch: 'full' },
    { path: '**', redirectTo: '/home', pathMatch: 'full' }
];

@NgModule({
    imports: [
        RouterModule.forChild(routes)
    ],
    exports: [
        RouterModule
    ]
})
export class PageRoutingModule {
}
```

The error message is exactly the same than @marcuskrahl 

I thought that it should be a problem with my old webpack's version (1), so I'm trying now to upgrade it to webpack 2. I didn't finished this job, but do you think that it could be a good way ?

**Comment by tbosch** [comment]
So in general, this won't work with AOT as we don't support closures.
Instead, you need to refactor the `loadChildren` into a top level function and reference it.

**Comment by gillesfabre34** [comment]
Thanks ! 
Changing the line in

`{ path: 'settings', loadChildren: function() {  return require('./settings/settings.module')['SettingsModule']; }`

all is ok now.

**Comment by Ayyappa752** [comment]
Hi @gillesfabre34  I have faced the similar problem, and tried the solution provided above. but I'm getting an error at "require". Compiler is saying that it can't find name "require". any Namespace i need to import?
I'm using Angular 2. I tried using System.Import, but even "system" is not available
