### PR TITLE
fix(compiler-cli): escape template literal in TCB

### LINKED ISSUE #67675: double escaped backtick in template literal string in template html  breaks from @angular/ v21.2.2
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

No

### Description

```html
@let versionInfo = `Version: \`${info}\``;
<div>{{ versionInfo }}</div>
```

double escaped backtick in template html cause a error with version `21.2.2` and later but works with version `21.2.1`

the scenario is that I just want to show some markdown string literals in the template html so I have to escape the backtick symbol to make it a code block for markdown

and if I remove the second escaped backtick it works again with version `21.2.2`

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-yviu1qjq

and below is the worked link with the same codes but with version `21.2.1`

https://stackblitz.com/edit/stackblitz-starters-ntqt2vnt

### Please provide the exception or error you saw

```true
TS2304: Cannot find name '_t1'. [plugin angular-compiler]
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI       : 21.2.2
Angular           : 21.2.2
Node.js           : 22.22.0
Package Manager   : npm 10.8.2
Operating System  : linux x64

┌───────────────────────────┬───────────────────┬───────────────────┐
│ Package                   │ Installed Version │ Requested Version │
├───────────────────────────┼───────────────────┼───────────────────┤
│ @angular/build            │ 21.2.2            │ 21.2.2            │
│ @angular/cli              │ 21.2.2            │ 21.2.2            │
│ @angular/common           │ 21.2.2            │ 21.2.2            │
│ @angular/compiler         │ 21.2.2            │ 21.2.2            │
│ @angular/compiler-cli     │ 21.2.2            │ 21.2.2            │
│ @angular/core             │ 21.2.2            │ 21.2.2            │
│ @angular/forms            │ 21.2.2            │ 21.2.2            │
│ @angular/platform-browser │ 21.2.2            │ 21.2.2            │
│ @angular/router           │ 21.2.2            │ 21.2.2            │
│ rxjs                      │ 7.8.2             │ ^7.8.2            │
│ typescript                │ 5.9.3             │ ^5.9.3            │
└───────────────────────────┴───────────────────┴───────────────────┘
```

### Anything else?

Please help and sorry for my poor English

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes a regression introduced by #67381 where we weren't escaping backticks in template literals.

Fixes #67675.

### CODE REVIEW

**Review by JoostK — COMMENTED** [review]
A test in https://github.com/angular/angular/blob/main/packages/compiler-cli/test/ngtsc/template_typecheck_spec.ts would be meaningful to verify the template is checked as expected;

```ts
@Component({
  template: `
    @let var = `Version: \`${check(version)}\``;
  `
})
export class Cmp {
  version = 'test'
  check(input: number): string {
    return String(input);
  }
}
```

Should report a type assignability error from string to number. That shows that the template's substitutions are type-checked as expected.

**Comment by crisbeto** [comment]
Added the extra test case.

**Review by JoostK — APPROVED** [review]

**Comment by mattrbeck** [comment]
This PR was merged into the repository. The changes were merged into the following branches:

- main: 2bd708fb6bc3ada19c5dd21077a7f609996f6346
- 21.2.x: 26c43d14baad1a6b3629a77825e702a97a4f8482
