### ISSUE TITLE
Component with local properties doesn't inherit service from superclass

### ISSUE THREAD

**Issue by ebrehault** [angular/angular#15502]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
My BaseComponent injects a service (example: https://github.com/ebrehault/component-extension-example/blob/master/src/app/base-component/base-component.component.ts#L13).
My CustomComponent inherits from BaseComponent (example: https://github.com/ebrehault/component-extension-example/blob/master/src/app/custom-component/custom-component.component.ts#L9) and it works fine, the service is properly injected.
But my CustomWithproperty component which is also inheriting from BaseComponent but defines a custom property (example: https://github.com/ebrehault/component-extension-example/blob/master/src/app/custom-with-property/custom-with-property.component.ts#L11) does not work, the service is not injected.

**Expected behavior**
The service should be injected.

**Minimal reproduction of the problem with instructions**

Here is an example generated with Angular CLI 1.0.0:
https://github.com/ebrehault/component-extension-example

**What is the motivation / use case for changing the behavior?**

Adding custom properties (or methods) in a component should not break superclass injected services.

Note: it looks like a regression, as it used to work with Angular 2.4

**Please tell us about your environment:**

Ubuntu 16.10.
npm 3.10.10
served with `ng serve`

* **Angular version:** 4.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome 56
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.2.1

* **Node (for AoT issues):** `node --version` =   
6.10.0

**Comment by DzmitryShylovich** [comment]
http://plnkr.co/edit/rGUqSuwk0pqkn7MsOkHb?p=preview works fine

**Comment by ebrehault** [comment]
True but you use Typescript 2.0.
That one with Typescript 2.2.1 is broken: http://plnkr.co/edit/iDsenqxhVXsMFZK8BFjI?p=preview

**Comment by DzmitryShylovich** [comment]
Confirmed.

cc @chuckjaz

**Comment by zolotyh** [comment]
@ebrehault If you add constructor and code for super call, then all should work fine
```
constructor(service: MyServiceService) {
    super(service);
 }
```

**Comment by Toxicable** [comment]
Yeah I don't see what the issue is here. The base classes constructor is never being called so why would your service ever be defined?

**Comment by GianlucaMaggio** [comment]
As reported here: https://github.com/angular/angular/issues/11606#issuecomment-262315256, Angular Team has implemented this feature and it should work as we expected (an as before Typescript 2.1 was).

**Comment by Toxicable** [comment]
@GianlucaMaggio Oh my mistake, sorry I had not seen that, definitely looks like an issue to me then

**Comment by DzmitryShylovich** [comment]
@ebrehault see https://github.com/angular/angular/issues/14366#issuecomment-289550051
angular is not fully compatible with ts 2.2.x+

**Comment by ebrehault** [comment]
Ok, good to know, thanks :)

**Comment by GianlucaMaggio** [comment]
I tried also with 2.1.x but the problem still exists.

**Comment by DzmitryShylovich** [comment]
Yeah, doesn't work with 2.1.1 either http://plnkr.co/edit/LdAbafO54zcW7TFfkpD3?p=preview

**Comment by GianlucaMaggio** [comment]
Yes, but we cannot use 2.0.10 with Angular 4 due to compatibility issues like`: Typescript: error node_modules/@angular/common/src/platform_id.d.ts(8,42): error TS1039: Initializers are not allowed in ambient contexts.` 

So we are blocked now! Why none recognize it as a **regression**?

**Comment by DzmitryShylovich** [comment]
@GianlucaMaggio just specify the constructor excplicitly

**Comment by GianlucaMaggio** [comment]
@DzmitryShylovich, I'm sorry, we have hundreds of components! We are not "playing" with Angular, we are building a platform on it and this **regression** is important for us!  
We counted a lot on this feature, please fix it @tbosch.

**Comment by tbosch** [comment]
@GianlucaMaggio This is with JIT, right? AOT should work fine...

**Comment by DzmitryShylovich** [comment]
at least with jit. see plunkr https://github.com/angular/angular/issues/15502#issuecomment-289578621

**Comment by DzmitryShylovich** [comment]
@tbosch yeap, it does wirt with aot. ts 2.2.1

**Comment by GianlucaMaggio** [comment]
@tbosch yes, it is JIT.

**Comment by marjan-georgiev** [comment]
Works great! Thanks for the quick fix and release!
