### ISSUE TITLE
Ivy and AOT Enabled compiles but Chrome console has errors

### ISSUE THREAD

**Issue by dmantelli** [angular/angular#35045]
# 🐞 bug report

### Description

 I'm trying to compile my application in Angular 8.2.14 with enableIvy=true and AOT = true. It compiles successfully, but when i run it Chrome console shows an error.

## 🔥 Exception or Error
<pre><code>

Unhandled Promise rejection: Angular JIT compilation failed: '@angular/compiler' not loaded!
  - JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
  - Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
  - Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping. ; Zone: <root> ; Task: Promise.then ; Value: Error: Angular JIT compilation failed: '@angular/compiler' not loaded!
  - JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
  - Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
  - Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping.

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.3.23
Node: 13.3.0
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, service-worker, upgrade

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.23
@angular-devkit/build-angular     0.803.23
@angular-devkit/build-optimizer   0.803.23
@angular-devkit/build-webpack     0.803.23
@angular-devkit/core              7.3.9
@angular-devkit/schematics        8.3.23
@angular/cli                      8.3.23
@angular/pwa                      0.803.23
@ngtools/webpack                  8.3.23
@schematics/angular               8.3.23
@schematics/update                0.803.23
rxjs                              6.5.4
typescript                        3.5.3
webpack                           4.39.2

</code></pre>

**Anything else relevant?**

**Comment by AndrewKushnir** [comment]
Hi @dmantelli, thanks for reporting the issue. Could you please try to update Angular packages to the RC version (`9.0.0-rc.11`) and test the behavior once again? If the problem still exists, please provide a minimum repro case (in a form of GitHub repo), so that we can reproduce the problem and perform further investigation. Thank you.

**Comment by alxhub** [comment]
This error message indicates that part of your application is uncompiled, and is trying to use Angular JIT mode at runtime. To make JIT work, you need:

```
import '@angular/compiler';
```

at the top of your main file. Of course, using JIT at runtime is probably _not_ what you're trying to do. We'll need you to provide a reproduction to investigate further, which should include detailed steps on how you're building and serving this code.

**Comment by peterpeterparker** [comment]
Just gonna let that here.

Today I faced the exact same error. `prod` build was ok but I wasn't able to try out the locally because even if `ionic serve` respectively `ng serve` was ok, I still faced the above error in the browser.

Turns out the update process, run with the command `ng update --next`, had wrongly added a key `aot: true` in the wrong place in my `angular.json`.

```
"app": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "prefix": "app",
      "schematics": {},
         "architect": {
           "build": {
             "builder": "@angular-devkit/build-angular:browser",
             "options": {
                 "aot": true, <-----
```

One removed, problem was solved.

**Comment by alxhub** [comment]
This is actually how it's supposed to work. With Ivy, dev mode (`ng serve`) uses AOT as well.

**Comment by hiepxanh** [comment]
> Turns out the update process, run with the command ng update --next, had wrongly added a key aot: true in the wrong place in my angular.json.

it work correctly sir, this is AOT mode enable on `ng serve` by design

**Comment by peterpeterparker** [comment]
edited my above comment to reflect your feedback respectively that the configuration was correctly added. that being said, in such a case, I wasn't able to use aot while debugging respectively only prod build was ok.

**Comment by hiepxanh** [comment]
> Hi @dmantelli, thanks for reporting the issue. Could you please try to update Angular packages to the RC version (9.0.0-rc.11) and test the behavior once again? If the problem still exists, please provide a minimum repro case (in a form of GitHub repo), so that we can reproduce the problem and perform further investigation. Thank you.

It's weird that I have a workspace have two project that using angular 9 RC 13, the first project work correctly after I fixed few bug (have the same systoms). But it's better that chrome logs the same but the terminal complie with few errors that show addidition information about the problem. Then I can fix it. But the other project complie successful without any problem, that why it hard for me to find out what problem causing. Once I found the real trouble behind, I will create a new repository to report it, not because I'm lazy to provide a example repository. 
BTW, Now I realize a developer that need to be a detective that can guess which code not working even compiler successful.

**Comment by hiepxanh** [comment]
finally, found the problem, it's take me 3 hours with try and guess, seem like angular need better error suggest. 
I'm working with `Ionic` project and find out that it relate to ionic library that I install is have some issues. Detail on here [NGCC post-install script doesn't catch all libraries
](https://github.com/angular/angular/issues/34573)

How to resolve?
`npm i @ionic-native/status-bar@beta @ionic-native/splash-screen@beta @ionic-native/core@beta -S` work for me.

@dmantelli  how about your case? provide the `package.json` and minimum repo, we can help you. Careful with third-party library.

@AndrewKushnir Should I create a PR that add an suggestion to the error that warning developer on console that they could have trouble with third-party library?
 

## Minimal Reproduction

- `ng new sampleApp`
- `cd sampleApp`
- `npm install @ionic-native/core@beta @ionic-native/status-bar@beta`
- Add the following to `app.module.ts`:
```
  import { BrowserModule } from '@angular/platform-browser';
  import { NgModule } from '@angular/core';
+ import { StatusBar } from '@ionic-native/status-bar/ngx'
  import { AppRoutingModule } from './app-routing.module';
  import { AppComponent } from './app.component';

  @NgModule({
    declarations: [
      AppComponent
    ],
    imports: [
      BrowserModule,
      AppRoutingModule
    ],
+   providers: [StatusBar],
    bootstrap: [AppComponent]
  })
  export class AppModule { }
```
Then run it:
- `npm run postinstall`
- `ng serve -o`

# Error:
```
Error: Angular JIT compilation failed: '@angular/compiler' not loaded!
  - JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
  - Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
  - Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping.
```

**Comment by AustineA** [comment]
If anyone ever runs into this. Here's what worked for me
Add this here src/polyfills.ts
`import '@angular/compiler';`

**Comment by alxhub** [comment]
@AustineA that "fix" just causes your application to run in JIT mode, which is likely _not_ what you intend and has significant performance and code size implications.

**Comment by rahulroykumar** [comment]
Hello @alxhub 

Is there a fix for this ? I am also running in to same issue with  "postinstall": "ngcc"
and when I do
"postinstall": " ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points"
or no postinstall script at all
I get below error on browser:

uncaught NullInjectorError: StaticInjectorError(Platform: core)[CompilerFactory]: NullInjectorError: No provider for CompilerFactory!

I am guessing this is due  to ngcc not able to make this party library code ivy compatible..Any pointers on how to fix it?Meanwhile i am just trying to figure out how to find the exact library which might be causing this.

**Comment by JoostK** [comment]
@hiepxanh I am a bit confused by your comment, as this:

> How to resolve?
npm i @ionic-native/status-bar@beta @ionic-native/splash-screen@beta @ionic-native/core@beta -S work for me.

is contradictory to the minimal reproduction you provide (suggesting there is still an issue) which refers to the exact same packages.

Anyway, as noted in #34573 there was in issue with how Ionic packages were bundled, causing ngcc not to process them. This has been resolved with the 5.21.0 release of Ionic, and as such the issue with the `StatusBar` import has been resolved.


@dmantelli From the issue description there is not enough information to investigate your issue. You mention you were using Angular 8.2.14 at the time which is way behind on ngcc/Ivy related fixes, so there's a big chance that the issue may have been fixed in the meantime. As such, could you please try with the latest Angular 9 release and let us know whether your issue has been fixed? If it hasn't, please provide additional information for us to investigate, as otherwise this issue is not actionable.

**Comment by kara** [comment]
>As such, could you please try with the latest Angular 9 release and let us know whether your issue has been fixed? If it hasn't, please provide additional information for us to investigate, as otherwise this issue is not actionable.

Since we don't have anything to investigate here, I'm closing this issue. @dmantelli Please feel free to open a new issue if you have more info.

**Comment by PriyaChotiya** [comment]
Hello all. Facing same issue after update to 9.
After run command ng build --prod 

Error: Angular JIT compilation failed: '@angular/compiler' not loaded!
  - JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
  - Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
  - Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping.

Please help me. Thanks in advance.

**Comment by PriyaChotiya** [comment]
Find one solution . Update all dependencies . and add aot= true in angular.json and add "postinstall": "ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points" in package.json and then delete node_modules and package lock file and agian install which works for me .

**Comment by abhishekssd** [comment]
> Find one solution . Update all dependencies . and add aot= true in angular.json and add "postinstall": "ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points" in package.json and then delete node_modules and package lock file and agian install which works for me .

It does not work i am getting issue on the npm install after i added the postinstall ngcc in package.json  and lead to this issue  https://github.com/angular/angular-cli/issues/16017
`
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! projectname@0.0.0 postinstall: `ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the claimflightsangular6@0.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Win10\AppData\Roaming\npm-cache\_logs\2020-03-14T07_13_42_638Z-debug.log
`

**Comment by abhishekssd** [comment]
> Hello all. Facing same issue after update to 9.
> After run command ng build --prod
> 
> Error: Angular JIT compilation failed: '@angular/compiler' not loaded!
> 
> * JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
> * Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
> * Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping.
> 
> Please help me. Thanks in advance.
Same issue here .. i am also getting this issue when trying to migrate into angular9 from angular8
I did not found any solution till now .
I have checked with ng serve --aot the project is running but when i try with --prod like ng serve --prod or ng build --prod lead me to this issue.
i have found this is due to angular 9 tree shaking and other features the ivy break down the project

**Comment by abhishekssd** [comment]
> > As such, could you please try with the latest Angular 9 release and let us know whether your issue has been fixed? If it hasn't, please provide additional information for us to investigate, as otherwise this issue is not actionable.
> 
> Since we don't have anything to investigate here, I'm closing this issue. @dmantelli Please feel free to open a new issue if you have more info.

Hello Sir,
I am run into the same issue and when i added the postinstall ngcc in package.json i got issue 
polyfills.9d5cc8a05ced6b03d524.js:1 Unhandled Promise rejection: Angular JIT compilation failed: '@angular/compiler' not loaded!
  - JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
  - Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
  - Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping. ; Zone: <root> ; Task: Promise.then ; Value: Error: Angular JIT compilation failed: '@angular/compiler' not loaded!
  - JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
  - Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
  - Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping.
    at X (main.4f8463188acdbc130cbc.js:1)
    at Function.get (main.4f8463188acdbc130cbc.js:1)
    at $e (main.4f8463188acdbc130cbc.js:1)
    at Qa (main.4f8463188acdbc130cbc.js:1)
    at main.4f8463188acdbc130cbc.js:1
    at e.processProvider (main.4f8463188acdbc130cbc.js:1)
    at main.4f8463188acdbc130cbc.js:1
    at main.4f8463188acdbc130cbc.js:1
    at Array.forEach (<anonymous>)
    at Ee (main.4f8463188acdbc130cbc.js:1) Error: Angular JIT compilation failed: '@angular/compiler' not loaded!
  - JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
  - Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
  - Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping.
    at X (http://localhost:4200/main.4f8463188acdbc130cbc.js:1:136563)
    at Function.get (http://localhost:4200/main.4f8463188acdbc130cbc.js:1:196749)
    at $e (http://localhost:4200/main.4f8463188acdbc130cbc.js:1:142897)
    at Qa (http://localhost:4200/main.4f8463188acdbc130cbc.js:1:202240)
    at http://localhost:4200/main.4f8463188acdbc130cbc.js:1:200460
    at e.processProvider (http://localhost:4200/main.4f8463188acdbc130cbc.js:1:200474)
    at http://localhost:4200/main.4f8463188acdbc130cbc.js:1:200258
    at http://localhost:4200/main.4f8463188acdbc130cbc.js:1:139481
    at Array.forEach (<anonymous>)
    at Ee (http://localhost:4200/main.4f8463188acdbc130cbc.js:1:139428)
i have also observed when i serve on localhost with ng serve the code works well and there is no issue comes in console but when i try to build or serve with ng build --prod and ng serve --prod the chrome has issue of jit.
i did not get any issue for the issue please help

**Comment by nanijnv1** [comment]
> Just gonna let that here.
> 
> Today I faced the exact same error. `prod` build was ok but I wasn't able to try out the locally because even if `ionic serve` respectively `ng serve` was ok, I still faced the above error in the browser.
> 
> Turns out the update process, run with the command `ng update --next`, had **correctly** added a key `aot: true` in in my `angular.json` to activate lazy loading on local serve too.
> 
> ```
> "app": {
>       "root": "",
>       "sourceRoot": "src",
>       "projectType": "application",
>       "prefix": "app",
>       "schematics": {},
>          "architect": {
>            "build": {
>              "builder": "@angular-devkit/build-angular:browser",
>              "options": {
>                  "aot": true, <-----
> ```
> 
> As I didn't found any solution for the problem, I removed the option to not use aot when debugging.

Yeah It worked for me, maybe we should not use aot : true when  debugging
