### ISSUE TITLE
primeng not working with ngcc

### ISSUE THREAD

**Issue by sergey-morenets** [angular/angular#30565]
# 🐞 Bug report

### Command (mark with an `x`)
ng build --prod

### Is this a regression?
No 

### Description

I have a project with PrimeNg dependency. When I upgraded to 8.0.0-rc.1 my project compiled properly. But if I enable Ivy flag in tsconfig.json:

  "angularCompilerOptions": {
    "enableIvy": true,
    "allowEmptyCodegenFiles": true
  },

I get a lot of error messages about incorrect module usage when I build the project.

## 🔬 Minimal Reproduction

1. Create new project with Angular CLI 8.0.0-rc.1
2. Add Primeng dependency and import its modules into AppModule.

## 🔥 Exception or Error
<pre><code>
ERROR in node_modules/primeng/components/confirmdialog/confirmdialog.d.ts(64,22): error TS-996002: Appears in the NgModule.imports of SharedModule, but could not be resolved to an NgModule class
node_modules/ngx-filter-pipe/src/app/shared/ngx-filter-pipe/ngx-filter.module.d.ts(1,22): error TS-996002: Appears in the NgModule.imports of SharedModule, but could not be resolved to an NgModule class
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.0.0-rc.1
Node: 11.3.0
OS: win32 x64
Angular: 8.0.0-rc.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-rc.1
@angular-devkit/build-angular     0.800.0-rc.1
@angular-devkit/build-optimizer   0.800.0-rc.1
@angular-devkit/build-webpack     0.800.0-rc.1
@angular-devkit/core              8.0.0-rc.1
@angular-devkit/schematics        8.0.0-rc.1
@angular/cdk                      8.0.0-beta.2
@angular/http                     8.0.0-beta.10+1.sha-a28b3e3
@angular/material                 8.0.0-beta.2
@ngtools/webpack                  8.0.0-rc.1
@schematics/angular               8.0.0-rc.1
@schematics/update                0.800.0-rc.1
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0

</code></pre>

**Comment by speige** [comment]
@sergey-morenets You might consider opening an issue with primeng asking them to use https://github.com/ng-packagr/ng-packagr when publishing to npm. I'm the author of https://github.com/rintoj/ngx-virtual-scroller & my library also broke ivy until I used ng-packagr.

**Comment by sergey-morenets** [comment]
Hi @speige 

I would love to do that. But I doubt I have enough technical skills to explain in details what should be changed on PrimeNg side. I guess the Angular team member will do it better and in cleaner way.

I also found an issue that might relate to the current ticket: https://github.com/primefaces/primeng/issues/7627

**Comment by sergey-morenets** [comment]
@speige Any updates on this? PrimeNG team recently released 8.0 but it's not compatible with Angular 8.2.0-next.1 in Ivy mode.

**Comment by leo6104** [comment]
I create ng-packagr replacement PR in PrimeNG. 
https://github.com/primefaces/primeng/pull/8058 
If anyone in angular team can review this PR, please comment on the PR. I will apply the comments.

**Comment by JonWallsten** [comment]
@alxhub: This is a problem in my monorepo as well. Now when you have fixed https://github.com/angular/angular/issues/33562 (thanks alot for that), this is the next blocker. It can be reproduced in the same monorepo I gave you access to in the issue mentioned.

**Comment by manughub** [comment]
@petebacondarwin @mgechev is this resolved ?

**Comment by virshu** [comment]
It works for me in 9.0.0-rc3 and rc4

**Comment by petebacondarwin** [comment]
@JonWallsten can you check whether the latest primeng is now working for you too?

**Comment by JonWallsten** [comment]
@petebacondarwin: My issue is not directly related to primeeng. I have the same issue, but with @angular/material and my own packages. But I've created a separate ticket for that since I wrote this. You can close this is it's fixed.

**Comment by petebacondarwin** [comment]
Thanks @JonWallsten and @virshu.

**Comment by piotrbrzuska** [comment]
hello, I have this error again with angular version 9.0.0-rc.7 (with 9.0.0-rc.6 it works)

**Comment by petebacondarwin** [comment]
@piotrbrzuska - could you give some more details of your error?

**Comment by piotrbrzuska** [comment]
nevermind, I'm testing it again and it looks like it works
