### ISSUE TITLE
When upgrading to 5.0.0-beta ngc fails to compile

### ISSUE THREAD

**Issue by steveblue** [angular/angular#19019]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When upgrading from 4.3.6 to 5.0.0-beta (any version), ngc fails to compile any ngfactory files in the `genDir`. 

## Expected behavior

`ngc` should be able to compile using same config as 4.3.6
`ngc` should print an ERROR in terminal

## Minimal reproduction of the problem with instructions

The issue is replicated on[ this branch of the angular2-rollup starter](https://github.com/steveblue/angular2-rollup/tree/feature/5.0.0-support). 

All that is changed from `4.3.6` is the version number for `@angular` packages in the package.json.

Clone the repo from and checkout the 5.0.0-support branch 
Follow install instructions in README.md
Run `ngr --build prod --serve`

Notice the ERROR

```
LOG ngc started compiling ngfactory 
main.prod.ts(9,36): error TS2307: Cannot find module './ngfactory/tmp/app/app.module.ngfactory'.

WARN main.prod.ts(9,36): error TS2307: Cannot find module './ngfactory/tmp/app/app.module.ngfactory'.
```

This is because `ngc` fails to compile any `ngfactory` files. `tsconfig.prod.json` is where ngc is configured. 

```
 "files": [
    "./tmp/app/app.module.ts",
    "main.prod.ts"
  ],
```

In 4.3.6, `ngc` would compile `app.module.ngfactory.ts` before moving onto `main.prod.ts`.

In 5.0.0-beta `ngc` fails to compile `app.module.ngfactory.ts`

## What is the motivation / use case for changing the behavior?

Better error handling here could help to resolve the issue for other users. 
angular2-rollup cannot be built for AOT until this is resolved.

## Environment

<pre><code>
Angular version: 5.0.0-beta.4- 5.0.0-beta.6 tested

For Tooling issues:
- Node version: 6.5.0  
- Platform:  MacOS 

Others:

</code></pre>

**Comment by steveblue** [comment]
I think this is more of a support request so I am closing. I am guessing there is a change in how `ngc` compiles, omitting ngfactory files that I need to consider.
