### ISSUE TITLE
Error after upgrade to 8.0.0-beta.6 setNgClass is not a function and applyChanges is not a function

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular#29088]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

`"@angular/common": "8.0.0-beta.6",`

### Is this a regression?

 Yes, the previous version in which this bug was not present was: "@angular/common": "8.0.0-beta.5",

### Description

After upgrading my app to Angular 8.0.0-beta.6. I started receiving below errors:

```
core.js:4699 ERROR TypeError: this._delegate.setNgClass is not a function
    at NgClass.set [as ngClass] (common.js:3241)
    at DefaultClassDirective.push../node_modules/@angular/flex-layout/esm5/extended.es5.js.ClassDirective.updateWithValue (extended.es5.js:207)
    at MediaMarshaller.push../node_modules/@angular/flex-layout/esm5/core.es5.js.MediaMarshaller.updateElement (core.es5.js:3309)
    at MediaMarshaller.push../node_modules/@angular/flex-layout/esm5/core.es5.js.MediaMarshaller.setValue (core.es5.js:3197)
    at DefaultClassDirective.push../node_modules/@angular/flex-layout/esm5/core.es5.js.BaseDirective2.setValue (core.es5.js:605)
    at core.es5.js:443
    at Array.forEach (<anonymous>)
    at DefaultClassDirective.push../node_modules/@angular/flex-layout/esm5/core.es5.js.BaseDirective2.ngOnChanges (core.es5.js:437)
    at checkAndUpdateDirectiveInline (core.js:17257)
    at checkAndUpdateNodeInline (core.js:25086)
defaultErrorLogger @ core.js:4699
8core.js:4699 ERROR TypeError: this._delegate.applyChanges is not a function
    at NgClass.push../node_modules/@angular/common/fesm5/common.js.NgClass.ngDoCheck (common.js:3246)
    at DefaultClassDirective.push../node_modules/@angular/flex-layout/esm5/extended.es5.js.ClassDirective.ngDoCheck (extended.es5.js:225)
    at checkAndUpdateDirectiveInline (core.js:17264)
    at checkAndUpdateNodeInline (core.js:25086)
    at checkAndUpdateNode (core.js:25048)
    at prodCheckAndUpdateNode (core.js:25589)
    at Object.eval [as updateDirectives] (MyComponent.ngfactory.js:112)
    at Object.updateDirectives (core.js:25377)
    at checkAndUpdateView (core.js:25030)
    at callViewAction (core.js:25271)
```

When I downgraded the package **@angular/common** to **8.0.0-beta.5** it started working fine.

I initially thought I should report this error to `@angular/flex-layout` repo, but then I thought that since downgrading **@angular/common** to **8.0.0-beta.5** fixes problem, it could be an issue with **@angular/common** package.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.0.0-beta.4
Node: 8.11.4
OS: win32 x64
Angular: 8.0.0-beta.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.14.0-beta.0
@angular-devkit/build-angular      0.14.0-beta.0
@angular-devkit/build-optimizer    0.14.0-beta.0
@angular-devkit/build-webpack      0.14.0-beta.0
@angular-devkit/core               8.0.0-beta.0
@angular-devkit/schematics         8.0.0-beta.0
@angular/cdk                       7.3.3
@angular/cdk-experimental          7.3.2
@angular/cli                       8.0.0-beta.4
@angular/fire                      5.1.0
@angular/flex-layout               7.0.0-beta.23
@angular/material                  7.3.3
@angular/material-moment-adapter   7.3.3
@angular/pwa                       0.14.0-beta.0
@ngtools/webpack                   8.0.0-beta.0
@schematics/angular                8.0.0-beta.0
@schematics/update                 0.14.0-beta.4
rxjs                               6.4.0
typescript                         3.2.4
webpack                            4.29.3
</code></pre>

**Comment by alexzuza** [comment]
I suspect it might be due to the following code:

https://github.com/angular/flex-layout/blob/master/src/lib/extended/class/class.ts#L44-L50

flex-layout library extends base ngClass directive and **if you didn't have CommonModule imported in module where you have failed component** then it causes such an error.

**Comment by pkozlowski-opensource** [comment]
> I suspect it might be due to the following code:

Yes, flex-layout is using private APIs - see https://github.com/angular/angular/blob/master/docs/PUBLIC_API.md where it is stated:

> We explicitly don't consider the following to be our public API surface:
> * constructors of injectable classes (services and directives) - please use DI to obtain instances of these classes
> * extending any of our classes unless the support for this is specifically documented in the API docs

This ultimately needs to be reported & fixed in flex-layout and I think that @matsko was working on this. Closing this ticket here as it belongs to flex-layout
