### PR TITLE
docs(docs-infra): Signal forms custom validator with 'fieldTree' fiel…

### LINKED ISSUE #66687: Signal forms custom validator with 'fieldTree' field in validation result error
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

Yes

### Description

After upgrading to 21.1.0 and with the removal customError() from signal forms returning ValidationError from custom validator results in compilation error.

Documentation https://angular.dev/guide/forms/signals/validation#using-validate has an example. It does not state that 'fieldTree' works only in submit function, but have a comment in the example code.

```typescript
interface DTO {
  firstName: string;
  lastName: string;
}

export class App {
  private readonly model = model<DTO>({
    firstName: '',
    lastName: '',
  });

  protected readonly form = form(this.model, (path) => {
    validate(path, (ctx) => {
      if (ctx.valueOf(path.firstName).length < 5) {
        return {
          kind: 'test',
          message: 'Message',
          fieldTree: path.lastName, // or ctx.fieldTree.lastName
        };
      }
      return null;
    });    
  });
}
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-8ik35v9w?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
Argument of type '(ctx: RootFieldContext<DTO>) => { kind: string; message: string; fieldTree: SchemaPath<string, 1, Child>; } | null' is not assignable to parameter of type 'FieldValidator<DTO, Root>'.
  Type '{ kind: string; message: string; fieldTree: SchemaPath<string, 1, Child>; } | null' is not assignable to type 'ValidationResult<WithoutField>'.
    Type '{ kind: string; message: string; fieldTree: SchemaPath<string, 1, PathKind.Child>; }' is not assignable to type 'ValidationResult<WithoutField>'.
      Type '{ kind: string; message: string; fieldTree: SchemaPath<string, 1, PathKind.Child>; }' is not assignable to type 'WithoutField'.
        Types of property 'fieldTree' are incompatible.
          Type 'SchemaPath<string, 1, Child>' is not assignable to type 'undefined'.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI       : 21.1.0
Angular           : 21.1.0
Node.js           : 24.12.0
Package Manager   : npm 11.7.0
Operating System  : win32 x64

┌───────────────────────────────────┬───────────────────┬───────────────────┐
│ Package                           │ Installed Version │ Requested Version │
├───────────────────────────────────┼───────────────────┼───────────────────┤
│ @angular-devkit/build-angular     │ 21.1.0            │ 21.1.0            │
│ @angular-devkit/core              │ 21.1.0            │ 21.1.0            │
│ @angular-devkit/schematics        │ 21.1.0            │ 21.1.0            │
│ @angular/animations               │ 21.1.0            │ 21.1.0            │
│ @angular/build                    │ 21.1.0            │ 21.1.0            │
│ @angular/cdk                      │ 21.1.0            │ 21.1.0            │
│ @angular/cli                      │ 21.1.0            │ 21.1.0            │
│ @angular/common                   │ 21.1.0            │ 21.1.0            │
│ @angular/compiler                 │ 21.1.0            │ 21.1.0            │
│ @angular/compiler-cli             │ 21.1.0            │ 21.1.0            │
│ @angular/core                     │ 21.1.0            │ 21.1.0            │
│ @angular/forms                    │ 21.1.0            │ 21.1.0            │
│ @angular/google-maps              │ 21.1.0            │ 21.1.0            │
│ @angular/language-service         │ 21.1.0            │ 21.1.0            │
│ @angular/localize                 │ 21.1.0            │ 21.1.0            │
│ @angular/material                 │ 21.1.0            │ 21.1.0            │
│ @angular/platform-browser         │ 21.1.0            │ 21.1.0            │
│ @angular/platform-browser-dynamic │ 21.1.0            │ 21.1.0            │
│ @angular/pwa                      │ 21.1.0            │ 21.1.0            │
│ @angular/router                   │ 21.1.0            │ 21.1.0            │
│ @angular/service-worker           │ 21.1.0            │ 21.1.0            │
│ @schematics/angular               │ 21.1.0            │ 21.1.0            │
│ rxjs                              │ 7.8.2             │ ~7.8.0            │
│ typescript                        │ 5.9.3             │ ^5.9.3            │
└───────────────────────────────────┴───────────────────┴───────────────────┘
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by aparzi**
Signal forms custom validator with 'fieldTree' field in validation result error
Update docs for fieldTree property

fixes #66687

## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular/blob/main/contributing-docs/commit-message-guidelines.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] angular.dev application / infrastructure changes
- [ ] Other... Please describe:

Issue Number: #66687

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

File: adev/src/content/guide/forms/signals/validation.md [hunk 1]
```diff
@@ -474,6 +476,57 @@ return [
...
+      <label>
+        First Name
+        <input [formField]="userForm.firstName" />
+      </label>
+      <label>
+        Last Name
+        <input [formField]="userForm.lastName" />
+      </label>
+    </form>
+  `,
```
Comment (JeanMeche) [inline adev/src/content/guide/forms/signals/validation.md]: We can skip the template as it doesn't affect validation

File: adev/src/content/guide/forms/signals/validation.md [hunk 2]
```diff
@@ -474,6 +476,57 @@ return [
...
+  readonly userModel = model<DTO>({
+    firstName: '',
+    lastName: '',
+  });
+
+  userForm = form(this.userModel, (path) => {
+    validateTree(path, (ctx) => {
+      if (ctx.valueOf(path.firstName).length < 5) {
+        return {
+          kind: 'test',
```
Comment (JeanMeche) [inline adev/src/content/guide/forms/signals/validation.md]: We probably would want a better `kind` here.

File: adev/src/content/guide/forms/signals/validation.md [hunk 3]
```diff
@@ -474,6 +476,42 @@ return [
 ];
 ```
 
+The `validateTree()` function creates custom validation rules that can target multiple fields or provide complex validation logic for a whole subtree. It is particularly useful when using a `model()` for your form state.
```
Comment (JeanMeche) [inline adev/src/content/guide/forms/signals/validation.md]:
```suggestion
The `validateTree()` function creates custom validation rules that can target multiple fields or provide complex validation logic for a whole subtree.
```
This isn't specifc to `model`.

File: adev/src/content/guide/forms/signals/validation.md [hunk 4]
```diff
@@ -474,6 +476,42 @@ return [
...
+  readonly userModel = model<DTO>({
+    firstName: '',
+    lastName: '',
+  });
+
+  userForm = form(this.userModel, (path) => {
+    validateTree(path, (ctx) => {
+      if (ctx.valueOf(path.firstName).length < 5) {
+        return {
+          kind: 'minLength',
```
Comment (JeanMeche) [inline adev/src/content/guide/forms/signals/validation.md]:
```suggestion
          kind: 'minLength5',
```

`'minLength'` is already the `kind` specified by `MinLengthValidationError`.

File: adev/src/content/guide/forms/signals/validation.md [hunk 5]
```diff
@@ -474,6 +476,42 @@ return [
 ];
 ```
 
+The `validateTree()` function creates custom validation rules that can target multiple fields or provide complex validation logic for a whole subtree. It is particularly useful when using a `model()` for your form state.
+
+```angular-ts
+import {Component, model} from '@angular/core';
+import {form, FormField, validateTree} from '@angular/forms/signals';
+
+interface DTO {
```
Comment (JeanMeche) [inline adev/src/content/guide/forms/signals/validation.md]:
```suggestion
interface User {
```
`DTO` is too generic of a name, we should be providing meaningful examples

File: adev/src/content/guide/forms/signals/validation.md [hunk 6]
```diff
@@ -474,6 +476,42 @@ return [
...
+import {Component, model} from '@angular/core';
+import {form, FormField, validateTree} from '@angular/forms/signals';
+
+interface User {
+  firstName: string;
+  lastName: string;
+}
+
+@Component({})
+export class UserFormComponent {
```
Comment (SkyZeroZx) [inline adev/src/content/guide/forms/signals/validation.md:496]: We can avoid suffix `Component` to align with style guidelines , in another way we can use a placeholder for the template to follow similar styles in adev
```ts
@Component({ /* ... */ })
```

**Comment by aparzi** [comment]
PR updated

File: adev/src/content/guide/forms/signals/validation.md
Comment (leonsenft) [inline adev/src/content/guide/forms/signals/validation.md]: Let's remove this snippet since it's out of place. Submission should be covered elsewhere.

File: adev/src/content/guide/forms/signals/validation.md [hunk 7]
```diff
@@ -461,6 +461,8 @@ export class UrlFormComponent {
 }
 ```
 
+### Using validateTree()
```
Comment (leonsenft) [inline adev/src/content/guide/forms/signals/validation.md:480]: Can we move this section to the end (right before `### Reusable validation rules`)? I think it makes sense to keep the remaining part of this section under `### Using validate()`

**Review by leonsenft — CHANGES_REQUESTED** [review]

File: adev/src/content/guide/forms/signals/validation.md (hunk 7 above)
Comment (aparzi) [reply adev/src/content/guide/forms/signals/validation.md:480]: It should already be like this

Comment (leonsenft) [reply adev/src/content/guide/forms/signals/validation.md:480]: I meant the section beginning with

> The validator function receives a `FieldContext` object with:

Should remain under `### Using validate()` _before_ the `### Using validateTree()` section.

**Review by leonsenft — CHANGES_REQUESTED** [review]

**Comment by JeanMeche** [comment]
To capture a discussion we had, we should consider a more meaningful example. 
The current one works, but there’s likely a better way to illustrate the feature.

File: adev/src/content/guide/forms/signals/validation.md [hunk 8]
```diff
@@ -490,6 +477,44 @@ NOTE: Child fields also have a `key` signal, and array item fields have both `ke
...
+        };
+      }
+
+      return null;
+    });
+  });
+}
+```
+
+The `validateTree()` validator function receives a `ValidationContext` object that provides access to the values and states of all fields in the tree.
```
Comment (leonsenft) [inline adev/src/content/guide/forms/signals/validation.md]: It's `FieldContext`, not `ValidationContext`:

```suggestion
The `validateTree()` validator function receives the same `FieldContext` object as `validate()`.
```

**Review by leonsenft — CHANGES_REQUESTED** [review]
Please address the lint failure.

**Review by leonsenft — APPROVED** [review]

**Comment by leonsenft** [comment]
The correct commit type is just `docs:`:

> `docs-infra:` used for infrastructure changes to the docs-app (angular.dev) within the /adev directory, such as application code, tooling, or configuration. For modifications to documentation content (e.g., editing a .md file), use docs: without a scope instead.

https://github.com/angular/angular/blob/main/contributing-docs/commit-message-guidelines.md#-scope

**Review by leonsenft — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
This PR was merged into the repository. The changes were merged into the following branches:

- main: 63d828aa339365b7b563b42eec9c0b27a33babf0
- 21.1.x: 054972c8e021089f385e085f9cd8b8ab9ecb82e8
