### ISSUE TITLE
Ivy: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).

### ISSUE THREAD

**Issue by kccsf** [angular/angular#31160]
# 🐞 bug report

### Affected Package
@angular/material
@angular/flex-layout

### Is this a regression?
Yes - works prior to building with Ivy.

### Description

 Building with Ivy causes .d.ts files to be modified. As part of those modifications, the following line is added:
    `static ngBaseDef: ɵngcc0.ɵɵBaseDef;`

This causes the build to fail. Switching 'enableIvy' back to false still results in a broken build due to the .d.ts file modifications (although the 'WARNING' lines disappear).

## 🔬 Minimal Reproduction

https://github.com/kccsf/IvyIssue

## 🔥 Exception or Error
<pre><code>

WARNING in Unknown member type: "[key: string]: (data: any) => void;

WARNING in Unknown member type: "[key: string]: (data: any) => void;

WARNING in Unknown member type: "[key: string]: (data: any) => void;

ERROR in node_modules/@angular/flex-layout/extended/typings/class/class.d.ts(30,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
node_modules/@angular/flex-layout/extended/typings/img-src/img-src.d.ts(38,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
node_modules/@angular/flex-layout/flex/typings/flex/flex.d.ts(50,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
node_modules/@angular/flex-layout/grid/typings/align-columns/align-columns.d.ts(28,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
node_modules/@angular/flex-layout/grid/typings/align-rows/align-rows.d.ts(28,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
node_modules/@angular/flex-layout/grid/typings/areas/areas.d.ts(31,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
node_modules/@angular/flex-layout/grid/typings/auto/auto.d.ts(31,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
node_modules/@angular/flex-layout/grid/typings/columns/columns.d.ts(32,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
node_modules/@angular/flex-layout/grid/typings/gap/gap.d.ts(31,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
node_modules/@angular/flex-layout/grid/typings/rows/rows.d.ts(32,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
node_modules/@angular/material/menu/typings/menu.d.ts(161,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.1.0-beta.2
Node: 10.15.3
OS: win32 x64
Angular: 8.1.0-next.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.0-beta.2
@angular-devkit/build-angular     0.801.0-beta.2
@angular-devkit/build-optimizer   0.801.0-beta.2
@angular-devkit/build-webpack     0.801.0-beta.2
@angular-devkit/core              8.1.0-beta.2
@angular-devkit/schematics        8.1.0-beta.2
@angular/cdk                      8.0.0
@angular/cli                      8.1.0-beta.2
@angular/flex-layout              8.0.0-beta.26
@angular/material                 8.0.1
@ngtools/webpack                  8.1.0-beta.2
@schematics/angular               8.1.0-beta.2
@schematics/update                0.801.0-beta.2
rxjs                              6.3.3
typescript                        3.4.5
webpack                           4.34.0

</code></pre>

**Anything else relevant?**

**Comment by magnattic** [comment]
This seems to happen when a Directive inherits from another class (that doesn't have any metadata).

I have the same problem when I compile my library that uses angular-l10n:
https://github.com/robisim74/angular-l10n/issues/253

The base class that causes the problem is this one:
https://github.com/robisim74/angular-l10n/blob/master/src/models/base-directive.ts

**Comment by magnattic** [comment]
Apparently this is a regression in 8.1.0, it works fine with 8.0.0 and enableIvy: true.

See the discussion on https://github.com/robisim74/angular-l10n/issues/253

**Comment by aeslinger0** [comment]
I hope this is resolved quickly. This is a blocker for me. Is there a work-around for this? I got this when I enabled Ivy, so I disabled Ivy, but I'm still getting the errors!

**Comment by kccsf** [comment]
@aeslinger0 Now that you have switched off Ivy, reinstall the affected package(s) (ie in the case of this original issue, material/flex-layout) so that the modified files are reverted.

**Comment by fclemonschool** [comment]
I have same error at 8.1.0-rc.0 with ngx-simple-modal(1.3.13).
So, I reinstall package and switched off ivy.

**Comment by petebacondarwin** [comment]
This is a known issue and is being actively worked on. cc @alxhub

**Comment by sergey-morenets** [comment]
@petebacondarwin  Was this issue fixed? It reproduces for me with Angular 8.1.0

**Comment by JoostK** [comment]
> @petebacondarwin Was this issue fixed? It reproduces for me with Angular 8.1.0

Ivy changes are only in `next` tagged releases. That's 8.2.0-next.0 atm

**Comment by petebacondarwin** [comment]
And this fix did make it onto 8.2.0-next.0

**Comment by vasyliv** [comment]
has the same bug
```

ERROR in ../node_modules/@angular/material/menu/typings/menu.d.ts:161:23 - error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).

161     static ngBaseDef: ɵngcc0.ɵɵBaseDef;
                          ~~~~~~~~~~~~~~~~
../node_modules/@renet-consulting/external-auth/lib/external-auth.base.d.ts:31:23 - error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).

31     static ngBaseDef: ɵngcc0.ɵɵBaseDef;
                         ~~~~~~~~~~~~~~~~
../node_modules/@renet-consulting/ngx-mat-input/lib/input.base.d.ts:39:23 - error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).

39     static ngBaseDef: ɵngcc0.ɵɵBaseDef;
                         ~~~~~~~~~~~~~~~~

```

**Comment by petebacondarwin** [comment]
@vasyliv - do you mean that you have a new instance of this bug using the `next` Angular version? If so, can you provide more information on how we can reproduce it?

**Comment by Desnoo** [comment]
@petebacondarwin This is still an issue with angular@next.
`ℹ ｢wds｣: Project is running at http://0.0.0.0:4200/webpack-dev-server/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: 404s will fallback to //index.html
 14% building 41/42 modules 1 active /home/xxx/client/node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!/home/xxx/client/node_modules/postcss-loader/src/index.js??embedded!/home/xxx/client/node_modules/sass-loader/lib/loader.js??ref--13-3!/h                                                                                               y chunk {main} main.js, main.js.map (main) 1.87 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 667 bytes [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.09 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 20.2 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 601 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 338 kB [initial] [rendered]
Date: 2019-07-10T09:43:28.002Z - Hash: f60fafe3ccbed8e0415b - Time: 234272ms
                                                                                                                                                                                                   a WARNING in Unknown member type: "[key: string]: (data: any) => void;                                                                               

ERROR in ../node_modules/@angular/material/menu/typings/menu.d.ts:161:23 - error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).

161     static ngBaseDef: ɵngcc0.ɵɵBaseDef;
                          ~~~~~~~~~~~~~~~~

** Angular Live Development Server is listening on 0.0.0.0:4200, open your browser on http://localhost:4200/ **
ℹ ｢wdm｣: Failed to compile.
ℹ ｢wdm｣: Compiling...
 70% building 100/100 modules 0 active                                                                                                                                                             n     ERROR in node_modules/@angular/material/menu/typings/menu.d.ts(161,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
    
 93% after chunk asset optimization SourceMapDevToolPlugin polyfills.js attach SourceM                                                                                                             r Date: 2019-07-10T09:44:33.068Z - Hash: 0b906827c5d995f9fa77         
2 unchanged chunks
chunk {xxx-module} xxx-module.js,xxx-module.js.map (xxx-module) 9.78 kB  [rendered]
chunk {main} main.js, main.js.map (main) 4.54 MB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 323 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 9 kB [entry] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 9.22 MB [initial] [rendered]
Time: 63134ms
ℹ ｢wdm｣: Compiled successfully.
`
Are any further information required?

**Comment by JoostK** [comment]
@Desnoo I am surprises there's the following in the list of versions:

```
@angular/compiler                   8.1.0
@angular/compiler-cli               8.1.0
```

Both of these should also be `8.2.0-next.0`, as the compiler packages are the most important to be up-to-date to fix this issue. Could you try again after updating those packages?

**Comment by Desnoo** [comment]
@JoostK Thanks for your fast reply. I missed to update those dependencies. After updating the packages, no further error occured. Thanks.

**Comment by centogram** [comment]
+1 updating those packages worked for me as well.

**Comment by philipschikora** [comment]
+1 worked

**Comment by BojanKogoj** [comment]
That fixes this error, but I now get the error as in this issue https://github.com/angular/flex-layout

**Comment by duard** [comment]
```
Date: 2019-07-19T17:57:58.970Z
Hash: 6b925fae8ae00c4a2c42
Time: 63764ms
chunk {main} main.js, main.js.map (main) 1.97 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 717 bytes [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 186 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 330 kB [initial] [rendered]

WARNING in Unknown member type: "[key: string]: (data: any) => void;

ERROR in node_modules/@angular/flex-layout/extended/typings/class/class.d.ts(30,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
node_modules/@angular/flex-layout/extended/typings/img-src/img-src.d.ts(38,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
node_modules/@angular/flex-layout/flex/typings/flex/flex.d.ts(50,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
node_modules/@angular/flex-layout/grid/typings/align-columns/align-columns.d.ts(28,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
node_modules/@angular/flex-layout/grid/typings/align-rows/align-rows.d.ts(28,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
node_modules/@angular/flex-layout/grid/typings/areas/areas.d.ts(31,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
node_modules/@angular/flex-layout/grid/typings/auto/auto.d.ts(31,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
node_modules/@angular/flex-layout/grid/typings/columns/columns.d.ts(32,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
node_modules/@angular/flex-layout/grid/typings/gap/gap.d.ts(31,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
node_modules/@angular/flex-layout/grid/typings/rows/rows.d.ts(32,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).

** Angular Live Development Server is listening on redecomprecerto.sigpharma.xyz:4200, open your browser on http://redecomprecerto.sigpharma.xyz:4200/ **
ℹ ｢wdm｣: Failed to compile.
ℹ ｢wdm｣: Compiling...
                                                                                          
Date: 2019-07-19T17:58:03.508Z - Hash: 85913cef8251329a3657 - Time: 4177ms
2 unchanged chunks
chunk {main} main.js, main.js.map (main) 16.5 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 130 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 4.15 MB [initial] [rendered]
ℹ ｢wdm｣: Compiled successfully.
    
    ERROR in node_modules/@angular/flex-layout/extended/typings/class/class.d.ts(30,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
    node_modules/@angular/flex-layout/extended/typings/img-src/img-src.d.ts(38,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
    node_modules/@angular/flex-layout/flex/typings/flex/flex.d.ts(50,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
    node_modules/@angular/flex-layout/grid/typings/align-columns/align-columns.d.ts(28,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
    node_modules/@angular/flex-layout/grid/typings/align-rows/align-rows.d.ts(28,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
    node_modules/@angular/flex-layout/grid/typings/areas/areas.d.ts(31,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
    node_modules/@angular/flex-layout/grid/typings/auto/auto.d.ts(31,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
    node_modules/@angular/flex-layout/grid/typings/columns/columns.d.ts(32,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
    node_modules/@angular/flex-layout/grid/typings/gap/gap.d.ts(31,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).
    node_modules/@angular/flex-layout/grid/typings/rows/rows.d.ts(32,23): error TS2314: Generic type 'ɵɵBaseDef<T>' requires 1 type argument(s).

```

![ivy](https://user-images.githubusercontent.com/36894/61555412-bd741200-aa35-11e9-9dd4-ba5c295aa006.png)

**Comment by pim3nt3l** [comment]
I solved it modifying the line **166** of the file **node_modules/@angular/material/menu/typings/menu.d.ts** and leave it as bellow

static ngBaseDef: ɵngcc0.ɵɵBaseDef<_MatMenuBase>;

**Comment by ErVishalM** [comment]
> I solved it modifying the line **166** of the file **node_modules/@angular/material/menu/typings/menu.d.ts** and leave it as bellow, it appears to be a type missing to define correctly the var ngBaseDef
> 
> static ngBaseDef: ɵngcc0.ɵɵBaseDef<_MatMenuBase>;
> 
> I tested the app and its appears to be working at all

It fixed this error but got new error - https://github.com/ag-grid/ag-grid/issues/3281
Can you look into it. If i enable the ivy mode then it is giving me error otherwise it is working fine.

**Comment by agroves333** [comment]
Using the following packages with Ivy enabled:
```
"@angular/compiler": "^8.2.0-next.0",
"@angular/compiler-cli": "^8.2.0-next.0",
```
And getting this error which also seems related so I'll post here:
```
ERROR in ./node_modules/@angular/router/__ivy_ngcc__/fesm5/router.js 4741:8-29
"export 'ɵɵhostProperty' (imported as 'ɵngcc0') was not found in '@angular/core'
ERROR in ./src/app/pages/vehicle/vehicle.ts 100:4-23
"export 'ɵɵstyleSanitizer' (imported as 'i0') was not found in '@angular/core'
ERROR in ./src/app/components/image-card/image-card.component.ts 56:12-31
"export 'ɵɵstyleSanitizer' (imported as 'i0') was not found in '@angular/core'
ERROR in ./src/app/pages/event/event.ts 317:12-31
"export 'ɵɵstyleSanitizer' (imported as 'i0') was not found in '@angular/core'
```

**Comment by petebacondarwin** [comment]
@agroves333 can you confirm that you have updated all the `@angular/...` dependencies?

**Comment by willkara** [comment]
Looks like this is still broken by default when running `ng new App` and then enabling Ivy.

I was able to fix it by making the cli/compiler version changes.

Is there an ETA on when it'll be fixed on a stable version?

**Comment by mahdiprog** [comment]
same here

**Comment by benelliott** [comment]
@petebacondarwin I'm still seeing this bug on 8.0.0-next.8, with type errors springing up for .d.ts entries for abstract superclasses (without metadata) for concrete components. Would you like me to try to create a reproduction or are you aware of the issue?

**Comment by JoostK** [comment]
@benelliott we are aware of that issue, it's a slight variation of the one reported here. A compilation error occurs for base classes without `@Directive()` decorator that require generic type arguments themselves.

You can probably workaround that issue by adding the `@Directive()` decorator to the base class, which ensures that an `ngDirectiveDef` is produced instead of the `ngBaseDef`; the former does not suffer from the same bug.

**Comment by benelliott** [comment]
@JoostK Thanks - is there a separate issue I can follow for that one?

The typedefs are coming from an internal library - AFAIK selectorless directives are only supported on v9+ so I couldn't add that to my library without breaking compat for v8 right?

**Comment by JoostK** [comment]
@benelliott There's no github issue at the moment. The plan is to get rid of `ngBaseDef` altogether, so no effort has been put into fixing this issue. Feel free to open an issue for tracking purposes, if you like.

Your point regarding backwards compatibility is a valid concern for which I don't know the answer. I suspect it may indeed break, as you're afraid of.

As an alternative, you could insert a default type for the generic type parameter:

```typescript
export class BaseComp<T> {}
```

becomes

```typescript
export class BaseComp<T=unknown> {}
```

This is not ideal and should just be considered as a temporary workaround.

**Comment by benelliott** [comment]
@JoostK Thanks. I think this won't work in my case as the generic is bounded by an `extends`, ie I can't do `BaseComp<T extends U = unknown>`.

**Comment by benelliott** [comment]
For anyone else who has the same issue as me - I worked around it by adding a Directive with a dummy selector (not empty, but something that obviously shouldn't be used) to my abstract classes and then declaring them in my modules, inspired by this commit in `@angular/components`: 

https://github.com/angular/components/commit/8c9801398c9593cc29c292d65bd206463909a432

**Comment by xboysms** [comment]
ok, please undo package-lock.json file
then npm install 
should work, it is working fine for me

**Comment by abadakhshan** [comment]
I still have this problem


```
node_modules/narik-app-core/lib/base/narik-detail-form.d.ts:61:40 - error TS2314: Generic type 'NarikDetailForm<TE>' requires 1 type argument(s).

61     static ngBaseDef: ɵngcc0.ɵɵBaseDef<NarikDetailForm>;
```


```
"dependencies": {
    "@angular/animations": "~9.0.0-next.12",
    "@angular/cdk": "^8.0.0",
    "@angular/common": "~9.0.0-next.12",
    "@angular/compiler": "~9.0.0-next.12",
    "@angular/core": "~9.0.0-next.12",
    "@angular/flex-layout": "^8.0.0-beta.26",
    "@angular/forms": "~9.0.0-next.12",
    "@angular/material": "^8.0.0",
    "@angular/platform-browser": "~9.0.0-next.12",
    "@angular/platform-browser-dynamic": "~9.0.0-next.12"...
...
}
```
```
"devDependencies": {
    "@angular-builders/custom-webpack": "^8.0.2",
    "@angular-devkit/build-angular": "~0.900.0-next.15",
    "@angular/cli": "~9.0.0-next.15",
    "@angular/compiler-cli": "~9.0.0-next.12",
    "@angular/language-service": "~9.0.0-next.12",
....
}
```

**Comment by gkalpak** [comment]
These errors will likely be fixed by #33264.

**Comment by abadakhshan** [comment]
Thank you @gkalpak 
It was fixed  by "9.0.0-next.14"
