### ISSUE TITLE
update 2 to 4 has problem [ts] Property 'map' does not exist on type 'Observable<Response>'.

### ISSUE THREAD

**Issue by AlicePrincess** [angular/angular#15548]
![image](https://cloud.githubusercontent.com/assets/18545458/24392948/a7c10c84-13c8-11e7-932b-8753c6047275.png)

I need to how to solve

**Comment by DzmitryShylovich** [comment]
`import 'rxjs/add/operator/map';`

**Comment by AlicePrincess** [comment]
![image](https://cloud.githubusercontent.com/assets/18545458/24393097/6031eafe-13c9-11e7-8579-0a4075138f6a.png)

**Comment by AlicePrincess** [comment]
![image](https://cloud.githubusercontent.com/assets/18545458/24393120/70d0774a-13c9-11e7-8f65-d99c4696db9b.png)

**Comment by Toxicable** [comment]
Works fine here https://plnkr.co/edit/ovErXQGoQT5PQCzrSi6K?p=preview
If you remove `import 'rxjs/add/operator/map'` you'll notice that you get the error

In the future please fill out the Issue template correctly, otherwise your issue may be ignored.
Also note that this Issue tracker is not suitable for support requests, please Post on stack Overflow with the tag `angular` or see https://gitter.im/angular/angular

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by AlicePrincess** [comment]
I know the cause of the problem，should not use cnpm，thanks all

**Comment by MedFirasMrabet** [comment]
@AlicePrincess can u be more specific about your solution please because I have the same exactly issue ?

**Comment by engemasa** [comment]
For anyone still curious as to the fix, If you import the generic `import { Observable } from 'rxjs/Rx';` rather than `import { Observable } from 'rxjs/add/operator/map'`, that should resolve your issue. 

See [stackoverflow](https://stackoverflow.com/questions/37208801/property-map-does-not-exist-on-type-observableresponse).

**Comment by sarunint** [comment]
Importing the whole `rxjs/Rx` is considered a bad practise since it will import all operators (including the ones that you don't use) and make your bundle too big.

I recommend using Lettable Operators, which was recently introduced in `rxjs@5.5.0`, to allow better tree shaking.

**Comment by famousTM** [comment]
Many errors like so:
error TS2339: Property 'map' does not exist on type 'AngularFireList<{}>'.
error TS2339: Property 'take' does not exist on type 'AngularFireObject<{}>'.
error TS2339: Property 'subscribe' does not exist on type 'AngularFireObject<{}>'.

The site has been upgraded from older packages to Angular 5 and now it no longer works. Any ideas on how to change the functions to work?

**Comment by GregGorman** [comment]
I'm new to Angular so I may be wrong here but it looks like there are some breaking changes with the new versions on rxjs/Rx (major version change usually means breaking changes.) If you look in the node modules rxjs folder you'll find an add folder.  In there will be the operator folder.  

import 'rxjs/add/operator/map';  will fix one of your errors. 

adding import 'rxjs/add/operator/take'; will fix the second 

and import 'rxjs/add/operator/subscribeOn'; will get you part of the way to fixing the third.  This looks like a breaking change and you're going to have to read the documentation.

**Comment by sasikiranr** [comment]
I'm having the same issue, even though I imported the map from 'import 'rxjs/add/operator/map''
Property 'map' does not exist on type observable<response>. 
is this related with any typescript version or something else.

**Comment by manartaha** [comment]
@sasikiranr  make sure that you have imported **import { Http , Response} from '@angular/http';** and **import { Observable } from 'rxjs/Observable';**

**Comment by chathurangakup** [comment]
have there any opetrator without map??

**Comment by crossRT** [comment]
@chathurangakup I guess I having the same problem as u.
even if `import 'rxjs/add/operator/map';` is not able to solve this issue.

**Comment by manartaha** [comment]
Try to use **httpClient** instead of http in your constructor and **remove** the operator **map** from your **return** it may solve your problem

**Comment by crossRT** [comment]
@manartaha I'm using HttpClient from angular core instead of HTTP.

**Comment by crossRT** [comment]
thanks @vermouthyr 
the link is very useful.

**Comment by Rasive** [comment]
@vermouthyr Holy moly, thanks man, was driving me nuts!

**Comment by BryanMCarroll** [comment]
@vermouthyr Thank you!

**Comment by karim-khan** [comment]
Thanks @crossRT

**Comment by AnisBOULAID** [comment]
@engemasa instead of using `import { Observable } from 'rxjs/Rx';` , just install the package rxjs-compat, this will fix the issue

**Comment by abhargavasharma** [comment]
I installed rxjs-compat(npm install rxjs-compat), and also used below code

import { Http, Headers, Response }    from '@angular/http';
import 'rxjs/Rx';
import { map } from "rxjs/operators";
import { Observable } from 'rxjs/Observable';

It worked for me

**Comment by hamzaavvan** [comment]
Angular apps rely on rx@5.5+ import `map` operator like this:
`import { map } from "rxjs/operators";`

And it should work 👍 Best of luck

**Comment by govarthananve** [comment]
thanks @vermouthyr

**Comment by susampath** [comment]
@vermouthyr Thanks for Your Code .Its Totally Worked for Me.

**Comment by tmell004** [comment]
Thank you vermouthyr it is very helpfull

**Comment by lkolli33** [comment]
Simply writing this code 
import { Injectable } from '@angular/core';
import {Http,Response,Headers} from  '@angular/http';
import 'rxjs/add/operator/map';

@Injectable({
  providedIn: 'root'
})
export class DataService {

  constructor(private _http:Http) { }
  getItems()
  {
     return this._http.get('http://localhost:3000/api/items').
    map(res=>res.json());
  
  }

}

Simply writing this and installing

npm install --save rxjs-compat@6

worked for me..no need for importing extra libraries

**Comment by maroom1** [comment]
how to read getItems in the component ?  @lkolli33 
I am getting an error 

this.dataService.getItems().subscribe((posts) => {
    console.log(posts);
  });

when subscribe function is not present in the recommendations , please suggest

**Comment by lkolli33** [comment]
Below is the code @maroom1 

  getItems()
  {
    this._dataService.getItems().subscribe(items=>{
      console.log("Items:",items);
    });
  }

**Comment by KhayelihleS** [comment]
@engemasa, Thanks it works

**Comment by diegodelfin7** [comment]
@hamzaavvan thanks bro , it worked for me.

**Comment by smitpatelx** [comment]
**THE FINAL ANSWER FOR THOSE WHO USES ANGULAR 6:**

Add the below command in your ***.service.ts** file"

    import { map } from "rxjs/operators";
    
    **********************************************Example**Below**************************************
    getPosts(){
    this.http.get('http://jsonplaceholder.typicode.com/posts')
    .pipe(map(res => res.json()));
    }
    }

I am using 
windows 10;

angular6 with typescript V 2.3.4.0

**Comment by BeTheChange1994** [comment]
@smitpatelx Thank you so much, true gent!!!

**Comment by Mohammad-Quanit** [comment]
Use map in pipe function.
https://github.com/angular/angularfire2/blob/master/docs/firestore/collections.md

**Comment by lkolli33** [comment]
Actually http is deprecated and **httpclient** is introduced in **Angular 6** which automatically includes map operator.
So we can remove map and include httpclient instead of http.
Below is the working code..
---------------------------------------------------------------------------------------------------

import { Injectable } from '@angular/core';
import {HttpClient,HttpHeaders,HttpResponse} from '@angular/common/http';

@Injectable({
  providedIn: 'root'
})
export class EmployeeService {

  constructor(private _httpClient:HttpClient) { }

  getEmployees()
  {
    return this._httpClient.get('http://localhost:3000/emp/employees');
  }
}

**Comment by vineesh33** [comment]
we can resolve this issue, try below things

import{Http, RequestOptions, Response, Headers} from '@angular/http';
import { map } from 'rxjs/operators';

 constructor(private http : Http) { }
   httpdata;
  ngOnInit() {
    this.http.get("http://jsonplaceholder.typicode.com/users").
      pipe(map(
         (response) => response.json()
      )).
      subscribe(
         (data) => {this.displaydata(data);}
      )
   
    
  }
  
  displaydata(data) {this.httpdata = data;}
 
}

This is working as expected. 

Thanks
Vineesh

**Comment by pasame-el-codigo** [comment]
@hamzaavvan thanx

**Comment by maksof-kashif** [comment]
hello! angular new version not support .map you have to install this through cmd
npm install --save rxjs-compat
via this you can enjoy with old technique .
note:
don't forget to import these lines.
import { Observable, Subject } from 'rxjs';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/catch';
thank you

**Comment by HarshaDhananjaya** [comment]
@vineesh33 it was really helpful

**Comment by Rename94** [comment]
npm install --save rxjs-compat@6
SOLVED

**Comment by blondie63** [comment]
> Thanks @manartaha ..
> Actually http is deprecated and httpclient is introduced in Angular 6 which automatically includes map operator.
> So we can remove map operator and include httpclient instead of http.
> Below is the working code..
> 
> import { Injectable } from '@angular/core';
> import {HttpClient} from '@angular/common/http';
> 
> @Injectable({
> providedIn: 'root'
> })
> export class EmployeeService {
> 
> constructor(private _httpClient:HttpClient) { }
> 
> getEmployees()
> {
> return this._httpClient.get('http://localhost:3000/emp/employees');
> }
> }

i've a simple api.service.ts based on http and need to convert to httpclient
someone can help me ?

**Comment by lkolli33** [comment]
> > Thanks @manartaha ..
> > Actually http is deprecated and httpclient is introduced in Angular 6 which automatically includes map operator.
> > So we can remove map operator and include httpclient instead of http.
> > Below is the working code..
> > import { Injectable } from '@angular/core';
> > import {HttpClient} from '@angular/common/http';
> > @Injectable({
> > providedIn: 'root'
> > })
> > export class EmployeeService {
> > constructor(private _httpClient:HttpClient) { }
> > getEmployees()
> > {
> > return this._httpClient.get('http://localhost:3000/emp/employees');
> > }
> > }
> 
> i've a simple api.service.ts based on http and need to convert to httpclient
> someone can help me ?

Sure ...post your service..

**Comment by blondie63** [comment]
Many thanks, there was only two errors:
1. need to comment row 2
2. i add a missing } in row 141

ps. a friend said me that my code is not good because is not OOP.. what do you think ?

**Comment by lkolli33** [comment]
Yes @blondie63 ...Iam a C# programmer previously ..so have to try  in angular

**Comment by Anirudh16** [comment]
> Angular apps rely on rxjs@5.5+ import `map` operator like this:
> `import { map } from "rxjs/operators";`
> 
> And if you're using rxjs@6+ then execute the command for backward compatibility:
> `npm install --save rxjs-compat@6`
> 
> **Note** Sometimes map operator gives an error **`Property map does not exist on type Observable<Object>`**
> 
> To kick this out, import `Observable` like this:
> `import { Observable } from "rxjs/Rx";`
> 


Hello tried these steps but still issue persists

**Comment by SatyaShekhar** [comment]
import {map} from 'rxjs/operators'

constructor(private _http:Http){

    }
    getEmployees() {
        return this._http
                        .get('http://jsonplaceholder.typicode.com/posts')
                        .pipe(map((response: Response) => response.json()));
    }

**Comment by SamiddhaD** [comment]
Run this command:
sudo npm install --save rxjs-compat
Also import:
import 'rxjs/Rx'
This solved in my case.
