### ISSUE TITLE
bug(ivy): runtime error for unknown element even with NO_ERRORS_SCHEMA

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular#33976]
The ivy runtime throws an error if there is an unknown element, even if the NgModule contains the `NO_ERRORS_SCHEMA`.

See the reproduction here: 

```
git clone https://github.com/petebacondarwin/ivy-schema-test && cd ivy-schema-test && npm i && npm start -o
```

Open console in the browser to see the error:

```
core.js:6068 ERROR Error: 'some-element' is not a known element:
1. If 'some-element' is an Angular component, then verify that it is part of this module.
2. If 'some-element' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
    at validateElement (core.js:23517)
    at ɵɵelementStart (core.js:23323)
    at Module.ɵɵelement (core.js:23389)
    at AppComponent_Template (app.component.html:2)
    at executeTemplate (core.js:13880)
    at renderView (core.js:13682)
    at renderComponent (core.js:15111)
    at renderChildComponents (core.js:13484)
    at renderView (core.js:13708)
    at ComponentFactory$1.create (core.js:34077)
```

The `AppComponent` template looks like:

```html
<div>
  <some-element></some-element>
</div>
```

but the `AppModule` has the `NO_ERRORS_SCHEMA`:

```ts
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule
  ],
  providers: [],
  schemas: [NO_ERRORS_SCHEMA],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

Note that if you remove the `NO_ERRORS_SCHEMA` then the build fails, as expected, during AOT compile time.

This looks like a regression that was introduced by https://github.com/angular/angular/commit/c83f5013bfb0182dc653d7e5d8a1750e09ea50e9

**Comment by IgorMinar** [comment]
fixed by https://github.com/angular/angular/pull/34024
