### ISSUE TITLE
Angular forms: ɵɵcontentQuery(...) is not a function

### ISSUE THREAD

**Issue by kibetmasi** [angular/angular#66251]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

Yes

### Description

After updating my angular repo from v20 to v21, an expected error arises when I use Angular reactive forms and Angular Material together. The error thrown is

```
ERROR TypeError: ɵɵcontentQuery(...) is not a function
    at Object.MatFormField_ContentQueries [as contentQueries] (_form-field-chunk.mjs:1050:59)
    at executeContentQueries (_debug_node-chunk.mjs:2712:15)
    at ɵɵelementStart (_debug_node-chunk.mjs:14136:5)
    at LoginComponent_Template
```

```ts
import { Component, computed, inject, OnInit, signal } from '@angular/core';
import {
  FormBuilder,
  Validators,
  ReactiveFormsModule,
  FormsModule,
  FormGroup,
} from '@angular/forms';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss'],
  imports: [
    FormsModule,
    RouterLink,
    ReactiveFormsModule,
  ],
})
export class LoginComponent implements OnInit {
  private readonly formBuilder = inject(FormBuilder);
  private readonly auth = inject(AuthService);
  private readonly settings = inject(SettingsService);
  readonly signals = inject(SignalsService);
  loginForm!: FormGroup;

  private readonly options = this.settings.getOptions();
  readonly themeStyle = computed(() => this.options.theme);
  readonly hide = signal(true);

  ngOnInit(): void {
    this.loginForm = this.formBuilder.nonNullable.group({
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required]],
    });
  }

  login() {
    if (this.loginForm.invalid) {
      this.loginForm.markAsDirty();
      return;
    }
    this.auth.login(this.loginForm.getRawValue() as CreateAuthInput);
  }
}

```

```html
<form class="login-form">
            <mat-form-field appearance="outline">
                <mat-label>Email</mat-label>
                <input matInput placeholder="Enter your email" required type="email">
                <mat-icon class="material-icons-outlined color-icon p-3" matSuffix>face</mat-icon>
            </mat-form-field>
            <mat-form-field appearance="outline">
                <mat-label>Password</mat-label>
                <input matInput placeholder="Enter your password" required>
            </mat-form-field>
            <div class="form-options">
                <mat-checkbox>Remember Me</mat-checkbox>
                <a class="forget-pwd" routerLink="/auth/forgot-password">Forgot Password?</a>
            </div>
            <button class="login-btn" mat-flat-button color="primary">
         Login
        </button>
        </form>
```

### Please provide a link to a minimal reproduction of the bug

Update Angular from version 20 to Angular 21 

### Please provide the exception or error you saw

```true
ERROR TypeError: ɵɵcontentQuery(...) is not a function
    at Object.MatFormField_ContentQueries [as contentQueries] (_form-field-chunk.mjs:1050:59)
    at executeContentQueries (_debug_node-chunk.mjs:2712:15)
    at ɵɵelementStart (_debug_node-chunk.mjs:14136:5)
    at LoginComponent_Template
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI       : 21.0.3
Angular           : 21.0.0
Node.js           : 22.16.0
Package Manager   : npm 10.9.2
Operating System  : win32 x64

┌───────────────────────────────────┬───────────────────┬───────────────────┐
│ Package                           │ Installed Version │ Requested Version │
├───────────────────────────────────┼───────────────────┼───────────────────┤
│ @angular/animations               │ 21.0.0            │ ^21.0.0           │
│ @angular/build                    │ 21.0.0            │ ^21.0.0           │
│ @angular/cdk                      │ 21.0.0            │ ^21.0.0           │
│ @angular/cli                      │ 21.0.3            │ ^21.0.0           │
│ @angular/common                   │ 21.0.5            │ ^21.0.0           │
│ @angular/compiler                 │ 21.0.5            │ ^21.0.0           │
│ @angular/compiler-cli             │ 21.0.0            │ ^21.0.0           │
│ @angular/core                     │ 21.0.0            │ ^21.0.0           │
│ @angular/elements                 │ 21.0.2            │ ^21.0.2           │
│ @angular/forms                    │ 21.0.0            │ ^21.0.0           │
│ @angular/material                 │ 21.0.0            │ ^21.0.0           │
│ @angular/material-moment-adapter  │ 21.0.0            │ ^21.0.0           │
│ @angular/platform-browser         │ 21.0.0            │ ^21.0.0           │
│ @angular/platform-browser-dynamic │ 21.0.0            │ ^21.0.0           │
│ @angular/router                   │ 21.0.0            │ ^21.0.0           │
│ rxjs                              │ 7.8.2             │ ~7.8.2            │
│ typescript                        │ 5.9.3             │ ~5.9.3            │
│ zone.js                           │ 0.15.1            │ ~0.15.1           │
└───────────────────────────────────┴───────────────────┴───────────────────┘
```

**Comment by JoostK** [comment]
This is almost certainly a problem with your dependencies, backed up by the version table showing all mixed patch versions.

Please open a new issue with reproduction if the issue persists.
