### PR TITLE
fix(zone.js): add missing types field in package.json

### LINKED ISSUE #38584: Typings is missing in zone.js 0.11.1
# 🐞 bug report

### Affected Package

 

After update zone.js from 0.10.3 to 0.11.1, my code
```ts

    const bluebirdPatchSymbol = Zone.__symbol__('bluebird') as keyof ZoneType;
    const bluebirdPatch = Zone[bluebirdPatchSymbol] as (b: typeof Bluebird) => void;
    bluebirdPatch(Bluebird);
```
 reports 
```
ERROR in error TS2688: Cannot find type definition file for 'zone.js'.
src/browser/main.ts:14:33 - error TS2304: Cannot find name 'Zone'.

14     const bluebirdPatchSymbol = Zone.__symbol__('bluebird') as keyof ZoneType;
                                   ~~~~
src/browser/main.ts:14:70 - error TS2304: Cannot find name 'ZoneType'.

14     const bluebirdPatchSymbol = Zone.__symbol__('bluebird') as keyof ZoneType;
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 0.10.3

### Description

`"typings"` field is missing in new package.json.

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

in #36540
```

    typings property are removed from package.json, instead using files property, because now we have several d.ts files as typings.

"files": [
    "./zone.js.d.ts",
    "./zone.api.extensions.ts",
    "./zone.configurations.api.ts"
  ],

```

in #38528
```
After update to APF, the directories and files options are not compatible,
so we need to remove those fileds to make sure everything work as expected.
```

### PR DESCRIPTION
**Pull request by JiaLiPassion**
Close #38584

In zone.js 0.11.1, the `types` field is missing in the `package.json`,
the reason is in zone.js 0.11.0, the `files` field is used to specify the
types, but it cause the npm package not contain any bundles issue, so zone.js
0.11.1 remove the `files` field, which cause the `type` definition gone.

This PR concat the `zone.js.d.ts`, `zone.configurations.api.ts`, `zone.api.extensions.ts`
types into a single `zone.js.d.ts` file.

### CODE REVIEW

File: packages/zone.js/package.json [hunk 1]
```diff
@@ -6,6 +6,7 @@
   "module": "./fesm2015/zone.js",
   "es2015": "./fesm2015/zone.js",
   "fesm2015": "./fesm2015/zone.js",
+  "types": "./lib/zone.js.d.ts",
```
Comment (JoostK) [inline packages/zone.js/package.json:9]: APF typically uses `"typings"` here instead of `"types"` (although I believe TS honors both).

- Here's [the APF spec](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview).
- And here's [`@angular/core`'s package.json](https://unpkg.com/@angular/core@10.0.12/package.json) as an example.

Comment (JiaLiPassion) [reply packages/zone.js/package.json]: @JoostK , thank you for the review, I just updated the field to `typings`.

File: packages/zone.js/package.json [hunk 2]
```diff
@@ -6,6 +6,7 @@
   "module": "./fesm2015/zone.js",
   "es2015": "./fesm2015/zone.js",
   "fesm2015": "./fesm2015/zone.js",
+  "typings": "./lib/zone.js.d.ts",
```
Comment (gkalpak) [inline packages/zone.js/package.json:9]: Shouldn't this be `./zone.js.d.ts`?

**Review by gkalpak — CHANGES_REQUESTED** [review]

File: packages/zone.js/package.json (hunk 2 above)
Comment (JiaLiPassion) [reply packages/zone.js/package.json:9]: @gkalpak , yeah, sorry for the miss, just updated.

Comment (gkalpak) [reply packages/zone.js/package.json]: Could we have a test that tests this?

Comment (JiaLiPassion) [reply packages/zone.js/package.json]: Sure, I will try to add an integration test case.

Comment (JiaLiPassion) [reply packages/zone.js/package.json]: @gkalpak, I am adding a test case here https://github.com/angular/angular/pull/38585/commits/fa0ea5ce4a2bad7c7a0173d9d69d2e42f6972b72#diff-9c62e04f38b4712d65fb087790ae3dd2R17,
1. I moved `zone.js.d.ts` to `zone.js/typings` folder.
2. I write a test case and try to add the `zone.js.d.ts` reference to the `typeRoots` filed of the `tsconfig.json` file, but it seems the compile not working, `yarn tsc -p .` can not find all typings inside `zone.js.d.ts`.

Do I have to use `/// <reference path="..." />` syntax or have to `import 'zone.js'` in the test file? 

Could you take a look at the `tsconfig.json` https://github.com/angular/angular/pull/38585/commits/fa0ea5ce4a2bad7c7a0173d9d69d2e42f6972b72#diff-9c62e04f38b4712d65fb087790ae3dd2R17? 

Thank you

Comment (JiaLiPassion) [reply packages/zone.js/package.json]: I just added test case to check the `typing`. https://github.com/angular/angular/pull/38585/files#diff-094b1fcb59e12d1e53e7ca63fe36c9e4

File: packages/zone.js/test/typings/package.json [hunk 3]
```diff
@@ -0,0 +1,19 @@
...
+  "keywords": [],
+  "author": "",
+  "license": "MIT",
+  "dependencies": {
+    "@types/node": "12.11.1",
+    "domino": "^2.1.6",
+    "zone.js": "file:../../../../dist/bin/packages/zone.js/npm_package"
+  },
+  "devDependencies": {
+    "typescript": "^4.0.2"
```
Comment (alan-agius4) [inline packages/zone.js/test/typings/package.json:17]:
```suggestion
    "typescript": "~4.0.2"
```

File: packages/zone.js/test/typings/tsconfig.json [hunk 4]
```diff
@@ -0,0 +1,25 @@
+{
+  "compilerOptions": {
```
Comment (alan-agius4) [inline packages/zone.js/test/typings/tsconfig.json:2]: We should test against the full set to strict options set by the Angular CLI.

Comment (JiaLiPassion) [reply packages/zone.js/test/typings/tsconfig.json:2]: Got it, I just updated the `tsconfig.json`

File: packages/zone.js/test/typings/package.json (hunk 3 above)
Comment (JiaLiPassion) [reply packages/zone.js/test/typings/package.json:17]: Got it, just updated, thank you.

File: packages/zone.js/test/typings/type.test.ts [hunk 5]
```diff
@@ -0,0 +1,18 @@
...
+const h1 = w.document.querySelector('h1');
+const listener = () => {};
+h1!.addEventListener('click', listener);
+const clickListeners = h1!.eventListeners!('click');
+if (!clickListeners || clickListeners.length === 0 || clickListeners[0] !== listener) {
+  throw new Error('eventListeners not work!!!');
+}
+
+const globalZoneConfig = w as ZoneGlobalConfigurations;
+globalZoneConfig.__Zone_disable_EventEmitter = true;
```
Comment (gkalpak) [inline packages/zone.js/test/typings/type.test.ts:18]: I am a little confused. What does this file test?

Comment (JiaLiPassion) [reply packages/zone.js/test/typings/type.test.ts:18]: Since the test only test the `tsc` compile success or not, so I just put several type definitions from 
1. `zone.ts`.
2. `zone.configurations.api.ts`
3. `zone.api.extensions.ts`
in this test file.

And check whether the tsc ok or not.

Comment (mhevery) [reply packages/zone.js/test/typings/type.test.ts:18]: maybe add a comment to make it clear as to why it is there?

**Review by mhevery — APPROVED** [review]
Please resolve' other comments before merging.

File: packages/zone.js/package.json [hunk 6]
```diff
@@ -6,6 +6,7 @@
   "module": "./fesm2015/zone.js",
   "es2015": "./fesm2015/zone.js",
   "fesm2015": "./fesm2015/zone.js",
+  "typings": "./zone.js.d.ts",
```
Comment (gkalpak) [inline packages/zone.js/package.json:9]: Thinking about this again, given that the JS file is named `zone.js` (and the corresponding main TS file `zone.ts`), shouldn't the typings file be named `zone.d.ts`? Typically, the `.d.ts` file names are computed by replacing the `.js/.ts` extension from the source code files with `.d.ts`.

**Review by gkalpak — APPROVED** [review]
LGTM with one comment/suggestion.

File: packages/zone.js/test/typings/type.test.ts (hunk 5 above)
Comment (JiaLiPassion) [reply packages/zone.js/test/typings/type.test.ts:18]: Sure, I have added comments to explain the purpose of this file.

File: packages/zone.js/package.json (hunk 6 above)
Comment (JiaLiPassion) [reply packages/zone.js/package.json:9]: Yeah, I am not sure about this one, @mhevery , what do you think of the name?

Comment (JiaLiPassion) [reply packages/zone.js/package.json:9]: I have updated the name of `typings` to `zone.d.ts`, and as we discussed, we still keep the original `zone.js.d.ts`, I made that change in #38797
