### ISSUE TITLE
Weird compilation errors during the update from Angular 8.3.15 to Angular 9 RC7

### ISSUE THREAD

**Issue by usarskyy** [angular/angular#34568]
### Affected Package

Not sure

### Is this a regression?

Yes, everything was working fine in Angular 8.3.15

### Description

After I executed `ng update @angular/cli @angular/core --next` I got the following errors:

```
    Error: error TS100: Error during template compile of 'RoutingHelper'
      Function calls are not supported in decorators but 'RestaurantManagerRoutingConstants' was called.
    error TS100: Error during template compile of 'RoutingHelper'
      Function calls are not supported in decorators but 'RestaurantManagerRoutingConstants' was called.
    error TS100: Error during template compile of 'RoutingHelper'
      Function calls are not supported in decorators but 'RestaurantManagerRoutingConstants' was called.
    error TS100: Error during template compile of 'RoutingHelper'
      Function calls are not supported in decorators but 'RestaurantManagerRoutingConstants' was called.
    error TS100: Error during template compile of 'RoutingHelper'
      Function calls are not supported in decorators but 'RestaurantManagerRoutingConstants' was called.
    error TS100: Error during template compile of 'RoutingHelper'
      Function calls are not supported in decorators but 'RestaurantManagerRoutingConstants' was called.
    error TS100: Error during template compile of 'RoutingHelper'
      Function calls are not supported in decorators but 'RestaurantManagerRoutingConstants' was called.
    error TS100: Error during template compile of 'RoutingHelper'
      Function calls are not supported in decorators but 'RestaurantManagerRoutingConstants' was called.
    error TS100: Error during template compile of 'RoutingHelper'
      Function calls are not supported in decorators but 'RestaurantManagerRoutingConstants' was called.
    error TS100: Unexpected value 'OrderlyWebComponentsModule in E:/.../orderly-web-apps/dist/orderly-web-components/lib/orderly-web-components.module.d.ts' imported by the module 'AppModule in E:/.../orderly-web-apps/projects/restaurant-admin-web/src/app/app.module.ts'. Please add a @NgModule annotation.
    error TS100: UpdateUserProfileComponent cannot be used as an entry component.
```

**First**, there are no details about these errors:

```
    error TS100: Error during template compile of 'RoutingHelper'
      Function calls are not supported in decorators but 'RestaurantManagerRoutingConstants' was called.
```
I have no idea why it stopped compiling. It would be great to get at least file name where this error happened.

**Second**, all my modules are attributed with @NgModule. `OrderlyWebComponentsModule` is a separate library with commonly used components and is also decorated as following:

```
@NgModule({
            declarations: [
              ...
              UpdateUserProfileComponent,
              ...
            ],
            imports: [ ... ],
            exports: [
              ...
              UpdateUserProfileComponent,
              ...
            ]
          })
export class OrderlyWebComponentsModule {}
```

public-api.ts file contains following references

```
...
export * from './lib/update-user-profile/update-user-profile.component';
...
export * from './lib/orderly-web-components.module';
```

Therefore the last error doesn't make any sense:
```
error TS100: Unexpected value 'OrderlyWebComponentsModule in E:/PROJECTS/Orderly/Orderly.AngularClient/AngularApps/orderly-web-apps/dist/orderly-web-components/lib/orderly-web-components.module.d.ts' imported by the module 'AppModule in E:/PROJECTS/Orderly/Orderly.AngularClient/AngularApps/orderly-web-apps/projects/restaurant-admin-web/src/app/app.module.ts'. Please add a @NgModule annotation.
```

## 🔬 Minimal Reproduction

Still not sure what causes this behavior. In my case I just have one local library that is imported into a project.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-rc.7
Node: 10.16.3
OS: win32 x64

Angular: 9.0.0-rc.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.0-rc.7
@angular-devkit/build-angular      0.900.0-rc.7
@angular-devkit/build-ng-packagr   0.900.0-rc.7
@angular-devkit/build-optimizer    0.900.0-rc.7
@angular-devkit/build-webpack      0.900.0-rc.7
@angular-devkit/core               9.0.0-rc.7
@angular-devkit/schematics         9.0.0-rc.7
@ngtools/webpack                   9.0.0-rc.7
@schematics/angular                9.0.0-rc.7
@schematics/update                 0.900.0-rc.7
ng-packagr                         9.0.0-rc.3
rxjs                               6.5.3
typescript                         3.6.4
webpack                            4.41.2

</code></pre>

**Comment by Splaktar** [comment]
@usarskyy if you [disable Ivy](https://next.angular.io/guide/ivy#opting-out-of-ivy-in-version-9), does you app compile properly?

**Comment by petebacondarwin** [comment]
Can you show us where the `RestaurantManagerRoutingConstants` is being called?

**Comment by usarskyy** [comment]
hi @Splaktar !
No, it does not compile. However error message is different.

```
E:\...\orderly-web-apps>ng build restaurant-admin-web

chunk {main} main.js, main.js.map (main) 691 bytes [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 171 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 154 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 3.86 MB [initial] [rendered]
Date: 2019-12-27T11:24:47.729Z - Hash: 32e52c898811754e5417 - Time: 9105ms

ERROR in UpdateUserProfileComponent cannot be used as an entry component.
```

If I compile library project "orderly-web-components" with enabled Ivy compiler I get the following error:

```
E:\...\orderly-web-apps>ng build orderly-web-components
Building Angular Package
******************************************************************************
It is not recommended to publish Ivy libraries to NPM repositories.
Read more here: https://next.angular.io/guide/ivy#maintaining-library-compatibility
******************************************************************************

------------------------------------------------------------------------------
Building entry point 'orderly-web-components'
------------------------------------------------------------------------------
Compiling TypeScript sources through ngc
Compiling @angular/core : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/router : es2015 as esm2015
Compiling @angular/forms : es2015 as esm2015
Compiling @ng-bootstrap/ng-bootstrap : es2015 as esm2015
Compiling @angular/common/http : es2015 as esm2015
Compiling @ng-select/ng-select : es2015 as esm2015
ERROR: projects/orderly-web-components/src/lib/update-user-profile/update-user-profile.component.html:40:26 - error NG8002: Can't bind to 'items' since it isn't a known property of 'ng-select'.
1. If 'items' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

40               <ng-select [items]="languages$ | async"
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  projects/orderly-web-components/src/lib/update-user-profile/update-user-profile.component.ts:16:16
    16   templateUrl: './update-user-profile.component.html',
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component UpdateUserProfileComponent.
projects/orderly-web-components/src/lib/update-user-profile/update-user-profile.component.html:43:26 - error NG8002: Can't bind to 'compareWith' since it isn't a known property of 'ng-select'.
1. If 'compareWith' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

43                          [compareWith]="compareLangs"
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  projects/orderly-web-components/src/lib/update-user-profile/update-user-profile.component.ts:16:16
    16   templateUrl: './update-user-profile.component.html',
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component UpdateUserProfileComponent.

An unhandled exception occurred: projects/orderly-web-components/src/lib/update-user-profile/update-user-profile.component.html:40:26 - error NG8002: Can't bind to 'items' since it isn't a known property of 'ng-select'.
1. If 'items' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

40               <ng-select [items]="languages$ | async"
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  projects/orderly-web-components/src/lib/update-user-profile/update-user-profile.component.ts:16:16
    16   templateUrl: './update-user-profile.component.html',
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component UpdateUserProfileComponent.
projects/orderly-web-components/src/lib/update-user-profile/update-user-profile.component.html:43:26 - error NG8002: Can't bind to 'compareWith' since it isn't a known property of 'ng-select'.
1. If 'compareWith' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

43                          [compareWith]="compareLangs"
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  projects/orderly-web-components/src/lib/update-user-profile/update-user-profile.component.ts:16:16
    16   templateUrl: './update-user-profile.component.html',
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component UpdateUserProfileComponent.

See "C:\...\Temp\ng-R6GXND\angular-errors.log" for further details.
```

Here is how `ng-select` is used:

```
<ng-select [items]="languages$ | async"
                         formControlName="language"
                         bindLabel="name"
                         [compareWith]="compareLangs"
                         placeholder="Select language">
              </ng-select>
```

When I disable Ivy, everything is compiled successfully. Could you please explain why Ivy can't find these properties?
I can provide you any debug output you need to find the bug.

**Comment by usarskyy** [comment]
hi @petebacondarwin !

Here is one single direct reference:

```
export class RoutingHelper {
  public static RestaurantManager: RestaurantManagerRoutingConstants = new RestaurantManagerRoutingConstants();

  public static getAccountConfirmationFullUrl(token: string) {
    return RoutingConstants.ACCOUNT_CONFIRMATION + '/' + token;
  }
}
```

Then `RestaurantManager` property is used multiple times in routes config and guards. For example:

```
{
            path: RoutingHelper.RestaurantManager.TABLES,
            component: TablesWithDisplaysListComponent
          },
```

But there are no references in decorators.

**Comment by usarskyy** [comment]
@petebacondarwin 
I was also experiencing similar issue while compiling my project with `--prod` option and I managed to solve it. Here is how I did it:
 
Initially I had the following code:

```
export class RestaurantManagerRoutingConstants {
  public getSomeUrl(id: number) {
    return "blah/" + id;
}

export class RoutingHelper {
  public static RestaurantManager: RestaurantManagerRoutingConstants = new RestaurantManagerRoutingConstants();

  public static getAccountConfirmationFullUrl(token: string) {
    return RoutingConstants.ACCOUNT_CONFIRMATION + '/' + token;
  }
}

export class SomeService {
    public method1() {
        const url = RoutingHelper.RestaurantManager.getSomeUrl(123);
    }
}
```

`RoutingHelper` was kind of a single root entry point to simplify access to helper classes that generate URLs. So, I converted all methods in these helper classes to `static` and referenced helper classes directly:

```
const url = RestaurantManagerRoutingConstants.getSomeUrl(123);
```

But I still have no idea why compiler was complaining about decorators.

**Comment by spock123** [comment]
@usarskyy aren't entryComponents deprecated in NG9 ?

**Comment by ImTung** [comment]
> @usarskyy aren't entryComponents deprecated in NG9 ?

Yes, more deprecated detail: https://next.angular.io/guide/deprecations

**Comment by alxhub** [comment]
Hello @usarskyy,

Unfortunately without a reproduction that we can run and debug the error in, I don't think we'll be able to make progress on this issue. The Ivy errors you're experiencing look legitimate - perhaps `CommonModule` is missing from the module of the component in question?

**Comment by JoostK** [comment]
Closing as there's no reproduction. Please open a new issue if the problem persists.
