### ISSUE TITLE
JITCompiler not available in production environment anymore, breaking dynamic components

### ISSUE THREAD

**Issue by FSDRE** [angular/angular#37908]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 Yes, the previous version in which this bug was not present was: NG8.2.14 / NG9.0.6

### Description

We operate an app where dynamic component templates are received via an API from the server.
These templates get compiled at runtime into an Angular component while the rest of the app gets compiled AOT.
Because of the dynamic components we need the Angular JITCompiler to be available at runtime.
So basically we have an AOT app including multiple completely dynamic components that can get compiled and rendered whenever it is necessary (whenever templates are received from the server).
The dynamic templates are unknown at the time of AOT compilation of the app.

This worked in NG 8.2.14 and NG 9.0.6 flawlessly. Afer upgrading to >=NG9.0.7 the compiler gets stripped away in production mode by optimization. This is an issue since it breaks any app depending on runtime compilation.

The possible solutions presented in the error are pretty "weird":

1. "JIT compilation is discouraged for production use-cases! Consider AOT mode instead."
Yeah, no shit sherlock 😄 as I stated above, the templates that are compiled at runtime are not known at AOT build time.
The statement sounds a little bit like "Angular is AOT only so get rid of your dynamic stuff".

2. "Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping"
This would be great but does not work. Tried importing it in main.ts or even polyfills.ts

Currently we have no way of getting back our much needed runtime compiler.

Any help is much appreciated!

## 🔬 Minimal Reproduction

 [https://github.com/FSDRE/ngcompile](https://github.com/FSDRE/ngcompile)

* See `main.ts`, compiler gets imported
* `npm run startProd` -> Error in the browser...

## 🔥 Exception or Error
<pre><code>

ERROR Error: Angular JIT compilation failed: '@angular/compiler' not loaded!
  - JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
  - Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
  - Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping.
    at Se (main.9d222ff640ce74575712.js:1)
    at Function.get (main.9d222ff640ce74575712.js:1)
    at Ct (main.9d222ff640ce74575712.js:1)
    at new mf (main.9d222ff640ce74575712.js:1)
    at Kh (main.9d222ff640ce74575712.js:1)
    at e.td [as compileModuleAndAllComponentsSync] (main.9d222ff640ce74575712.js:1)
    at e.createComponentFactory (main.9d222ff640ce74575712.js:1)
    at e.ngOnInit (main.9d222ff640ce74575712.js:1)
    at Rn (main.9d222ff640ce74575712.js:1)
    at Pn (main.9d222ff640ce74575712.js:1)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.0.1
Node: 12.18.1
OS: win32 x64

Angular: 10.0.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.1
@angular-devkit/build-angular     0.1000.1
@angular-devkit/build-optimizer   0.1000.1
@angular-devkit/build-webpack     0.1000.1
@angular-devkit/core              10.0.1
@angular-devkit/schematics        10.0.1
@angular/cli                      10.0.1
@ngtools/webpack                  10.0.1
@schematics/angular               10.0.1
@schematics/update                0.1000.1
rxjs                              6.5.5
typescript                        3.9.6
webpack                           4.43.0
</code></pre>

**Anything else relevant?**

**Comment by petebacondarwin** [comment]
I think this is probably more of a CLI issue... transferring
