### ISSUE TITLE
Running Angular2 RC1 on Android device give errors, but run perfect on Desktop or iOS device

### ISSUE THREAD

**Issue by hermanfransen** [angular/angular#8918]
I am working on a project with Angular 2.0.0-rc.1 and ran into a bug (I guess). The app runs perfect in the browser on my MacBook, my iPhone and my iPad. But when I run it in a browser on my Android device I get two kinds of errors:

- TypeError: undefined is not a function with reflector.parameters
- Unhandled promise rejection

To reproduce this problem, I random googled plunks running Angular 2.0.0-rc.1 and found the same problems.

All these plunks work perfect without any error in the browser on Chrome 51.0 (64-bit) with OS X 10.11.15

The errors I get in the browser are on Android KitKat 4.4.2; SM-T310 Build/KOT49H running Chrome 40.0.2214.109 Blink-version 537.36 (@189407) Javascript-version v8 3.30.33.16. I connected this device with an USB cable to my OS X machine, enabled the developer options on this Android device and used the `chrome://inspect/#devices` to detect the errors

#### First problem:

http://embed.plnkr.co/TCzW7hZaL46Nz9ZgVWDb/

```
Error: TypeError: undefined is not a function
at ReflectionCapabilities.parameters (https://npmcdn.com/@angular/core@2.0.0-rc.1/src/reflection/reflection_capabilities.js:137:20)
at Reflector.parameters (https://npmcdn.com/@angular/core@2.0.0-rc.1/src/reflection/reflector.js:87:48)
at _dependenciesFor (https://npmcdn.com/@angular/core@2.0.0-rc.1/src/di/reflective_provider.js:178:41)

```
Line 137 of the reflection_capabilities.js: `parameters.fill(undefined);`. This statement is part of the function `ReflectionCapabilities.prototype.parameters`

Same errors with:

https://embed.plnkr.co/Exme2m706sNHtpTGtSVq/
https://embed.plnkr.co/vZ3exjdx2Lo2J2ptSJE2/

#### Second problem:

http://embed.plnkr.co/mztUE3cxHgetbdwn85kV/

```
Unhandled promise rejection Promise {__zone_symbol__then: function, [[PromiseStatus]]: "rejected", [[PromiseValue]]: Error: undefined is not a function
Error loading http://run.plnkr.co/plunks/mztUE3cxHgetbdwn85kV/ap…}__proto__: Promise[[PromiseStatus]]: "rejected"[[PromiseValue]]: Error: undefined is not a function

```
Same errors with:

https://embed.plnkr.co/zbre21tIvfkcZTwpXLNc/
https://embed.plnkr.co/A1Lycbvs4mVCgpc1Lt71/
https://embed.plnkr.co/jsoGHETv5eiygbtkhtb2/
https://embed.plnkr.co/oTLzMZAiUSsuBC4X7Tc2/

**Comment by hermanfransen** [comment]
I created an Android Virtual Device based on Nexus 9 and getting the same errors.

![Nexus 9](https://cloud.githubusercontent.com/assets/10079064/15674924/cbd31106-273f-11e6-9d3c-c44ea2953c27.png)

**Comment by Leedabord** [comment]
i have just found something similar, maybe (I'm new to this) ...  my code runs fine on my laptop browser, but only https://embed.plnkr.co/...  works on my android device.  https://run.plnkr.co/plunks/...   doesn't seem to recognize angularJS and hence shows only the HTML .  any ideas?   thx.

**Comment by robwormald** [comment]
The first will be Array.prototype.fill not existing:
```javascript
var parameters = new Array(typeOrFunc.length);
parameters.fill(undefined);
return parameters;
```
, per MDN it's not available before Chrome 45: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/fill

The second is harder to debug as it's not really a good stack trace, but I suspect it's a similar issue. Easy fix is just dropping in the es6-shim or core-js polyfills.

**Comment by hermanfransen** [comment]
@robwormald :: thanks a lot, that did the job !!!

**Comment by Leedabord** [comment]
@hermanfransen sorry about my previous post to your issue --  i didn't mean to confuse your issue with mine.  I thought mine was related to yours.  please feel free to remove / delete my post if needed.  thx
