### ISSUE TITLE
No Directive annotation found on AppComponent

### ISSUE THREAD

**Issue by keyiis** [angular/angular#9833]
Today,after i update angular from 2.0.0-rc.3 to 2.0.0-rc.4,app run error:
```
app.js:22385 Error: No Directive annotation found on AppComponent
    at new BaseException (app.js:3012)
    at DirectiveResolver.resolve (app.js:15853)
    at CompileMetadataResolver.getDirectiveMetadata (app.js:15320)
    at RuntimeCompiler._getCompiledHostTemplate (app.js:13901)
    at RuntimeCompiler._getTransitiveCompiledTemplates (app.js:13934)
    at RuntimeCompiler.compileComponentAsync (app.js:13860)
    at RuntimeCompiler.resolveComponent (app.js:13856)
    at app.js:41690
    at app.js:41889
    at ZoneDelegate.invoke (polyfills.js:9123)
    at Object.onInvoke (app.js:45484)
    at ZoneDelegate.invoke (polyfills.js:9122)
    at Zone.run (polyfills.js:9016)
    at NgZoneImpl.runInner (app.js:45515)
    at NgZone.run (app.js:45404)
    at ApplicationRef_.run (app.js:41887)
    at Object.coreLoadAndBootstrap (app.js:41687)
    at Object.bootstrap (app.js:129)
    at Object.<anonymous> (app.js:8)
    at __webpack_require__ (polyfills.js:51)
    at webpackJsonpCallback (polyfills.js:22)
    at app.js:1
```
then i clean(delete all logic) AppComponent as below:
```
import { Component } from '@angular/core';

@Component({
  selector: 'my-app',
  template: '<h1>My First Angular 2 App</h1>'
})
export class AppComponent { }
```
But the same error occurs.

**Comment by pkozlowski-opensource** [comment]
Please provide a minimal reproduce scenario in a plunker, as requested in the issue template. Otherwise it is not actionable and will be closed.

**Comment by keyiis** [comment]
@pkozlowski-opensource I changed nodejs version from 6.2 to 5.11,the issues resolved.
plunker can't visit in china.
