### ISSUE TITLE
compiling application using ngc doesnt emit angular decorators

### ISSUE THREAD

**Issue by mlakmal** [angular/angular#20164]
## I'm submitting a...
<pre><code>
[ x] Bug report  
</code></pre>

## Current behavior
when using angular v 5.0.0 ngc compiler to compile module with work space typescript v 2.6.1 does not emit decorator info.

## Expected behavior
with typescript v 2.4.2 and angular v 5.0.0 ngc compiler or (typescript v 2.6.1 with angular v 4.4.6 ngc compiler) output module as below.
```
import { MODULE_CONST } from "./moduleDef";
import { NgModule } from "@angular/core";
export class UxModule {
    /**
     * @return {?}
     */
    static forRoot() {
        return {
            ngModule: UxModule,
            providers: MODULE_CONST.providers
        };
    }
}
UxModule.decorators = [
    { type: NgModule, args: [{
                imports: MODULE_CONST.imports,
                declarations: MODULE_CONST.declarations,
                entryComponents: MODULE_CONST.entryComponents,
                exports: MODULE_CONST.exports
            },] },
];
/** @nocollapse */
UxModule.ctorParameters = () => [];
function UxModule_tsickle_Closure_declarations() {
    /** @type {!Array<{type: !Function, args: (undefined|!Array<?>)}>} */
    UxModule.decorators;
    /**
     * @nocollapse
     * @type {function(): !Array<(null|{type: ?, decorators: (undefined|!Array<{type: !Function, args: (undefined|!Array<?>)}>)})>}
     */
    UxModule.ctorParameters;
}
```
but with typescript > 2.5.3 and angular v 5.0.0 ngc compiler outputs below (which doesn't contain decorator info)
```
import { MODULE_CONST } from "./moduleDef";
import { NgModule, ModuleWithProviders } from "@angular/core";
export class UxModule {
    /**
     * @return {?}
     */
    static forRoot() {
        return {
            ngModule: UxModule,
            providers: MODULE_CONST.providers
        };
    }
}
function UxModule_tsickle_Closure_declarations() {
    /** @type {!Array<{type: !Function, args: (undefined|!Array<?>)}>} */
    UxModule.decorators;
    /**
     * @nocollapse
     * @type {function(): !Array<(null|{type: ?, decorators: (undefined|!Array<{type: !Function, args: (undefined|!Array<?>)}>)})>}
     */
    UxModule.ctorParameters;
}
```

## What is the motivation / use case for changing the behavior?
We are building angular libraries using same commands that angular repo uses to create its libraries.  after upgrading the angular version to 5.0.0 library commands started to fail with missing decorator info.

## Environment

<pre><code>
Angular version: 5.0.0
Typescript: >2.5.3
 
For Tooling issues:
- Node version: 6.9.2 (also tried 8.1.3)
- Platform:  Mac, Windows
</pre></code>

**Comment by Toxicable** [comment]
Angular isn't tested in TS any higher than 2.4.2 so for now that's the recommended version you use

**Comment by mlakmal** [comment]
thats too bad. we want to use latest features from typescript but seems like angular compiler wont allow that ...

**Comment by jskrzypek** [comment]
@mlakmal you can try playing with some of the `angularCompilerOptions` in your tsconfig like `"annotationsAs"` (https://github.com/angular/angular/blob/master/packages/compiler-cli/src/transformers/api.ts#L113).

Setting it to `"decorators"` instead of `"static fields"` fixed an issue we were having with some non-emitted static fields on our decorated classes

**Comment by jeevananthamDviVert** [comment]
While installing and added all in appmodule.ts..after running it..i get this error..how to resolve it .

ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/ngx-advanced-searchbox/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
