### ISSUE TITLE
4.0.0-Rc.1 Upgrade Errors when running tests

### ISSUE THREAD

**Issue by arturh85** [angular/angular#14780]
**I'm submitting a ...**

[X] bug report 

**Current behavior**
Error Messages on running npm run test after upgrade from 2.4.8 to 4.0.0-rc1:

```
[at-loader] Checking finished with 1045 errors
Hash: 2075dbec0d36e9d4552f
Version: webpack 2.2.0
Time: 17756ms
                Asset       Size  Chunks                    Chunk Names
          0.bundle.js  690 bytes       0  [emitted]
config/spec-bundle.js    8.18 MB       1  [emitted]  [big]  config/spec-bundle.js

WARNING in ./~/@angular/core/@angular/core.es5.js
3702:272-293 Critical dependency: the request of a dependency is an expression

WARNING in ./~/@angular/core/@angular/core.es5.js
3705:332-415 Critical dependency: the request of a dependency is an expression

ERROR in ./src/app/home/x-large/x-large.directive.spec.ts
Module not found: Error: Can't resolve '@angular/platform-browser/src/dom/debug/by' in 'C:\projects\angular2-webpack-starter\src\app\home\x-large'
 @ ./src/app/home/x-large/x-large.directive.spec.ts 5:11-64
 @ ./src \.spec\.ts
 @ ./config/spec-bundle.js

ERROR in [at-loader] compiled\node_modules\@angular\common\src\common_module.ngfactory.ts:13:36
    Type 'any' is not a constructor function type.

ERROR in [at-loader] compiled\node_modules\@angular\common\src\common_module.ngfactory.ts:14:27
    Namespace ''*'' has no exported member 'CommonModule'.

ERROR in [at-loader] compiled\node_modules\@angular\common\src\common_module.ngfactory.ts:15:30
    Namespace ''*'' has no exported member 'NgLocaleLocalization'.

ERROR in [at-loader] compiled\node_modules\@angular\common\src\common_module.ngfactory.ts:16:30
    Namespace ''*'' has no exported member 'Injector'.

ERROR in [at-loader] compiled\node_modules\@angular\common\src\common_module.ngfactory.ts:19:35
    Namespace ''*'' has no exported member 'NgLocaleLocalization'.

ERROR in [at-loader] compiled\node_modules\@angular\common\src\common_module.ngfactory.ts:20:111
    Property 'parent' does not exist on type 'CommonModuleInjector'.

ERROR in [at-loader] compiled\node_modules\@angular\common\src\common_module.ngfactory.ts:23:28
    Namespace ''*'' has no exported member 'CommonModule'.

ERROR in [at-loader] compiled\node_modules\@angular\common\src\common_module.ngfactory.ts:35:44
    Namespace ''*'' has no exported member 'NgModuleFactory'.

ERROR in [at-loader] compiled\node_modules\@angular\common\src\directives\ng_class.ngfactory.ts:14:19
    Namespace ''*'' has no exported member 'NgClass'.

ERROR in [at-loader] compiled\node_modules\@angular\common\src\directives\ng_class.ngfactory.ts:24:27
    Namespace ''*'' has no exported member 'AppView'.

.....

ERROR in [at-loader] compiled\src\app\no-content\no-content.component.ngfactory.ts:96:25
    Property 'renderer' does not exist on type 'View_NoContentComponent0'.

ERROR in [at-loader] compiled\src\app\no-content\no-content.component.ngfactory.ts:97:10
    Property 'init' does not exist on type 'View_NoContentComponent0'.

ERROR in [at-loader] compiled\src\app\no-content\no-content.component.ngfactory.ts:97:41
    Property 'renderer' does not exist on type 'View_NoContentComponent0'.
```

Everything works when running my application in either debug or production mode without errors - although the same errors appear when trying an aot build with:

`[at-loader] Checking finished with 16433 errors`

**Minimal reproduction of the problem with instructions**

The same errors as I get in my real project can be observed using this minimal angular2-webpack-starter which I upgraded using the npm install command specified in the release notes:

```
git clone https://github.com/arturh85/angular2-webpack-starter.git
cd angular2-webpack-starter
npm i
npm test
```

* **Angular version:** upgrading from 2.4.8 to 4.0.0-rc1

see https://github.com/arturh85/angular2-webpack-starter/commit/057b37f1f6d378de11140d07a37af07185199d30#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

* **Node (for AoT issues):** `node --version` =   
v6.2.2 (Windows 10)

**Comment by DzmitryShylovich** [comment]
I think it's a duplicate of https://github.com/angular/angular/issues/14730

**Comment by dharders** [comment]
I am facing this issue when I run my app on iOS Safari (i.e. when not running tests) with cli `ng serve`. Chrome Desktop is fine.

```SyntaxError: Unexpected token 'const'``` and ```SyntaxError: Unexpected token 'let'```

I assume this is because iOS Safari (9.3.5) doesn't understand 'let' and 'const' without a polyfill, where Chrome Desktop does. But previously let and const were converted automatically at compile time.

iOS worked in 2.4.8, not in 4.0.0-rc.1

**Comment by arturh85** [comment]
I removed the part which is duplicated in #14730

**Comment by rahulrsingh09** [comment]
Facing the same error when using ng serve

WARNING in ./~/@angular/core/@angular/core.es5.js
3702:272-293 Critical dependency: the request of a dependency is an expression

**Comment by arturh85** [comment]
To be clear, for me this ticket is about the errors thrown for every single component like 

`ERROR in [at-loader] compiled\src\app\no-content\no-content.component.ngfactory.ts:97:41
    Property 'renderer' does not exist on type 'View_NoContentComponent0'.`

I get more than 16k errors like this so something fundamental seems to be wrong.

**Comment by DzmitryShylovich** [comment]
@arturh85 same errors with rc2?

**Comment by arturh85** [comment]
Nope, and the issue duplicated in #14730 is also fixed. Thanks for the great work angular team! 👍
