### PR TITLE
fix(compiler-cli): ensure LogicalFileSystem maintains case in paths

### LINKED ISSUE #36992: Ivy (9.1.5) causes build failure
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/compiler-cli (ngcc)

### Is this a regression?

 Yes, the previous version in which this bug was not present was: `9.1.0`

### Description

In JIT mode build fails with
File name 'node_modules/apollo-angular/selectpipe.d.ts' differs from already included file name 'node_modules/apollo-angular/SelectPipe.d.ts' only in casing
In AOT mode build fails with
Symbol SelectPipe declared in * is not exported from apollo-angular

## 🔬 Minimal Reproduction

Clone https://github.com/n9niwas/ngccbug
Run
```bash
yarn
yarn start
```

## 🔥 Exception or Error
<pre><code>
ERROR in node_modules/apollo-angular/ApolloModule.d.ts:4:25 - error TS1149: File name '/Users/blah/Documents/ngrepros/ngccbug/node_modules/apollo-angular/selectpipe.d.ts' differs from already included file name '/Users/blah/Documents/ngrepros/ngccbug/node_modules/apollo-angular/SelectPipe.d.ts' only in casing.

4 import * as ɵngcc1 from './selectpipe';
</code></pre>

Also if I enable `aot` the error is different:
<pre><code>
ERROR in Symbol SelectPipe declared in /Users/blah/Documents/ngrepros/ngccbug/node_modules/apollo-angular/selectpipe.d.ts is not exported from apollo-angular (import into /Users/blah/Documents/ngrepros/ngccbug/src/app/app.component.ts)
</code></pre>
This was also working fine in `9.1.0`

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.4
Node: 13.11.0
OS: darwin x64

Angular: 9.1.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.4
@angular-devkit/build-angular     0.901.4
@angular-devkit/build-optimizer   0.901.4
@angular-devkit/build-webpack     0.901.4
@angular-devkit/core              9.1.4
@angular-devkit/schematics        9.1.4
@angular/cli                      9.1.4
@ngtools/webpack                  9.1.4
@schematics/angular               9.1.4
@schematics/update                0.901.4
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Anything else relevant?**

### PR DESCRIPTION
**Pull request by petebacondarwin**
The work to support case-sensitivity in the `FileSystem` went too far
with the `LogicalFileSystem`, which is used to compute import paths
that will be added to files processed by ngtsc and ngcc.

Previously all logical paths were canonicalised, which meant that on
case-insensitive file-systems, the paths were all set to lower case.
This resulted in incorrect imports being added to files. For example:

```
import { Apollo } from './Apollo';
import { SelectPipe } from './SelectPipe';
import * as ɵngcc0 from '@angular/core';
import * as ɵngcc1 from './selectpipe';
```

The import from `./SelectPipe` is from the original file, while the
import from `./selectpipe` is added by ngcc. This causes the
TypeScript compiler to complain, or worse for paths not to be
matched correctly.

Now, when computing logical paths, the original absolute paths
are matched against rootDirs in a canonical manner, but the actual
logical path that is returned maintains it original casing.

Fixes #36992, #36993, #37000

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by petebacondarwin** [comment]
CI tests on Windows are passing for this PR: https://app.circleci.com/pipelines/github/angular/angular/14835/workflows/7f8b8352-63e9-4707-9da0-0b605ca91b3a

**Review by JoostK — APPROVED** [review]

**Comment by alxhub** [comment]
[Presubmit](http://test/OCL:311369303:BASE:311369350:1589394507795:8d582435)

**Comment by petebacondarwin** [comment]
@alxhub can you identify what failed in the presubmit?
