### ISSUE TITLE
Angular 6 upgrade: ERROR in No NgModule metadata found for 'AppModule'

### ISSUE THREAD

**Issue by Airblader** [angular/angular#24123]
## I'm submitting a...
<pre><code>
[x] Bug report  
</code></pre>

## Current behavior
We upgraded our Angular 5 apps to Angular 6. While building works fine for all Linux and macOS users, our Windows users run into

> ERROR in No NgModule metadata found for 'AppModule'

when running `ng build`. However, `ng build --aot` works fine.

## Expected behavior
`ng build` should work even without `--aot` on all platforms.

## Minimal reproduction of the problem with instructions
Unfortunately, I cannot produce a repository that reproduces the issue. I realize that this is less than ideal, but I'm happy to debug our app if there are any ideas as to what to look into. Sadly, running `ng build --verbose`only shows the same error twice instead of once.

## What is the motivation / use case for changing the behavior?
We want to build our app :-)

## Environment

<pre><code>
Angular version: 6.0.3

Browser:
- [x] All browsers (or none, since the build is failing)
 
For Tooling issues:
- Node version: 9.11.1
- Platform:  Windows (Linux & macOS work!)
</code></pre>

Others:
- This happens *only* for Windows users as far as we can tell for now.
- Related: https://github.com/angular/angular-cli/issues/10516, but opening here since the error message comes from angular itself, not from the CLI.
- I looked through [existing issues](https://github.com/angular/angular/search?q=No+NgModule+metadata&unscoped_q=No+NgModule+metadata) but couldn't find anything helpful and certainly nothing mentioning the specificness to Windows.

**Comment by alexzuza** [comment]
Hello!
Unfortunately, it's hard to tell what's wrong with your build without minimal reproduction.

**Comment by patrykp57** [comment]
You should read this topic https://github.com/angular/angular-cli/issues/8798 and follow steps from there https://update.angular.io/

**Comment by Airblader** [comment]
@alexzuza 
Yes, I realize that (and I'm sorry – I'd love to have something reproducible). As I said, if you can give me any hints as to how to debug it, I'm happy to do that.

@patrykp57
I've seen and read that thread. We have tried even killing the entire checkout (including node_modules, obviously) and reinstalling. Also, that thread never makes a mention that it only affects Windows users, which seems to be an important piece of information here.

Also, we did upgrade to Angular 6 following that guide. We only had to side-step some of the instructions due to various bugs in the CLI (such as not being able to ng update when using a private registry). As I said, for all Linux and macOS users everything is fine – it's just Windows users having this issue.

**Comment by patrykp57** [comment]
@alexzuza 
Did you force cache clean ? I had the same problem few weeks ago and it was related to Angular-CLI. Try to remove Angular-CLI globally first, remove node_modules, then run `npm cache clear --force`, `npm cache verify`, install Angular-CLI globally and finally run `npm install`

**Comment by Airblader** [comment]
@patrykp57 I'll tell one of our Windows users to try this out and report back.

**Comment by Airblader** [comment]
@patrykp57 We followed those instructions on a Windows machine, but we still get the same error.

**Comment by patrykp57** [comment]
@Airblader  What is your NPM version ?

**Comment by Airblader** [comment]
@patrykp57 The one we tested earlier is on 5.6.0, on Linux it works even with 5.2.0.

**Comment by patrykp57** [comment]
@Airblader  Could you show whole package.json ?

**Comment by Airblader** [comment]
Sure. I only retracted the name of one package because it's our internal UI library and comes from a private registry.

```
{
  "name": "[retracted]",
  "version": "5.0.0",
  "description": "[retracted]",
  "author": "[retracted]",
  "license": "[retracted]",
  "scripts": {
    "ng": "ng",
    "start": "npm run watch",
    "build": "ng build",
    "watch": "ng build --watch --output-hashing=all --source-map --preserve-symlinks",
    "prod": "node --max_old_space_size=4096 node_modules/@angular/cli/bin/ng build --prod",
    "test": "karma start ./karma.conf.js",
    "lint": "ng lint",
    "e2e": "protractor ./protractor.conf.js",
    "prepree2e": "npm start",
    "pree2e": "webdriver-manager update --standalone false --gecko false --quiet",
    "postinstall": "node ./node_modules/[retracted]/angular-customization/customize-cli.js"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "6.0.3",
    "@angular/common": "6.0.3",
    "@angular/core": "6.0.3",
    "@angular/forms": "6.0.3",
    "@angular/platform-browser": "6.0.3",
    "@angular/platform-browser-dynamic": "6.0.3",
    "@angular/router": "6.0.3",
    "[retracted]": "~0.22.0",
    "@ngx-translate/core": "~10.0.0",
    "@types/filesize": "^3.2.15",
    "angular2-uuid": "^1.1.1",
    "core-js": "^2.4.1",
    "d3": "^4.4.0",
    "dagre": "^0.7.4",
    "dragula": "^3.7.2",
    "filesize": "^3.5.11",
    "hammerjs": "^2.0.8",
    "lodash": "^3.10.1",
    "mkpath": "^1.0.0",
    "moment": "^2.19.0",
    "monaco-editor": "^0.8.3",
    "ng2-dragula": "^1.3.0",
    "ng2-file-upload": "^1.3.0",
    "rxjs": "6.1.0",
    "web-animations-js": "^2.2.2",
    "webcola": "^3.3.8",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.1",
    "@angular/cli": "^6.0.3",
    "@angular/compiler": "6.0.3",
    "@angular/compiler-cli": "6.0.3",
    "@types/core-js": "~0.9.41",
    "@types/d3": "^4.4.0",
    "@types/glob": "^5.0.30",
    "@types/hammerjs": "^2.0.30",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "autoprefixer": "^6.5.3",
    "browser-sync": "^2.18.8",
    "codelyzer": "^2.0.0",
    "css-loader": "^0.27.3",
    "cssnano": "^3.10.0",
    "exports-loader": "^0.6.3",
    "file-loader": "^0.10.0",
    "gulp": "^3.9.1",
    "gulp-batch": "^1.0.5",
    "istanbul-instrumenter-loader": "^2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "json-loader": "^0.5.4",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-sourcemap-loader": "^0.3.7",
    "less-loader": "^4.0.2",
    "mkpath": "^1.0.0",
    "node-sass": "^4.9.0",
    "postcss-loader": "^2.1.5",
    "postcss-url": "^5.1.2",
    "pre-build-webpack": "^0.1.0",
    "protractor": "~5.1.0",
    "raw-loader": "^0.5.1",
    "sass-loader": "^6.0.3",
    "script-loader": "^0.7.0",
    "source-map-loader": "^0.1.5",
    "style-loader": "^0.13.1",
    "stylus-loader": "^3.0.1",
    "swiper": "~4.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.7.2",
    "url-loader": "^0.5.7",
    "webpack": "^2.4.1",
    "webpack-dev-server": "~2.4.2",
    "xml2js": "^0.4.17"
  },
  "resolutions": {
    "rxjs": "6.1.0",
    "@ngx-translate/core": "~10.0.0",
    "@ngx-translate/http-loader": "~3.0.0"
  }
}
```

The `customize-cli` script modifies the webpack files a little, but this is unrelated and removing this from the build doesn't make a difference.

**Comment by patrykp57** [comment]
Half of your packages are out of date. You have to update webpack, webpack-dev-server, tslint. Currently I'm using `webpack@4.8.3`, `webpack-dev-server@3.1.4`, `tslint@5.7.0` for Angular 6.0.3 and everything is working fine. If u run `npm install` there you would have list of warnings which point your out of date packages, try to repair it all.

**Comment by Airblader** [comment]
> Half of your packages are out of date.

The versions in the package.json are indeed a bit outdated, but the dependency management fixes this. We're also using webpack@4.8.3 and webpack-dev-server@3.1.4 according to the lock file.

**Comment by Airblader** [comment]
We have now observed this issue on a non-Windows machine as well, though it still seems to mostly affect Windows.

**Comment by alexzuza** [comment]
@Airblader It's time to reproduce the issue with minimal code)

**Comment by Airblader** [comment]
@alexzuza From above

> Yes, I realize that (and I'm sorry – I'd love to have something reproducible). As I said, if you can give me any hints as to how to debug it, I'm happy to do that.

I maintain OSS projects myself. I understand the importance of reproducing the issue. If I could, I would have done it, but creating new CLI projects doesn't do the trick. I can try to boil down our setup if I can get any hints as to where to start looking.

**Comment by MinstrelPrince** [comment]
@Airblader 
Seriously I am a window user and upgrading my angular 5 app to angular 6 I am plagued with this same issue and have tried all fixes recommended in other threads and none seems to work...
The error does'nt even  give a pointer to what might be wrong...
I have removed and re-install npm updated globally, webpack up to date, typescript up to date. all to no avail. Below is my package.json file perhaps someone can point out something out of the ordinary.
Guide to resolving this issue will be much appreciated. Thanks




`{
  "name": "compliance-planet-client",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.0.3",
    "@angular/common": "^6.0.3",
    "@angular/compiler": "^6.0.3",
    "@angular/core": "^6.0.3",
    "@angular/forms": "^6.0.3",
    "@angular/http": "^6.0.3",
    "@angular/platform-browser": "^6.0.3",
    "@angular/platform-browser-dynamic": "^6.0.3",
    "@angular/router": "^6.0.3",
    "@aspnet/signalr-client": "^1.0.0-alpha2-final",
    "@ngx-progressbar/core": "^4.0.1",
    "@ngx-progressbar/http": "^4.0.1",
    "@ngx-progressbar/router": "^4.0.1",
    "@types/chart.js": "^2.7.20",
    "@types/file-saver": "^1.3.0",
    "angular-async-local-storage": "^5.0.2",
    "angular-crypto-js": "^1.0.7",
    "angular-datatables": "^6.0.0",
    "bootstrap": "^3.3.7",
    "chart.js": "^2.7.1",
    "chartjs": "^0.3.24",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.5.4",
    "crypto-js": "^3.1.9-1",
    "datatables.net": "^1.10.16",
    "datatables.net-dt": "^1.10.16",
    "file-saver": "^1.3.3",
    "jquery": "^3.2.1",
    "jqwidgets-framework": "^5.5.0",
    "msgpack5": "^4.0.1",
    "ng-sweet-alert": "^1.0.11",
    "ng2-charts": "^1.6.0",
    "ng2-toastr": "^4.1.2",
    "ngx-bootstrap": "^2.0.0-beta.9",
    "ngx-ckeditor": "^0.3.1",
    "ngx-cookie-service": "^1.0.9",
    "ngx-dropdown": "0.0.22",
    "ngx-sweetalert2": "^0.2.7",
    "npm": "^6.1.0",
    "rxjs": "^6.0.0",
    "rxjs-compat": "^6.2.0",
    "sweetalert2": "^7.7.0",
    "tether": "^1.4.3",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.6",
    "@angular/cli": "^6.0.7",
    "@angular/compiler-cli": "^6.0.3",
    "@angular/language-service": "^6.0.3",
    "@types/chartjs": "0.0.31",
    "@types/crypto-js": "^3.1.38",
    "@types/datatables.net": "^1.10.8",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^2.0.2",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "~2.7.2"
  },
  "aot": "node --max-old-space-size=8192 ./node_modules/@angular/cli/bin/ng build --prod --aot"
}
`

**Comment by kyyash** [comment]
Any solution for this issue, we are facing it on RHEL

**Comment by jsgoupil** [comment]
I am unable to run a NON-AOT build on my Windows machine. Use the latest angular/cli, create a new project. Set aot to false in angular.json then run ng serve --configuration=production

You will get this warning:

    main.7dfa8fb0b1103f7eed7c.js:1 Uncaught Error: Unexpected value 'e' imported by the module 
    'function(){}'. Please add a @NgModule annotation.

**Comment by jsgoupil** [comment]
I have posted a new bug
https://github.com/angular/angular/issues/24450

**Comment by mhevery** [comment]
This issue seems abandoned without any reproducible instruction.  We are closing the issue. If you have reproducible instructions please file a new issue.

**Comment by thruba** [comment]
any solution for the above ? I 'm facing this issue in windows
I'm getting this error in the library pattern using 
ng-packgr for 3.0..1
angular 6.0.3

**Comment by eliashdezr** [comment]
This error is displayed when there's a **template** compilation error or a **node_module** library issue, but somehow the `angular-cli` process can't caught it and display it, so in order to see what is going on just run the `ng build --prod` command and it will display whatever error you have.

After fixing the errors you won't see that message again.

**Comment by simeyla** [comment]
I received the above error after updating @angular/material from 6.4.1 -> 6.4.2

When switching to a `--prod` build I then received : 

> ERROR in Couldn't resolve original symbol for ./common-behaviors/common-module from S:/tfs/rr/Defender.NG/node_modules/@angular/material/core/typings/index.d.ts

I've pretty much resigned myself to having to blow away node_modules everytime I update angular - which I did - and then I started receiving errors related to my actual project (including a circular reference) which I was  able to fix and get up and running again.

**Comment by violetstar** [comment]
😊

**Comment by shanemac10** [comment]
So maybe it's a VS Code thing or npm thing, I don't know, but somehow the file paths to our symlink'ed modules had their direct paths added (../../../patient/node_modules/*). We spent quite awhile trying to hunt down this issue, and apparently an automated process re-wrote the file paths in app.module.ts.

SHOULD BE:
```
import { BrowserModule } 		from '@angular/platform-browser';
import { NgModule } 			from '@angular/core';
import { RouterModule, Routes } 	from '@angular/router';
import { HttpClientModule } 		from '@angular/common/http';
import { BrowserAnimationsModule }	from '@angular/platform-browser/animations';
import { FlexLayoutModule } 		from '@angular/flex-layout';
import { FormsModule }			from '@angular/forms';
```
OVERWRITTEN FILE PATHS:
```
import { BrowserModule } 		from '../../../patient/node_modules/@angular/platform-browser';
import { NgModule } 			from '../../../patient/node_modules/@angular/core';
import { RouterModule, Routes } 	from '../../../patient/node_modules/@angular/router';
import { HttpClientModule } 		from '../../../patient/node_modules/@angular/common/http';
import { BrowserAnimationsModule }	from '../../../patient/node_modules/@angular/platform-browser/animations';
import { FlexLayoutModule } 		from '../../../patient/node_modules/@angular/flex-layout';
import { FormsModule }			from '../../../patient/node_modules/@angular/forms';
 ```

**Comment by michahell** [comment]
I got past this problem by `not declaring platformBrowserDynamic` as mentioned here:
https://stackoverflow.com/questions/39685179/angular-2-no-ngmodule-metadata-found

which to me, totally makes zero sense  😬 👍

**Comment by mklechan** [comment]
ok....this worked for me too, not sure why....

**Comment by degrootsde** [comment]
@michahell The link in your answer contains the solution indeed (for me). Maybe it is good to mention that  the answer that did it for me was by https://stackoverflow.com/users/516708/bahri-gungor and not the selected answer.
 I quote his answer her:

> > After upgrading to Angular 6, I encountered the "ERROR in No NgModule metadata found for 'AppModule'." with the angular-bootstrap-md package, which requires a tsconfig.json "include" as follows:
> 
> "include": ["node_modules/angular-bootstrap-md/**/*.ts",  "src/**/*.ts"],
> 
> After days of troubleshooting and hair pulling, the solution was to arrange the list so that the app.module.ts was located first, under "src/**/*.ts". An Angular bug, perhaps?
> 
> "include": ["src/**/*.ts","node_modules/angular-bootstrap-md/**/*.ts" ],
> 
> I genuinely hope this helps somebody, as I tried everything in this posting and nothing helped. After this change, everything compiles and works beautifully, as expected.

**Comment by bh3605** [comment]
@shanemac10  Those replacements were caused by VSCode. If you move a file it will ask if you'd like to update its reference. Clicking yes will update ALL references and replace it with the relative file path.

**Comment by mariohmol** [comment]
Hi.. i'm having this issue when i try to run a e2e test in travis.. if I run this local works as expected..  https://travis-ci.org/mariohmol/ng-brazil/builds/431752859

**Comment by jesperthomsen** [comment]
We fixed this by either moving main.ts to be the first entry in the "include" array in tsconfig.app.json or adding a "files" array containing main.ts. We bumped into this error in quite a few projects.

There was no additional error messages to go by - we saw this error a few times too, but accompanied by other errors. In those cases , it was mostly caused by actual errors in using rxjs functions. Once those were fixed and the error persisted, this was what needed to be done.
