### ISSUE TITLE
error: Module "mymodule" has no exported membe "mycomponent"  after upgrading to angular 16

### ISSUE THREAD

**Issue by graphicsxp** [angular/angular#51288]
### Which @angular/* package(s) are the source of the bug?

core, Don't known / other

### Is this a regression?

Yes

### Description

i am using an angular workspace with a blend of applications and libraries of my own which are used by these applications. My workspace configuration/structure is the same since i started the project with angular 10 (some changes along the way at each upgrade but nothing major).

but today after migrating to 16, one and only of my libraries failed to be imported in my application, the other libraries are imported just fine. I can't find any differences in the way they are configured though, particularly in angular.json.

this is how it is imported :  
´import { DesignerComponent } from 'process'; ´
I get the error below.

If I import it like this :  
`import { DesignerComponent } from '../../../../../process/src/lib/designer/designer.component';`

then it compiles just fine

### Please provide the exception or error you saw

```true
error TS2305: Module '"process
"' has no exported member 'DesignerComponent'.

15 import { DesignerComponent } from 'process';
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.1.7
Node: 16.16.0
Package Manager: npm 8.11.0
OS: win32 x64

Angular: 16.1.8
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.7
@angular-devkit/build-angular   16.1.7
@angular-devkit/core            16.1.7
@angular-devkit/schematics      16.1.7
@angular/cdk                    16.1.7
@angular/cli                    16.1.7
@schematics/angular             16.1.7
ng-packagr                      16.1.0
rxjs                            7.8.1
typescript                      4.9.5
zone.js                         0.13.1
```
