### ISSUE TITLE
Bundle is broken after compiling with AOT and Rollup

### ISSUE THREAD

**Issue by steveblue** [angular/angular#11635]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 

When updating to the latest Rollup 0.35.0 bundling fails silently in the Terminal, producing an Error in the Browser console when the bundle is attempting to bootstrap. The same bundle works with 0.34.0 in rc.7 and 2.0.0. The  Error points to the `OuterSubscriber` class of rxjs not being deployed to the bundle that is imported somewhere in an @angular package. It may be possible classes that extend OuterSubscriber are being used but Rollup is failing to import OuterSubscriber.

Here is a copy of the error in the console:

```
zone.js:344 Unhandled Promise rejection: (SystemJS) OuterSubscriber is not defined
	ReferenceError: OuterSubscriber is not defined
	    at eval (http://localhost:4200/bundle.js:637:122)
	    at eval (http://localhost:4200/bundle.js:746:128)
	Evaluating http://localhost:4200/bundle.js
	Error loading http://localhost:4200/bundle.js ; Zone: <root> ; Task: Promise.then ; Value: Error: (SystemJS) OuterSubscriber is not defined(…) (SystemJS) OuterSubscriber is not defined
	ReferenceError: OuterSubscriber is not defined
	    at eval (http://localhost:4200/bundle.js:637:122)
	    at eval (http://localhost:4200/bundle.js:746:128)
	Evaluating http://localhost:4200/bundle.js
	Error loading http://localhost:4200/bundle.jsconsoleError @ zone.js:344
zone.js:346 Error: Uncaught (in promise): Error: (SystemJS) OuterSubscriber is not defined(…)consoleError @ zone.js:346
```

**Expected behavior**

Angular packages when compiled AOT should be able to properly bundle with Rollup.

**Reproduction of the problem**
Reproduce the issue by cloning this boilerplate repository:

[https://github.com/steveblue/angular2-rollup](https://github.com/steveblue/angular2-rollup)

To reproduce, bump the version of Rollup to 0.35.0 and run `npm install`, `NODE_ENV=prod npm start`

I was able to verify the issue in two products using this starter, someone else reported the issue on StackOverflow here: http://stackoverflow.com/questions/39490738/outersubscriber-is-not-defined-when-bundeling-with-rollup-js/39504769?noredirect=1#comment66339077_39504769 and they seem to be using a completely different process with gulp-rollup.

**What is the motivation / use case for changing the behavior?**

Rollup is a minimal way to bundle apps for production and it currently works brilliantly with Rollup 0.34.0. 

**Please tell us about your environment:**

OS X El Capitan 10.11.6
VS Code 1.5.2
npm 3.3.12
Express 4.14.0

* **Angular version:** 2.0.0-rc.X

2.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 

Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.0.2
 
* **Node (for AoT issues):** `node --version` =   
v5.5.0

**Comment by mlaval** [comment]
@steveblue I can see that your project is now using rollup 0.36.3 and is working.
Can this issue be closed please?

**Comment by steveblue** [comment]
@mlaval Well I'm not 100% sure this issue can be closed. In a very simple Hello World 0.36.3 works but in another application we are stuck on Rollup 0.34.0 still. Still trying to diagnose the issue, let me get back to you.

**Comment by steveblue** [comment]
I think this is resolved. It's most likely some code in one of my projects that is making the build fail after upgrading rollup past 0.34.0, every other project seems to work.
