### ISSUE TITLE
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js)

### ISSUE THREAD

**Issue by JandroMejia97** [angular/angular#35320]
# 🐞 bug report

### Affected Package

 The issue is caused by package @ngtools/webpack

### Is this a regression?

 No.

### Description

 A clear and concise description of the problem...
After updating angular version 8 to 9, when I try to execute the commands `ionic serve` or` ng serve` I get the compilation error.

## 🔥 Exception or Error
<pre><code>
[ng] ERROR in ./src/zone-flags.ts
[ng] Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
[ng] Error: /home/mejia97/Documentos/CTM/ctm-front/src/zone-flags.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
[ng]     at AngularCompilerPlugin.getCompiledFile (/home/mejia97/Documentos/CTM/ctm-front/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:909:23)
[ng]     at /home/mejia97/Documentos/CTM/ctm-front/node_modules/@ngtools/webpack/src/loader.js:41:31
[ng]     at runMicrotasks (<anonymous>)
[ng]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.1
Node: 13.7.0
OS: linux x64

Angular: 9.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cli                      9.0.1
@angular/fire                     5.4.2
@ngtools/webpack                  9.0.1
@schematics/angular               8.1.3
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**
