### ISSUE TITLE
ContentChild Behavior Changed

### ISSUE THREAD

**Issue by dxvladislavvolkov** [angular/angular#33231]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core@9.0.0-next.10

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 9.0.0-next.9

### Description

 devextreme-angular built using angular@^6.0.0 and it works fine with angular/core@9.0.0-next.9 but with angular/core@9.0.0-next.10 I get an error in devextreme-angular. This is because it uses ContentChild and the result is processed at ngOnInit and ngAfterViewInit and now on ngOnInit result of ContentChild is undefined.

## 🔬 Minimal Reproduction

 You can reproduce it [here](https://stackblitz.com/edit/angular-7ck7uh?file=src/app/app.component.html)
Open DevTools and you will see the error.

If you change the version to a lower one, then everything works fine

## 🔥 Exception or Error
<pre><code>

preview-1cd940f8faa7073a7cacb.js:1 ERROR Error: E0120 - Adapter for a DevExpressValidator component cannot be configured. See:
http://js.devexpress.com/error/19_2/E0120
    at makeError (error.js:52)
    at Object.Error (error.js:19)
    at inheritor._initAdapter (validator.js:95)
    at inheritor._init (validator.js:55)
    at inheritor.eval [as _init] (class.js:17)
    at inheritor.endUpdate (component.js:279)
    at inheritor.endUpdate (dom_component.js:300)
    at inheritor.eval [as endUpdate] (class.js:17)
    at DxValidatorComponent.DxComponent.ngAfterViewInit (component.js:184)
    at callProviderLifecycles (core.umd.js:21803)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

@angular/core@9.0.0-next.10
</code></pre>

**Anything else relevant?**

**Comment by alexzuza** [comment]
The logic that statically determines whether a query is dynamic was removed in that version https://github.com/angular/angular/pull/32720

So if you want it to be initialized in `ngOnInit` then I guess you need to set `static` property to true manually here https://github.com/DevExpress/devextreme-angular/blob/3e9cf414587e3fc8b5680686b54d80fa4053dea0/templates/component.tst#L91

```
@ContentChild(DxValidatorComponent, { static: true })
```

**Comment by Airblader** [comment]
Or fix it since this behavior is deprecated and will be removed entirely in the future.

**Comment by dxvladislavvolkov** [comment]
@alexzuza but angular 6 does not have this flag

**Comment by dxvladislavvolkov** [comment]
@dannyskoog the same issue will be with angular 7 and this behavior is regression or breaking change

**Comment by dannyskoog** [comment]
@dxvladislavvolkov and while updating to Angular 7, did you perform the `migrations` provided with that particular major version?

**Comment by dxvladislavvolkov** [comment]
@dannyskoog yes. And I get the same error

**Comment by mhevery** [comment]
yes, expected change per breaking changes doc.
