### ISSUE TITLE
Compiler: generated code contains a defineDirective with an features-array containing void 0 causing error "fn is not a function" at runtime

### ISSUE THREAD

**Issue by rehdie** [angular/angular#60033]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

I just started a new project using Angular 19 and primeng 19.

Creating a simple component which contains an inputText, the compiler produces code, which causes "fn is not a function".

using the command `ng build --configuration development` produces code in main.js, which looks like this:

```
  static \u0275dir = /* @__PURE__ */ \u0275\u0275defineDirective({
    type: _InputText,
    selectors: [["", "pInputText", ""]],
    hostAttrs: [1, "p-inputtext", "p-component"],
    hostVars: 14,
    hostBindings: function InputText_HostBindings(rf, ctx) {
      if (rf & 1) {
        \u0275\u0275listener("input", function InputText_input_HostBindingHandler($event) {
          return ctx.onInput($event);
        });
      }
      if (rf & 2) {
        let tmp_1_0;
        \u0275\u0275classProp("p-filled", ctx.filled)("p-variant-filled", ((tmp_1_0 = ctx.variant) !== null && tmp_1_0 !== void 0 ? tmp_1_0 : ctx.config.inputStyle() || ctx.config.inputVariant()) === "filled")("p-inputtext-fluid", ctx.hasFluid)("p-inputtext-sm", ctx.pSize === "small")("p-inputfield-sm", ctx.pSize === "small")("p-inputtext-lg", ctx.pSize === "large")("p-inputfield-lg", ctx.pSize === "large");
      }
    },
    inputs: {
      variant: "variant",
      fluid: [2, "fluid", "fluid", booleanAttribute],
      pSize: "pSize"
    },
    features: [\u0275\u0275ProvidersFeature([InputTextStyle]), void 0, \u0275\u0275InheritDefinitionFeature]
  });
```

IMHO the  `void 0` array-element in the features-array should not be there. If there is anything wrong in my code or in the code of primeng, the compiler should report an error and not produce broken code.

In the Chrome-developer-tools it looks like this (in my own local version, i did not debug the stackblitz version):

![Image](https://github.com/user-attachments/assets/774a09c0-614a-4132-9df9-7faa928bd42b)

The 2nd element of the array definition.features contains an undefined in this case and therefore produces "fn is not a function".

### Please provide a link to a minimal reproduction of the bug

https://stackblitz-starters-nxtcukvt.stackblitz.io

### Please provide the exception or error you saw

```true
see above ("fn is not a function" in the browser-console)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Windows 11
Intellij IDEA
Chrome-Browser 
Angular 19.1.7
Primeng 19.0.6
```

**Comment by rehdie** [comment]
Result of ng version:

```
Angular CLI: 19.1.8
Node: 20.18.0
Package Manager: npm 10.8.2
OS: win32 x64

Angular: 19.1.7
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1901.8
@angular-devkit/build-angular   19.1.8
@angular-devkit/core            19.1.8
@angular-devkit/schematics      19.1.8
@angular/cli                    19.1.8
@schematics/angular             19.1.8
rxjs                            7.8.1
typescript                      5.7.3
zone.js                         0.15.0

```

**Comment by rpastro** [comment]
I'm seeing the same issue after upgrading from 19.1.6 to 19.1.7.   Looking at the generated code for PrimeNG library, it seems that `i0.ɵɵInputTransformsFeature` is undefined after the Angular update.

```
  })();
  static ɵdir = /*@__PURE__*/i0.ɵɵdefineDirective({
    type: AutoFocus,
    selectors: [["", "pAutoFocus", ""]],
    inputs: {
      autofocus: [2, "autofocus", "autofocus", booleanAttribute],
      _autofocus: [0, "pAutoFocus", "_autofocus"]
    },
    features: [i0.ɵɵInputTransformsFeature, i0.ɵɵInheritDefinitionFeature]
  });
```

**Comment by rehdie** [comment]
The stackblitz-link seems to be wrong, this one should work: https://stackblitz.com/edit/stackblitz-starters-nxtcukvt

**Comment by rehdie** [comment]
> I'm seeing the same issue after upgrading from 19.1.6 to 19.1.7. Looking at the generated code for PrimeNG library, it seems that `i0.ɵɵInputTransformsFeature` is undefined after the Angular update.
> 
> ```
>   })();
>   static ɵdir = /*@__PURE__*/i0.ɵɵdefineDirective({
>     type: AutoFocus,
>     selectors: [["", "pAutoFocus", ""]],
>     inputs: {
>       autofocus: [2, "autofocus", "autofocus", booleanAttribute],
>       _autofocus: [0, "pAutoFocus", "_autofocus"]
>     },
>     features: [i0.ɵɵInputTransformsFeature, i0.ɵɵInheritDefinitionFeature]
>   });
> ```

When changing to angular 19.1.6 it works, thanks.

**Comment by rehdie** [comment]
> I'm seeing the same issue after upgrading from 19.1.6 to 19.1.7. Looking at the generated code for PrimeNG library, it seems that `i0.ɵɵInputTransformsFeature` is undefined after the Angular update.
> 
> ```
>   })();
>   static ɵdir = /*@__PURE__*/i0.ɵɵdefineDirective({
>     type: AutoFocus,
>     selectors: [["", "pAutoFocus", ""]],
>     inputs: {
>       autofocus: [2, "autofocus", "autofocus", booleanAttribute],
>       _autofocus: [0, "pAutoFocus", "_autofocus"]
>     },
>     features: [i0.ɵɵInputTransformsFeature, i0.ɵɵInheritDefinitionFeature]
>   });
> ```

Thanks rpastro. Changing to 19.1.6 fixed the problem....

**Comment by JoostK** [comment]
The `ɵɵInputTransformsFeature` was removed in 798752b423afc717fd6cff42409e36880af86d27. This is an issue with PrimeNG, which is publishing precompiled code intead of partially compiled code. The former is not supported.

**Comment by rpastro** [comment]
Thanks for the input @JoostK .  I have opened an issue against PrimeNG.

**Comment by cagataycivici** [comment]
https://x.com/cagataycivici/status/1892926951016317052?s=46

**Comment by mertsincan** [comment]
Is this change considered a breaking change? We've started receiving emails about this issue, in addition to the ones linked in this thread. We released PrimeNG 19.0.6 (15 days ago) and didn’t encounter any build issues at the time. However, after this patch release, we need to find a solution and publish a fix.

At this point, we can't guarantee that those who lock Angular to 19.1.6 or 19.1.0 and update PrimeNG to 19.0.7 (next) won’t face issues. In such cases, we'll need two test environments: Angular 19.1.6 and Angular 19.1.7+ to ensure compatibility. WDYT?

**Comment by JeanMeche** [comment]
Full compilation have need been supported acrros versions (even patches). 
To ensure compatibility accross version, libraries should use partial compilation. This ensures no instructions are part of library bundles.

**Comment by imaksp** [comment]
Hi @mertsincan, someone has created PR to fix this, I think it should not create any issue with previous releases.
https://github.com/primefaces/primeng/pull/17731

someone from angular team could review it.

**Comment by mertsincan** [comment]
Thank you for your suggestion! I’ll give it a try. I’ll also need to test the new build on Angular 19.1.6. To be honest, if this is the case, I would have expected to encounter these issues earlier :)

**Comment by mertsincan** [comment]
I've tested the new build on Angular 19.1.6 and 19.1.7, and everything seems to work fine. I’ll release it today and await community feedback 🤞  Thanks again!

**Comment by JeanMeche** [comment]
@mertsincan Perfect, you'll be safe from those changes from now on !

**Comment by nicolaric-akenza** [comment]
hmm.. weirdly i suddenly get this issue when running the tests:
```
 No value provided for @angular/core symbol 'ɵɵInputTransformsFeature'.

      1 | import { z } from 'zod';
      2 | import { serializeResponse } from './response.serializer';
    > 3 | import { HttpResponse } from '@angular/common/http';
        | ^
      4 |
      5 | describe('response serializer', () => {
      6 |     it('should serialize response', async () => {
```

on this file:
```
import { z } from 'zod';
import { serializeResponse } from './response.serializer';
import { HttpResponse } from '@angular/common/http';

describe('response serializer', () => {
    it('should serialize response', async () => {
        const zodSchema = z.object({
            name: z.string(),
        });

        const serializedResponse = await serializeResponse(
            zodSchema,
            new HttpResponse({ body: { name: 'test' } }),
        );

        expect(serializedResponse.body).toStrictEqual({ name: 'test' });
    });
});
```

Do you have any idea why this happens? I really dont understand what the dependency between `HttpResponse` and `ɵɵInputTransformsFeature` is.
