### PR TITLE
fix(compiler): don’t throw when using `ANALYZE_FOR_ENTRY_COMPONENTS` …

### LINKED ISSUE #13565: Routes cannot contain additional objects in angular 2.3.1
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If you add an object instance to your route definition, the app fails to load with the error `Cannot convert undefined or null to object` with the stack trace:

```Uncaught TypeError: Cannot convert undefined or null to object
    at Function.getPrototypeOf (<anonymous>)
    at ReflectionCapabilities.annotations (http://localhost:4200/main.bundle.js:60005:50)
    at Reflector.annotations (http://localhost:4200/main.bundle.js:60197:44)
    at DirectiveResolver.isDirective (http://localhost:4200/main.bundle.js:18021:61)
    at http://localhost:4200/main.bundle.js:19618:42
    at Array.forEach (native)
    at CompileMetadataResolver._getEntryComponentsFromProvider (http://localhost:4200/main.bundle.js:19617:30)
    at http://localhost:4200/main.bundle.js:19590:83
    at Array.forEach (native)
    at CompileMetadataResolver._getProvidersMetadata (http://localhost:4200/main.bundle.js:19560:19)
    at http://localhost:4200/main.bundle.js:19562:23
    at Array.forEach (native)
    at CompileMetadataResolver._getProvidersMetadata (http://localhost:4200/main.bundle.js:19560:19)
    at http://localhost:4200/main.bundle.js:19198:63
    at Array.forEach (native)
```
The error ist thrown because `ReflectionCapabilities.annotations` tries to access the `prototype` of the passed variable which in this case is an object instance so fails.

This worked in 2.2.4 but fails with 2.3.1. It fails for a webpack build, I haven't tried any other build tools.

**Expected behavior**

The user should be able to add arbitrary properties to route entries without causing compilation errors.

**Minimal reproduction of the problem with instructions**

Add an object instance to a route definition like:

```
import { SomeObject } from "./some-object.model";

const routes: any = [
  {
    path: '',
    children: [],
    data: {
      otherProperty: new SomeObject(),
    }
  }
];
```

see https://github.com/marcuskrahl/angular-bug-route-with-object-instance for an example repository

**Workaround**
If the object instance creation is replaced with a function call, the example works without any problems (but of course the access of the data has to be changed).
```
...
    data: {
      otherProperty:  () => new SomeObject(),
    }
...
```

**What is the motivation / use case for changing the behavior?**

You should be able to add application dependant information to routing entries.

**Please tell us about your environment:**

angular-cli changed to 2.3.1 runtime on Windows 7.
Also does not work on custom webpack build without angular-cli.

* **Angular version:** 2.3.1

* **Browser:** [all]
 
* **Language:** [TypeScript 2.0.10]

* **Node (for AoT issues):** `node --version` =

### PR DESCRIPTION
**Pull request by tbosch**
…with user classes

Fixed #13565

### CODE REVIEW

File: modules/@angular/core/src/reflection/reflection_capabilities.ts [hunk 1]
```diff
@@ -233,3 +242,15 @@ function convertTsickleDecoratorIntoMetadata(decoratorInvocations: any[]): any[]
...
+
+function getParentCtor(ctor: any): any {
+  const parentProto = Object.getPrototypeOf(ctor.prototype);
+  const parentCtor = parentProto ? parentProto.constructor : null;
+  // Note: We always use `Object` as the null value
+  // to simplify checking later on.
+  return parentCtor || Object;
+}
+
+function isFunction(typeOrFunc: any): boolean {
```
Comment (vicb) [inline modules/@angular/core/src/reflection/reflection_capabilities.ts]: return type = `typeOrFunc is Function` and add missing types in `getParentCtor`

**Comment by vicb** [comment]
LGTM with 1 minor comment
